/* Generated by scripts/build-research-campaign-v13.mjs. */
export const ATLAS_RESEARCH_CAMPAIGN_INPUT_V13 = {
  "version": "v241-atlas-research-campaign-manifest-v13",
  "generatedAt": "2026-07-19T05:52:37.093Z",
  "sourceSha256": {
    "jointValidation": "d89f596a4c97841071ae713eb3d86aa2948c473c173e80f069a8e6bb6d9841e8",
    "priorRegressions": "e293c89315e8b0b3828fe060e218e083375b71cac241759433f0ab00067a9ff4",
    "denseScreen": "4fd9bb849e67529418638d23df16b4c4141a030ffeee189b369870ca62d45495",
    "densePlan": "8769211cd8db3aa963793d170b3b3ec87b3a873a96dc210d4623525ed66038f5",
    "denseAggregate": "0908048d4c5eed8303cab3fd8b89f30bc176f9276dc5cebc657f009e1a98bf7f",
    "kerrGateV8": "306ee73de6b1c7f9b6a62478f93134e612b7978e7d8b874eeae1ac48846c44da",
    "kerrCampaignProgressV8": "b4f463125ff8df735699b9273e323baaaa64e233478005f02aab76e742d522b6",
    "v6ShardQuarantine": "b7ab13f6043465ec39e5715c6dd12ed0ef79255e6a94ce29f35a45c51478776e",
    "stmSmoke": "3eaf637e0b92fc3c1f524f5a1bcf3e38a427373024ed97920042483ffe307340",
    "bundleStandalone": "ea662e683ed01528d7a01c3f2a23c7774538bae8d55eaccb0aa48cdda3c4a232",
    "bundleLite": "40a87187bad911f22a4f0f74736d312dc08c407b007986df049ac413f4b47239",
    "lifecycle": "ecd53fd0e3d24d8f50eba8d6256c30205c2e6c8003e7fc1de8da782291cad6b8",
    "contentPacks": "a50ab31ce2e4fc3ad2a0e1e5aa321671e4d587f4b32a93a9dfc1908f81e985f5",
    "catalogExpansion": "ba5f14c30ecbb2af65a2b2d7415ed19efe3593c9a4e49c707b74cc45054e4a15",
    "security": "938cfd3b878d1c2319521df1b6b34ed318820a97e55c7ba57973ecf7922b98ca",
    "historicalKerrGateV7": "47e0c37faeadf96374bf12465bec9f2b616e6cf86fd22056477c76ee68366927",
    "historicalKerrGateDiagnosticV7": "23448b5bcca5ac7fe152fa5a49783627c502cffd985b47c24dd53fb904bca36a",
    "shard:shard-0000.json": "b23af6bcc6d8d859651d1bd874189f8b4948fa4307cf4819bdabefc58b49002a",
    "shard:shard-0001.json": "f82dad9212b690700944287de18cc6a4fe26fb74ec489241ee23fc4e60345ffe",
    "shard:shard-0002.json": "6e8916d6ec148f8589a29ecbe07174304cb2e5756429049928d763e176602d21",
    "shard:shard-0003.json": "0e538d7c91018444eb6bbf72ae2099794012f1adcc459e884d665415faaeb228"
  },
  "reference": {
    "coordinateFrame": "ICRF-J2000-barycentric",
    "timeScale": "TDB",
    "fixtureSha256": "d7d916c08f09c4f49fa575c2f2898af9469350ca3aeaeca0e319ef175e6efee7",
    "provenanceReady": true,
    "dop853RerunPassed": true,
    "ias15RerunPassed": true
  },
  "promotionInput": {
    "legacyPositionRmsKm": 97.4962129987326,
    "legacyVelocityRmsMS": 0.16038441711601498,
    "candidatePositionRmsKm": 97.49777481741557,
    "candidateVelocityRmsMS": 0.16038507156539808,
    "comparativeAggregateImprovementDemonstrated": false,
    "independentPerBodyComparisonComplete": true,
    "perBodyNoRegression": false,
    "effectIsolationComplete": false,
    "supportingGatesPassed": false
  },
  "weakField": {
    "historicalRegressionCount": 15,
    "confirmedRegressionCount": 10,
    "allHistoricalRowsResolved": false,
    "attributionCounts": {
      "cross-solver-regression-confirmed": 7,
      "inconclusive": 8
    },
    "attributions": [
      {
        "checkpoint": "+30d",
        "offsetDays": 30,
        "bodyId": "mercury",
        "priorV8Classification": "cross-solver-regression-confirmed",
        "jointValidationClassification": "cross-solver-regression-confirmed",
        "attribution": "cross-solver-regression-confirmed",
        "resolved": true
      },
      {
        "checkpoint": "+30d",
        "offsetDays": 30,
        "bodyId": "earth",
        "priorV8Classification": "cross-solver-regression-confirmed",
        "jointValidationClassification": "cross-solver-regression-confirmed",
        "attribution": "cross-solver-regression-confirmed",
        "resolved": true
      },
      {
        "checkpoint": "+30d",
        "offsetDays": 30,
        "bodyId": "moon",
        "priorV8Classification": "cross-solver-regression-confirmed",
        "jointValidationClassification": "inconclusive",
        "attribution": "inconclusive",
        "resolved": false
      },
      {
        "checkpoint": "+30d",
        "offsetDays": 30,
        "bodyId": "jupiter",
        "priorV8Classification": "inconclusive",
        "jointValidationClassification": "no-confirmed-regression",
        "attribution": "inconclusive",
        "resolved": true
      },
      {
        "checkpoint": "+365d",
        "offsetDays": 365,
        "bodyId": "mercury",
        "priorV8Classification": "cross-solver-regression-confirmed",
        "jointValidationClassification": "cross-solver-regression-confirmed",
        "attribution": "cross-solver-regression-confirmed",
        "resolved": true
      },
      {
        "checkpoint": "+365d",
        "offsetDays": 365,
        "bodyId": "earth",
        "priorV8Classification": "solver-disagreement",
        "jointValidationClassification": "cross-solver-regression-confirmed",
        "attribution": "cross-solver-regression-confirmed",
        "resolved": true
      },
      {
        "checkpoint": "+365d",
        "offsetDays": 365,
        "bodyId": "uranus",
        "priorV8Classification": "solver-disagreement",
        "jointValidationClassification": "no-confirmed-regression",
        "attribution": "inconclusive",
        "resolved": true
      },
      {
        "checkpoint": "+365d",
        "offsetDays": 365,
        "bodyId": "neptune",
        "priorV8Classification": "solver-disagreement",
        "jointValidationClassification": "no-confirmed-regression",
        "attribution": "inconclusive",
        "resolved": true
      },
      {
        "checkpoint": "+10y",
        "offsetDays": 3652.5,
        "bodyId": "mercury",
        "priorV8Classification": "solver-disagreement",
        "jointValidationClassification": "cross-solver-regression-confirmed",
        "attribution": "cross-solver-regression-confirmed",
        "resolved": true
      },
      {
        "checkpoint": "+10y",
        "offsetDays": 3652.5,
        "bodyId": "mars",
        "priorV8Classification": "cross-solver-regression-confirmed",
        "jointValidationClassification": "cross-solver-regression-confirmed",
        "attribution": "cross-solver-regression-confirmed",
        "resolved": true
      },
      {
        "checkpoint": "+10y",
        "offsetDays": 3652.5,
        "bodyId": "jupiter",
        "priorV8Classification": "cross-solver-regression-confirmed",
        "jointValidationClassification": "inconclusive",
        "attribution": "inconclusive",
        "resolved": false
      },
      {
        "checkpoint": "+10y",
        "offsetDays": 3652.5,
        "bodyId": "uranus",
        "priorV8Classification": "solver-disagreement",
        "jointValidationClassification": "no-confirmed-regression",
        "attribution": "inconclusive",
        "resolved": true
      },
      {
        "checkpoint": "+10y",
        "offsetDays": 3652.5,
        "bodyId": "neptune",
        "priorV8Classification": "solver-disagreement",
        "jointValidationClassification": "no-confirmed-regression",
        "attribution": "inconclusive",
        "resolved": true
      },
      {
        "checkpoint": "+10y",
        "offsetDays": 3652.5,
        "bodyId": "pluto",
        "priorV8Classification": "solver-disagreement",
        "jointValidationClassification": "no-confirmed-regression",
        "attribution": "inconclusive",
        "resolved": true
      },
      {
        "checkpoint": "+10y",
        "offsetDays": 3652.5,
        "bodyId": "ceres",
        "priorV8Classification": "solver-disagreement",
        "jointValidationClassification": "cross-solver-regression-confirmed",
        "attribution": "cross-solver-regression-confirmed",
        "resolved": true
      }
    ],
    "mercuryTenYear": {
      "dop853PositionDeltaMeters": 45.58964892497097,
      "ias15PositionDeltaMeters": 45.31713287080819,
      "positionJointUncertaintyMeters": 1.5270384855753094,
      "positionOutcome": "cross-solver-regression-confirmed",
      "physicalCauseEstablished": false
    },
    "fittedBlind": {
      "complete": true,
      "aggregateImprovement": false,
      "physicalCauseEstablished": false
    },
    "effectIsolationComplete": false,
    "uncertaintyFormula": "Ujoint=UDOP853+UIAS15+Ureference+Ufit"
  },
  "denseKerr": {
    "campaignVersion": "finite-observer-v8",
    "freezeCommitSha": "8315160a6f7afd4763e3840c7b6d5bb4da0ca663",
    "freezeBranch": "codex/orbit-atlas-v241-science-freeze",
    "campaignStatus": "failed",
    "campaignProgressSha256": "b61647e98b0b9719449afdb8dbba8daaa309812ab150e48e716a80205fe6d582",
    "v6QuarantineManifestSha256": "4cd425d95b81ad4d46f7ea9f2c70e40d6151d12ded5f8add714bde88addcc609",
    "failedShardIndex": 3,
    "failure": "CalledProcessError: Command '['E:\\\\86137\\\\myai\\\\solar_sim\\\\next-web\\\\.venv-science\\\\Scripts\\\\python.exe', 'E:\\\\86137\\\\myai\\\\solar_sim\\\\next-web\\\\scripts\\\\run-kerr-dense-shards-v8.py', '--profile', 'release', '--shard', '3']' returned non-zero exit status 2.",
    "noAutomaticRetry": true,
    "profile": "release",
    "plannedRayCount": 3097,
    "plannedShardCount": 49,
    "completedReleaseShardCount": 3,
    "completedRayCount": 192,
    "completedExecutionCount": 1536,
    "completedShardIndices": [
      0,
      1,
      2
    ],
    "attemptedRayCount": 256,
    "attemptedExecutionCount": 2048,
    "failedShardEvidence": {
      "shardIndex": 3,
      "file": "dist/science/kerr-shards-v8/shard-0003.json",
      "fileSha256": "0e538d7c91018444eb6bbf72ae2099794012f1adcc459e884d665415faaeb228",
      "outputSha256": "6361c8d6a19fa25128cb0174d234edaa7fd31d574586b75d8a8f890f87cbb8df",
      "complete": false,
      "rayCount": 64,
      "executionCount": 512,
      "watchdogSeconds": 180,
      "incompleteExecutionCount": 4,
      "watchdogTimeoutExecutionCount": 4,
      "incompleteExecutionStatusCounts": {
        "watchdog-timeout": 4
      },
      "affectedRayIds": [
        "low-discrepancy-0174",
        "low-discrepancy-0204"
      ],
      "retainedAsImmutableNegativeEvidence": true
    },
    "rayClassCounts": {
      "canonical": 25,
      "low-discrepancy": 167,
      "critical-bracket": 0
    },
    "codeSha256": "0debb41b96f001f92f498ef6a36ceff77ede7f0dd2bdbe3c6e9db3dfbf6090a8",
    "environmentSha256": "5cb0191749e1062441ff59108144f9b413cd0767f4c64001b846a2f7fa18ef83",
    "frozenScreenManifestSha256": "08f42a50bc787df62dc018ee56b5f7b58065dcafe2e2a3703e3e67f3e6d94037",
    "finiteObserverScreenManifestSha256": "08f42a50bc787df62dc018ee56b5f7b58065dcafe2e2a3703e3e67f3e6d94037",
    "planSha256": "d4964f7e6a173617cf3a56c525a06faca583b5a0d9588810db0a2753d4166ff5",
    "maxNullConstraint": 2.9183821826720254e-10,
    "shortGatePassed": true,
    "shortGateExecuted": true,
    "shortGateCanonicalEvidenceSha256": "92dc107dd4412ae809a4ec40abef086e9c3d13b67a97a7819bd6f174ba9025a0",
    "shortGateFailure": null,
    "shortGateEvaluation": {
      "invalidCount": 0,
      "nonPhysicalCount": 0,
      "deterministicFailureCount": 0,
      "criticalTransitionCount": 40,
      "criticalTransitionExpected": 40,
      "maxNullConstraint": 2.3662139126156168e-11
    },
    "historicalV7": {
      "gatePassed": false,
      "criticalTransitionCount": 0,
      "criticalTransitionExpected": 40,
      "canonicalEvidenceSha256": "aae2f88bf26db445a18e3b193619b84ab2b68ea76c146f13403c6a3f0830cea5",
      "retainedAsImmutableNegativeEvidence": true
    },
    "complete": false,
    "gatePassed": false,
    "partialResultsAggregated": false,
    "blocker": "v8-dense-campaign-failed-no-retry-no-partial-aggregation"
  },
  "variationalStm": {
    "evidenceVersion": "v229-relativity-variational-stm-evidence-v12",
    "profile": "smoke",
    "shortGatePassed": false,
    "deterministicRerunPassed": true,
    "releaseQualificationAvailable": false,
    "effectiveRank": 66,
    "integratedStateAndPhiDimension": 4824,
    "holdoutDays": [
      365
    ],
    "fitIterations": 1,
    "gatePassed": false
  },
  "product": {
    "localGatesPassed": true,
    "standaloneTransferBytes": 594330,
    "liteTransferBytes": 594330,
    "contentPackVerifiedFiles": 809,
    "catalogExpansion": {
      "version": "v255-catalog-expansion",
      "canonicalSha256": "48712d04844b9380b287cf6ada8088405288567a3cf4525adefd5ea6fb697a2a",
      "gaiaRowCount": 46000,
      "iauConstellationCount": 88,
      "asterismCount": 32,
      "starClusterCount": 96,
      "nebulaCount": 128,
      "activeRenderBudget": {
        "mobile": 1000,
        "balanced": 4000,
        "dense": 8000,
        "closeup": 1200
      }
    }
  },
  "outcome": "relativity-v13-product-candidate-science-failed-shadow-retained",
  "defaultKernel": "legacy-eih-1pn",
  "runtimePromotionApplied": false,
  "boundary": "offline-research-campaign-no-root-contract-or-runtime-physics-mutation",
  "manifestSha256": "c1b8fbeb321a6ea00ce699a5a86b8547c029a557e403eb7245aa991ae6b1fffe"
} as const;
