/* This file is generated by scripts/build-current-evidence-manifest-v233.mjs. */
export const ATLAS_CURRENT_EVIDENCE_INPUT_V233 = {
  "version": "v233-current-evidence-manifest",
  "generatedAt": "2026-07-19T05:52:37.093Z",
  "sourceSha256": {
    "researchCampaign": "52b625b5e004dd1a0900554e8c77b0e3775ab8d3458cf9774e900bb061b94467",
    "denseScreen": "4fd9bb849e67529418638d23df16b4c4141a030ffeee189b369870ca62d45495",
    "densePlan": "8769211cd8db3aa963793d170b3b3ec87b3a873a96dc210d4623525ed66038f5",
    "denseAggregate": "0908048d4c5eed8303cab3fd8b89f30bc176f9276dc5cebc657f009e1a98bf7f",
    "kerrGateV8": "306ee73de6b1c7f9b6a62478f93134e612b7978e7d8b874eeae1ac48846c44da",
    "kerrCampaignProgressV8": "b4f463125ff8df735699b9273e323baaaa64e233478005f02aab76e742d522b6",
    "v6ShardQuarantine": "b7ab13f6043465ec39e5715c6dd12ed0ef79255e6a94ce29f35a45c51478776e",
    "stm": "3eaf637e0b92fc3c1f524f5a1bcf3e38a427373024ed97920042483ffe307340",
    "bundleStandalone": "ea662e683ed01528d7a01c3f2a23c7774538bae8d55eaccb0aa48cdda3c4a232",
    "bundleLite": "40a87187bad911f22a4f0f74736d312dc08c407b007986df049ac413f4b47239",
    "lifecycle": "ecd53fd0e3d24d8f50eba8d6256c30205c2e6c8003e7fc1de8da782291cad6b8",
    "contentPacks": "a50ab31ce2e4fc3ad2a0e1e5aa321671e4d587f4b32a93a9dfc1908f81e985f5",
    "catalogExpansion": "ba5f14c30ecbb2af65a2b2d7415ed19efe3593c9a4e49c707b74cc45054e4a15",
    "security": "938cfd3b878d1c2319521df1b6b34ed318820a97e55c7ba57973ecf7922b98ca",
    "productionAudit": "1711b1236db435c042e480767a137034c27b92ade4c13c3cc3dd76d518949bb0",
    "secretScan": "92b17cfc8b0ef32fde70d71fdf3d4690ffcb133bec104d964f417ce38eec0900",
    "shard:shard-0000.json": "b23af6bcc6d8d859651d1bd874189f8b4948fa4307cf4819bdabefc58b49002a",
    "shard:shard-0001.json": "f82dad9212b690700944287de18cc6a4fe26fb74ec489241ee23fc4e60345ffe",
    "shard:shard-0002.json": "6e8916d6ec148f8589a29ecbe07174304cb2e5756429049928d763e176602d21",
    "shard:shard-0003.json": "0e538d7c91018444eb6bbf72ae2099794012f1adcc459e884d665415faaeb228"
  },
  "promotionInput": {
    "legacyPositionRmsKm": 97.4962129987326,
    "legacyVelocityRmsMS": 0.16038441711601498,
    "candidatePositionRmsKm": 97.49777481741557,
    "candidateVelocityRmsMS": 0.16038507156539808,
    "comparativeAggregateImprovementDemonstrated": false,
    "independentPerBodyComparisonComplete": true,
    "perBodyNoRegression": false,
    "effectIsolationComplete": false,
    "supportingGatesPassed": false
  },
  "weakField": {
    "checkpointCount": 3,
    "bodyCount": 12,
    "perBodyRegressionCount": 15,
    "regressionsByCheckpoint": {
      "+30d": 4,
      "+365d": 4,
      "+10y": 7
    },
    "confirmedRegressionCount": 10,
    "attributionCounts": {
      "cross-solver-regression-confirmed": 7,
      "inconclusive": 8
    },
    "effectIsolationComplete": false
  },
  "denseKerr": {
    "campaignVersion": "finite-observer-v8",
    "freezeCommitSha": "8315160a6f7afd4763e3840c7b6d5bb4da0ca663",
    "freezeBranch": "codex/orbit-atlas-v241-science-freeze",
    "campaignStatus": "failed",
    "campaignProgressSha256": "b61647e98b0b9719449afdb8dbba8daaa309812ab150e48e716a80205fe6d582",
    "v6QuarantineManifestSha256": "4cd425d95b81ad4d46f7ea9f2c70e40d6151d12ded5f8add714bde88addcc609",
    "failedShardIndex": 3,
    "failure": "CalledProcessError: Command '['E:\\\\86137\\\\myai\\\\solar_sim\\\\next-web\\\\.venv-science\\\\Scripts\\\\python.exe', 'E:\\\\86137\\\\myai\\\\solar_sim\\\\next-web\\\\scripts\\\\run-kerr-dense-shards-v8.py', '--profile', 'release', '--shard', '3']' returned non-zero exit status 2.",
    "noAutomaticRetry": true,
    "profile": "release",
    "plannedRayCount": 3097,
    "plannedShardCount": 49,
    "completedReleaseShardCount": 3,
    "completedRayCount": 192,
    "completedExecutionCount": 1536,
    "completedShardIndices": [
      0,
      1,
      2
    ],
    "attemptedRayCount": 256,
    "attemptedExecutionCount": 2048,
    "failedShardEvidence": {
      "shardIndex": 3,
      "file": "dist/science/kerr-shards-v8/shard-0003.json",
      "fileSha256": "0e538d7c91018444eb6bbf72ae2099794012f1adcc459e884d665415faaeb228",
      "outputSha256": "6361c8d6a19fa25128cb0174d234edaa7fd31d574586b75d8a8f890f87cbb8df",
      "complete": false,
      "rayCount": 64,
      "executionCount": 512,
      "watchdogSeconds": 180,
      "incompleteExecutionCount": 4,
      "watchdogTimeoutExecutionCount": 4,
      "incompleteExecutionStatusCounts": {
        "watchdog-timeout": 4
      },
      "affectedRayIds": [
        "low-discrepancy-0174",
        "low-discrepancy-0204"
      ],
      "retainedAsImmutableNegativeEvidence": true
    },
    "rayClassCounts": {
      "canonical": 25,
      "low-discrepancy": 167,
      "critical-bracket": 0
    },
    "codeSha256": "0debb41b96f001f92f498ef6a36ceff77ede7f0dd2bdbe3c6e9db3dfbf6090a8",
    "environmentSha256": "5cb0191749e1062441ff59108144f9b413cd0767f4c64001b846a2f7fa18ef83",
    "frozenScreenManifestSha256": "08f42a50bc787df62dc018ee56b5f7b58065dcafe2e2a3703e3e67f3e6d94037",
    "finiteObserverScreenManifestSha256": "08f42a50bc787df62dc018ee56b5f7b58065dcafe2e2a3703e3e67f3e6d94037",
    "planSha256": "d4964f7e6a173617cf3a56c525a06faca583b5a0d9588810db0a2753d4166ff5",
    "maxNullConstraint": 2.9183821826720254e-10,
    "shortGatePassed": true,
    "shortGateExecuted": true,
    "shortGateCanonicalEvidenceSha256": "92dc107dd4412ae809a4ec40abef086e9c3d13b67a97a7819bd6f174ba9025a0",
    "shortGateFailure": null,
    "shortGateEvaluation": {
      "invalidCount": 0,
      "nonPhysicalCount": 0,
      "deterministicFailureCount": 0,
      "criticalTransitionCount": 40,
      "criticalTransitionExpected": 40,
      "maxNullConstraint": 2.3662139126156168e-11
    },
    "historicalV7": {
      "gatePassed": false,
      "criticalTransitionCount": 0,
      "criticalTransitionExpected": 40,
      "canonicalEvidenceSha256": "aae2f88bf26db445a18e3b193619b84ab2b68ea76c146f13403c6a3f0830cea5",
      "retainedAsImmutableNegativeEvidence": true
    },
    "complete": false,
    "gatePassed": false,
    "partialResultsAggregated": false,
    "blocker": "v8-dense-campaign-failed-no-retry-no-partial-aggregation"
  },
  "variationalStm": {
    "evidenceVersion": "v229-relativity-variational-stm-evidence-v12",
    "profile": "smoke",
    "shortGatePassed": false,
    "deterministicRerunPassed": true,
    "releaseQualificationAvailable": false,
    "effectiveRank": 66,
    "integratedStateAndPhiDimension": 4824,
    "holdoutDays": [
      365
    ],
    "fitIterations": 1,
    "gatePassed": false
  },
  "product": {
    "gates": {
      "contentPacks": true,
      "standaloneBundle": true,
      "liteBundle": true,
      "lifecycle": true,
      "catalogExpansion": true,
      "security": true,
      "productionAudit": true,
      "secretScan": true
    },
    "localProductGatesPassed": true,
    "bundles": {
      "standaloneTransferBytes": 594330,
      "liteTransferBytes": 594330,
      "hardLimitBytes": 614400,
      "engineeringTargetBytes": 604160
    },
    "contentPacks": {
      "packCount": 6,
      "manifestFileCount": 809,
      "verifiedFileCount": 809
    },
    "catalogExpansion": {
      "version": "v255-catalog-expansion",
      "canonicalSha256": "48712d04844b9380b287cf6ada8088405288567a3cf4525adefd5ea6fb697a2a",
      "gaiaRowCount": 46000,
      "iauConstellationCount": 88,
      "asterismCount": 32,
      "starClusterCount": 96,
      "nebulaCount": 128,
      "activeRenderBudget": {
        "mobile": 1000,
        "balanced": 4000,
        "dense": 8000,
        "closeup": 1200
      },
      "livePhysicsMutation": "not-applied",
      "workerPhysicsMutation": "not-applied",
      "eihOnePnMutation": "not-applied"
    }
  },
  "boundary": "generated-current-evidence-no-root-contract-or-runtime-physics-mutation",
  "manifestSha256": "9b897052d5a03984e75b78f177fe131e6a9e04baecc59d24d6b03655065c8ce8"
} as const;
