import { getAtlasResourceSnapshot, type AtlasRuntimeResourceSnapshot } from "./atlasResourceLifecycle";
import { getKerrScienceImageProbeClientSnapshotV346, type KerrScienceImageProbeClientSnapshotV346 } from "./kerrScienceImageProbeClientV346";
import type { KerrScienceImageProbeHitV346 } from "./kerrScienceImagePixelProbeV346";

export const ATLAS_SCIENCE_IMAGE_PROBE_TELEMETRY_VERSION_V346 = "v346-science-image-probe-telemetry-v1" as const;
export type AtlasScienceImageProbeTelemetryV346 = Readonly<{ version: typeof ATLAS_SCIENCE_IMAGE_PROBE_TELEMETRY_VERSION_V346; selectedKey: string; fitsPixel: string; arrayIndex: string; celestialWcs: "unavailable"; sceneRevisionDelta: 0; canvasCount: 1; typedArrayCaches: number; objectUrls: number; client: KerrScienceImageProbeClientSnapshotV346; boundary: "local-probe-state-dom-dataset-no-app-shell-render-no-science-mutation" }>;
let current = create();
function create(): AtlasScienceImageProbeTelemetryV346 { const resources = getAtlasResourceSnapshot(); return Object.freeze({ version: ATLAS_SCIENCE_IMAGE_PROBE_TELEMETRY_VERSION_V346, selectedKey: "none", fitsPixel: "none", arrayIndex: "none", celestialWcs: "unavailable", sceneRevisionDelta: 0, canvasCount: 1, typedArrayCaches: resources.typedArrayCaches, objectUrls: resources.objectUrls, client: getKerrScienceImageProbeClientSnapshotV346(), boundary: "local-probe-state-dom-dataset-no-app-shell-render-no-science-mutation" }); }
function write(node: Pick<HTMLElement, "dataset"> | null, value: AtlasScienceImageProbeTelemetryV346): void { if (!node) return; node.dataset.atlasScienceProbeSelectionV346 = value.selectedKey; node.dataset.atlasScienceProbeFitsPixelV346 = value.fitsPixel; node.dataset.atlasScienceProbeArrayIndexV346 = value.arrayIndex; node.dataset.atlasScienceProbeCelestialWcsV346 = value.celestialWcs; node.dataset.atlasScienceProbeTypedArrayCacheCountV346 = String(value.typedArrayCaches); node.dataset.atlasScienceProbeObjectUrlCountV346 = String(value.objectUrls); }
export function publishAtlasScienceImageProbeTelemetryV346(hit: KerrScienceImageProbeHitV346 | null, options: Readonly<{ node?: Pick<HTMLElement, "dataset"> | null; resources?: AtlasRuntimeResourceSnapshot; client?: KerrScienceImageProbeClientSnapshotV346 }> = {}): AtlasScienceImageProbeTelemetryV346 { const resources = options.resources ?? getAtlasResourceSnapshot(); current = Object.freeze({ ...current, selectedKey: hit?.key ?? "none", fitsPixel: hit ? hit.fitsPixel.join(",") : "none", arrayIndex: hit ? hit.arrayIndex.join(",") : "none", typedArrayCaches: resources.typedArrayCaches, objectUrls: resources.objectUrls, client: options.client ?? getKerrScienceImageProbeClientSnapshotV346() }); write(options.node ?? (typeof document === "undefined" ? null : document.querySelector<HTMLElement>("[data-atlas-app-shell]")), current); return current; }
export function getAtlasScienceImageProbeTelemetryV346(): AtlasScienceImageProbeTelemetryV346 { return current; }
export function resetAtlasScienceImageProbeTelemetryV346ForTests(): void { current = create(); }
