/* Generated by scripts/build-research-campaign-v13.mjs. */
export const ATLAS_RESEARCH_CAMPAIGN_INPUT_V13 = {
  "version": "v241-atlas-research-campaign-manifest-v13",
  "generatedAt": "2026-07-18T04:25:24.897637+00:00",
  "sourceSha256": {
    "jointValidation": "d89f596a4c97841071ae713eb3d86aa2948c473c173e80f069a8e6bb6d9841e8",
    "priorRegressions": "e293c89315e8b0b3828fe060e218e083375b71cac241759433f0ab00067a9ff4",
    "denseScreen": "4fd9bb849e67529418638d23df16b4c4141a030ffeee189b369870ca62d45495",
    "densePlan": "21d414b7f1be6430686529608e04327d59ee6572ac403f34d9af8e214e3aeaaf",
    "denseAggregate": "2fc25232147fc8affdaadbce6961b5c4f946718fee00ab2d1a687880a39fbe73",
    "kerrGateV8": "306ee73de6b1c7f9b6a62478f93134e612b7978e7d8b874eeae1ac48846c44da",
    "stmSmoke": "3eaf637e0b92fc3c1f524f5a1bcf3e38a427373024ed97920042483ffe307340",
    "bundleStandalone": "75d9151bc9a1dfc7b7e5345266da3d521780c5065a0c2948d4c50a6a98eb9137",
    "bundleLite": "305a9c708251c333b577765acb69277f6a5a099b267331f1fbadc9487d7fa73b",
    "lifecycle": "110578969cf27ae8e72320257ca69adce659860848a5f878f6be853e86288a92",
    "contentPacks": "363e5ac16abca8a1b55992491d6cb347c027b0ee5474f90ab1e9bad2f8f155cd",
    "security": "938cfd3b878d1c2319521df1b6b34ed318820a97e55c7ba57973ecf7922b98ca",
    "historicalKerrGateV7": "47e0c37faeadf96374bf12465bec9f2b616e6cf86fd22056477c76ee68366927",
    "historicalKerrGateDiagnosticV7": "23448b5bcca5ac7fe152fa5a49783627c502cffd985b47c24dd53fb904bca36a"
  },
  "reference": {
    "coordinateFrame": "ICRF-J2000-barycentric",
    "timeScale": "TDB",
    "fixtureSha256": "d7d916c08f09c4f49fa575c2f2898af9469350ca3aeaeca0e319ef175e6efee7",
    "provenanceReady": true,
    "dop853RerunPassed": true,
    "ias15RerunPassed": true
  },
  "promotionInput": {
    "legacyPositionRmsKm": 97.4962129987326,
    "legacyVelocityRmsMS": 0.16038441711601498,
    "candidatePositionRmsKm": 97.49777481741557,
    "candidateVelocityRmsMS": 0.16038507156539808,
    "comparativeAggregateImprovementDemonstrated": false,
    "independentPerBodyComparisonComplete": true,
    "perBodyNoRegression": false,
    "effectIsolationComplete": false,
    "supportingGatesPassed": false
  },
  "weakField": {
    "historicalRegressionCount": 15,
    "confirmedRegressionCount": 10,
    "allHistoricalRowsResolved": false,
    "attributionCounts": {
      "cross-solver-regression-confirmed": 7,
      "inconclusive": 8
    },
    "attributions": [
      {
        "checkpoint": "+30d",
        "offsetDays": 30,
        "bodyId": "mercury",
        "priorV8Classification": "cross-solver-regression-confirmed",
        "jointValidationClassification": "cross-solver-regression-confirmed",
        "attribution": "cross-solver-regression-confirmed",
        "resolved": true
      },
      {
        "checkpoint": "+30d",
        "offsetDays": 30,
        "bodyId": "earth",
        "priorV8Classification": "cross-solver-regression-confirmed",
        "jointValidationClassification": "cross-solver-regression-confirmed",
        "attribution": "cross-solver-regression-confirmed",
        "resolved": true
      },
      {
        "checkpoint": "+30d",
        "offsetDays": 30,
        "bodyId": "moon",
        "priorV8Classification": "cross-solver-regression-confirmed",
        "jointValidationClassification": "inconclusive",
        "attribution": "inconclusive",
        "resolved": false
      },
      {
        "checkpoint": "+30d",
        "offsetDays": 30,
        "bodyId": "jupiter",
        "priorV8Classification": "inconclusive",
        "jointValidationClassification": "no-confirmed-regression",
        "attribution": "inconclusive",
        "resolved": true
      },
      {
        "checkpoint": "+365d",
        "offsetDays": 365,
        "bodyId": "mercury",
        "priorV8Classification": "cross-solver-regression-confirmed",
        "jointValidationClassification": "cross-solver-regression-confirmed",
        "attribution": "cross-solver-regression-confirmed",
        "resolved": true
      },
      {
        "checkpoint": "+365d",
        "offsetDays": 365,
        "bodyId": "earth",
        "priorV8Classification": "solver-disagreement",
        "jointValidationClassification": "cross-solver-regression-confirmed",
        "attribution": "cross-solver-regression-confirmed",
        "resolved": true
      },
      {
        "checkpoint": "+365d",
        "offsetDays": 365,
        "bodyId": "uranus",
        "priorV8Classification": "solver-disagreement",
        "jointValidationClassification": "no-confirmed-regression",
        "attribution": "inconclusive",
        "resolved": true
      },
      {
        "checkpoint": "+365d",
        "offsetDays": 365,
        "bodyId": "neptune",
        "priorV8Classification": "solver-disagreement",
        "jointValidationClassification": "no-confirmed-regression",
        "attribution": "inconclusive",
        "resolved": true
      },
      {
        "checkpoint": "+10y",
        "offsetDays": 3652.5,
        "bodyId": "mercury",
        "priorV8Classification": "solver-disagreement",
        "jointValidationClassification": "cross-solver-regression-confirmed",
        "attribution": "cross-solver-regression-confirmed",
        "resolved": true
      },
      {
        "checkpoint": "+10y",
        "offsetDays": 3652.5,
        "bodyId": "mars",
        "priorV8Classification": "cross-solver-regression-confirmed",
        "jointValidationClassification": "cross-solver-regression-confirmed",
        "attribution": "cross-solver-regression-confirmed",
        "resolved": true
      },
      {
        "checkpoint": "+10y",
        "offsetDays": 3652.5,
        "bodyId": "jupiter",
        "priorV8Classification": "cross-solver-regression-confirmed",
        "jointValidationClassification": "inconclusive",
        "attribution": "inconclusive",
        "resolved": false
      },
      {
        "checkpoint": "+10y",
        "offsetDays": 3652.5,
        "bodyId": "uranus",
        "priorV8Classification": "solver-disagreement",
        "jointValidationClassification": "no-confirmed-regression",
        "attribution": "inconclusive",
        "resolved": true
      },
      {
        "checkpoint": "+10y",
        "offsetDays": 3652.5,
        "bodyId": "neptune",
        "priorV8Classification": "solver-disagreement",
        "jointValidationClassification": "no-confirmed-regression",
        "attribution": "inconclusive",
        "resolved": true
      },
      {
        "checkpoint": "+10y",
        "offsetDays": 3652.5,
        "bodyId": "pluto",
        "priorV8Classification": "solver-disagreement",
        "jointValidationClassification": "no-confirmed-regression",
        "attribution": "inconclusive",
        "resolved": true
      },
      {
        "checkpoint": "+10y",
        "offsetDays": 3652.5,
        "bodyId": "ceres",
        "priorV8Classification": "solver-disagreement",
        "jointValidationClassification": "cross-solver-regression-confirmed",
        "attribution": "cross-solver-regression-confirmed",
        "resolved": true
      }
    ],
    "mercuryTenYear": {
      "dop853PositionDeltaMeters": 45.58964892497097,
      "ias15PositionDeltaMeters": 45.31713287080819,
      "positionJointUncertaintyMeters": 1.5270384855753094,
      "positionOutcome": "cross-solver-regression-confirmed",
      "physicalCauseEstablished": false
    },
    "fittedBlind": {
      "complete": true,
      "aggregateImprovement": false,
      "physicalCauseEstablished": false
    },
    "effectIsolationComplete": false,
    "uncertaintyFormula": "Ujoint=UDOP853+UIAS15+Ureference+Ufit"
  },
  "denseKerr": {
    "campaignVersion": "finite-observer-v8",
    "profile": "release",
    "plannedRayCount": 3097,
    "plannedShardCount": 49,
    "completedReleaseShardCount": 0,
    "completedRayCount": 0,
    "completedExecutionCount": 0,
    "completedShardIndices": [],
    "rayClassCounts": {},
    "codeSha256": "0debb41b96f001f92f498ef6a36ceff77ede7f0dd2bdbe3c6e9db3dfbf6090a8",
    "environmentSha256": "5cb0191749e1062441ff59108144f9b413cd0767f4c64001b846a2f7fa18ef83",
    "frozenScreenManifestSha256": "08f42a50bc787df62dc018ee56b5f7b58065dcafe2e2a3703e3e67f3e6d94037",
    "finiteObserverScreenManifestSha256": "08f42a50bc787df62dc018ee56b5f7b58065dcafe2e2a3703e3e67f3e6d94037",
    "planSha256": "d4964f7e6a173617cf3a56c525a06faca583b5a0d9588810db0a2753d4166ff5",
    "maxNullConstraint": null,
    "shortGatePassed": true,
    "shortGateExecuted": true,
    "shortGateCanonicalEvidenceSha256": "92dc107dd4412ae809a4ec40abef086e9c3d13b67a97a7819bd6f174ba9025a0",
    "shortGateFailure": null,
    "shortGateEvaluation": {
      "invalidCount": 0,
      "nonPhysicalCount": 0,
      "deterministicFailureCount": 0,
      "criticalTransitionCount": 40,
      "criticalTransitionExpected": 40,
      "maxNullConstraint": 2.3662139126156168e-11
    },
    "historicalV7": {
      "gatePassed": false,
      "criticalTransitionCount": 0,
      "criticalTransitionExpected": 40,
      "canonicalEvidenceSha256": "aae2f88bf26db445a18e3b193619b84ab2b68ea76c146f13403c6a3f0830cea5",
      "retainedAsImmutableNegativeEvidence": true
    },
    "complete": false,
    "gatePassed": false,
    "partialResultsAggregated": false,
    "blocker": "v8-dense-release-shards-incomplete-no-partial-aggregation"
  },
  "variationalStm": {
    "evidenceVersion": "v229-relativity-variational-stm-evidence-v12",
    "profile": "smoke",
    "shortGatePassed": false,
    "deterministicRerunPassed": true,
    "releaseQualificationAvailable": false,
    "effectiveRank": 66,
    "integratedStateAndPhiDimension": 4824,
    "holdoutDays": [
      365
    ],
    "fitIterations": 1,
    "gatePassed": false
  },
  "product": {
    "localGatesPassed": true,
    "standaloneTransferBytes": 592056,
    "liteTransferBytes": 592055,
    "contentPackVerifiedFiles": 805
  },
  "outcome": "relativity-v13-research-candidate-shadow-retained",
  "defaultKernel": "legacy-eih-1pn",
  "runtimePromotionApplied": false,
  "boundary": "offline-research-campaign-no-root-contract-or-runtime-physics-mutation",
  "manifestSha256": "aa85cd0f3dddc7fdd442ba56e4f8714e3e52068c96ee9411127842b5e5d53b83"
} as const;
