import { getAtlasResourceSnapshot, type AtlasRuntimeResourceSnapshot } from "./atlasResourceLifecycle";
import type { KerrScienceImageRoiSummaryV347 } from "./kerrScienceImageRoiV347";
export const ATLAS_SCIENCE_IMAGE_ROI_TELEMETRY_VERSION_V347 = "v347-science-image-roi-telemetry-v1" as const;
export type AtlasScienceImageRoiTelemetryV347 = Readonly<{ version: typeof ATLAS_SCIENCE_IMAGE_ROI_TELEMETRY_VERSION_V347; roiId: string; sampleCount: number; uncertaintyCombination: "componentwise-linear-interval-no-independence-assumed"; celestialWcs: "unavailable"; apertureFlux: "unavailable-no-solid-angle-or-celestial-wcs"; objectUrls: number; typedArrayCaches: number; sceneRevisionDelta: 0; canvasCount: 1; boundary: "local-roi-state-dom-dataset-no-app-shell-render-no-science-mutation" }>;
let current: AtlasScienceImageRoiTelemetryV347 = Object.freeze({ version: ATLAS_SCIENCE_IMAGE_ROI_TELEMETRY_VERSION_V347, roiId: "none", sampleCount: 0, uncertaintyCombination: "componentwise-linear-interval-no-independence-assumed", celestialWcs: "unavailable", apertureFlux: "unavailable-no-solid-angle-or-celestial-wcs", objectUrls: 0, typedArrayCaches: 0, sceneRevisionDelta: 0, canvasCount: 1, boundary: "local-roi-state-dom-dataset-no-app-shell-render-no-science-mutation" });
function write(node: Pick<HTMLElement, "dataset"> | null, value: AtlasScienceImageRoiTelemetryV347): void { if (!node) return; node.dataset.atlasScienceRoiSelectionV347 = value.roiId; node.dataset.atlasScienceRoiSampleCountV347 = String(value.sampleCount); node.dataset.atlasScienceRoiUncertaintyV347 = value.uncertaintyCombination; node.dataset.atlasScienceRoiCelestialWcsV347 = value.celestialWcs; node.dataset.atlasScienceRoiApertureFluxV347 = value.apertureFlux; node.dataset.atlasScienceRoiObjectUrlCountV347 = String(value.objectUrls); }
export function publishAtlasScienceImageRoiTelemetryV347(summary: KerrScienceImageRoiSummaryV347 | null, options: Readonly<{ node?: Pick<HTMLElement, "dataset"> | null; resources?: AtlasRuntimeResourceSnapshot }> = {}): AtlasScienceImageRoiTelemetryV347 { const resources = options.resources ?? getAtlasResourceSnapshot(); current = Object.freeze({ ...current, roiId: summary?.roiId ?? "none", sampleCount: summary?.sampleCount ?? 0, objectUrls: resources.objectUrls, typedArrayCaches: resources.typedArrayCaches }); write(options.node ?? (typeof document === "undefined" ? null : document.querySelector<HTMLElement>("[data-atlas-app-shell]")), current); return current; }
export function getAtlasScienceImageRoiTelemetryV347(): AtlasScienceImageRoiTelemetryV347 { return current; }
export function resetAtlasScienceImageRoiTelemetryV347ForTests(): void { current = Object.freeze({ ...current, roiId: "none", sampleCount: 0, objectUrls: 0, typedArrayCaches: 0 }); }
