/* This file is generated by scripts/build-current-evidence-manifest-v233.mjs. */
export const ATLAS_CURRENT_EVIDENCE_INPUT_V233 = {
  "version": "v233-current-evidence-manifest",
  "generatedAt": "2026-07-18T04:25:24.897637+00:00",
  "sourceSha256": {
    "researchCampaign": "21d56b7942b15806ae5f47d8ad062f18d1533b389a85350f19bd13c8ebc1c290",
    "denseScreen": "4fd9bb849e67529418638d23df16b4c4141a030ffeee189b369870ca62d45495",
    "densePlan": "21d414b7f1be6430686529608e04327d59ee6572ac403f34d9af8e214e3aeaaf",
    "denseAggregate": "2fc25232147fc8affdaadbce6961b5c4f946718fee00ab2d1a687880a39fbe73",
    "kerrGateV8": "306ee73de6b1c7f9b6a62478f93134e612b7978e7d8b874eeae1ac48846c44da",
    "stm": "3eaf637e0b92fc3c1f524f5a1bcf3e38a427373024ed97920042483ffe307340",
    "bundleStandalone": "75d9151bc9a1dfc7b7e5345266da3d521780c5065a0c2948d4c50a6a98eb9137",
    "bundleLite": "305a9c708251c333b577765acb69277f6a5a099b267331f1fbadc9487d7fa73b",
    "lifecycle": "110578969cf27ae8e72320257ca69adce659860848a5f878f6be853e86288a92",
    "contentPacks": "363e5ac16abca8a1b55992491d6cb347c027b0ee5474f90ab1e9bad2f8f155cd",
    "security": "938cfd3b878d1c2319521df1b6b34ed318820a97e55c7ba57973ecf7922b98ca",
    "productionAudit": "1711b1236db435c042e480767a137034c27b92ade4c13c3cc3dd76d518949bb0",
    "secretScan": "92b17cfc8b0ef32fde70d71fdf3d4690ffcb133bec104d964f417ce38eec0900"
  },
  "promotionInput": {
    "legacyPositionRmsKm": 97.4962129987326,
    "legacyVelocityRmsMS": 0.16038441711601498,
    "candidatePositionRmsKm": 97.49777481741557,
    "candidateVelocityRmsMS": 0.16038507156539808,
    "comparativeAggregateImprovementDemonstrated": false,
    "independentPerBodyComparisonComplete": true,
    "perBodyNoRegression": false,
    "effectIsolationComplete": false,
    "supportingGatesPassed": false
  },
  "weakField": {
    "checkpointCount": 3,
    "bodyCount": 12,
    "perBodyRegressionCount": 15,
    "regressionsByCheckpoint": {
      "+30d": 4,
      "+365d": 4,
      "+10y": 7
    },
    "confirmedRegressionCount": 10,
    "attributionCounts": {
      "cross-solver-regression-confirmed": 7,
      "inconclusive": 8
    },
    "effectIsolationComplete": false
  },
  "denseKerr": {
    "campaignVersion": "finite-observer-v8",
    "profile": "release",
    "plannedRayCount": 3097,
    "plannedShardCount": 49,
    "completedReleaseShardCount": 0,
    "completedRayCount": 0,
    "completedExecutionCount": 0,
    "completedShardIndices": [],
    "rayClassCounts": {},
    "codeSha256": "0debb41b96f001f92f498ef6a36ceff77ede7f0dd2bdbe3c6e9db3dfbf6090a8",
    "environmentSha256": "5cb0191749e1062441ff59108144f9b413cd0767f4c64001b846a2f7fa18ef83",
    "frozenScreenManifestSha256": "08f42a50bc787df62dc018ee56b5f7b58065dcafe2e2a3703e3e67f3e6d94037",
    "finiteObserverScreenManifestSha256": "08f42a50bc787df62dc018ee56b5f7b58065dcafe2e2a3703e3e67f3e6d94037",
    "planSha256": "d4964f7e6a173617cf3a56c525a06faca583b5a0d9588810db0a2753d4166ff5",
    "maxNullConstraint": null,
    "shortGatePassed": true,
    "shortGateExecuted": true,
    "shortGateCanonicalEvidenceSha256": "92dc107dd4412ae809a4ec40abef086e9c3d13b67a97a7819bd6f174ba9025a0",
    "shortGateFailure": null,
    "shortGateEvaluation": {
      "invalidCount": 0,
      "nonPhysicalCount": 0,
      "deterministicFailureCount": 0,
      "criticalTransitionCount": 40,
      "criticalTransitionExpected": 40,
      "maxNullConstraint": 2.3662139126156168e-11
    },
    "historicalV7": {
      "gatePassed": false,
      "criticalTransitionCount": 0,
      "criticalTransitionExpected": 40,
      "canonicalEvidenceSha256": "aae2f88bf26db445a18e3b193619b84ab2b68ea76c146f13403c6a3f0830cea5",
      "retainedAsImmutableNegativeEvidence": true
    },
    "complete": false,
    "gatePassed": false,
    "partialResultsAggregated": false,
    "blocker": "v8-dense-release-shards-incomplete-no-partial-aggregation"
  },
  "variationalStm": {
    "evidenceVersion": "v229-relativity-variational-stm-evidence-v12",
    "profile": "smoke",
    "shortGatePassed": false,
    "deterministicRerunPassed": true,
    "releaseQualificationAvailable": false,
    "effectiveRank": 66,
    "integratedStateAndPhiDimension": 4824,
    "holdoutDays": [
      365
    ],
    "fitIterations": 1,
    "gatePassed": false
  },
  "product": {
    "gates": {
      "contentPacks": true,
      "standaloneBundle": true,
      "liteBundle": true,
      "lifecycle": true,
      "security": true,
      "productionAudit": true,
      "secretScan": true
    },
    "localProductGatesPassed": true,
    "bundles": {
      "standaloneTransferBytes": 592056,
      "liteTransferBytes": 592055,
      "hardLimitBytes": 614400,
      "engineeringTargetBytes": 604160
    },
    "contentPacks": {
      "packCount": 6,
      "manifestFileCount": 805,
      "verifiedFileCount": 805
    }
  },
  "boundary": "generated-current-evidence-no-root-contract-or-runtime-physics-mutation",
  "manifestSha256": "6358335961ca2cb20771e644f50542dca20edbe588f4f900a94111d1d8c4c0cb"
} as const;
