import { createHash } from "node:crypto";
import { parseKerrStokesTransferArtifactV406, type KerrStokesTransferArtifactV406 } from "./kerrStokesTransferV406";
import { parseKerrPolarizationOrientationBasisArtifactV422, type KerrPolarizationOrientationBasisArtifactV422 } from "./kerrPolarizationOrientationBasisV422";

export const KERR_PREDICTED_STOKES_VERSION_V423 = "v423-kerr-predicted-stokes-WCS-admission-v1" as const;
export const KERR_PREDICTED_STOKES_ARTIFACT_VERSION_V423 = "v423-kerr-predicted-stokes-WCS-admission-artifact-v1" as const;
export const KERR_PREDICTED_STOKES_SUMMARY_VERSION_V423 = "v423-kerr-predicted-stokes-WCS-admission-summary-v1" as const;
export const KERR_PREDICTED_STOKES_RESPONSE_VERSION_V423 = "v423-kerr-predicted-stokes-WCS-admission-response-v1" as const;
export const KERR_V406_ARTIFACT_SHA256_V423 = "92830ac3ac89856664fcfbfd00f698b02aa6daa851463de9dc019bfc207e8038" as const;
export const KERR_V406_FILE_SHA256_V423 = "3abf793d1bf53407de93f5ab34abfc3c7eb9fefdfe4b4a1ee505fa802eb3023a" as const;
export const KERR_V422_ARTIFACT_SHA256_V423 = "b087df36d8afe38d73e7afefbd711398e71f31d1d0e7e569d38af07a7e8cfc20" as const;
export const KERR_V422_FILE_SHA256_V423 = "29953d0a54dbc841c9029c4553bf3566ba664b4c9b231ed5dd09da9b324a02f9" as const;
type Method = "walker-penrose" | "independent-ks-parallel-transport";
type RayId = "disk-00" | "disk-01" | "disk-02" | "disk-03";
export type KerrPredictedStokesRowV423 = Readonly<{ rayId: RayId; rayIndex: 12 | 13 | 14 | 15; spinA: number; observedFrequencyHz: number; transportMethod: Method; continuousCoordinate: Readonly<{ pixelX: number; pixelY: number; semantics: "FITS-1-based-continuous-source-coordinate-not-pixel-sample" }>; evpaDeg: number; predictedSpectralStokes: Readonly<{ i: number; q: number; u: number; v: null; linearAmplitude: number; linearFraction: number; unit: "W m^-2 sr^-1 Hz^-1" }>; normalizedOrientation: Readonly<{ qOverI: number; uOverI: number; qHat: number; uHat: number; normalizedQBasisResidual: number; normalizedUBasisResidual: number; linearFractionResidual: number }>; provenance: Readonly<{ source: "v406-derived-thin-disk-vacuum-transfer"; predictionNotMeasurement: true; detectorProjectionApplied: false; absoluteObservedCountsAvailable: false }>; uncertainty: Readonly<{ diskQuadratureRelative: number; formulaSpectralRelative: number; geometryRadiusDifferenceM: number; geometryRedshiftDifference: number; combination: "componentwise-no-rss-no-scalar-total" }>; pixelSampleAvailable: false; interpolationAllowed: false }>;
export type KerrPredictedStokesViewV423 = Readonly<{ version: typeof KERR_PREDICTED_STOKES_VERSION_V423; status: "qualified-24-sparse-model-predicted-stokes-rows-WCS-linked-measurement-authority-unavailable"; source: Readonly<{ v406ArtifactSha256: typeof KERR_V406_ARTIFACT_SHA256_V423; v422ArtifactSha256: typeof KERR_V422_ARTIFACT_SHA256_V423 }>; model: Readonly<{ kind: "Novikov-Thorne-thin-disk-derived-spectral-Stokes-prediction"; emittedLinearPolarizationFraction: 0.12; propagation: "vacuum-geometric-optics-no-emission-absorption-scattering-after-disk"; circularV: "unavailable-not-modeled" }>; counts: Readonly<{ rayCount: 4; frequencyCount: 3; transportMethodCount: 2; predictionRowCount: 24; measuredRowCount: 0; pixelSampleCount: 0 }>; units: Readonly<{ frequency: "Hz"; spectralStokes: "W m^-2 sr^-1 Hz^-1"; evpa: "deg modulo 180" }>; rows: readonly KerrPredictedStokesRowV423[]; maxima: Readonly<{ normalizedQBasisResidual: number; normalizedUBasisResidual: number; linearFractionResidual: number; physicalConeViolation: number; v422EvpaDifferenceDeg: number; v422BasisDifference: number; pythonOracleDifference: number }>; thresholds: Readonly<{ normalizedBasisResidual: 1e-12; linearFractionResidual: 1e-12; physicalConeViolation: 0; identityEvpaDifferenceDeg: 1e-10; identityBasisDifference: 1e-10; pythonOracleDifference: 1e-12 }>; authorityBoundary: Readonly<{ modelPredictionQualified: true; measurementAuthorityGranted: false; detectorAuthorityGranted: false; pixelAuthorityGranted: false; rasterAuthorityGranted: false; denseAuthorityGranted: false; unavailableIsNotZero: true }>; products: Readonly<{ json: "available-24-row-predicted-Stokes-catalog"; csv: "available-24-row-predicted-Stokes-catalog"; fitsBinaryTable: "available-WCS-coordinate-plus-predicted-Stokes-table-no-image-data"; png: "available-sparse-prediction-diagnostic-not-science-raster"; fitsImage: "unavailable-no-raster-science-values"; measuredStokesCube: "unavailable-no-measurement-authority" }>; scienceCinematicBoundary: Readonly<{ science: "immutable-model-predicted-spectral-I-Q-U-and-provenance"; cinematic: "may-style-panels-glyphs-and-log-intensity-display-only"; predictedValueMutationAllowed: false; measurementClaimAllowed: false; pixelInterpolationAllowed: false }>; denseCampaignStatus: "incomplete-0-of-49"; browserQualification: "not-run"; boundary: "sparse-model-predicted-Stokes-at-continuous-WCS-coordinates-no-measurement-detector-pixel-raster-or-dense-authority" }>;
export type KerrPredictedStokesArtifactV423 = Readonly<{ version: typeof KERR_PREDICTED_STOKES_ARTIFACT_VERSION_V423; generatedAt: string; status: KerrPredictedStokesViewV423["status"]; sourceFiles: Readonly<{ v406FileSha256: typeof KERR_V406_FILE_SHA256_V423; v422FileSha256: typeof KERR_V422_FILE_SHA256_V423; pythonOracleFileSha256: string }>; pythonOracleArtifactSha256: string; view: KerrPredictedStokesViewV423; deterministicReplay: true; networkAttempted: false; denseShardExecuted: false; rasterGenerated: false; measurementAuthorityGranted: false; artifactSha256: string }>;
export type KerrPredictedStokesSummaryV423 = Readonly<{ version: typeof KERR_PREDICTED_STOKES_SUMMARY_VERSION_V423; status: KerrPredictedStokesViewV423["status"]; artifactSha256: string; model: KerrPredictedStokesViewV423["model"]; counts: KerrPredictedStokesViewV423["counts"]; units: KerrPredictedStokesViewV423["units"]; referenceFrequencyHz: 1e17; referenceRows: readonly KerrPredictedStokesRowV423[]; maxima: KerrPredictedStokesViewV423["maxima"]; authorityBoundary: KerrPredictedStokesViewV423["authorityBoundary"]; products: KerrPredictedStokesViewV423["products"]; denseCampaignStatus: "incomplete-0-of-49"; fullArtifactAvailable: true; boundary: "bounded-eight-reference-rows-no-full-spectrum-or-raster-array-in-react-state" }>;
export type KerrPredictedStokesResponseV423 = Readonly<{ version: typeof KERR_PREDICTED_STOKES_RESPONSE_VERSION_V423; available: boolean; reason: "ready" | "lite-boundary" | "local-shadow-only" | "evidence-corrupt" | "request-failed"; summary: KerrPredictedStokesSummaryV423 | null }>;
type Oracle = Readonly<{ version: string; status: string; rows: readonly Readonly<{ rayId: string; rayIndex: number; observedFrequencyHz: number; transportMethod: string; continuousPixelX: number; continuousPixelY: number; qHat: number; uHat: number; qNormalized: number; uNormalized: number }>[]; maxima: Readonly<Record<string, number>>; artifactSha256: string }>;
const SHA = /^[a-f0-9]{64}$/; const transient = new Set(["generatedAt", "artifactSha256"]);
function canonicalize(value: unknown): unknown { if (Array.isArray(value)) return value.map(canonicalize); if (!value || typeof value !== "object") return value; return Object.fromEntries(Object.entries(value as Record<string, unknown>).filter(([key]) => !transient.has(key)).sort(([left], [right]) => left.localeCompare(right)).map(([key, entry]) => [key, canonicalize(entry)])); }
export const canonicalShaV423 = (value: unknown): string => createHash("sha256").update(JSON.stringify(canonicalize(value))).digest("hex");
const finite = (...values: number[]) => values.every(Number.isFinite);
export function createKerrPredictedStokesViewV423(v406Value: unknown, v422Value: unknown, oracleValue: unknown): KerrPredictedStokesViewV423 {
  const v406: KerrStokesTransferArtifactV406 = parseKerrStokesTransferArtifactV406(v406Value), v422: KerrPolarizationOrientationBasisArtifactV422 = parseKerrPolarizationOrientationBasisArtifactV422(v422Value), oracle = oracleValue as Oracle;
  if (v406.artifactSha256 !== KERR_V406_ARTIFACT_SHA256_V423 || v422.artifactSha256 !== KERR_V422_ARTIFACT_SHA256_V423 || oracle.version !== "v423-kerr-predicted-stokes-admission-python-oracle-v1" || oracle.status !== "qualified-sparse-model-predicted-stokes-WCS-identity-no-measurement-authority" || !SHA.test(oracle.artifactSha256) || oracle.rows?.length !== 24 || !oracle.maxima) throw new Error("v423-source-lock");
  let pythonOracleDifference = 0;
  const rows = v406.view.samples.map((sample): KerrPredictedStokesRowV423 => { const basis = v422.view.rows.find((entry) => entry.rayId === sample.rayId && entry.rayIndex === sample.rayIndex && entry.spinA === sample.spinA); const oracleRow = oracle.rows.find((entry) => entry.rayId === sample.rayId && entry.rayIndex === sample.rayIndex && entry.observedFrequencyHz === sample.observedFrequencyHz && entry.transportMethod === sample.transportMethod); if (!basis || !oracleRow) throw new Error(`v423-row-identity:${sample.rayId}`); const chi = sample.evpaDeg * Math.PI / 180, qHat = Math.cos(2 * chi), uHat = Math.sin(2 * chi), qOverI = sample.observedStokes.q / sample.observedStokes.i, uOverI = sample.observedStokes.u / sample.observedStokes.i, linearFraction = sample.observedStokes.linearAmplitude / sample.observedStokes.i; const normalizedQBasisResidual = Math.abs(qOverI - linearFraction * qHat), normalizedUBasisResidual = Math.abs(uOverI - linearFraction * uHat), linearFractionResidual = Math.abs(linearFraction - 0.12); pythonOracleDifference = Math.max(pythonOracleDifference, Math.abs(qHat - oracleRow.qHat), Math.abs(uHat - oracleRow.uHat), Math.abs(qOverI - oracleRow.qNormalized), Math.abs(uOverI - oracleRow.uNormalized), Math.abs(basis.continuousCoordinate.pixelX - oracleRow.continuousPixelX), Math.abs(basis.continuousCoordinate.pixelY - oracleRow.continuousPixelY)); return Object.freeze({ rayId: sample.rayId, rayIndex: sample.rayIndex, spinA: sample.spinA, observedFrequencyHz: sample.observedFrequencyHz, transportMethod: sample.transportMethod, continuousCoordinate: basis.continuousCoordinate, evpaDeg: sample.evpaDeg, predictedSpectralStokes: Object.freeze({ i: sample.observedStokes.i, q: sample.observedStokes.q, u: sample.observedStokes.u, v: null, linearAmplitude: sample.observedStokes.linearAmplitude, linearFraction, unit: "W m^-2 sr^-1 Hz^-1" }), normalizedOrientation: Object.freeze({ qOverI, uOverI, qHat, uHat, normalizedQBasisResidual, normalizedUBasisResidual, linearFractionResidual }), provenance: Object.freeze({ source: "v406-derived-thin-disk-vacuum-transfer", predictionNotMeasurement: true, detectorProjectionApplied: false, absoluteObservedCountsAvailable: false }), uncertainty: Object.freeze({ ...sample.sourceUncertainty, combination: "componentwise-no-rss-no-scalar-total" }), pixelSampleAvailable: false, interpolationAllowed: false }); });
  const axial = (left: number, right: number) => { const d = Math.abs(left - right) % 180; return Math.min(d, 180 - d); };
  const maxima = Object.freeze({ normalizedQBasisResidual: Math.max(...rows.map((row) => row.normalizedOrientation.normalizedQBasisResidual)), normalizedUBasisResidual: Math.max(...rows.map((row) => row.normalizedOrientation.normalizedUBasisResidual)), linearFractionResidual: Math.max(...rows.map((row) => row.normalizedOrientation.linearFractionResidual)), physicalConeViolation: Math.max(...rows.map((row) => Math.max(0, row.predictedSpectralStokes.linearAmplitude - row.predictedSpectralStokes.i))), v422EvpaDifferenceDeg: Math.max(...rows.map((row) => axial(row.evpaDeg, v422.view.rows.find((entry) => entry.rayId === row.rayId)!.authorityEvpaDeg))), v422BasisDifference: Math.max(...rows.map((row) => { const basis = v422.view.rows.find((entry) => entry.rayId === row.rayId)!.orientationBasis; return Math.max(Math.abs(row.normalizedOrientation.qHat - basis.qHat), Math.abs(row.normalizedOrientation.uHat - basis.uHat)); })), pythonOracleDifference });
  if (rows.length !== 24 || rows.some((row) => !finite(row.predictedSpectralStokes.i, row.predictedSpectralStokes.q, row.predictedSpectralStokes.u) || row.predictedSpectralStokes.i <= 0 || row.predictedSpectralStokes.v !== null || row.pixelSampleAvailable !== false || row.interpolationAllowed !== false) || maxima.normalizedQBasisResidual >= 1e-12 || maxima.normalizedUBasisResidual >= 1e-12 || maxima.linearFractionResidual >= 1e-12 || maxima.physicalConeViolation !== 0 || maxima.v422EvpaDifferenceDeg >= 1e-10 || maxima.v422BasisDifference >= 1e-10 || maxima.pythonOracleDifference >= 1e-12) throw new Error(`v423-admission-gate:${JSON.stringify(maxima)}`);
  return Object.freeze({ version: KERR_PREDICTED_STOKES_VERSION_V423, status: "qualified-24-sparse-model-predicted-stokes-rows-WCS-linked-measurement-authority-unavailable", source: Object.freeze({ v406ArtifactSha256: KERR_V406_ARTIFACT_SHA256_V423, v422ArtifactSha256: KERR_V422_ARTIFACT_SHA256_V423 }), model: Object.freeze({ kind: "Novikov-Thorne-thin-disk-derived-spectral-Stokes-prediction", emittedLinearPolarizationFraction: 0.12, propagation: "vacuum-geometric-optics-no-emission-absorption-scattering-after-disk", circularV: "unavailable-not-modeled" }), counts: Object.freeze({ rayCount: 4, frequencyCount: 3, transportMethodCount: 2, predictionRowCount: 24, measuredRowCount: 0, pixelSampleCount: 0 }), units: Object.freeze({ frequency: "Hz", spectralStokes: "W m^-2 sr^-1 Hz^-1", evpa: "deg modulo 180" }), rows: Object.freeze(rows), maxima, thresholds: Object.freeze({ normalizedBasisResidual: 1e-12, linearFractionResidual: 1e-12, physicalConeViolation: 0, identityEvpaDifferenceDeg: 1e-10, identityBasisDifference: 1e-10, pythonOracleDifference: 1e-12 }), authorityBoundary: Object.freeze({ modelPredictionQualified: true, measurementAuthorityGranted: false, detectorAuthorityGranted: false, pixelAuthorityGranted: false, rasterAuthorityGranted: false, denseAuthorityGranted: false, unavailableIsNotZero: true }), products: Object.freeze({ json: "available-24-row-predicted-Stokes-catalog", csv: "available-24-row-predicted-Stokes-catalog", fitsBinaryTable: "available-WCS-coordinate-plus-predicted-Stokes-table-no-image-data", png: "available-sparse-prediction-diagnostic-not-science-raster", fitsImage: "unavailable-no-raster-science-values", measuredStokesCube: "unavailable-no-measurement-authority" }), scienceCinematicBoundary: Object.freeze({ science: "immutable-model-predicted-spectral-I-Q-U-and-provenance", cinematic: "may-style-panels-glyphs-and-log-intensity-display-only", predictedValueMutationAllowed: false, measurementClaimAllowed: false, pixelInterpolationAllowed: false }), denseCampaignStatus: "incomplete-0-of-49", browserQualification: "not-run", boundary: "sparse-model-predicted-Stokes-at-continuous-WCS-coordinates-no-measurement-detector-pixel-raster-or-dense-authority" });
}
export function parseKerrPredictedStokesArtifactV423(value: unknown): KerrPredictedStokesArtifactV423 { const source = value && typeof value === "object" && !Array.isArray(value) ? value as Partial<KerrPredictedStokesArtifactV423> : null; if (!source || source.version !== KERR_PREDICTED_STOKES_ARTIFACT_VERSION_V423 || source.status !== "qualified-24-sparse-model-predicted-stokes-rows-WCS-linked-measurement-authority-unavailable" || source.sourceFiles?.v406FileSha256 !== KERR_V406_FILE_SHA256_V423 || source.sourceFiles.v422FileSha256 !== KERR_V422_FILE_SHA256_V423 || !SHA.test(source.sourceFiles.pythonOracleFileSha256 ?? "") || !SHA.test(source.pythonOracleArtifactSha256 ?? "") || source.view?.rows?.length !== 24 || source.view.counts.measuredRowCount !== 0 || source.view.authorityBoundary.measurementAuthorityGranted !== false || source.view.rows.some((row) => row.predictedSpectralStokes.v !== null || row.provenance.predictionNotMeasurement !== true || row.pixelSampleAvailable !== false || row.interpolationAllowed !== false) || source.deterministicReplay !== true || source.networkAttempted !== false || source.denseShardExecuted !== false || source.rasterGenerated !== false || source.measurementAuthorityGranted !== false || !SHA.test(source.artifactSha256 ?? "")) throw new Error("v423-artifact-identity"); return value as KerrPredictedStokesArtifactV423; }
export function createKerrPredictedStokesSummaryV423(value: unknown): KerrPredictedStokesSummaryV423 { const artifact = parseKerrPredictedStokesArtifactV423(value); return Object.freeze({ version: KERR_PREDICTED_STOKES_SUMMARY_VERSION_V423, status: artifact.status, artifactSha256: artifact.artifactSha256, model: artifact.view.model, counts: artifact.view.counts, units: artifact.view.units, referenceFrequencyHz: 1e17, referenceRows: Object.freeze(artifact.view.rows.filter((row) => row.observedFrequencyHz === 1e17)), maxima: artifact.view.maxima, authorityBoundary: artifact.view.authorityBoundary, products: artifact.view.products, denseCampaignStatus: "incomplete-0-of-49", fullArtifactAvailable: true, boundary: "bounded-eight-reference-rows-no-full-spectrum-or-raster-array-in-react-state" }); }
export function parseKerrPredictedStokesSummaryV423(value: unknown): KerrPredictedStokesSummaryV423 { const source = value && typeof value === "object" && !Array.isArray(value) ? value as Partial<KerrPredictedStokesSummaryV423> : null; if (!source || source.version !== KERR_PREDICTED_STOKES_SUMMARY_VERSION_V423 || !SHA.test(source.artifactSha256 ?? "") || source.counts?.predictionRowCount !== 24 || source.counts.measuredRowCount !== 0 || source.referenceRows?.length !== 8 || source.authorityBoundary?.measurementAuthorityGranted !== false || source.products?.measuredStokesCube !== "unavailable-no-measurement-authority" || source.boundary !== "bounded-eight-reference-rows-no-full-spectrum-or-raster-array-in-react-state") throw new Error("v423-summary-identity"); return value as KerrPredictedStokesSummaryV423; }
export function parseKerrPredictedStokesResponseV423(value: unknown): KerrPredictedStokesResponseV423 { const source = value && typeof value === "object" && !Array.isArray(value) ? value as Partial<KerrPredictedStokesResponseV423> : null; if (!source || source.version !== KERR_PREDICTED_STOKES_RESPONSE_VERSION_V423) throw new Error("v423-response-version"); if (source.available === true && source.reason === "ready" && source.summary) return Object.freeze({ ...source, summary: parseKerrPredictedStokesSummaryV423(source.summary) }) as KerrPredictedStokesResponseV423; if (source.available === false && source.summary === null && ["lite-boundary", "local-shadow-only", "evidence-corrupt", "request-failed"].includes(source.reason ?? "")) return source as KerrPredictedStokesResponseV423; throw new Error("v423-response-identity"); }
export function serializeKerrPredictedStokesCsvV423(view: KerrPredictedStokesViewV423): string { const header = ["ray_id", "ray_index", "spin_a", "observed_frequency_Hz", "transport_method", "continuous_pixel_x_fits1", "continuous_pixel_y_fits1", "evpa_deg", "predicted_I", "predicted_Q", "predicted_U", "predicted_V", "linear_amplitude", "linear_fraction", "q_over_I", "u_over_I", "unit", "model_prediction", "measurement_authority", "pixel_sample_available", "interpolation_allowed"]; const rows = view.rows.map((row) => [row.rayId, row.rayIndex, row.spinA, row.observedFrequencyHz, row.transportMethod, row.continuousCoordinate.pixelX, row.continuousCoordinate.pixelY, row.evpaDeg, row.predictedSpectralStokes.i, row.predictedSpectralStokes.q, row.predictedSpectralStokes.u, "", row.predictedSpectralStokes.linearAmplitude, row.predictedSpectralStokes.linearFraction, row.normalizedOrientation.qOverI, row.normalizedOrientation.uOverI, row.predictedSpectralStokes.unit, true, false, row.pixelSampleAvailable, row.interpolationAllowed]); return `${[header, ...rows].map((row) => row.join(",")).join("\n")}\n`; }
