"use client";
import { acquireAtlasResource } from "./atlasResourceLifecycle";
import { parseKerrIndependentFitsValidationApiV546, type KerrIndependentFitsValidationArtifactV546 } from "./kerrIndependentFitsValidationV546";
type SnapshotV546 = Readonly<{ status: "idle" | "loading" | "ready" | "unavailable"; reason: string | null; requestCount: 0 | 1; responseBytes: number; summary: KerrIndependentFitsValidationArtifactV546 | null }>;
const INITIAL: SnapshotV546 = Object.freeze({ status: "idle", reason: null, requestCount: 0, responseBytes: 0, summary: null });
const listeners = new Set<() => void>(); let snapshot = INITIAL; let requestPromise: Promise<KerrIndependentFitsValidationArtifactV546> | null = null;
const publish = (next: SnapshotV546) => { snapshot = Object.freeze(next); listeners.forEach((listener) => listener()); };
export function loadKerrIndependentFitsValidationSummaryV546(): Promise<KerrIndependentFitsValidationArtifactV546> { if (requestPromise) return requestPromise; publish({ status: "loading", reason: null, requestCount: 1, responseBytes: 0, summary: null }); requestPromise = fetch("/api/atlas/relativity-evidence/v546/independent-fits-validation", { cache: "no-store" }).then(async (response) => { const body = await response.text(), responseBytes = new TextEncoder().encode(body).byteLength; if (responseBytes > 128 * 1024) throw new Error("response-too-large"); const api = parseKerrIndependentFitsValidationApiV546(JSON.parse(body)); if (!response.ok || !api.available || !api.summary) throw new Error(`v546-independent-fits-${api.reason}`); publish({ status: "ready", reason: null, requestCount: 1, responseBytes, summary: api.summary }); return api.summary; }).catch((error: unknown) => { publish({ status: "unavailable", reason: error instanceof Error ? error.message : "request-failed", requestCount: 1, responseBytes: snapshot.responseBytes, summary: null }); throw error; }); return requestPromise; }
export const getKerrIndependentFitsValidationSnapshotV546 = () => snapshot;
export function subscribeKerrIndependentFitsValidationV546(listener: () => void): () => void { listeners.add(listener); const release = acquireAtlasResource("subscription", "relativity-lab", "v546-independent-fits-validation", { owner: "v546-independent-fits-validation", estimatedBytes: 0 }); let done = false; return () => { if (done) return; done = true; listeners.delete(listener); release(); }; }
export function getKerrIndependentFitsValidationTelemetryV546() { return Object.freeze({ listenerCount: listeners.size, requestCount: snapshot.requestCount, status: snapshot.status }); }
export function resetKerrIndependentFitsValidationClientForTestsV546(): void { if (listeners.size) throw new Error("v546-listener-leak"); snapshot = INITIAL; requestPromise = null; }
