export const KERR_SPARSE_COORDINATE_PRODUCTS_VERSION_V557 = "v557-kerr-sparse-coordinate-products-v1" as const;
export const KERR_SPARSE_COORDINATE_PRODUCTS_API_VERSION_V557 = "v557-kerr-sparse-coordinate-products-api-v1" as const;
const SHA = /^[0-9a-f]{64}$/;
const TRANSIENT = new Set(["generatedAt", "artifactSha256", "evidenceSha256", "pointerSha256", "resultSha256"]);
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const canonicalize = (value: unknown): unknown => Array.isArray(value) ? value.map(canonicalize) : !isRecord(value) ? value : Object.fromEntries(Object.entries(value).filter(([key]) => !TRANSIENT.has(key)).sort(([left], [right]) => left.localeCompare(right)).map(([key, entry]) => [key, canonicalize(entry)]));
export const canonicalKerrSparseCoordinateProductsV557 = (value: unknown) => JSON.stringify(canonicalize(value));
export type KerrSparseCoordinateProductV557 = Readonly<{ id: "fits" | "csv"; path: string; mimeType: string; fileSha256: string; bytes: number; pixelReadbackSha256?: string; primaryShape?: readonly [4, 256, 256]; hduCount?: 2; rayIndexRows?: 16; rowCount?: 16 }>;
export type KerrSparseCoordinateProductsArtifactV557 = Readonly<{
  version: typeof KERR_SPARSE_COORDINATE_PRODUCTS_VERSION_V557;
  status: "qualified-sparse-screen-coordinate-and-ray-index-products";
  source: Readonly<{ v556ArtifactSha256: string; v556EvidenceSha256: string; v555ArtifactSha256: string; payloadSha256: string; rasterSha256: string; validatorFileSha256: string }>;
  contract: Readonly<{ coordinateFrame: "finite-distance-zamo-screen-alpha-beta-in-M"; notCelestialWcs: true; alphaRangeM: readonly [-22, 22]; betaRangeM: readonly [-16, 16]; width: 256; height: 256; alphaPixelScaleM: number; betaPixelScaleM: number; referencePixelFits: readonly [128.5, 128.5]; roundingMode: "floor(x+0.5)"; tablePixelOrigin: "zero-based"; fitsPixelOrigin: "one-based"; exactAuthorityCoordinatesRetained: true; quantizedCenterCoordinatesRetained: true; pixelReadbackRequired: true }>;
  products: readonly KerrSparseCoordinateProductV557[];
  validation: Readonly<{ contractPath: string; contractFileSha256: string; receiptPath: string; receiptFileSha256: string; receiptResultSha256: string; independentSubprocessAttemptCount: 2; qualifiedSubprocessCount: 2; abCanonicalIdentical: true; fitsChecksumQualified: true; fitsCsvCrosscheckQualified: true; primaryPixelReadbackSha256: string; maxAlphaQuantizationErrorM: number; maxBetaQuantizationErrorM: number }>;
  mutationAudit: Readonly<{ mutationCount: 10; rejectedMutationCount: 10; mutations: readonly string[] }>;
  counts: Readonly<{ authorityRayCount: 16; captureCount: 6; escapeCount: 6; diskHitCount: 4; rayIndexRowCount: 16; fitsHduCount: 2; coordinateAxisCount: 2; channelAxisCount: 1; measuredPixelCount: 0; observedFrameCount: 0 }>;
  qualification: Readonly<{ coordinateSemanticsQualified: true; rayIndexQualified: true; fitsCsvCrosscheckQualified: true; pixelReadbackQualified: true; denseScienceImageQualified: false; observedScienceImageQualified: false; measuredAuthorityGranted: false; productionPromotionQualified: false }>;
  boundary: Readonly<{ denseCampaignStatus: "incomplete-0-of-49"; denseAggregateAvailable: false; measuredFrameAvailable: false; browserQualification: "not-run"; localShadowOnly: true; formalProductPointer: "v263"; formalDefaultKernel: "legacy-eih-1pn" }>;
  environment: Readonly<{ python: string; numpy: string; astropy: string }>;
  sourceManifest: readonly Readonly<{ path: string; sha256: string }>[];
  sourceSha256: string;
  artifactSha256: string;
}>;
export function parseKerrSparseCoordinateProductsV557(value: unknown): KerrSparseCoordinateProductsArtifactV557 {
  if (!isRecord(value) || value.version !== KERR_SPARSE_COORDINATE_PRODUCTS_VERSION_V557 || value.status !== "qualified-sparse-screen-coordinate-and-ray-index-products" || !SHA.test(String(value.artifactSha256)) || !SHA.test(String(value.sourceSha256))) throw new Error("v557-coordinate-artifact-boundary");
  const artifact = value as unknown as KerrSparseCoordinateProductsArtifactV557, fits = artifact.products.find((product) => product.id === "fits"), csv = artifact.products.find((product) => product.id === "csv");
  if (!fits || !csv || artifact.products.length !== 2 || !SHA.test(fits.fileSha256) || !SHA.test(csv.fileSha256) || fits.bytes <= 0 || csv.bytes <= 0 || JSON.stringify(fits.primaryShape) !== JSON.stringify([4, 256, 256]) || fits.hduCount !== 2 || fits.rayIndexRows !== 16 || csv.rowCount !== 16 || artifact.contract.coordinateFrame !== "finite-distance-zamo-screen-alpha-beta-in-M" || artifact.contract.notCelestialWcs !== true || JSON.stringify(artifact.contract.alphaRangeM) !== JSON.stringify([-22, 22]) || JSON.stringify(artifact.contract.betaRangeM) !== JSON.stringify([-16, 16]) || artifact.contract.width !== 256 || artifact.contract.height !== 256 || artifact.contract.roundingMode !== "floor(x+0.5)" || artifact.contract.tablePixelOrigin !== "zero-based" || artifact.contract.fitsPixelOrigin !== "one-based" || artifact.contract.exactAuthorityCoordinatesRetained !== true || artifact.contract.quantizedCenterCoordinatesRetained !== true || artifact.contract.pixelReadbackRequired !== true || artifact.validation.independentSubprocessAttemptCount !== 2 || artifact.validation.qualifiedSubprocessCount !== 2 || artifact.validation.abCanonicalIdentical !== true || artifact.validation.fitsChecksumQualified !== true || artifact.validation.fitsCsvCrosscheckQualified !== true || !SHA.test(artifact.validation.primaryPixelReadbackSha256) || artifact.mutationAudit.mutationCount !== 10 || artifact.mutationAudit.rejectedMutationCount !== 10 || artifact.counts.authorityRayCount !== 16 || artifact.counts.captureCount !== 6 || artifact.counts.escapeCount !== 6 || artifact.counts.diskHitCount !== 4 || artifact.counts.rayIndexRowCount !== 16 || artifact.counts.fitsHduCount !== 2 || artifact.counts.coordinateAxisCount !== 2 || artifact.counts.channelAxisCount !== 1 || artifact.counts.measuredPixelCount !== 0 || artifact.counts.observedFrameCount !== 0 || artifact.qualification.coordinateSemanticsQualified !== true || artifact.qualification.rayIndexQualified !== true || artifact.qualification.fitsCsvCrosscheckQualified !== true || artifact.qualification.pixelReadbackQualified !== true || artifact.qualification.denseScienceImageQualified !== false || artifact.qualification.observedScienceImageQualified !== false || artifact.qualification.measuredAuthorityGranted !== false || artifact.boundary.denseCampaignStatus !== "incomplete-0-of-49" || artifact.boundary.denseAggregateAvailable !== false || artifact.boundary.measuredFrameAvailable !== false || artifact.boundary.browserQualification !== "not-run" || artifact.boundary.localShadowOnly !== true || artifact.boundary.formalProductPointer !== "v263" || artifact.boundary.formalDefaultKernel !== "legacy-eih-1pn") throw new Error("v557-coordinate-qualification-boundary");
  for (const valueSha of [artifact.source.v556ArtifactSha256, artifact.source.v556EvidenceSha256, artifact.source.v555ArtifactSha256, artifact.source.payloadSha256, artifact.source.rasterSha256, artifact.source.validatorFileSha256, artifact.validation.contractFileSha256, artifact.validation.receiptFileSha256, artifact.validation.receiptResultSha256]) if (!SHA.test(valueSha)) throw new Error("v557-coordinate-sha-boundary");
  return artifact;
}
export type KerrSparseCoordinateProductsApiV557 = Readonly<{ version: typeof KERR_SPARSE_COORDINATE_PRODUCTS_API_VERSION_V557; available: boolean; reason: "ready" | "lite-boundary" | "local-shadow-only" | "evidence-corrupt"; summary: KerrSparseCoordinateProductsArtifactV557 | null }>;
export function parseKerrSparseCoordinateProductsApiV557(value: unknown): KerrSparseCoordinateProductsApiV557 { if (!isRecord(value) || value.version !== KERR_SPARSE_COORDINATE_PRODUCTS_API_VERSION_V557 || typeof value.available !== "boolean" || !["ready", "lite-boundary", "local-shadow-only", "evidence-corrupt"].includes(String(value.reason))) throw new Error("v557-coordinate-api-boundary"); if (value.available) parseKerrSparseCoordinateProductsV557(value.summary); else if (value.summary !== null) throw new Error("v557-coordinate-api-unavailable-summary"); return value as unknown as KerrSparseCoordinateProductsApiV557; }
