export const KERR_OBSERVATION_QUANTITY_PROVENANCE_VERSION_V548 = "v548-kerr-observation-quantity-provenance-admission-v1" as const;
export const KERR_OBSERVATION_QUANTITY_PROVENANCE_API_VERSION_V548 = "v548-kerr-observation-quantity-provenance-admission-api-v1" as const;
export const KERR_OBSERVATION_QUANTITY_PROVENANCE_HUD_PROFILE_ID_V548 = "science-cinematic-v9r7-v548" as const;
const SHA = /^[0-9a-f]{64}$/;
const TRANSIENT = new Set(["generatedAt", "artifactSha256", "payloadSha256", "evidenceSha256", "pointerSha256", "stageChainSha256", "columnSha256", "receiptSha256", "resultSha256", "environmentSha256", "preflightSha256", "matrixSha256", "isolatedReceiptSha256", "executionMatrixSha256", "schemaPackSha256"]);
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const canonicalize = (value: unknown): unknown => Array.isArray(value) ? value.map(canonicalize) : !isRecord(value) ? value : Object.fromEntries(Object.entries(value).filter(([key]) => !TRANSIENT.has(key)).sort(([left], [right]) => left.localeCompare(right)).map(([key, entry]) => [key, canonicalize(entry)]));
export const canonicalKerrObservationQuantityProvenanceV548 = (value: unknown) => JSON.stringify(canonicalize(value));
export type KerrObservationQuantityIdV548 = "classification" | "emissionRadiusM" | "redshift" | "EVPA" | "intensityInvariantResidual" | "effectiveAreaM2" | "throughput" | "nonlinearity" | "physicalUncertainty" | "pixelSample";
export type KerrObservationQuantityProvenanceV548 = Readonly<{ id: KerrObservationQuantityIdV548; valueKind: "categorical" | "float64"; unit: string; sourceLayer: "v436-observation-authority" | "v538-column-schema" | "v545-calibration-intake" | "v546-fits-semantic-validator"; sourceArtifactSha256: string; sourceFileSha256: string; applicability: string; missingness: "not-missing-short-authority" | "measured-input-required" | "unavailable-no-measured-calibration" | "not-a-pixel-sample"; status: "qualified-short-authority" | "schema-qualified-value-missing" | "blocked-measured-input" | "unavailable"; scienceFieldMutation: false }>;
export type KerrObservationQuantityProvenanceAdmissionArtifactV548 = Readonly<{
  version: typeof KERR_OBSERVATION_QUANTITY_PROVENANCE_VERSION_V548;
  status: "observation-quantity-provenance-admission-qualified-measured-inputs-missing";
  source: Readonly<Record<"v436OracleSha256" | "v538ArtifactSha256" | "v545ArtifactSha256" | "v546ArtifactSha256" | "v547ArtifactSha256", string>>;
  contract: Readonly<{ quantityCount: 10; everyQuantityHasUnit: true; everyQuantityHasApplicability: true; everyQuantityHasMissingness: true; sourceArtifactShaRequired: true; sourceFileShaRequired: true; measuredAdmissionRequiresAllSixFiles: true; measuredCalibrationFileCount: 0; requiredMeasuredCalibrationFileCount: 6; measuredValuesMayNotBeSynthesized: true; pixelSamplesRequireObservedFrame: true; physicalUncertaintyCannotMeanZero: true; sciencePayloadImmutable: true; cinematicWritebackForbidden: true; networkAllowed: false; automaticRetryAllowed: false }>;
  quantityRegistry: readonly KerrObservationQuantityProvenanceV548[];
  missingMeasuredInputs: Readonly<{ requiredFileIds: readonly ["collecting-area", "exposure-record", "spectral-response", "observed-frame", "detector-response", "wcs-orientation"]; missingFileCount: 6; missingFileIds: readonly string[]; stagingRootPresent: false; networkAttempted: false }>;
  admission: Readonly<{ v436ObservationPayloadQualified: true; v538InstrumentColumnSchemaQualified: true; v545SupplementalIntakeQualified: true; v546SemanticValidatorQualified: true; v547BlindReviewProtocolQualified: true; v547ReviewDecision: "synthetic-denial-only"; measuredCandidatePresent: false; measuredProvenanceComplete: false; measuredAuthorityGranted: false; scienceRasterQualified: false; reason: "measured-inputs-missing" }>;
  mutationAudit: Readonly<{ mutationCount: 8; rejectedMutationCount: 8; mutations: readonly string[] }>;
  counts: Readonly<{ observationQuantityCount: 10; qualifiedShortAuthorityQuantityCount: 5; schemaQualifiedValueMissingCount: 1; blockedMeasuredInputQuantityCount: 3; unavailableQuantityCount: 1; measuredCalibrationFileCount: 0; measuredCandidateCount: 0; observedFrameCount: 0; sciencePixelCount: 0; physicalUncertaintyValueCount: 0; sciencePayloadMutationCount: 0; cinematicWritebackMutationCount: 0 }>;
  qualification: Readonly<{ observationQuantityRegistryQualified: true; provenanceCompletenessContractQualified: true; instrumentResponseSchemaJoinQualified: true; measuredInputGapAudited: true; sciencePayloadImmutable: true; cinematicReadonlyBoundaryQualified: true; measuredAuthorityGranted: false; scienceRasterQualified: false; productionPromotionQualified: false }>;
  boundary: Readonly<{ provenanceContainsPixelValues: false; measuredValuesInvented: false; sciencePayloadMutationAllowed: false; cinematicScienceWritebackAllowed: false; denseCampaignStatus: "incomplete-0-of-49"; browserQualification: "not-run"; formalProductPointer: "v263"; formalDefaultKernel: "legacy-eih-1pn" }>;
  sourceManifest: readonly Readonly<{ path: string; sha256: string }>[];
  sourceSha256: string;
  artifactSha256: string;
}>;
export type KerrObservationQuantityProvenanceAdmissionApiV548 = Readonly<{ version: typeof KERR_OBSERVATION_QUANTITY_PROVENANCE_API_VERSION_V548; available: boolean; reason: "ready" | "lite-boundary" | "local-shadow-only" | "evidence-corrupt"; summary: KerrObservationQuantityProvenanceAdmissionArtifactV548 | null }>;
function validQuantity(value: unknown): value is KerrObservationQuantityProvenanceV548 { const item = value as Partial<KerrObservationQuantityProvenanceV548> | null; return Boolean(item && typeof item.id === "string" && typeof item.unit === "string" && item.unit.length > 0 && typeof item.sourceLayer === "string" && SHA.test(item.sourceArtifactSha256 ?? "") && SHA.test(item.sourceFileSha256 ?? "") && typeof item.applicability === "string" && item.applicability.length > 0 && typeof item.missingness === "string" && typeof item.status === "string" && item.scienceFieldMutation === false); }
export function parseKerrObservationQuantityProvenanceAdmissionV548(value: unknown): KerrObservationQuantityProvenanceAdmissionArtifactV548 { if (!isRecord(value) || value.version !== KERR_OBSERVATION_QUANTITY_PROVENANCE_VERSION_V548 || value.status !== "observation-quantity-provenance-admission-qualified-measured-inputs-missing" || !SHA.test(String(value.artifactSha256)) || !SHA.test(String(value.sourceSha256))) throw new Error("v548-artifact-boundary"); const artifact = value as unknown as KerrObservationQuantityProvenanceAdmissionArtifactV548; if (artifact.contract.quantityCount !== 10 || artifact.contract.measuredCalibrationFileCount !== 0 || artifact.contract.requiredMeasuredCalibrationFileCount !== 6 || artifact.contract.measuredValuesMayNotBeSynthesized !== true || artifact.contract.pixelSamplesRequireObservedFrame !== true || artifact.contract.physicalUncertaintyCannotMeanZero !== true || artifact.quantityRegistry.length !== 10 || artifact.quantityRegistry.some((entry) => !validQuantity(entry)) || new Set(artifact.quantityRegistry.map((entry) => entry.id)).size !== 10 || artifact.missingMeasuredInputs.missingFileCount !== 6 || artifact.missingMeasuredInputs.stagingRootPresent !== false || artifact.missingMeasuredInputs.networkAttempted !== false || artifact.admission.v547ReviewDecision !== "synthetic-denial-only" || artifact.admission.measuredCandidatePresent !== false || artifact.admission.measuredProvenanceComplete !== false || artifact.admission.measuredAuthorityGranted !== false || artifact.admission.scienceRasterQualified !== false || artifact.mutationAudit.mutationCount !== 8 || artifact.mutationAudit.rejectedMutationCount !== 8 || artifact.counts.measuredCalibrationFileCount !== 0 || artifact.counts.measuredCandidateCount !== 0 || artifact.counts.observedFrameCount !== 0 || artifact.counts.sciencePixelCount !== 0 || artifact.counts.physicalUncertaintyValueCount !== 0 || artifact.qualification.measuredInputGapAudited !== true || artifact.qualification.measuredAuthorityGranted !== false || artifact.qualification.scienceRasterQualified !== false || artifact.boundary.provenanceContainsPixelValues !== false || artifact.boundary.measuredValuesInvented !== false || artifact.boundary.denseCampaignStatus !== "incomplete-0-of-49" || artifact.boundary.formalProductPointer !== "v263" || artifact.boundary.formalDefaultKernel !== "legacy-eih-1pn") throw new Error("v548-qualification-boundary"); return artifact; }
export function parseKerrObservationQuantityProvenanceApiV548(value: unknown): KerrObservationQuantityProvenanceAdmissionApiV548 { if (!isRecord(value) || value.version !== KERR_OBSERVATION_QUANTITY_PROVENANCE_API_VERSION_V548 || typeof value.available !== "boolean" || !["ready", "lite-boundary", "local-shadow-only", "evidence-corrupt"].includes(String(value.reason))) throw new Error("v548-api-boundary"); if (value.available) parseKerrObservationQuantityProvenanceAdmissionV548(value.summary); else if (value.summary !== null) throw new Error("v548-api-unavailable-summary"); return value as unknown as KerrObservationQuantityProvenanceAdmissionApiV548; }
export type KerrObservationQuantityProvenanceHudModeV548 = "science" | "cinematic";
const scienceProfile = Object.freeze({ id: KERR_OBSERVATION_QUANTITY_PROVENANCE_HUD_PROFILE_ID_V548, mode: "science" as const, panel: "#030c12", panelRaised: "#071824", ink: "#effcff", muted: "#7796a7", qualified: "#7beec2", warning: "#f2c371", unavailable: "#ff88a8", scienceBoundary: Object.freeze({ linearDisplay: true, bloomIntensity: 0 as const, colorGradeIntensity: 0 as const, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }), cinematicSeed: null });
const cinematicProfile = Object.freeze({ ...scienceProfile, mode: "cinematic" as const, panel: "#150907", panelRaised: "#27140e", ink: "#fff5e8", muted: "#bd9a80", qualified: "#92ecc5", warning: "#f5bf6e", unavailable: "#ff92ae", scienceBoundary: Object.freeze({ linearDisplay: false, bloomIntensity: 0.031, colorGradeIntensity: 0.02, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }), cinematicSeed: "orbit-atlas-v548-provenance-admission-seed-01" });
export const resolveKerrObservationQuantityProvenanceHudProfileV548 = (mode: KerrObservationQuantityProvenanceHudModeV548) => mode === "science" ? scienceProfile : cinematicProfile;
export function createKerrObservationQuantityProvenanceHudEncodingV548(artifact: KerrObservationQuantityProvenanceAdmissionArtifactV548, mode: KerrObservationQuantityProvenanceHudModeV548) { return Object.freeze({ version: "v548-observation-quantity-provenance-hud-v1" as const, profileId: KERR_OBSERVATION_QUANTITY_PROVENANCE_HUD_PROFILE_ID_V548, mode, artifactKey: artifact.artifactSha256, quantityIds: artifact.quantityRegistry.map((entry) => entry.id), missingFileIds: artifact.missingMeasuredInputs.missingFileIds, measuredAuthorityGranted: false as const, scienceRasterQualified: false as const, measuredValuesInvented: false as const, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }); }
export function compareKerrObservationQuantityProvenanceHudEncodingsV548(science: ReturnType<typeof createKerrObservationQuantityProvenanceHudEncodingV548>, cinematic: ReturnType<typeof createKerrObservationQuantityProvenanceHudEncodingV548>) { if (science.mode !== "science" || cinematic.mode !== "cinematic" || science.artifactKey !== cinematic.artifactKey || JSON.stringify(science.quantityIds) !== JSON.stringify(cinematic.quantityIds) || JSON.stringify(science.missingFileIds) !== JSON.stringify(cinematic.missingFileIds) || science.measuredAuthorityGranted !== cinematic.measuredAuthorityGranted || science.scienceRasterQualified !== cinematic.scienceRasterQualified) throw new Error("v548-hud-boundary"); return Object.freeze({ quantityRegistryStable: true as const, missingInputBoundaryStable: true as const, authorityStable: true as const, rasterQualificationStable: true as const, scientificFieldMutation: false as const }); }
