export const KERR_SUPPLEMENTAL_CALIBRATION_INTAKE_VERSION_V545 = "v545-kerr-supplemental-calibration-intake-artifact-v1" as const;
export const KERR_SUPPLEMENTAL_CALIBRATION_INTAKE_API_VERSION_V545 = "v545-kerr-supplemental-calibration-intake-api-v1" as const;
export const KERR_SUPPLEMENTAL_CALIBRATION_HUD_PROFILE_ID_V545 = "science-cinematic-v9r4-v545" as const;
export const KERR_SUPPLEMENTAL_STAGING_ROOT_V545 = "dist/staging/kerr-supplemental-calibration-v545" as const;
const SHA = /^[0-9a-f]{64}$/;
const TRANSIENT = new Set(["generatedAt", "artifactSha256", "payloadSha256", "evidenceSha256", "pointerSha256", "stageChainSha256", "columnSha256", "receiptSha256", "resultSha256", "environmentSha256", "preflightSha256", "matrixSha256", "isolatedReceiptSha256", "executionMatrixSha256", "schemaPackSha256"]);
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const canonicalize = (value: unknown): unknown => Array.isArray(value) ? value.map(canonicalize) : !isRecord(value) ? value : Object.fromEntries(Object.entries(value).filter(([key]) => !TRANSIENT.has(key)).sort(([left], [right]) => left.localeCompare(right)).map(([key, entry]) => [key, canonicalize(entry)]));
export const canonicalKerrSupplementalCalibrationIntakeV545 = (value: unknown) => JSON.stringify(canonicalize(value));

export type KerrSupplementalCalibrationFileIdV545 = "collecting-area" | "exposure-record" | "spectral-response" | "observed-frame" | "provenance";
export type KerrSupplementalCalibrationFileNameV545 = "collecting-area.json" | "exposure-record.json" | "spectral-response.csv" | "observed-frame.fits" | "provenance.json";
export type KerrSupplementalContentClassV545 = "measured-science-candidate" | "synthetic-validation-fixture";
export type KerrSupplementalCandidateFilesV545 = Readonly<Record<KerrSupplementalCalibrationFileNameV545, Uint8Array>>;
export type KerrSupplementalCandidateValidationV545 = Readonly<{ status: "candidate-ready-for-independent-validation" | "synthetic-fixture-qualified-nonauthoritative" | "invalid"; preflightQualified: boolean; contentClass: KerrSupplementalContentClassV545 | "unavailable"; readyFileCount: number; crossFileIdentityQualified: boolean; provenanceShaLinkageQualified: boolean; fitsContainerPreflightQualified: boolean; fitsSemanticValidation: "pending-independent-astropy-validation" | "not-run"; candidateReadyForIndependentValidation: boolean; measuredAuthorityGranted: false; scienceRasterAllowed: false; reasons: readonly string[] }>;
export type KerrSupplementalCalibrationIntakeArtifactV545 = Readonly<{
  version: typeof KERR_SUPPLEMENTAL_CALIBRATION_INTAKE_VERSION_V545;
  status: "supplemental-intake-protocol-qualified-inputs-missing-science-authority-blocked";
  source: Readonly<Record<"v544ArtifactSha256" | "v544EvidenceSha256" | "v544PointerSha256" | "v458ArtifactSha256" | "v511ArtifactSha256" | "v314StateSha256", string>>;
  contract: Readonly<{ stagingRoot: typeof KERR_SUPPLEMENTAL_STAGING_ROOT_V545; authorityCategoryCount: 4; requiredFileCount: 5; maximumJsonOrCsvFileBytes: number; maximumFitsFileBytes: number; maximumTotalBytes: number; exactWhitelistRequired: true; regularFilesOnly: true; symlinkTraversalAllowed: false; crossFileIdentityRequired: true; provenanceShaForFourInputsRequired: true; fitsIndependentAstropyValidationRequired: true; explicitAuthorityGrantRequired: true; syntheticFixtureMayGrantAuthority: false; networkAllowed: false; automaticRetryAllowed: false }>;
  schemaPack: Readonly<{ version: "v545-supplemental-calibration-schema-pack-v1"; files: readonly Readonly<{ id: KerrSupplementalCalibrationFileIdV545; fileName: KerrSupplementalCalibrationFileNameV545; format: "json" | "csv" | "fits"; authorityCategory: string; status: "missing"; bytes: 0; sha256: null; schemaVersion: string }>[]; schemaPackSha256: string }>;
  inspect: Readonly<{ stagingRootPresent: false; readyFileCount: 0; missingFileCount: 5; missingFileIds: readonly KerrSupplementalCalibrationFileIdV545[]; invalidFileIds: readonly []; bytesRead: 0; attemptConsumed: false; networkAttempted: false; candidateReadyForIndependentValidation: false }>;
  validationFixtures: Readonly<{ acceptedSyntheticFixtureCount: 1; syntheticAuthorityGranted: false; rejectedMutationCount: 8; mutations: readonly string[] }>;
  counts: Readonly<{ authorityCategoryCount: 4; requiredFileCount: 5; readyFileCount: 0; measuredFileCount: 0; spectralResponseRowCount: 0; observedFrameCount: 0; sciencePixelRows: 0; fitsProductCount: 0; pngProductCount: 0 }>;
  qualification: Readonly<{ schemaPackQualified: true; boundedValidatorQualified: true; crossFileIdentityFirewallQualified: true; provenanceShaFirewallQualified: true; syntheticAuthorityFirewallQualified: true; supplementalMeasuredAuthorityGranted: false; electronExpectationQualified: false; scienceRasterQualified: false }>;
  boundary: Readonly<{ filesGeneratedInStaging: false; measuredValuesInvented: false; observedFrameInvented: false; sciencePayloadMutationAllowed: false; cinematicScienceWritebackAllowed: false; denseCampaignStatus: "incomplete-0-of-49"; browserQualification: "not-run"; formalProductPointer: "v263"; formalDefaultKernel: "legacy-eih-1pn" }>;
  sourceManifest: readonly Readonly<{ path: string; sha256: string }>[]; sourceSha256: string; artifactSha256: string;
}>;
export type KerrSupplementalCalibrationIntakeApiV545 = Readonly<{ version: typeof KERR_SUPPLEMENTAL_CALIBRATION_INTAKE_API_VERSION_V545; available: boolean; reason: "ready" | "lite-boundary" | "local-shadow-only" | "evidence-corrupt"; summary: KerrSupplementalCalibrationIntakeArtifactV545 | null }>;

const FILE_NAMES = Object.freeze(["collecting-area.json", "exposure-record.json", "spectral-response.csv", "observed-frame.fits", "provenance.json"] as const);
const text = (bytes: Uint8Array) => new TextDecoder("utf-8", { fatal: true }).decode(bytes);
const json = (bytes: Uint8Array): Record<string, unknown> => { const value: unknown = JSON.parse(text(bytes)); if (!isRecord(value)) throw new Error("json-object-required"); return value; };
const common = (value: Record<string, unknown>) => ({ contentClass: value.contentClass, instrumentId: value.instrumentId, detectorId: value.detectorId, campaignId: value.campaignId });
const validCommon = (value: ReturnType<typeof common>): value is { contentClass: KerrSupplementalContentClassV545; instrumentId: string; detectorId: string; campaignId: string } => [value.instrumentId, value.detectorId, value.campaignId].every((entry) => typeof entry === "string" && entry.trim().length > 0) && (value.contentClass === "measured-science-candidate" || value.contentClass === "synthetic-validation-fixture");
const finite = (value: unknown) => typeof value === "number" && Number.isFinite(value);
const csvRows = (source: string) => source.replace(/\r/g, "").trim().split("\n").map((line) => line.split(","));

export function validateKerrSupplementalCalibrationCandidateV545(files: KerrSupplementalCandidateFilesV545, digest: (value: Uint8Array) => string): KerrSupplementalCandidateValidationV545 {
  const reasons: string[] = [], names = Object.keys(files).sort();
  if (JSON.stringify(names) !== JSON.stringify([...FILE_NAMES].sort())) reasons.push("exact-file-whitelist");
  let total = 0; for (const name of FILE_NAMES) { const size = files[name]?.byteLength ?? 0; total += size; const limit = name === "observed-frame.fits" ? 256 * 1024 * 1024 : 8 * 1024 * 1024; if (size <= 0 || size > limit) reasons.push(`file-size:${name}`); }
  if (total > 288 * 1024 * 1024) reasons.push("total-size");
  let area: Record<string, unknown> | null = null, exposure: Record<string, unknown> | null = null, provenance: Record<string, unknown> | null = null, spectral: string[][] = [];
  try { area = json(files["collecting-area.json"]); exposure = json(files["exposure-record.json"]); provenance = json(files["provenance.json"]); spectral = csvRows(text(files["spectral-response.csv"])); } catch { reasons.push("parse-failure"); }
  const identities = [area, exposure, provenance].filter((entry): entry is Record<string, unknown> => entry !== null).map(common);
  if (identities.length !== 3 || identities.some((entry) => !validCommon(entry)) || identities.some((entry) => JSON.stringify(entry) !== JSON.stringify(identities[0]))) reasons.push("cross-file-identity");
  let contentClass: KerrSupplementalContentClassV545 | "unavailable" = "unavailable";
  if (identities[0] && validCommon(identities[0])) contentClass = identities[0].contentClass;
  if (!area || area.version !== "v545-collecting-area-v1" || !finite(area.collectingAreaM2) || !(Number(area.collectingAreaM2) > 0) || !finite(area.standardUncertaintyM2) || Number(area.standardUncertaintyM2) < 0 || Number(area.standardUncertaintyM2) >= Number(area.collectingAreaM2) || !/^https:\/\//.test(String(area.traceableSourceUrl ?? "")) || !SHA.test(String(area.rawArtifactSha256 ?? ""))) reasons.push("collecting-area-schema");
  if (!exposure || exposure.version !== "v545-exposure-record-v1" || typeof exposure.observationId !== "string" || !["visible", "euv", "soft-x-ray"].includes(String(exposure.bandId)) || !finite(exposure.tdbStartJd) || !finite(exposure.tdbEndJd) || !finite(exposure.exposureS) || !(Number(exposure.tdbEndJd) > Number(exposure.tdbStartJd)) || Math.abs((Number(exposure.tdbEndJd) - Number(exposure.tdbStartJd)) * 86400 - Number(exposure.exposureS)) > 1e-3 || !SHA.test(String(exposure.observationGeometrySha256 ?? ""))) reasons.push("exposure-schema");
  const header = ["bandId", "wavelengthM", "throughput", "standardUncertainty", "repeatIndex", "instrumentId", "detectorId", "campaignId", "rawArtifactSha256"];
  if (spectral.length !== 82 || JSON.stringify(spectral[0]) !== JSON.stringify(header)) reasons.push("spectral-row-count-or-header");
  else { const data = spectral.slice(1), bands = ["visible", "euv", "soft-x-ray"]; for (const band of bands) { const rows = data.filter((row) => row[0] === band); const wavelengths = [...new Set(rows.map((row) => Number(row[1])))].sort((left, right) => left - right); if (rows.length !== 27 || wavelengths.length !== 9 || wavelengths.some((value, index) => !Number.isFinite(value) || value <= 0 || (index > 0 && value <= wavelengths[index - 1]))) reasons.push(`spectral-coverage:${band}`); for (const wavelength of wavelengths) { const repeats = rows.filter((row) => Number(row[1]) === wavelength).map((row) => Number(row[4])).sort(); if (JSON.stringify(repeats) !== "[1,2,3]") reasons.push(`spectral-repeats:${band}`); } } if (data.some((row) => !["visible", "euv", "soft-x-ray"].includes(row[0]) || !finite(Number(row[1])) || !finite(Number(row[2])) || Number(row[2]) < 0 || Number(row[2]) > 1 || !finite(Number(row[3])) || Number(row[3]) < 0 || row[5] !== identities[0]?.instrumentId || row[6] !== identities[0]?.detectorId || row[7] !== identities[0]?.campaignId || !SHA.test(row[8]))) reasons.push("spectral-values-or-identity"); }
  const fits = files["observed-frame.fits"], fitsContainer = fits?.byteLength >= 2880 && fits.byteLength % 2880 === 0 && text(fits.slice(0, 30)).startsWith("SIMPLE  ="); if (!fitsContainer) reasons.push("fits-container-preflight");
  let provenanceShaQualified = false;
  const provenanceSourcesQualified = Array.isArray(provenance?.sources) && provenance.sources.length === 4 && provenance.sources.every((entry) => isRecord(entry) && typeof entry.id === "string" && /^https:\/\//.test(String(entry.url ?? "")) && typeof entry.licenseOrTerms === "string" && entry.licenseOrTerms.length > 0 && SHA.test(String(entry.sourceSha256 ?? "")));
  if (provenance?.version === "v545-supplemental-provenance-v1" && provenance.usageScope === "local-shadow-research-only" && typeof provenance.operatorAttestation === "string" && provenance.operatorAttestation.length > 0 && provenanceSourcesQualified && isRecord(provenance.fileSha256)) { const links = provenance.fileSha256; provenanceShaQualified = links.collectingArea === digest(files["collecting-area.json"]) && links.exposureRecord === digest(files["exposure-record.json"]) && links.spectralResponse === digest(files["spectral-response.csv"]) && links.observedFrame === digest(files["observed-frame.fits"]); }
  if (!provenanceShaQualified) reasons.push("provenance-sha-linkage");
  const preflightQualified = reasons.length === 0, measured = contentClass === "measured-science-candidate";
  return Object.freeze({ status: !preflightQualified ? "invalid" : measured ? "candidate-ready-for-independent-validation" : "synthetic-fixture-qualified-nonauthoritative", preflightQualified, contentClass, readyFileCount: preflightQualified ? 5 : 0, crossFileIdentityQualified: !reasons.includes("cross-file-identity"), provenanceShaLinkageQualified: provenanceShaQualified, fitsContainerPreflightQualified: fitsContainer, fitsSemanticValidation: preflightQualified ? "pending-independent-astropy-validation" : "not-run", candidateReadyForIndependentValidation: preflightQualified && measured, measuredAuthorityGranted: false, scienceRasterAllowed: false, reasons: Object.freeze(reasons) });
}

export function parseKerrSupplementalCalibrationIntakeArtifactV545(value: unknown): KerrSupplementalCalibrationIntakeArtifactV545 { if (!isRecord(value) || value.version !== KERR_SUPPLEMENTAL_CALIBRATION_INTAKE_VERSION_V545 || value.status !== "supplemental-intake-protocol-qualified-inputs-missing-science-authority-blocked" || !SHA.test(String(value.artifactSha256)) || !SHA.test(String(value.sourceSha256))) throw new Error("v545-artifact-boundary"); const artifact = value as unknown as KerrSupplementalCalibrationIntakeArtifactV545; if (artifact.contract.requiredFileCount !== 5 || artifact.contract.authorityCategoryCount !== 4 || artifact.schemaPack.files.length !== 5 || artifact.inspect.readyFileCount !== 0 || artifact.inspect.missingFileCount !== 5 || artifact.validationFixtures.acceptedSyntheticFixtureCount !== 1 || artifact.validationFixtures.syntheticAuthorityGranted !== false || artifact.counts.sciencePixelRows !== 0 || artifact.qualification.supplementalMeasuredAuthorityGranted !== false || artifact.qualification.scienceRasterQualified !== false || artifact.boundary.formalProductPointer !== "v263" || artifact.boundary.formalDefaultKernel !== "legacy-eih-1pn" || artifact.boundary.denseCampaignStatus !== "incomplete-0-of-49") throw new Error("v545-boundary"); return artifact; }
export function parseKerrSupplementalCalibrationIntakeApiV545(value: unknown): KerrSupplementalCalibrationIntakeApiV545 { if (!isRecord(value) || value.version !== KERR_SUPPLEMENTAL_CALIBRATION_INTAKE_API_VERSION_V545 || typeof value.available !== "boolean" || !["ready", "lite-boundary", "local-shadow-only", "evidence-corrupt"].includes(String(value.reason))) throw new Error("v545-api-boundary"); if (value.available) parseKerrSupplementalCalibrationIntakeArtifactV545(value.summary); else if (value.summary !== null) throw new Error("v545-api-unavailable-summary"); return value as unknown as KerrSupplementalCalibrationIntakeApiV545; }
export type KerrSupplementalCalibrationHudModeV545 = "science" | "cinematic";
const scienceProfile = Object.freeze({ id: KERR_SUPPLEMENTAL_CALIBRATION_HUD_PROFILE_ID_V545, mode: "science" as const, panel: "#030d10", panelRaised: "#07191e", ink: "#ebfcff", muted: "#78999f", qualified: "#75edb9", warning: "#efc170", unavailable: "#ff8aaa", scienceBoundary: Object.freeze({ linearDisplay: true, bloomIntensity: 0 as const, colorGradeIntensity: 0 as const, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }), cinematicSeed: null });
const cinematicProfile = Object.freeze({ ...scienceProfile, mode: "cinematic" as const, panel: "#140a07", panelRaised: "#25140e", ink: "#fff4e4", muted: "#b9997e", qualified: "#8ce9bf", warning: "#f3be6e", unavailable: "#ff94af", scienceBoundary: Object.freeze({ linearDisplay: false, bloomIntensity: 0.036, colorGradeIntensity: 0.024, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }), cinematicSeed: "orbit-atlas-v545-supplemental-intake-seed-01" });
export function resolveKerrSupplementalCalibrationHudProfileV545(mode: KerrSupplementalCalibrationHudModeV545) { return mode === "science" ? scienceProfile : cinematicProfile; }
export function createKerrSupplementalCalibrationHudEncodingV545(artifact: KerrSupplementalCalibrationIntakeArtifactV545, mode: KerrSupplementalCalibrationHudModeV545) { return Object.freeze({ version: "v545-supplemental-calibration-hud-v1" as const, profileId: KERR_SUPPLEMENTAL_CALIBRATION_HUD_PROFILE_ID_V545, mode, artifactKey: artifact.artifactSha256, schemaPackKey: artifact.schemaPack.schemaPackSha256, files: artifact.schemaPack.files, authorityCategoryCount: 4 as const, requiredFileCount: 5 as const, readyFileCount: 0 as const, scienceRasterQualified: false as const, imageHduCount: 0 as const, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }); }
export function compareKerrSupplementalCalibrationHudEncodingsV545(science: ReturnType<typeof createKerrSupplementalCalibrationHudEncodingV545>, cinematic: ReturnType<typeof createKerrSupplementalCalibrationHudEncodingV545>) { if (science.mode !== "science" || cinematic.mode !== "cinematic" || science.artifactKey !== cinematic.artifactKey || science.schemaPackKey !== cinematic.schemaPackKey || JSON.stringify(science.files) !== JSON.stringify(cinematic.files)) throw new Error("v545-hud-boundary"); return Object.freeze({ schemaStable: true as const, fileInventoryStable: true as const, scienceQualificationStable: true as const, scientificFieldMutation: false as const }); }
