export const KERR_RESPONSE_AWARE_OFFLINE_REPLAY_VERSION_V540 = "v540-kerr-response-aware-offline-replay-artifact-v1" as const;
export const KERR_RESPONSE_AWARE_OFFLINE_REPLAY_RECEIPT_VERSION_V540 = "v540-kerr-response-aware-offline-replay-receipt-v1" as const;
export const KERR_RESPONSE_AWARE_OFFLINE_REPLAY_API_VERSION_V540 = "v540-kerr-response-aware-offline-replay-api-v1" as const;
export const KERR_RESPONSE_AWARE_OFFLINE_REPLAY_HUD_PROFILE_ID_V540 = "science-cinematic-v8r9-v540" as const;

export type KerrResponseAwareOfflineReplayReceiptV540 = Readonly<{
  version: typeof KERR_RESPONSE_AWARE_OFFLINE_REPLAY_RECEIPT_VERSION_V540;
  generatedAt: string;
  status: "offline-clean-room-replay-qualified";
  crate: Readonly<{ fileSha256: string; bytes: number; memberCount: 9; totalUncompressedBytes: number }>;
  sandbox: Readonly<{ independentTemporaryDirectoryUsed: true; temporaryDirectoryRemoved: true; absolutePathStored: false; pathTraversalRejected: true; symlinkRejected: true; duplicateMemberRejected: true; maximumCrateBytes: 1048576; maximumMemberBytes: 262144; maximumTotalUncompressedBytes: 1048576; maximumMemberCount: 16; networkGuardInstalled: true; networkAttemptCount: 0 }>;
  integrity: Readonly<{ zipCrcQualified: true; memberReadCount: 9; manifestMemberCount: 8; manifestReplayCount: 8; metadataGraphQualified: true; contentAddressedMemberCount: 8 }>;
  fits: Readonly<{ hduCount: 2; primaryNaxis: 0; binaryTableHduCount: 1; imageHduCount: 0; rowCount: 4; columnCount: 17; checksumCardCount: 4; checksumReplayQualified: true; physicalUncertaintyTrueCount: 0; pixelTrueCount: 0; rowShaReplayCount: 4 }>;
  schema: Readonly<{ rowCount: 17; qualifiedRowCount: 17; columnShaReplayCount: 17; physicalUncertaintyValueCount: 0; pixelSampleCount: 0 }>;
  provenance: Readonly<{ v537ArtifactSha256: string; v538ArtifactSha256: string; v538EvidenceSha256: string; v538PointerSha256: string; canonicalReplayCount: 4; sourceLinkReplayCount: 6 }>;
  qualification: Readonly<{ offlineReplayQualified: true; safeExtractionQualified: true; manifestReplayQualified: true; fitsReplayQualified: true; columnSchemaReplayQualified: true; provenanceReplayQualified: true; scienceImageQualified: false; physicalUncertaintyQualified: false; productionPromotionQualified: false }>;
  boundary: Readonly<{ replayDoesNotCreateNewMeasurement: true; replayDoesNotCreatePixelSamples: true; replayDoesNotUseNetwork: true; measuredCalibrationFiles: 0; requiredMeasuredCalibrationFiles: 6; denseCampaignStatus: "incomplete-0-of-49"; formalProductPointer: "v263"; formalDefaultKernel: "legacy-eih-1pn" }>;
  receiptSha256: string;
}>;
export type KerrResponseAwareOfflineReplayArtifactV540 = Readonly<{
  version: typeof KERR_RESPONSE_AWARE_OFFLINE_REPLAY_VERSION_V540;
  generatedAt: string;
  status: "offline-clean-room-replay-qualified-heavy-browser-pending";
  source: Readonly<{ v539ArtifactSha256: string; v539CrateFileSha256: string; v539EvidenceSha256: string; v539PointerSha256: string }>;
  receipt: KerrResponseAwareOfflineReplayReceiptV540;
  receiptExport: Readonly<{ path: "dist/science/kerr-response-aware-offline-replay-v540/replay-receipt.json"; fileSha256: string; canonicalSha256: string; bytes: number; abByteIdentical: true }>;
  counts: Readonly<{ replayAttemptCount: 2; qualifiedReplayCount: 2; networkAttemptCount: 0; temporaryDirectoryLeakCount: 0; manifestReplayCount: 8; fitsRowReplayCount: 4; columnSchemaReplayCount: 17; provenanceCanonicalReplayCount: 4; pixelSampleCount: 0; fitsImageHduCount: 0; physicalUncertaintyValueCount: 0 }>;
  qualification: Readonly<{ cleanRoomReplayQualified: true; deterministicReceiptQualified: true; safeExtractionQualified: true; networkIsolationQualified: true; scienceImageQualified: false; physicalUncertaintyQualified: false; productionPromotionQualified: false }>;
  boundary: Readonly<{ replayInputIsOnlyV539Crate: true; workspaceSourceFilesUsedDuringReplay: 0; absolutePathStored: false; networkAttempted: false; sciencePayloadMutationAllowed: false; cinematicScienceWritebackAllowed: false; measuredCalibrationFiles: 0; denseCampaignStatus: "incomplete-0-of-49"; browserQualification: "not-run"; formalProductPointer: "v263"; formalDefaultKernel: "legacy-eih-1pn" }>;
  sourceManifest: readonly Readonly<{ path: string; sha256: string }>[];
  sourceSha256: string;
  artifactSha256: string;
}>;
export type KerrResponseAwareOfflineReplaySummaryV540 = Omit<KerrResponseAwareOfflineReplayArtifactV540, "generatedAt" | "sourceManifest" | "sourceSha256">;
export type KerrResponseAwareOfflineReplayApiV540 = Readonly<{ version: typeof KERR_RESPONSE_AWARE_OFFLINE_REPLAY_API_VERSION_V540; available: boolean; reason: "ready" | "lite-boundary" | "local-shadow-only" | "evidence-corrupt"; summary: KerrResponseAwareOfflineReplaySummaryV540 | null }>;
export type KerrResponseAwareOfflineReplayHudModeV540 = "science" | "cinematic";

const SHA = /^[a-f0-9]{64}$/;
const TRANSIENT = new Set(["generatedAt", "artifactSha256", "payloadSha256", "evidenceSha256", "pointerSha256", "stageChainSha256", "columnSha256", "receiptSha256"]);
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const compare = (left: string, right: string) => left < right ? -1 : left > right ? 1 : 0;
const canonicalize = (value: unknown): unknown => Array.isArray(value) ? value.map(canonicalize) : !isRecord(value) ? value : Object.fromEntries(Object.entries(value).filter(([key]) => !TRANSIENT.has(key)).sort(([left], [right]) => compare(left, right)).map(([key, entry]) => [key, canonicalize(entry)]));
export const canonicalKerrResponseAwareOfflineReplayV540 = (value: unknown) => JSON.stringify(canonicalize(value));

function validReceipt(receipt: Partial<KerrResponseAwareOfflineReplayReceiptV540> | undefined): receipt is KerrResponseAwareOfflineReplayReceiptV540 {
  return receipt?.version === KERR_RESPONSE_AWARE_OFFLINE_REPLAY_RECEIPT_VERSION_V540 && receipt.status === "offline-clean-room-replay-qualified" && SHA.test(receipt.crate?.fileSha256 ?? "") && receipt.crate?.memberCount === 9
    && receipt.sandbox?.independentTemporaryDirectoryUsed === true && receipt.sandbox.temporaryDirectoryRemoved === true && receipt.sandbox.absolutePathStored === false && receipt.sandbox.pathTraversalRejected === true && receipt.sandbox.symlinkRejected === true && receipt.sandbox.duplicateMemberRejected === true
    && receipt.sandbox.maximumCrateBytes === 1048576 && receipt.sandbox.maximumMemberBytes === 262144 && receipt.sandbox.maximumTotalUncompressedBytes === 1048576 && receipt.sandbox.maximumMemberCount === 16 && receipt.sandbox.networkGuardInstalled === true && receipt.sandbox.networkAttemptCount === 0
    && receipt.integrity?.zipCrcQualified === true && receipt.integrity.memberReadCount === 9 && receipt.integrity.manifestMemberCount === 8 && receipt.integrity.manifestReplayCount === 8 && receipt.integrity.metadataGraphQualified === true && receipt.integrity.contentAddressedMemberCount === 8
    && receipt.fits?.hduCount === 2 && receipt.fits.primaryNaxis === 0 && receipt.fits.binaryTableHduCount === 1 && receipt.fits.imageHduCount === 0 && receipt.fits.rowCount === 4 && receipt.fits.columnCount === 17 && receipt.fits.checksumCardCount === 4 && receipt.fits.checksumReplayQualified === true && receipt.fits.physicalUncertaintyTrueCount === 0 && receipt.fits.pixelTrueCount === 0 && receipt.fits.rowShaReplayCount === 4
    && receipt.schema?.rowCount === 17 && receipt.schema.qualifiedRowCount === 17 && receipt.schema.columnShaReplayCount === 17 && receipt.schema.physicalUncertaintyValueCount === 0 && receipt.schema.pixelSampleCount === 0
    && Object.values(receipt.provenance ?? {}).slice(0, 4).every((value) => typeof value === "string" && SHA.test(value)) && receipt.provenance?.canonicalReplayCount === 4 && receipt.provenance.sourceLinkReplayCount === 6
    && receipt.qualification?.offlineReplayQualified === true && receipt.qualification.safeExtractionQualified === true && receipt.qualification.manifestReplayQualified === true && receipt.qualification.fitsReplayQualified === true && receipt.qualification.columnSchemaReplayQualified === true && receipt.qualification.provenanceReplayQualified === true && receipt.qualification.scienceImageQualified === false && receipt.qualification.physicalUncertaintyQualified === false && receipt.qualification.productionPromotionQualified === false
    && receipt.boundary?.replayDoesNotCreateNewMeasurement === true && receipt.boundary.replayDoesNotCreatePixelSamples === true && receipt.boundary.replayDoesNotUseNetwork === true && receipt.boundary.measuredCalibrationFiles === 0 && receipt.boundary.requiredMeasuredCalibrationFiles === 6 && receipt.boundary.denseCampaignStatus === "incomplete-0-of-49" && receipt.boundary.formalProductPointer === "v263" && receipt.boundary.formalDefaultKernel === "legacy-eih-1pn" && SHA.test(receipt.receiptSha256 ?? "");
}
function validCore(value: Partial<KerrResponseAwareOfflineReplayArtifactV540>): boolean {
  return value.version === KERR_RESPONSE_AWARE_OFFLINE_REPLAY_VERSION_V540 && value.status === "offline-clean-room-replay-qualified-heavy-browser-pending" && Object.values(value.source ?? {}).length === 4 && Object.values(value.source ?? {}).every((entry) => SHA.test(entry)) && validReceipt(value.receipt)
    && value.receiptExport?.path === "dist/science/kerr-response-aware-offline-replay-v540/replay-receipt.json" && SHA.test(value.receiptExport.fileSha256) && value.receiptExport.canonicalSha256 === value.receipt?.receiptSha256 && Number.isSafeInteger(value.receiptExport.bytes) && value.receiptExport.bytes > 0 && value.receiptExport.abByteIdentical === true
    && value.counts?.replayAttemptCount === 2 && value.counts.qualifiedReplayCount === 2 && value.counts.networkAttemptCount === 0 && value.counts.temporaryDirectoryLeakCount === 0 && value.counts.manifestReplayCount === 8 && value.counts.fitsRowReplayCount === 4 && value.counts.columnSchemaReplayCount === 17 && value.counts.provenanceCanonicalReplayCount === 4 && value.counts.pixelSampleCount === 0 && value.counts.fitsImageHduCount === 0 && value.counts.physicalUncertaintyValueCount === 0
    && value.qualification?.cleanRoomReplayQualified === true && value.qualification.deterministicReceiptQualified === true && value.qualification.safeExtractionQualified === true && value.qualification.networkIsolationQualified === true && value.qualification.scienceImageQualified === false && value.qualification.physicalUncertaintyQualified === false && value.qualification.productionPromotionQualified === false
    && value.boundary?.replayInputIsOnlyV539Crate === true && value.boundary.workspaceSourceFilesUsedDuringReplay === 0 && value.boundary.absolutePathStored === false && value.boundary.networkAttempted === false && value.boundary.sciencePayloadMutationAllowed === false && value.boundary.cinematicScienceWritebackAllowed === false && value.boundary.measuredCalibrationFiles === 0 && value.boundary.denseCampaignStatus === "incomplete-0-of-49" && value.boundary.browserQualification === "not-run" && value.boundary.formalProductPointer === "v263" && value.boundary.formalDefaultKernel === "legacy-eih-1pn" && SHA.test(value.artifactSha256 ?? "");
}
export function parseKerrResponseAwareOfflineReplayArtifactV540(value: unknown): KerrResponseAwareOfflineReplayArtifactV540 { if (!isRecord(value) || !validCore(value as Partial<KerrResponseAwareOfflineReplayArtifactV540>)) throw new Error("v540-offline-replay-boundary"); const artifact = value as unknown as KerrResponseAwareOfflineReplayArtifactV540; if (!Array.isArray(artifact.sourceManifest) || artifact.sourceManifest.some((entry) => !entry.path || !SHA.test(entry.sha256)) || !SHA.test(artifact.sourceSha256)) throw new Error("v540-offline-replay-manifest"); return artifact; }
export function createKerrResponseAwareOfflineReplaySummaryV540(value: unknown): KerrResponseAwareOfflineReplaySummaryV540 { const artifact = parseKerrResponseAwareOfflineReplayArtifactV540(value); const summary = { ...artifact } as Record<string, unknown>; delete summary.generatedAt; delete summary.sourceManifest; delete summary.sourceSha256; return Object.freeze(summary) as unknown as KerrResponseAwareOfflineReplaySummaryV540; }
export function parseKerrResponseAwareOfflineReplayApiV540(value: unknown): KerrResponseAwareOfflineReplayApiV540 { if (!isRecord(value) || value.version !== KERR_RESPONSE_AWARE_OFFLINE_REPLAY_API_VERSION_V540 || typeof value.available !== "boolean" || !["ready", "lite-boundary", "local-shadow-only", "evidence-corrupt"].includes(String(value.reason))) throw new Error("v540-api-boundary"); if (value.available) { if (!isRecord(value.summary) || !validCore(value.summary as Partial<KerrResponseAwareOfflineReplayArtifactV540>)) throw new Error("v540-api-summary"); } else if (value.summary !== null) throw new Error("v540-api-unavailable-summary"); return value as unknown as KerrResponseAwareOfflineReplayApiV540; }

const scienceProfile = Object.freeze({ id: KERR_RESPONSE_AWARE_OFFLINE_REPLAY_HUD_PROFILE_ID_V540, mode: "science" as const, panel: "#02080a", panelRaised: "#07131a", ink: "#effdff", muted: "#78959c", qualified: "#74f4c5", unavailable: "#ff91ad", localShadowOnly: true as const, defaultApplied: false as const, scienceBoundary: Object.freeze({ linearDisplay: true, bloomIntensity: 0, colorGradeIntensity: 0, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }), cinematicSeed: null as string | null });
const cinematicProfile = Object.freeze({ ...scienceProfile, mode: "cinematic" as const, panel: "#100907", panelRaised: "#1b130f", ink: "#fff7ea", muted: "#b09a84", qualified: "#8ff5ca", unavailable: "#ff96b2", scienceBoundary: Object.freeze({ linearDisplay: false, bloomIntensity: 0.05, colorGradeIntensity: 0.035, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }), cinematicSeed: "orbit-atlas-v540-offline-replay-seed-01" });
export const resolveKerrResponseAwareOfflineReplayHudProfileV540 = (mode: KerrResponseAwareOfflineReplayHudModeV540) => mode === "science" ? scienceProfile : cinematicProfile;
export function createKerrResponseAwareOfflineReplayHudEncodingV540(summary: KerrResponseAwareOfflineReplaySummaryV540, mode: KerrResponseAwareOfflineReplayHudModeV540) { if (!SHA.test(summary.artifactSha256) || !SHA.test(summary.receipt.receiptSha256)) throw new Error("v540-hud-source"); return Object.freeze({ version: "v540-response-aware-offline-replay-hud-v1" as const, profileId: KERR_RESPONSE_AWARE_OFFLINE_REPLAY_HUD_PROFILE_ID_V540, mode, scientificPayloadKey: summary.receipt.provenance.v537ArtifactSha256, columnSchemaKey: summary.receipt.provenance.v538ArtifactSha256, crateFileKey: summary.receipt.crate.fileSha256, replayArtifactKey: summary.artifactSha256, receiptKey: summary.receipt.receiptSha256, receipt: summary.receipt, replayAttemptCount: 2 as const, networkAttemptCount: 0 as const, temporaryDirectoryLeakCount: 0 as const, imageHduCount: 0 as const, pixelSampleCount: 0 as const, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }); }
export function compareKerrResponseAwareOfflineReplayHudEncodingsV540(science: ReturnType<typeof createKerrResponseAwareOfflineReplayHudEncodingV540>, cinematic: ReturnType<typeof createKerrResponseAwareOfflineReplayHudEncodingV540>) { if (science.mode !== "science" || cinematic.mode !== "cinematic" || science.scientificPayloadKey !== cinematic.scientificPayloadKey || science.columnSchemaKey !== cinematic.columnSchemaKey || science.crateFileKey !== cinematic.crateFileKey || science.replayArtifactKey !== cinematic.replayArtifactKey || science.receiptKey !== cinematic.receiptKey || JSON.stringify(science.receipt) !== JSON.stringify(cinematic.receipt)) throw new Error("v540-hud-boundary"); return Object.freeze({ scientificPayloadStable: true as const, columnSchemaStable: true as const, crateStable: true as const, replayReceiptStable: true as const, replayAttemptCount: 2 as const, networkAttemptCount: 0 as const, temporaryDirectoryLeakCount: 0 as const, imageHduCount: 0 as const, scientificFieldMutation: false as const }); }
