import { createHash } from "node:crypto";

export const KERR_HIGH_ENERGY_LIKELIHOOD_AUTHORITY_VERSION_V432 = "v432-kerr-high-energy-likelihood-authority-v1" as const;
export const KERR_HIGH_ENERGY_LIKELIHOOD_AUTHORITY_ARTIFACT_VERSION_V432 = "v432-kerr-high-energy-likelihood-authority-artifact-v1" as const;
export const KERR_HIGH_ENERGY_LIKELIHOOD_AUTHORITY_SUMMARY_VERSION_V432 = "v432-kerr-high-energy-likelihood-authority-summary-v1" as const;
export const KERR_HIGH_ENERGY_LIKELIHOOD_AUTHORITY_API_VERSION_V432 = "v432-kerr-high-energy-likelihood-authority-api-v1" as const;
export const KERR_V431_ARTIFACT_SHA256_V432 = "291e960f25529c371f297deccdb3d436778ce905fbd29acea807887894d0c7e6" as const;
export const KERR_V431_ARTIFACT_FILE_SHA256_V432 = "034132d9396712924d8cf88992bbfd60c60f3d1a6fe248e69843aaf625c94400" as const;
export const KERR_V431_ORACLE_SHA256_V432 = "55fe6c8fb0621444cd2687aa66607c394e6e15bb7c37b6ee80a2d3330f91fdd2" as const;
export const KERR_V431_ORACLE_FILE_SHA256_V432 = "bf57f621e55acf3a08676cc5412ddd99283aadf034a33bf4e37d437e449a9199" as const;
export const KERR_V431_EVIDENCE_SHA256_V432 = "6c9d3b11696d80376c9522bb0ba653c89d72527f7e5d5a838c1d6a692607404c" as const;
export const KERR_V431_EVIDENCE_FILE_SHA256_V432 = "0d0cc01179ccdda30a7f06952c5a3d1c1f6239b05627659f7fea92637a3d8125" as const;
export const KERR_V431_POINTER_SHA256_V432 = "8136f9c26a4d73cdaa399f4c5f916052a0e40f41ee096cc43bd072ac2392b541" as const;
export const KERR_V431_POINTER_FILE_SHA256_V432 = "e112295c65a1cccc84039a53f046a2c5249b21338568534dbf3d338c1ad5a2bd" as const;

const SHA = /^[a-f0-9]{64}$/;
const TRANSIENT = new Set(["generatedAt", "artifactSha256", "evidenceSha256", "pointerSha256"]);
type Matrix = readonly (readonly number[])[];
export type KerrLikelihoodAuthorityFamilyV432 = "negative-binomial" | "poisson-lognormal";
export type KerrLikelihoodAuthorityCandidateV432 = Readonly<{ model: KerrLikelihoodAuthorityFamilyV432; fittedParameter: number; trueParameter: number; relativeParameterError: number; holdoutLogLikelihood: number; poissonLogLikelihood: number; deltaAicVsPoisson: number; coverage90: number; intervalMethod: string; lower90: readonly number[]; upper90: readonly number[]; holdoutCellCount: 6144 }>;
export type KerrLikelihoodAuthorityFamilyResultV432 = Readonly<{ id: string; generatingFamily: KerrLikelihoodAuthorityFamilyV432; calibrationSeed: number; holdoutSeed: number; calibrationReplicateCount: 256; holdoutReplicateCount: 256; trueParameter: number; correctCandidate: KerrLikelihoodAuthorityCandidateV432; wrongCandidate: KerrLikelihoodAuthorityCandidateV432; selectionDeltaLogLikelihood: number; deterministicReplayPassed: true; authorityGatePassed: true; calibrationCounts: Matrix; holdoutCounts: Matrix }>;

export type KerrHighEnergyLikelihoodAuthorityOracleV432 = Readonly<{ version: "v432-kerr-high-energy-likelihood-authority-python-oracle-v1"; generatedAt: string; status: "qualified-synthetic-negative-binomial-and-poisson-lognormal-authority-parameter-recovery-and-holdout-selection-no-measured-authority"; sourceV431ArtifactSha256: typeof KERR_V431_ARTIFACT_SHA256_V432; sourceV431ArtifactFileSha256: typeof KERR_V431_ARTIFACT_FILE_SHA256_V432; sourceV431OracleSha256: typeof KERR_V431_ORACLE_SHA256_V432; sourceV431OracleFileSha256: typeof KERR_V431_ORACLE_FILE_SHA256_V432; prediction: Readonly<{ predictedCounts: readonly number[] }>; campaign: Readonly<{ seed: 43220260730; calibrationReplicatesPerFamily: 256; holdoutReplicatesPerFamily: 256; families: readonly KerrLikelihoodAuthorityFamilyResultV432[] }>; counts: Readonly<{ candidateFamilyCount: 2; calibrationReplicateCount: 512; syntheticHoldoutReplicateCount: 512; syntheticCountCellCount: 24576; parameterRecoveryResultCount: 2; holdoutSelectionResultCount: 2; measuredObservedCountCount: 0; measuredHoldoutDatasetCount: 0; measuredResidualMetricCount: 0; measuredValidationRunCount: 0; alternativeLikelihoodImplementationQualifiedCount: 2; scienceResponseApplicationCount: 0 }>; qualification: Readonly<Record<string, boolean>>; measuredResponseAuthorityGranted: false; scienceResponseApplicationCount: 0; networkAttempted: false; boundary: string; artifactSha256: string }>;
export type KerrHighEnergyLikelihoodAuthorityContractV432 = Readonly<{ version: "v432-kerr-high-energy-likelihood-authority-contract-v1"; status: "synthetic-alternative-likelihood-authority-qualified-measured-authority-pending"; candidateModels: readonly Readonly<{ id: KerrLikelihoodAuthorityFamilyV432; parameter: string; fitRule: string; predictiveInterval: string; quadratureNodes?: number }>[]; quadrature: Readonly<{ nodes: readonly number[]; weights: readonly number[]; measure: string; sharedLatentCommonMode: true }>; selectionMetric: "independent-holdout-log-likelihood-with-one-parameter-AIC-penalty"; selectionBeforeScienceUse: true; residualDiagnosticsMayAuditButNeverSelectFamily: true; postHocLikelihoodSwitchForbidden: true; parameterRecoveryRelativeErrorMaximum: 0.15; coverage90Range: readonly [0.87, 0.93]; deltaAicVsPoissonMinimum: 100; correctVsWrongHoldoutLogLikelihoodMinimum: 20; alternativeLikelihoodImplementationsQualified: readonly ["negative-binomial", "poisson-lognormal"]; measuredObservedCountsRequiredForInstrumentAuthority: true; independentMeasuredHoldoutRequired: true; measuredAuthorityGranted: false; formalProductPointer: "v263"; denseCampaignStatus: "incomplete-0-of-49"; boundary: string }>;
export type KerrLikelihoodAuthorityCandidateSummaryV432 = Readonly<{ model: KerrLikelihoodAuthorityFamilyV432; fittedParameter: number; trueParameter: number; relativeParameterError: number; holdoutLogLikelihood: number; poissonLogLikelihood: number; deltaAicVsPoisson: number; coverage90: number; intervalMethod: string; holdoutCellCount: 6144; maximumPythonRelativeDifference: number }>;
export type KerrHighEnergyLikelihoodAuthorityFamilySummaryV432 = Readonly<{ id: string; generatingFamily: KerrLikelihoodAuthorityFamilyV432; calibrationSeed: number; holdoutSeed: number; trueParameter: number; correctCandidate: KerrLikelihoodAuthorityCandidateSummaryV432; wrongCandidate: KerrLikelihoodAuthorityCandidateSummaryV432; selectionDeltaLogLikelihood: number; deterministicReplayPassed: true; authorityGatePassed: true }>;
export type KerrHighEnergyLikelihoodAuthorityViewV432 = Readonly<{ version: typeof KERR_HIGH_ENERGY_LIKELIHOOD_AUTHORITY_VERSION_V432; status: KerrHighEnergyLikelihoodAuthorityOracleV432["status"]; source: Readonly<{ v431ArtifactSha256: typeof KERR_V431_ARTIFACT_SHA256_V432; v431OracleSha256: typeof KERR_V431_ORACLE_SHA256_V432; v431EvidenceSha256: typeof KERR_V431_EVIDENCE_SHA256_V432; v431PointerSha256: typeof KERR_V431_POINTER_SHA256_V432 }>; campaign: Readonly<{ candidateFamilyCount: 2; calibrationReplicateCount: 512; syntheticHoldoutReplicateCount: 512; syntheticCountCellCount: 24576; independentSyntheticSplit: true; fixedSeed: 43220260730 }>; selection: Readonly<{ metric: KerrHighEnergyLikelihoodAuthorityContractV432["selectionMetric"]; selectionBeforeScienceUse: true; postHocLikelihoodSwitchForbidden: true; residualDiagnosticsMayAuditButNeverSelectFamily: true; negativeBinomialQualified: true; poissonLognormalQualified: true; modelMisspecificationDiscriminatorQualified: true; measuredAuthority: false }>; families: readonly KerrHighEnergyLikelihoodAuthorityFamilySummaryV432[]; counts: KerrHighEnergyLikelihoodAuthorityOracleV432["counts"]; products: Readonly<{ json: "available-authority-summary-and-boundary"; oracle: "available-full-synthetic-holdout-authority-fixture"; contract: "available-preregistered-candidate-contract"; csv: "available-family-recovery-and-selection-diagnostics"; fits: "available-likelihood-authority-summary-no-detector-image"; png: "available-likelihood-authority-map-not-instrument-performance" }>; authorityBoundary: Readonly<{ negativeBinomialMathAuthorityGranted: true; poissonLognormalMathAuthorityGranted: true; parameterRecoveryAuthorityGranted: true; coverageAuthorityGranted: true; holdoutSelectionAuthorityGranted: true; modelMisspecificationDiscriminatorAuthorityGranted: true; alternativeLikelihoodImplementationAuthorityGranted: true; fixturePerformanceAuthorityGranted: false; measuredLikelihoodAuthorityGranted: false; measuredInstrumentPerformanceAuthorityGranted: false; measuredResponseAuthorityGranted: false; scienceProjectionAuthorityGranted: false; detectorAuthorityGranted: false; denseAuthorityGranted: false; unavailableIsNotZero: true }>; denseCampaignStatus: "incomplete-0-of-49"; browserQualification: "not-run"; boundary: string }>;
export type KerrHighEnergyLikelihoodAuthorityArtifactV432 = Readonly<{ version: typeof KERR_HIGH_ENERGY_LIKELIHOOD_AUTHORITY_ARTIFACT_VERSION_V432; generatedAt: string; status: KerrHighEnergyLikelihoodAuthorityViewV432["status"]; sourceFiles: Readonly<{ v431ArtifactFileSha256: typeof KERR_V431_ARTIFACT_FILE_SHA256_V432; v431OracleFileSha256: typeof KERR_V431_ORACLE_FILE_SHA256_V432; v431EvidenceFileSha256: typeof KERR_V431_EVIDENCE_FILE_SHA256_V432; v431PointerFileSha256: typeof KERR_V431_POINTER_FILE_SHA256_V432; pythonOracleFileSha256: string; authorityContractFileSha256: string }>; pythonOracleArtifactSha256: string; view: KerrHighEnergyLikelihoodAuthorityViewV432; deterministicReplay: true; networkAttempted: false; denseShardExecuted: false; measuredObservedCountsPresent: false; measuredHoldoutPresent: false; measuredValidationRunCount: 0; scienceResponseApplicationCount: 0; artifactSha256: string }>;
export type KerrHighEnergyLikelihoodAuthoritySummaryV432 = Readonly<{ version: typeof KERR_HIGH_ENERGY_LIKELIHOOD_AUTHORITY_SUMMARY_VERSION_V432; status: KerrHighEnergyLikelihoodAuthorityViewV432["status"]; artifactSha256: string; campaign: KerrHighEnergyLikelihoodAuthorityViewV432["campaign"]; selection: KerrHighEnergyLikelihoodAuthorityViewV432["selection"]; families: KerrHighEnergyLikelihoodAuthorityViewV432["families"]; counts: KerrHighEnergyLikelihoodAuthorityViewV432["counts"]; products: KerrHighEnergyLikelihoodAuthorityViewV432["products"]; authorityBoundary: KerrHighEnergyLikelihoodAuthorityViewV432["authorityBoundary"]; denseCampaignStatus: "incomplete-0-of-49"; fullArtifactAvailable: true; boundary: "bounded-family-recovery-holdout-selection-and-authority-no-holdout-count-arrays-or-quadrature-in-react-state" }>;
export type KerrHighEnergyLikelihoodAuthorityApiV432 = Readonly<{ version: typeof KERR_HIGH_ENERGY_LIKELIHOOD_AUTHORITY_API_VERSION_V432; available: boolean; reason: "ready" | "lite-boundary" | "local-shadow-only" | "evidence-corrupt" | "request-failed"; summary: KerrHighEnergyLikelihoodAuthoritySummaryV432 | null }>;

function canonicalize(value: unknown): unknown { if (Array.isArray(value)) return value.map(canonicalize); if (!value || typeof value !== "object") return value; return Object.fromEntries(Object.entries(value as Record<string, unknown>).filter(([key]) => !TRANSIENT.has(key)).sort(([a], [b]) => a.localeCompare(b)).map(([key, entry]) => [key, canonicalize(entry)])); }
export const canonicalShaV432 = (value: unknown): string => createHash("sha256").update(JSON.stringify(canonicalize(value))).digest("hex");
const maximumRelativeDifference = (left: unknown, right: unknown): number => { if (typeof left === "number" && typeof right === "number") return Math.abs(left - right) / Math.max(1, Math.abs(right)); if (Array.isArray(left) && Array.isArray(right) && left.length === right.length) return Math.max(0, ...left.map((entry, index) => maximumRelativeDifference(entry, right[index]))); if (left && right && typeof left === "object" && typeof right === "object") { const a = left as Record<string, unknown>, b = right as Record<string, unknown>, keys = Object.keys(a); if (keys.length !== Object.keys(b).length || keys.some((key) => !Object.hasOwn(b, key))) return Number.POSITIVE_INFINITY; return Math.max(0, ...keys.map((key) => maximumRelativeDifference(a[key], b[key]))); } return left === right ? 0 : Number.POSITIVE_INFINITY; };

function logGamma(value: number): number { const coefficients = [676.5203681218851, -1259.1392167224028, 771.3234287776531, -176.6150291621406, 12.507343278686905, -0.13857109526572012, 9.984369578019572e-6, 1.5056327351493116e-7]; if (value < 0.5) return Math.log(Math.PI) - Math.log(Math.sin(Math.PI * value)) - logGamma(1 - value); const z = value - 1; let x = 0.9999999999998099; coefficients.forEach((coefficient, index) => { x += coefficient / (z + index + 1); }); const t = z + coefficients.length - 0.5; return 0.5 * Math.log(2 * Math.PI) + (z + 0.5) * Math.log(t) - t + Math.log(x); }
export function fitNegativeBinomialAlphaV432(counts: Matrix, mean: readonly number[]): number { const numerator = counts.reduce((total, row) => total + row.reduce((sum, value, index) => sum + (value - mean[index]) ** 2 - value, 0), 0), denominator = counts.length * mean.reduce((sum, value) => sum + value * value, 0); return Math.max(1e-10, numerator / denominator); }
export function fitPoissonLognormalSigmaV432(counts: Matrix, mean: readonly number[]): number { const residual = counts.map((row) => row.map((value, index) => value - mean[index])), means = mean.map((_, index) => residual.reduce((sum, row) => sum + row[index], 0) / residual.length), covariance = Array.from({ length: mean.length }, (_, left) => Array.from({ length: mean.length }, (_, right) => residual.reduce((sum, row) => sum + (row[left] - means[left]) * (row[right] - means[right]), 0) / (residual.length - 1))); const ratios: number[] = []; for (let left = 0; left < mean.length; left += 1) for (let right = left + 1; right < mean.length; right += 1) ratios.push(covariance[left][right] / (mean[left] * mean[right])); return Math.sqrt(Math.log1p(Math.max(1e-12, ratios.reduce((sum, value) => sum + value, 0) / ratios.length))); }
export function poissonLogLikelihoodV432(counts: Matrix, mean: readonly number[]): number { return counts.reduce((total, row) => total + row.reduce((sum, value, index) => sum + value * Math.log(mean[index]) - mean[index] - logGamma(value + 1), 0), 0); }
export function negativeBinomialLogLikelihoodV432(counts: Matrix, mean: readonly number[], alpha: number): number { const shape = 1 / alpha; return counts.reduce((total, row) => total + row.reduce((sum, value, index) => { const probability = shape / (shape + mean[index]); return sum + logGamma(value + shape) - logGamma(shape) - logGamma(value + 1) + shape * Math.log(probability) + value * Math.log1p(-probability); }, 0), 0); }
export function poissonLognormalLogLikelihoodV432(counts: Matrix, mean: readonly number[], sigma: number, nodes: readonly number[], weights: readonly number[]): number { if (nodes.length !== 32 || weights.length !== 32) throw new Error("v432-quadrature-shape"); const logFactors = nodes.map((node) => -0.5 * sigma * sigma + Math.sqrt(2) * sigma * node), intensities = logFactors.map((factor) => mean.map((value) => Math.log(value) + factor)), logWeights = weights.map((weight) => Math.log(weight) - 0.5 * Math.log(Math.PI)); return counts.reduce((total, row) => { const terms = nodes.map((_, node) => logWeights[node] + row.reduce((sum, value, index) => sum + value * intensities[node][index] - Math.exp(intensities[node][index]) - logGamma(value + 1), 0)); const maximum = Math.max(...terms); return total + maximum + Math.log(terms.reduce((sum, value) => sum + Math.exp(value - maximum), 0)); }, 0); }

function candidateMetrics(model: KerrLikelihoodAuthorityFamilyV432, calibration: Matrix, holdout: Matrix, mean: readonly number[], candidate: KerrLikelihoodAuthorityCandidateV432, contract: KerrHighEnergyLikelihoodAuthorityContractV432): KerrLikelihoodAuthorityCandidateSummaryV432 {
  if (calibration.length !== 256 || holdout.length !== 256 || mean.length !== 24 || calibration.some((row) => row.length !== 24) || holdout.some((row) => row.length !== 24) || candidate.lower90.length !== 24 || candidate.upper90.length !== 24) throw new Error("v432-candidate-shape");
  const fittedParameter = model === "negative-binomial" ? fitNegativeBinomialAlphaV432(calibration, mean) : fitPoissonLognormalSigmaV432(calibration, mean);
  const holdoutLogLikelihood = model === "negative-binomial" ? negativeBinomialLogLikelihoodV432(holdout, mean, fittedParameter) : poissonLognormalLogLikelihoodV432(holdout, mean, fittedParameter, contract.quadrature.nodes, contract.quadrature.weights);
  const poisson = poissonLogLikelihoodV432(holdout, mean);
  const coverage = holdout.reduce((total, row) => total + row.filter((value, index) => value >= candidate.lower90[index] && value <= candidate.upper90[index]).length, 0) / (holdout.length * mean.length);
  const trueParameter = model === "negative-binomial" ? 2e-5 : 8e-3;
  const result = { model, fittedParameter, trueParameter, relativeParameterError: Math.abs(fittedParameter - trueParameter) / trueParameter, holdoutLogLikelihood, poissonLogLikelihood: poisson, deltaAicVsPoisson: 2 * (holdoutLogLikelihood - poisson) - 2, coverage90: coverage, intervalMethod: candidate.intervalMethod, holdoutCellCount: 6144 as const };
  const target = { model: candidate.model, fittedParameter: candidate.fittedParameter, trueParameter: candidate.trueParameter, relativeParameterError: candidate.relativeParameterError, holdoutLogLikelihood: candidate.holdoutLogLikelihood, poissonLogLikelihood: candidate.poissonLogLikelihood, deltaAicVsPoisson: candidate.deltaAicVsPoisson, coverage90: candidate.coverage90, intervalMethod: candidate.intervalMethod, holdoutCellCount: candidate.holdoutCellCount };
  const difference = maximumRelativeDifference(result, target);
  if (difference >= 1e-8) throw new Error(`v432-candidate-cross-validation:${model}:${difference}`);
  return Object.freeze({ ...result, maximumPythonRelativeDifference: difference });
}

export function parseKerrHighEnergyLikelihoodAuthorityOracleV432(value: unknown): KerrHighEnergyLikelihoodAuthorityOracleV432 { const source = value as Partial<KerrHighEnergyLikelihoodAuthorityOracleV432> | null; if (!source || source.version !== "v432-kerr-high-energy-likelihood-authority-python-oracle-v1" || source.status !== "qualified-synthetic-negative-binomial-and-poisson-lognormal-authority-parameter-recovery-and-holdout-selection-no-measured-authority" || source.sourceV431ArtifactSha256 !== KERR_V431_ARTIFACT_SHA256_V432 || source.sourceV431ArtifactFileSha256 !== KERR_V431_ARTIFACT_FILE_SHA256_V432 || source.sourceV431OracleSha256 !== KERR_V431_ORACLE_SHA256_V432 || source.sourceV431OracleFileSha256 !== KERR_V431_ORACLE_FILE_SHA256_V432 || source.prediction?.predictedCounts.length !== 24 || source.campaign?.families.length !== 2 || source.campaign.families.some((family) => family.calibrationCounts.length !== 256 || family.holdoutCounts.length !== 256 || family.calibrationCounts.some((row) => row.length !== 24) || family.holdoutCounts.some((row) => row.length !== 24)) || source.counts?.candidateFamilyCount !== 2 || source.counts.syntheticCountCellCount !== 24576 || source.counts.alternativeLikelihoodImplementationQualifiedCount !== 2 || source.counts.measuredObservedCountCount !== 0 || source.counts.measuredHoldoutDatasetCount !== 0 || source.counts.measuredValidationRunCount !== 0 || source.qualification?.negativeBinomialMathQualified !== true || source.qualification.poissonLognormalMathQualified !== true || source.qualification.holdoutSelectionQualified !== true || source.qualification.measuredLikelihoodQualified !== false || source.measuredResponseAuthorityGranted !== false || source.scienceResponseApplicationCount !== 0 || source.networkAttempted !== false || !SHA.test(source.artifactSha256 ?? "")) throw new Error("v432-oracle-identity"); return value as KerrHighEnergyLikelihoodAuthorityOracleV432; }

export function createKerrHighEnergyLikelihoodAuthorityViewV432(oracleValue: unknown, contract: KerrHighEnergyLikelihoodAuthorityContractV432): KerrHighEnergyLikelihoodAuthorityViewV432 {
  const oracle = parseKerrHighEnergyLikelihoodAuthorityOracleV432(oracleValue);
  if (contract.version !== "v432-kerr-high-energy-likelihood-authority-contract-v1" || contract.status !== "synthetic-alternative-likelihood-authority-qualified-measured-authority-pending" || contract.candidateModels.length !== 2 || contract.quadrature.nodes.length !== 32 || contract.quadrature.weights.length !== 32 || contract.quadrature.weights.some((weight) => !Number.isFinite(weight) || weight <= 0) || contract.selectionMetric !== "independent-holdout-log-likelihood-with-one-parameter-AIC-penalty" || contract.selectionBeforeScienceUse !== true || contract.residualDiagnosticsMayAuditButNeverSelectFamily !== true || contract.postHocLikelihoodSwitchForbidden !== true || contract.alternativeLikelihoodImplementationsQualified.length !== 2 || contract.measuredAuthorityGranted !== false || contract.formalProductPointer !== "v263" || contract.denseCampaignStatus !== "incomplete-0-of-49") throw new Error("v432-contract");
  const families = oracle.campaign.families.map((family) => {
    const correctCandidate = candidateMetrics(family.correctCandidate.model, family.calibrationCounts, family.holdoutCounts, oracle.prediction.predictedCounts, family.correctCandidate, contract);
    const wrongCandidate = candidateMetrics(family.wrongCandidate.model, family.calibrationCounts, family.holdoutCounts, oracle.prediction.predictedCounts, family.wrongCandidate, contract);
    const selectionDeltaLogLikelihood = correctCandidate.holdoutLogLikelihood - wrongCandidate.holdoutLogLikelihood;
    if (correctCandidate.model !== family.generatingFamily || correctCandidate.relativeParameterError >= contract.parameterRecoveryRelativeErrorMaximum || correctCandidate.coverage90 < contract.coverage90Range[0] || correctCandidate.coverage90 > contract.coverage90Range[1] || correctCandidate.deltaAicVsPoisson <= contract.deltaAicVsPoissonMinimum || selectionDeltaLogLikelihood <= contract.correctVsWrongHoldoutLogLikelihoodMinimum || Math.abs(selectionDeltaLogLikelihood - family.selectionDeltaLogLikelihood) / Math.max(1, Math.abs(family.selectionDeltaLogLikelihood)) >= 1e-8 || family.deterministicReplayPassed !== true || family.authorityGatePassed !== true) throw new Error(`v432-family-gate:${family.generatingFamily}`);
    return Object.freeze({ id: family.id, generatingFamily: family.generatingFamily, calibrationSeed: family.calibrationSeed, holdoutSeed: family.holdoutSeed, trueParameter: family.trueParameter, correctCandidate, wrongCandidate, selectionDeltaLogLikelihood, deterministicReplayPassed: true as const, authorityGatePassed: true as const });
  });
  return Object.freeze({ version: KERR_HIGH_ENERGY_LIKELIHOOD_AUTHORITY_VERSION_V432, status: oracle.status, source: Object.freeze({ v431ArtifactSha256: KERR_V431_ARTIFACT_SHA256_V432, v431OracleSha256: KERR_V431_ORACLE_SHA256_V432, v431EvidenceSha256: KERR_V431_EVIDENCE_SHA256_V432, v431PointerSha256: KERR_V431_POINTER_SHA256_V432 }), campaign: Object.freeze({ candidateFamilyCount: 2 as const, calibrationReplicateCount: 512 as const, syntheticHoldoutReplicateCount: 512 as const, syntheticCountCellCount: 24576 as const, independentSyntheticSplit: true as const, fixedSeed: 43220260730 as const }), selection: Object.freeze({ metric: contract.selectionMetric, selectionBeforeScienceUse: true as const, postHocLikelihoodSwitchForbidden: true as const, residualDiagnosticsMayAuditButNeverSelectFamily: true as const, negativeBinomialQualified: true as const, poissonLognormalQualified: true as const, modelMisspecificationDiscriminatorQualified: true as const, measuredAuthority: false as const }), families: Object.freeze(families), counts: oracle.counts, products: Object.freeze({ json: "available-authority-summary-and-boundary" as const, oracle: "available-full-synthetic-holdout-authority-fixture" as const, contract: "available-preregistered-candidate-contract" as const, csv: "available-family-recovery-and-selection-diagnostics" as const, fits: "available-likelihood-authority-summary-no-detector-image" as const, png: "available-likelihood-authority-map-not-instrument-performance" as const }), authorityBoundary: Object.freeze({ negativeBinomialMathAuthorityGranted: true as const, poissonLognormalMathAuthorityGranted: true as const, parameterRecoveryAuthorityGranted: true as const, coverageAuthorityGranted: true as const, holdoutSelectionAuthorityGranted: true as const, modelMisspecificationDiscriminatorAuthorityGranted: true as const, alternativeLikelihoodImplementationAuthorityGranted: true as const, fixturePerformanceAuthorityGranted: false as const, measuredLikelihoodAuthorityGranted: false as const, measuredInstrumentPerformanceAuthorityGranted: false as const, measuredResponseAuthorityGranted: false as const, scienceProjectionAuthorityGranted: false as const, detectorAuthorityGranted: false as const, denseAuthorityGranted: false as const, unavailableIsNotZero: true as const }), denseCampaignStatus: "incomplete-0-of-49", browserQualification: "not-run", boundary: "synthetic-negative-binomial-and-poisson-lognormal-math-parameter-recovery-coverage-and-independent-holdout-selection-only-no-measured-goodness-of-fit-instrument-performance-science-response-or-dense-authority" });
}

export function parseKerrHighEnergyLikelihoodAuthorityArtifactV432(value: unknown): KerrHighEnergyLikelihoodAuthorityArtifactV432 { const source = value as Partial<KerrHighEnergyLikelihoodAuthorityArtifactV432> | null; if (!source || source.version !== KERR_HIGH_ENERGY_LIKELIHOOD_AUTHORITY_ARTIFACT_VERSION_V432 || source.status !== "qualified-synthetic-negative-binomial-and-poisson-lognormal-authority-parameter-recovery-and-holdout-selection-no-measured-authority" || source.sourceFiles?.v431ArtifactFileSha256 !== KERR_V431_ARTIFACT_FILE_SHA256_V432 || source.sourceFiles.v431OracleFileSha256 !== KERR_V431_ORACLE_FILE_SHA256_V432 || source.sourceFiles.v431EvidenceFileSha256 !== KERR_V431_EVIDENCE_FILE_SHA256_V432 || source.sourceFiles.v431PointerFileSha256 !== KERR_V431_POINTER_FILE_SHA256_V432 || !SHA.test(source.sourceFiles.pythonOracleFileSha256 ?? "") || !SHA.test(source.sourceFiles.authorityContractFileSha256 ?? "") || !SHA.test(source.pythonOracleArtifactSha256 ?? "") || source.view?.campaign.candidateFamilyCount !== 2 || source.view.families.length !== 2 || source.view.counts.measuredObservedCountCount !== 0 || source.view.counts.alternativeLikelihoodImplementationQualifiedCount !== 2 || source.view.authorityBoundary.alternativeLikelihoodImplementationAuthorityGranted !== true || source.view.authorityBoundary.measuredInstrumentPerformanceAuthorityGranted !== false || source.deterministicReplay !== true || source.networkAttempted !== false || source.denseShardExecuted !== false || source.measuredObservedCountsPresent !== false || source.measuredHoldoutPresent !== false || source.measuredValidationRunCount !== 0 || source.scienceResponseApplicationCount !== 0 || !SHA.test(source.artifactSha256 ?? "")) throw new Error("v432-artifact-identity"); return value as KerrHighEnergyLikelihoodAuthorityArtifactV432; }
export function createKerrHighEnergyLikelihoodAuthoritySummaryV432(value: unknown): KerrHighEnergyLikelihoodAuthoritySummaryV432 { const artifact = parseKerrHighEnergyLikelihoodAuthorityArtifactV432(value), view = artifact.view; return Object.freeze({ version: KERR_HIGH_ENERGY_LIKELIHOOD_AUTHORITY_SUMMARY_VERSION_V432, status: view.status, artifactSha256: artifact.artifactSha256, campaign: view.campaign, selection: view.selection, families: view.families, counts: view.counts, products: view.products, authorityBoundary: view.authorityBoundary, denseCampaignStatus: view.denseCampaignStatus, fullArtifactAvailable: true, boundary: "bounded-family-recovery-holdout-selection-and-authority-no-holdout-count-arrays-or-quadrature-in-react-state" }); }
export function parseKerrHighEnergyLikelihoodAuthorityApiV432(value: unknown): KerrHighEnergyLikelihoodAuthorityApiV432 { const source = value as Partial<KerrHighEnergyLikelihoodAuthorityApiV432> | null; if (!source || source.version !== KERR_HIGH_ENERGY_LIKELIHOOD_AUTHORITY_API_VERSION_V432) throw new Error("v432-api-version"); if (source.available === true && source.reason === "ready" && source.summary) { if (source.summary.version !== KERR_HIGH_ENERGY_LIKELIHOOD_AUTHORITY_SUMMARY_VERSION_V432 || !SHA.test(source.summary.artifactSha256) || source.summary.counts.measuredObservedCountCount !== 0 || source.summary.counts.alternativeLikelihoodImplementationQualifiedCount !== 2 || source.summary.authorityBoundary.measuredInstrumentPerformanceAuthorityGranted !== false || Object.hasOwn(source.summary, "holdoutCounts") || Object.hasOwn(source.summary, "quadrature")) throw new Error("v432-api-summary"); return source as KerrHighEnergyLikelihoodAuthorityApiV432; } if (source.available === false && source.summary === null && ["lite-boundary", "local-shadow-only", "evidence-corrupt", "request-failed"].includes(source.reason ?? "")) return source as KerrHighEnergyLikelihoodAuthorityApiV432; throw new Error("v432-api-identity"); }
