"use client";
import { acquireAtlasResource } from "./atlasResourceLifecycle";
import { parseKerrMeasuredPackManifestApiV550, type KerrMeasuredPackManifestArtifactV550 } from "./kerrMeasuredPackManifestV550";
type SnapshotV550 = Readonly<{ status: "idle" | "loading" | "ready" | "unavailable"; reason: string | null; requestCount: 0 | 1; responseBytes: number; summary: KerrMeasuredPackManifestArtifactV550 | null }>;
const INITIAL: SnapshotV550 = Object.freeze({ status: "idle", reason: null, requestCount: 0, responseBytes: 0, summary: null }), listeners = new Set<() => void>(); let snapshot = INITIAL; let requestPromise: Promise<KerrMeasuredPackManifestArtifactV550> | null = null; const publish = (next: SnapshotV550) => { snapshot = Object.freeze(next); listeners.forEach((listener) => listener()); };
export function loadKerrMeasuredPackManifestSummaryV550(): Promise<KerrMeasuredPackManifestArtifactV550> { if (requestPromise) return requestPromise; publish({ status: "loading", reason: null, requestCount: 1, responseBytes: 0, summary: null }); requestPromise = fetch("/api/atlas/relativity-evidence/v550/measured-pack-manifest", { cache: "no-store" }).then(async (response) => { const body = await response.text(), responseBytes = new TextEncoder().encode(body).byteLength; if (responseBytes > 128 * 1024) throw new Error("response-too-large"); const api = parseKerrMeasuredPackManifestApiV550(JSON.parse(body)); if (!response.ok || !api.available || !api.summary) throw new Error(`v550-pack-${api.reason}`); publish({ status: "ready", reason: null, requestCount: 1, responseBytes, summary: api.summary }); return api.summary; }).catch((error: unknown) => { publish({ status: "unavailable", reason: error instanceof Error ? error.message : "request-failed", requestCount: 1, responseBytes: snapshot.responseBytes, summary: null }); throw error; }); return requestPromise; }
export const getKerrMeasuredPackManifestSnapshotV550 = () => snapshot;
export function subscribeKerrMeasuredPackManifestV550(listener: () => void): () => void { listeners.add(listener); const release = acquireAtlasResource("subscription", "relativity-lab", "v550-measured-pack-manifest", { owner: "v550-measured-pack-manifest", estimatedBytes: 0 }); let done = false; return () => { if (done) return; done = true; listeners.delete(listener); release(); }; }
export function getKerrMeasuredPackManifestTelemetryV550() { return Object.freeze({ listenerCount: listeners.size, requestCount: snapshot.requestCount, status: snapshot.status }); }
export function resetKerrMeasuredPackManifestClientForTestsV550(): void { if (listeners.size) throw new Error("v550-listener-leak"); snapshot = INITIAL; requestPromise = null; }
