"use client";
import { acquireAtlasResource } from "./atlasResourceLifecycle";
import { parseKerrSparseScienceImageApiV555, type KerrSparseScienceImageArtifactV555 } from "./kerrSparseScienceImageV555";
type SnapshotV555 = Readonly<{ status: "idle" | "loading" | "ready" | "unavailable"; reason: string | null; requestCount: 0 | 1; responseBytes: number; summary: KerrSparseScienceImageArtifactV555 | null }>;
const INITIAL: SnapshotV555 = Object.freeze({ status: "idle", reason: null, requestCount: 0, responseBytes: 0, summary: null }), listeners = new Set<() => void>(); let snapshot = INITIAL; let requestPromise: Promise<KerrSparseScienceImageArtifactV555> | null = null; const publish = (next: SnapshotV555) => { snapshot = Object.freeze(next); listeners.forEach((listener) => listener()); };
export function loadKerrSparseScienceImageSummaryV555(): Promise<KerrSparseScienceImageArtifactV555> { if (requestPromise) return requestPromise; publish({ status: "loading", reason: null, requestCount: 1, responseBytes: 0, summary: null }); requestPromise = fetch("/api/atlas/relativity-evidence/v555/sparse-science-image", { cache: "no-store" }).then(async (response) => { const body = await response.text(), responseBytes = new TextEncoder().encode(body).byteLength; if (responseBytes > 128 * 1024) throw new Error("response-too-large"); const api = parseKerrSparseScienceImageApiV555(JSON.parse(body)); if (!response.ok || !api.available || !api.summary) throw new Error(`v555-image-${api.reason}`); publish({ status: "ready", reason: null, requestCount: 1, responseBytes, summary: api.summary }); return api.summary; }).catch((error: unknown) => { publish({ status: "unavailable", reason: error instanceof Error ? error.message : "request-failed", requestCount: 1, responseBytes: snapshot.responseBytes, summary: null }); throw error; }); return requestPromise; }
export const getKerrSparseScienceImageSnapshotV555 = () => snapshot;
export function subscribeKerrSparseScienceImageV555(listener: () => void): () => void { listeners.add(listener); const release = acquireAtlasResource("subscription", "relativity-lab", "v555-sparse-science-image", { owner: "v555-sparse-science-image", estimatedBytes: 0 }); let done = false; return () => { if (done) return; done = true; listeners.delete(listener); release(); }; }
export const getKerrSparseScienceImageTelemetryV555 = () => Object.freeze({ listenerCount: listeners.size, requestCount: snapshot.requestCount, status: snapshot.status });
export function resetKerrSparseScienceImageClientForTestsV555(): void { if (listeners.size) throw new Error("v555-listener-leak"); snapshot = INITIAL; requestPromise = null; }
