export const KERR_RESPONSE_AWARE_REPLAY_KIT_VERSION_V541 = "v541-kerr-response-aware-standalone-replay-kit-artifact-v1" as const;
export const KERR_RESPONSE_AWARE_REPLAY_KIT_RESULT_VERSION_V541 = "v541-standalone-replay-kit-validation-result-v1" as const;
export const KERR_RESPONSE_AWARE_REPLAY_KIT_API_VERSION_V541 = "v541-kerr-response-aware-replay-kit-api-v1" as const;
export const KERR_RESPONSE_AWARE_REPLAY_KIT_HUD_PROFILE_ID_V541 = "science-cinematic-v9r0-v541" as const;
export const KERR_RESPONSE_AWARE_REPLAY_KIT_MEMBER_PATHS_V541 = Object.freeze(["README.md", "environment/environment.json", "environment/runtime-lock.txt", "manifest-sha256.txt", "payload/orbit-atlas-kerr-response-aware-v539.zip", "receipts/v540-replay-receipt.json", "validator/validate_replay_kit.py"] as const);
type MemberPathV541 = typeof KERR_RESPONSE_AWARE_REPLAY_KIT_MEMBER_PATHS_V541[number];
export type KerrResponseAwareReplayKitResultV541 = Readonly<{ version: typeof KERR_RESPONSE_AWARE_REPLAY_KIT_RESULT_VERSION_V541; generatedAt: string; status: "standalone-replay-kit-qualified"; validatorFileSha256: string; environmentSha256: string; runtimeLockFileSha256: string; crateFileSha256: string; v540ReceiptSha256: string; checks: Readonly<{ exactEnvironmentQualified: true; kitManifestReplayCount: 6; crateManifestReplayCount: 8; fitsRowReplayCount: 4; fitsColumnReplayCount: 17; columnSchemaReplayCount: 17; provenanceCanonicalReplayCount: 4; networkAttemptCount: 0; absolutePathStored: false }>; qualification: Readonly<{ standaloneValidatorQualified: true; environmentLockQualified: true; offlineReplayQualified: true; scienceImageQualified: false; physicalUncertaintyQualified: false; productionPromotionQualified: false }>; boundary: Readonly<{ workspaceImportCount: 0; networkAttempted: false; pixelSampleCount: 0; fitsImageHduCount: 0; physicalUncertaintyValueCount: 0; denseCampaignStatus: "incomplete-0-of-49"; formalProductPointer: "v263"; formalDefaultKernel: "legacy-eih-1pn"; portabilityBeyondLockedEnvironmentQualified: false }>; resultSha256: string }>;
export type KerrResponseAwareReplayKitArtifactV541 = Readonly<{
  version: typeof KERR_RESPONSE_AWARE_REPLAY_KIT_VERSION_V541; generatedAt: string; status: "standalone-replay-kit-qualified-locked-environment-only-heavy-browser-pending";
  source: Readonly<{ v539CrateFileSha256: string; v540ArtifactSha256: string; v540ReceiptSha256: string; v540EvidenceSha256: string; v540PointerSha256: string }>;
  kit: Readonly<{ path: "dist/science/kerr-response-aware-replay-kit-v541/orbit-atlas-kerr-response-aware-replay-kit-v541.zip"; fileSha256: string; bytes: number; memberCount: 7; manifestCoveredMemberCount: 6; abByteIdentical: true; fixedTimestamp: "2026-08-02T00:00:00"; fixedMode: "100644"; compression: "stored" }>;
  members: readonly Readonly<{ path: MemberPathV541; sha256: string; bytes: number; role: "readme" | "environment" | "integrity-manifest" | "science-crate" | "receipt" | "validator" }>[];
  environment: Readonly<{ version: "v541-replay-kit-environment-lock-v1"; generatedAt: string; status: "exact-runtime-lock-qualified-current-environment-only"; runtime: Readonly<{ pythonImplementation: "cpython"; pythonVersion: "3.12.3"; numpyVersion: "2.2.6"; astropyVersion: "7.2.0"; zlibVersion: "1.3.1" }>; validatorFileSha256: string; runtimeLockFileSha256: string; strictExactVersions: true; portabilityBeyondLockedEnvironmentQualified: false; absolutePathStored: false; environmentSha256: string }>;
  validation: Readonly<{ result: KerrResponseAwareReplayKitResultV541; resultExportPath: "dist/science/kerr-response-aware-replay-kit-v541/validation-receipt.json"; resultFileSha256: string; resultCanonicalSha256: string; subprocessAttemptCount: 2; qualifiedSubprocessCount: 2; temporaryDirectoryLeakCount: 0; workspaceImportCount: 0; networkAttemptCount: 0 }>;
  counts: Readonly<{ kitMemberCount: 7; manifestReplayCount: 6; validatorCount: 1; environmentManifestCount: 1; runtimeLockCount: 1; scienceCrateCount: 1; sourceReceiptCount: 1; validationReceiptCount: 1; pixelSampleCount: 0; fitsImageHduCount: 0; physicalUncertaintyValueCount: 0 }>;
  qualification: Readonly<{ standaloneReplayKitQualified: true; deterministicKitQualified: true; exactEnvironmentQualified: true; independentSubprocessReplayQualified: true; scienceImageQualified: false; physicalUncertaintyQualified: false; productionPromotionQualified: false; portabilityBeyondLockedEnvironmentQualified: false }>;
  boundary: Readonly<{ workspaceImportCount: 0; absolutePathStored: false; networkAttempted: false; exactRuntimeRequired: true; sciencePayloadMutationAllowed: false; cinematicScienceWritebackAllowed: false; measuredCalibrationFiles: 0; denseCampaignStatus: "incomplete-0-of-49"; browserQualification: "not-run"; formalProductPointer: "v263"; formalDefaultKernel: "legacy-eih-1pn" }>;
  sourceManifest: readonly Readonly<{ path: string; sha256: string }>[]; sourceSha256: string; artifactSha256: string;
}>;
export type KerrResponseAwareReplayKitSummaryV541 = Omit<KerrResponseAwareReplayKitArtifactV541, "generatedAt" | "sourceManifest" | "sourceSha256">;
export type KerrResponseAwareReplayKitApiV541 = Readonly<{ version: typeof KERR_RESPONSE_AWARE_REPLAY_KIT_API_VERSION_V541; available: boolean; reason: "ready" | "lite-boundary" | "local-shadow-only" | "evidence-corrupt"; summary: KerrResponseAwareReplayKitSummaryV541 | null }>;
export type KerrResponseAwareReplayKitHudModeV541 = "science" | "cinematic";

const SHA = /^[a-f0-9]{64}$/;
const TRANSIENT = new Set(["generatedAt", "artifactSha256", "payloadSha256", "evidenceSha256", "pointerSha256", "stageChainSha256", "columnSha256", "receiptSha256", "resultSha256", "environmentSha256"]);
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const compare = (left: string, right: string) => left < right ? -1 : left > right ? 1 : 0;
const canonicalize = (value: unknown): unknown => Array.isArray(value) ? value.map(canonicalize) : !isRecord(value) ? value : Object.fromEntries(Object.entries(value).filter(([key]) => !TRANSIENT.has(key)).sort(([left], [right]) => compare(left, right)).map(([key, entry]) => [key, canonicalize(entry)]));
export const canonicalKerrResponseAwareReplayKitV541 = (value: unknown) => JSON.stringify(canonicalize(value));

function validResult(result: Partial<KerrResponseAwareReplayKitResultV541> | undefined): result is KerrResponseAwareReplayKitResultV541 { return result?.version === KERR_RESPONSE_AWARE_REPLAY_KIT_RESULT_VERSION_V541 && result.status === "standalone-replay-kit-qualified" && [result.validatorFileSha256, result.environmentSha256, result.runtimeLockFileSha256, result.crateFileSha256, result.v540ReceiptSha256, result.resultSha256].every((entry) => SHA.test(entry ?? "")) && result.checks?.exactEnvironmentQualified === true && result.checks.kitManifestReplayCount === 6 && result.checks.crateManifestReplayCount === 8 && result.checks.fitsRowReplayCount === 4 && result.checks.fitsColumnReplayCount === 17 && result.checks.columnSchemaReplayCount === 17 && result.checks.provenanceCanonicalReplayCount === 4 && result.checks.networkAttemptCount === 0 && result.checks.absolutePathStored === false && result.qualification?.standaloneValidatorQualified === true && result.qualification.environmentLockQualified === true && result.qualification.offlineReplayQualified === true && result.qualification.scienceImageQualified === false && result.qualification.physicalUncertaintyQualified === false && result.qualification.productionPromotionQualified === false && result.boundary?.workspaceImportCount === 0 && result.boundary.networkAttempted === false && result.boundary.pixelSampleCount === 0 && result.boundary.fitsImageHduCount === 0 && result.boundary.physicalUncertaintyValueCount === 0 && result.boundary.denseCampaignStatus === "incomplete-0-of-49" && result.boundary.formalProductPointer === "v263" && result.boundary.formalDefaultKernel === "legacy-eih-1pn" && result.boundary.portabilityBeyondLockedEnvironmentQualified === false; }
function validCore(value: Partial<KerrResponseAwareReplayKitArtifactV541>): boolean { const environment = value.environment, validation = value.validation; return value.version === KERR_RESPONSE_AWARE_REPLAY_KIT_VERSION_V541 && value.status === "standalone-replay-kit-qualified-locked-environment-only-heavy-browser-pending" && Object.values(value.source ?? {}).length === 5 && Object.values(value.source ?? {}).every((entry) => SHA.test(entry)) && value.kit?.path === "dist/science/kerr-response-aware-replay-kit-v541/orbit-atlas-kerr-response-aware-replay-kit-v541.zip" && SHA.test(value.kit.fileSha256) && Number.isSafeInteger(value.kit.bytes) && value.kit.bytes > 0 && value.kit.memberCount === 7 && value.kit.manifestCoveredMemberCount === 6 && value.kit.abByteIdentical === true && value.kit.fixedTimestamp === "2026-08-02T00:00:00" && value.kit.fixedMode === "100644" && value.kit.compression === "stored"
    && value.members?.length === 7 && value.members.every((member, index) => member.path === KERR_RESPONSE_AWARE_REPLAY_KIT_MEMBER_PATHS_V541[index] && SHA.test(member.sha256) && Number.isSafeInteger(member.bytes) && member.bytes > 0)
    && environment?.version === "v541-replay-kit-environment-lock-v1" && environment.status === "exact-runtime-lock-qualified-current-environment-only" && environment.runtime?.pythonImplementation === "cpython" && environment.runtime.pythonVersion === "3.12.3" && environment.runtime.numpyVersion === "2.2.6" && environment.runtime.astropyVersion === "7.2.0" && environment.runtime.zlibVersion === "1.3.1" && SHA.test(environment.validatorFileSha256) && SHA.test(environment.runtimeLockFileSha256) && environment.strictExactVersions === true && environment.portabilityBeyondLockedEnvironmentQualified === false && environment.absolutePathStored === false && SHA.test(environment.environmentSha256)
    && validResult(validation?.result) && validation.resultExportPath === "dist/science/kerr-response-aware-replay-kit-v541/validation-receipt.json" && SHA.test(validation.resultFileSha256) && validation.resultCanonicalSha256 === validation.result.resultSha256 && validation.subprocessAttemptCount === 2 && validation.qualifiedSubprocessCount === 2 && validation.temporaryDirectoryLeakCount === 0 && validation.workspaceImportCount === 0 && validation.networkAttemptCount === 0
    && value.counts?.kitMemberCount === 7 && value.counts.manifestReplayCount === 6 && value.counts.validatorCount === 1 && value.counts.environmentManifestCount === 1 && value.counts.runtimeLockCount === 1 && value.counts.scienceCrateCount === 1 && value.counts.sourceReceiptCount === 1 && value.counts.validationReceiptCount === 1 && value.counts.pixelSampleCount === 0 && value.counts.fitsImageHduCount === 0 && value.counts.physicalUncertaintyValueCount === 0
    && value.qualification?.standaloneReplayKitQualified === true && value.qualification.deterministicKitQualified === true && value.qualification.exactEnvironmentQualified === true && value.qualification.independentSubprocessReplayQualified === true && value.qualification.scienceImageQualified === false && value.qualification.physicalUncertaintyQualified === false && value.qualification.productionPromotionQualified === false && value.qualification.portabilityBeyondLockedEnvironmentQualified === false
    && value.boundary?.workspaceImportCount === 0 && value.boundary.absolutePathStored === false && value.boundary.networkAttempted === false && value.boundary.exactRuntimeRequired === true && value.boundary.sciencePayloadMutationAllowed === false && value.boundary.cinematicScienceWritebackAllowed === false && value.boundary.measuredCalibrationFiles === 0 && value.boundary.denseCampaignStatus === "incomplete-0-of-49" && value.boundary.browserQualification === "not-run" && value.boundary.formalProductPointer === "v263" && value.boundary.formalDefaultKernel === "legacy-eih-1pn" && SHA.test(value.artifactSha256 ?? ""); }
export function parseKerrResponseAwareReplayKitArtifactV541(value: unknown): KerrResponseAwareReplayKitArtifactV541 { if (!isRecord(value) || !validCore(value as Partial<KerrResponseAwareReplayKitArtifactV541>)) throw new Error("v541-replay-kit-boundary"); const artifact = value as unknown as KerrResponseAwareReplayKitArtifactV541; if (!Array.isArray(artifact.sourceManifest) || artifact.sourceManifest.some((entry) => !entry.path || !SHA.test(entry.sha256)) || !SHA.test(artifact.sourceSha256)) throw new Error("v541-replay-kit-manifest"); return artifact; }
export function createKerrResponseAwareReplayKitSummaryV541(value: unknown): KerrResponseAwareReplayKitSummaryV541 { const artifact = parseKerrResponseAwareReplayKitArtifactV541(value); const summary = { ...artifact } as Record<string, unknown>; delete summary.generatedAt; delete summary.sourceManifest; delete summary.sourceSha256; return Object.freeze(summary) as unknown as KerrResponseAwareReplayKitSummaryV541; }
export function parseKerrResponseAwareReplayKitApiV541(value: unknown): KerrResponseAwareReplayKitApiV541 { if (!isRecord(value) || value.version !== KERR_RESPONSE_AWARE_REPLAY_KIT_API_VERSION_V541 || typeof value.available !== "boolean" || !["ready", "lite-boundary", "local-shadow-only", "evidence-corrupt"].includes(String(value.reason))) throw new Error("v541-api-boundary"); if (value.available) { if (!isRecord(value.summary) || !validCore(value.summary as Partial<KerrResponseAwareReplayKitArtifactV541>)) throw new Error("v541-api-summary"); } else if (value.summary !== null) throw new Error("v541-api-unavailable-summary"); return value as unknown as KerrResponseAwareReplayKitApiV541; }

const scienceProfile = Object.freeze({ id: KERR_RESPONSE_AWARE_REPLAY_KIT_HUD_PROFILE_ID_V541, mode: "science" as const, panel: "#02080a", panelRaised: "#07131a", ink: "#effdff", muted: "#78959c", qualified: "#74f4c5", unavailable: "#ff91ad", localShadowOnly: true as const, defaultApplied: false as const, scienceBoundary: Object.freeze({ linearDisplay: true, bloomIntensity: 0, colorGradeIntensity: 0, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }), cinematicSeed: null as string | null });
const cinematicProfile = Object.freeze({ ...scienceProfile, mode: "cinematic" as const, panel: "#100907", panelRaised: "#1b130f", ink: "#fff7ea", muted: "#b09a84", qualified: "#8ff5ca", unavailable: "#ff96b2", scienceBoundary: Object.freeze({ linearDisplay: false, bloomIntensity: 0.05, colorGradeIntensity: 0.035, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }), cinematicSeed: "orbit-atlas-v541-replay-kit-seed-01" });
export const resolveKerrResponseAwareReplayKitHudProfileV541 = (mode: KerrResponseAwareReplayKitHudModeV541) => mode === "science" ? scienceProfile : cinematicProfile;
export function createKerrResponseAwareReplayKitHudEncodingV541(summary: KerrResponseAwareReplayKitSummaryV541, mode: KerrResponseAwareReplayKitHudModeV541) { if (!SHA.test(summary.artifactSha256) || !SHA.test(summary.kit.fileSha256) || !SHA.test(summary.validation.result.resultSha256)) throw new Error("v541-hud-source"); return Object.freeze({ version: "v541-response-aware-replay-kit-hud-v1" as const, profileId: KERR_RESPONSE_AWARE_REPLAY_KIT_HUD_PROFILE_ID_V541, mode, scientificPayloadKey: summary.source.v539CrateFileSha256, replayReceiptKey: summary.source.v540ReceiptSha256, kitArtifactKey: summary.artifactSha256, kitFileKey: summary.kit.fileSha256, validationResultKey: summary.validation.result.resultSha256, members: summary.members, environment: summary.environment, result: summary.validation.result, memberCount: 7 as const, subprocessCount: 2 as const, networkAttemptCount: 0 as const, imageHduCount: 0 as const, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }); }
export function compareKerrResponseAwareReplayKitHudEncodingsV541(science: ReturnType<typeof createKerrResponseAwareReplayKitHudEncodingV541>, cinematic: ReturnType<typeof createKerrResponseAwareReplayKitHudEncodingV541>) { if (science.mode !== "science" || cinematic.mode !== "cinematic" || science.scientificPayloadKey !== cinematic.scientificPayloadKey || science.replayReceiptKey !== cinematic.replayReceiptKey || science.kitArtifactKey !== cinematic.kitArtifactKey || science.kitFileKey !== cinematic.kitFileKey || science.validationResultKey !== cinematic.validationResultKey || JSON.stringify(science.members) !== JSON.stringify(cinematic.members) || JSON.stringify(science.environment) !== JSON.stringify(cinematic.environment) || JSON.stringify(science.result) !== JSON.stringify(cinematic.result)) throw new Error("v541-hud-boundary"); return Object.freeze({ scientificPayloadStable: true as const, replayReceiptStable: true as const, replayKitStable: true as const, environmentLockStable: true as const, validationResultStable: true as const, memberCount: 7 as const, subprocessCount: 2 as const, networkAttemptCount: 0 as const, imageHduCount: 0 as const, scientificFieldMutation: false as const }); }
