export const KERR_REPLAY_ISOLATED_PREFLIGHT_VERSION_V543 = "v543-kerr-replay-isolated-preflight-artifact-v1" as const;
export const KERR_REPLAY_ISOLATED_PREFLIGHT_API_VERSION_V543 = "v543-kerr-replay-isolated-preflight-api-v1" as const;
export const KERR_REPLAY_ISOLATED_PREFLIGHT_HUD_PROFILE_ID_V543 = "science-cinematic-v9r2-v543" as const;
const SHA = /^[0-9a-f]{64}$/;
const TRANSIENT = new Set(["generatedAt", "artifactSha256", "payloadSha256", "evidenceSha256", "pointerSha256", "stageChainSha256", "columnSha256", "receiptSha256", "resultSha256", "environmentSha256", "preflightSha256", "matrixSha256", "isolatedReceiptSha256", "executionMatrixSha256"]);
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const canonicalize = (value: unknown): unknown => Array.isArray(value) ? value.map(canonicalize) : !isRecord(value) ? value : Object.fromEntries(Object.entries(value).filter(([key]) => !TRANSIENT.has(key)).sort(([left], [right]) => left.localeCompare(right)).map(([key, entry]) => [key, canonicalize(entry)]));
export const canonicalKerrReplayIsolatedPreflightV543 = (value: unknown) => JSON.stringify(canonicalize(value));

export type KerrReplayExecutionCellV543 = Readonly<{ id: "locked-runtime-science-replay" | "isolated-no-site-packages" | "same-lock-other-os" | "different-python" | "different-science-dependencies"; execution: string; pythonMode: string; dependencyState: string; packagePreflight: string; scienceReplay: string; scienceQualified: boolean }>;
export type KerrReplayIsolatedReceiptV543 = Readonly<{
  version: "v543-isolated-stdlib-preflight-receipt-v1";
  status: "isolated-package-preflight-qualified-science-replay-unavailable-no-site-packages";
  source: Readonly<{ v542PreflightValidatorFileSha256: string; v542RawPreflightSha256: string; v541KitFileSha256: string; v541ValidationResultSha256: string }>;
  execution: Readonly<{ pythonIsolatedFlag: 1; pythonNoSiteFlag: 1; siteModuleLoaded: false; sitePackagePathCount: 0; numpyModuleLoaded: false; astropyModuleLoaded: false; commandFlags: readonly ["-I", "-S"] }>;
  observedRuntime: Readonly<{ pythonImplementation: string; pythonVersion: string; numpyVersion: "unavailable"; astropyVersion: "unavailable"; zlibVersion: string; osFamily: string; osRelease: string; machine: string }>;
  packageChecks: Readonly<{ kitMemberCount: 7; kitManifestReplayCount: 6; crateMemberCount: 9; crateManifestReplayCount: 8; pathTraversalCount: 0; symlinkCount: 0; duplicateNameCount: 0; encryptedMemberCount: 0; networkAttemptCount: 0; workspaceImportCount: 0; numpyImported: false; astropyImported: false; exactDependencyTupleMatch: false }>;
  compatibility: Readonly<{ packagePreflightExecuted: true; packagePreflightQualified: true; exactScienceDependencyTupleDetected: false; scienceReplayExecuted: false; scienceReplayQualified: false; reason: string }>;
  qualification: Readonly<{ isolatedStdlibPreflightQualified: true; scienceReplayQualified: false; crossOperatingSystemQualified: false; crossEnvironmentScienceQualified: false; scienceImageQualified: false; productionPromotionQualified: false }>;
  boundary: Readonly<{ workspaceImportCount: 0; networkAttemptCount: 0; scienceDependencyImportCount: 0; fitsSemanticValidationPerformed: false; denseCampaignStatus: "incomplete-0-of-49"; formalProductPointer: "v263"; formalDefaultKernel: "legacy-eih-1pn" }>;
  rawPreflight: Readonly<Record<string, unknown>>;
  isolatedReceiptSha256: string;
}>;
export type KerrReplayExecutionMatrixV543 = Readonly<{ version: "v543-isolated-preflight-execution-matrix-v1"; status: "two-executed-package-environments-one-science-qualified-cross-environment-unqualified"; cells: readonly KerrReplayExecutionCellV543[]; cellCount: 5; executedCellCount: 2; packagePreflightQualifiedCellCount: 2; scienceQualifiedCellCount: 1; crossOperatingSystemExecutedCellCount: 0; unexecutedCellCount: 3; boundary: Readonly<{ packageQualificationPromotedToScience: false; crossOperatingSystemQualified: false; crossEnvironmentScienceQualified: false }>; executionMatrixSha256: string }>;
export type KerrReplayIsolatedPreflightArtifactV543 = Readonly<{
  version: typeof KERR_REPLAY_ISOLATED_PREFLIGHT_VERSION_V543;
  status: "isolated-stdlib-preflight-qualified-science-boundary-preserved-cross-environment-unqualified";
  source: Readonly<{ v542ArtifactSha256: string; v542PreflightSha256: string; v542MatrixSha256: string; v542EvidenceSha256: string; v542PointerSha256: string }>;
  exports: Readonly<Record<"receipt" | "matrix", Readonly<{ path: string; fileSha256: string; canonicalSha256: string }>> & Record<"runner" | "validator", Readonly<{ path: string; fileSha256: string }>>>;
  receipt: KerrReplayIsolatedReceiptV543;
  executionMatrix: KerrReplayExecutionMatrixV543;
  counts: Readonly<{ isolatedSubprocessAttemptCount: 2; qualifiedIsolatedSubprocessCount: 2; temporaryDirectoryLeakCount: 0; executedEnvironmentCount: 2; packageQualifiedEnvironmentCount: 2; scienceQualifiedEnvironmentCount: 1; crossOperatingSystemExecutionCount: 0; scienceDependencyImportCount: 0; networkAttemptCount: 0 }>;
  qualification: Readonly<{ isolatedNoSitePackagePreflightQualified: true; v541LockedEnvironmentScienceReplayQualified: true; packagePreflightPortabilityDemonstratedWithoutScienceDependencies: true; crossOperatingSystemQualified: false; crossEnvironmentScienceQualified: false; scienceImageQualified: false; productionPromotionQualified: false }>;
  boundary: Readonly<{ isolatedPreflightIssuesScienceQualification: false; fitsSemanticValidationPerformedInIsolation: false; denseCampaignStatus: "incomplete-0-of-49"; measuredCalibrationFiles: 0; browserQualification: "not-run"; formalProductPointer: "v263"; formalDefaultKernel: "legacy-eih-1pn" }>;
  sourceManifest: readonly Readonly<{ path: string; sha256: string }>[]; sourceSha256: string; artifactSha256: string;
}>;
export type KerrReplayIsolatedPreflightApiV543 = Readonly<{ version: typeof KERR_REPLAY_ISOLATED_PREFLIGHT_API_VERSION_V543; available: boolean; reason: "ready" | "lite-boundary" | "local-shadow-only" | "evidence-corrupt"; summary: KerrReplayIsolatedPreflightArtifactV543 | null }>;

function validCells(value: unknown): value is readonly KerrReplayExecutionCellV543[] { return Array.isArray(value) && value.length === 5 && value.filter((cell) => isRecord(cell) && cell.execution !== "not-run").length === 2 && value.filter((cell) => isRecord(cell) && cell.scienceQualified === true).length === 1 && value.every((cell) => isRecord(cell) && typeof cell.id === "string" && typeof cell.scienceReplay === "string" && typeof cell.scienceQualified === "boolean"); }
export function parseKerrReplayIsolatedPreflightArtifactV543(value: unknown): KerrReplayIsolatedPreflightArtifactV543 {
  if (!isRecord(value) || value.version !== KERR_REPLAY_ISOLATED_PREFLIGHT_VERSION_V543 || value.status !== "isolated-stdlib-preflight-qualified-science-boundary-preserved-cross-environment-unqualified" || !SHA.test(String(value.artifactSha256)) || !SHA.test(String(value.sourceSha256))) throw new Error("v543-artifact-boundary");
  const artifact = value as unknown as KerrReplayIsolatedPreflightArtifactV543, receipt = artifact.receipt, matrix = artifact.executionMatrix;
  if (receipt.version !== "v543-isolated-stdlib-preflight-receipt-v1" || !SHA.test(receipt.isolatedReceiptSha256) || receipt.execution.pythonIsolatedFlag !== 1 || receipt.execution.pythonNoSiteFlag !== 1 || receipt.execution.siteModuleLoaded !== false || receipt.execution.sitePackagePathCount !== 0 || receipt.observedRuntime.numpyVersion !== "unavailable" || receipt.observedRuntime.astropyVersion !== "unavailable" || receipt.qualification.scienceReplayQualified !== false) throw new Error("v543-receipt-boundary");
  if (matrix.version !== "v543-isolated-preflight-execution-matrix-v1" || !SHA.test(matrix.executionMatrixSha256) || !validCells(matrix.cells) || matrix.executedCellCount !== 2 || matrix.scienceQualifiedCellCount !== 1 || artifact.qualification.crossEnvironmentScienceQualified !== false || artifact.boundary.formalProductPointer !== "v263" || artifact.boundary.formalDefaultKernel !== "legacy-eih-1pn" || artifact.boundary.denseCampaignStatus !== "incomplete-0-of-49") throw new Error("v543-matrix-boundary");
  if (!Array.isArray(artifact.sourceManifest) || artifact.sourceManifest.some((entry) => !entry.path || !SHA.test(entry.sha256))) throw new Error("v543-source-manifest");
  return artifact;
}
export function parseKerrReplayIsolatedPreflightApiV543(value: unknown): KerrReplayIsolatedPreflightApiV543 { if (!isRecord(value) || value.version !== KERR_REPLAY_ISOLATED_PREFLIGHT_API_VERSION_V543 || typeof value.available !== "boolean" || !["ready", "lite-boundary", "local-shadow-only", "evidence-corrupt"].includes(String(value.reason))) throw new Error("v543-api-boundary"); if (value.available) parseKerrReplayIsolatedPreflightArtifactV543(value.summary); else if (value.summary !== null) throw new Error("v543-api-unavailable-summary"); return value as unknown as KerrReplayIsolatedPreflightApiV543; }

export type KerrReplayIsolatedPreflightHudModeV543 = "science" | "cinematic";
const scienceProfile = Object.freeze({ id: KERR_REPLAY_ISOLATED_PREFLIGHT_HUD_PROFILE_ID_V543, mode: "science" as const, panel: "#030e12", panelRaised: "#071a20", ink: "#e8fcff", muted: "#789ca5", qualified: "#78f0bd", warning: "#f2c578", unavailable: "#ff8fac", scienceBoundary: Object.freeze({ linearDisplay: true, bloomIntensity: 0 as const, colorGradeIntensity: 0 as const, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }), cinematicSeed: null });
const cinematicProfile = Object.freeze({ ...scienceProfile, mode: "cinematic" as const, panel: "#120a07", panelRaised: "#22140e", ink: "#fff5e7", muted: "#b79b82", qualified: "#90edc4", warning: "#f4c374", unavailable: "#ff98b1", scienceBoundary: Object.freeze({ linearDisplay: false, bloomIntensity: 0.04, colorGradeIntensity: 0.028, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }), cinematicSeed: "orbit-atlas-v543-isolated-seed-01" });
export function resolveKerrReplayIsolatedPreflightHudProfileV543(mode: KerrReplayIsolatedPreflightHudModeV543) { return mode === "science" ? scienceProfile : cinematicProfile; }
export function createKerrReplayIsolatedPreflightHudEncodingV543(artifact: KerrReplayIsolatedPreflightArtifactV543, mode: KerrReplayIsolatedPreflightHudModeV543) { return Object.freeze({ version: "v543-isolated-preflight-hud-v1" as const, profileId: KERR_REPLAY_ISOLATED_PREFLIGHT_HUD_PROFILE_ID_V543, mode, artifactKey: artifact.artifactSha256, v542ArtifactKey: artifact.source.v542ArtifactSha256, receiptKey: artifact.receipt.isolatedReceiptSha256, matrixKey: artifact.executionMatrix.executionMatrixSha256, cells: artifact.executionMatrix.cells, execution: artifact.receipt.execution, observedRuntime: artifact.receipt.observedRuntime, executedEnvironmentCount: 2 as const, packageQualifiedEnvironmentCount: 2 as const, scienceQualifiedEnvironmentCount: 1 as const, scienceDependencyImportCount: 0 as const, crossEnvironmentScienceQualified: false as const, imageHduCount: 0 as const, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }); }
export function compareKerrReplayIsolatedPreflightHudEncodingsV543(science: ReturnType<typeof createKerrReplayIsolatedPreflightHudEncodingV543>, cinematic: ReturnType<typeof createKerrReplayIsolatedPreflightHudEncodingV543>) { if (science.mode !== "science" || cinematic.mode !== "cinematic" || science.artifactKey !== cinematic.artifactKey || science.v542ArtifactKey !== cinematic.v542ArtifactKey || science.receiptKey !== cinematic.receiptKey || science.matrixKey !== cinematic.matrixKey || JSON.stringify(science.cells) !== JSON.stringify(cinematic.cells) || JSON.stringify(science.execution) !== JSON.stringify(cinematic.execution) || JSON.stringify(science.observedRuntime) !== JSON.stringify(cinematic.observedRuntime)) throw new Error("v543-hud-boundary"); return Object.freeze({ executionStable: true as const, compatibilityStable: true as const, scienceQualificationStable: true as const, executedEnvironmentCount: 2 as const, scienceQualifiedEnvironmentCount: 1 as const, scientificFieldMutation: false as const }); }
