import { createHash } from "node:crypto";

export const KERR_HIGH_ENERGY_MEASURED_ADMISSION_VERSION_V434 = "v434-kerr-high-energy-measured-admission-v1" as const;
export const KERR_HIGH_ENERGY_MEASURED_ADMISSION_ARTIFACT_VERSION_V434 = "v434-kerr-high-energy-measured-admission-artifact-v1" as const;
export const KERR_HIGH_ENERGY_MEASURED_ADMISSION_SUMMARY_VERSION_V434 = "v434-kerr-high-energy-measured-admission-summary-v1" as const;
export const KERR_HIGH_ENERGY_MEASURED_ADMISSION_API_VERSION_V434 = "v434-kerr-high-energy-measured-admission-api-v1" as const;
export const KERR_V433_ARTIFACT_SHA256_V434 = "637542a0666f9396b3013fc3664df304f4d91c1564dcb2df268b15e05e44eaf4" as const;
export const KERR_V433_ARTIFACT_FILE_SHA256_V434 = "7409c4d7e099822d4894b39ba79fca1fcc7045b49c23a897c08fad8ae92977bb" as const;
export const KERR_V433_ORACLE_SHA256_V434 = "bb95dc27e87721ae52f03424a413ecc524c79296b83419c5cccfb8bd00b28892" as const;
export const KERR_V433_ORACLE_FILE_SHA256_V434 = "7b0dfdf8db6c5e566891fff4290c22518e1499e6f3f7bfc3266bfaedcf661116" as const;
export const KERR_V433_EVIDENCE_SHA256_V434 = "56c823757bedf86aa100dcd2c302b589295a496f853e18d86f97a6a60ce7c96a" as const;
export const KERR_V433_EVIDENCE_FILE_SHA256_V434 = "9da3cabcada513fcddd18462c9b2ccaa06bc222ae7af2cd664d12ce7052abce2" as const;
export const KERR_V433_POINTER_SHA256_V434 = "1993dec9016120cd7f0bf11da53af6de09315432b7b790573020dee8bea9ee2b" as const;
export const KERR_V433_POINTER_FILE_SHA256_V434 = "86dd6b1834b5e5994a7dbb3d52b4e2fc39ac347d005bc82f1094f174bcd6c30a" as const;

const SHA = /^[a-f0-9]{64}$/;
const TRANSIENT = new Set(["generatedAt", "artifactSha256", "evidenceSha256", "pointerSha256"]);
export type KerrMeasuredLikelihoodFamilyV434 = "negative-binomial" | "poisson-lognormal";
export type KerrMeasuredAdmissionPackV434 = Readonly<{
  version: "v434-kerr-high-energy-measured-authority-pack-v1";
  sourceKind: "measured-authority-candidate" | "test-fixture-nonpublishable";
  measuredAttestation: string;
  instrument: Readonly<{ manufacturer: string; model: string; serialOrCampaignId: string }>;
  identity: Readonly<{ responseArtifactSha256: string; responseEvidenceSha256: string; likelihoodArtifactSha256: string; likelihoodEvidenceSha256: string; jointNuisanceArtifactSha256: string }>;
  channelLayout: Readonly<{ analyzerAngleCount: number; detectorChannelCount: number; flattenedCount: number; channelOrderSha256: string }>;
  responseCalibration: Readonly<{ campaignIds: readonly string[]; rawEventFileSha256: readonly string[] }>;
  likelihoodFit: Readonly<{ campaignIds: readonly string[]; sourceIds: readonly string[]; rawEventFileSha256: readonly string[] }>;
  independentHoldout: Readonly<{ campaignIds: readonly string[]; sourceIds: readonly string[]; rawEventFileSha256: readonly string[]; observedCountsArtifactSha256: string; processingParametersSha256: string; observedCountCellCount: number; replicateCount: number }>;
  preregistration: Readonly<{ artifactSha256: string; frozenBeforeHoldoutOpened: boolean; likelihoodFamily: KerrMeasuredLikelihoodFamilyV434 | string }>;
  crossBlockIndependence: Readonly<{ method: "independent-acquisition-design" | "measured-cross-covariance" | string; proofArtifactSha256: string; responseAndLikelihoodRawArtifactsDisjoint: boolean; replicateCount: number }>;
  thresholdPolicy: Readonly<{ source: string; artifactSha256: string; postHocThresholdTuning: boolean; multipleComparisonControl: boolean; effectSizeAndConfidenceInterval: boolean }>;
}>;
export type KerrMeasuredAdmissionChecksV434 = Readonly<{ identitySha: boolean; channelLayout: boolean; campaignDisjointness: boolean; rawEventDisjointness: boolean; holdoutIndependence: boolean; preregistration: boolean; crossBlockIndependence: boolean; thresholdPolicy: boolean }>;
export type KerrMeasuredAdmissionValidationV434 = Readonly<{ valid: boolean; measuredEligible: boolean; scienceAdmissionGranted: false; errors: readonly string[]; checks: KerrMeasuredAdmissionChecksV434; boundary: "structural-validation-never-grants-science-admission-independent-measured-validation-and-review-required" }>;
export type KerrMeasuredAdmissionContractV434 = Readonly<{ version: "v434-kerr-high-energy-measured-admission-contract-v1"; status: "admission-firewall-ready-no-measured-pack"; maximumPackBytes: 67108864; requiredIdentityShaCount: 5; requiredChannelLayout: Readonly<{ analyzerAngleCount: 4; detectorChannelCount: 6; flattenedCount: 24 }>; requiredGates: readonly string[]; measuredAttestation: "real-measured-response-likelihood-and-independent-holdout-not-synthetic-or-example"; admission: Readonly<{ structuralValidationAloneInsufficient: true; fixtureNeverAdmissible: true; independentMeasuredValidationRequired: true; independentReviewRequired: true; automaticRetryForbidden: true; currentStatus: "blocked-no-measured-authority-pack"; scienceResponseApplicationCount: 0 }>; formalProductPointer: "v263"; denseCampaignStatus: "incomplete-0-of-49"; boundary: string }>;
export type KerrMeasuredAdmissionOracleV434 = Readonly<{ version: "v434-kerr-high-energy-measured-admission-python-oracle-v1"; generatedAt: string; status: "qualified-measured-authority-admission-firewall-fixture-only-no-measured-pack-science-admission-blocked"; sourceV433ArtifactSha256: typeof KERR_V433_ARTIFACT_SHA256_V434; fixture: KerrMeasuredAdmissionPackV434; fixtureReport: KerrMeasuredAdmissionValidationV434; mutationResults: readonly Readonly<{ id: string; rejected: true; errors: readonly string[] }>[]; counts: Readonly<{ requiredGateCount: 9; fixtureCount: 1; mutationCount: 12; rejectedMutationCount: 12; measuredPackCount: 0; measuredResponseAuthorityCount: 0; measuredLikelihoodAuthorityCount: 0; independentMeasuredHoldoutCount: 0; independentReviewCount: 0; scienceResponseApplicationCount: 0 }>; qualification: Readonly<{ validatorQualified: true; mutationFirewallQualified: true; measuredPackQualified: false; scienceAdmissionQualified: false }>; networkAttempted: false; measuredImportAttempted: false; denseShardExecuted: false; scienceResponseApplicationCount: 0; boundary: string; artifactSha256: string }>;
export type KerrMeasuredAdmissionViewV434 = Readonly<{ version: typeof KERR_HIGH_ENERGY_MEASURED_ADMISSION_VERSION_V434; status: KerrMeasuredAdmissionOracleV434["status"]; source: Readonly<{ v433ArtifactSha256: typeof KERR_V433_ARTIFACT_SHA256_V434; v433OracleSha256: typeof KERR_V433_ORACLE_SHA256_V434; v433EvidenceSha256: typeof KERR_V433_EVIDENCE_SHA256_V434; v433PointerSha256: typeof KERR_V433_POINTER_SHA256_V434 }>; gates: Readonly<{ requiredGateCount: 9; passedFixtureGateCount: 8; independentReviewStatus: "not-run"; allRequiredBeforeAdmission: true; structuralValidationAloneInsufficient: true }>; fixture: Readonly<{ status: "validated-nonpublishable-validator-fixture"; structurallyValid: true; measuredEligible: false; scienceAdmissionGranted: false; mutationCount: 12; rejectedMutationCount: 12; maximumPythonTypeScriptDifference: number }>; counts: KerrMeasuredAdmissionOracleV434["counts"]; products: Readonly<{ json: "available-admission-summary-and-boundary"; oracle: "available-validator-conformance-fixture"; contract: "available-measured-admission-contract"; fixture: "available-nonpublishable-validator-fixture"; csv: "available-gate-status-table"; fits: "available-admission-status-no-detector-image"; png: "available-admission-firewall-diagram-not-instrument-performance" }>; authorityBoundary: Readonly<{ packSchemaAuthorityGranted: true; provenanceFirewallAuthorityGranted: true; disjointnessValidatorAuthorityGranted: true; preregistrationValidatorAuthorityGranted: true; crossBlockIndependenceValidatorAuthorityGranted: true; fixturePerformanceAuthorityGranted: false; measuredPackPresent: false; measuredResponseAuthorityGranted: false; measuredLikelihoodAuthorityGranted: false; independentMeasuredHoldoutQualified: false; independentReviewQualified: false; scienceAdmissionGranted: false; scienceResponseApplicationCount: 0; detectorAuthorityGranted: false; denseAuthorityGranted: false; unavailableIsNotZero: true }>; scienceBoundary: Readonly<{ status: "blocked-no-measured-authority-pack"; admitted: false; missingRequirements: readonly ["measured-response-authority", "measured-likelihood-authority", "independent-measured-holdout", "cross-block-independence-proof", "independent-review"]; scienceResponseApplicationCount: 0 }>; denseCampaignStatus: "incomplete-0-of-49"; browserQualification: "not-run"; boundary: string }>;
export type KerrMeasuredAdmissionArtifactV434 = Readonly<{ version: typeof KERR_HIGH_ENERGY_MEASURED_ADMISSION_ARTIFACT_VERSION_V434; generatedAt: string; status: KerrMeasuredAdmissionViewV434["status"]; sourceFiles: Readonly<{ v433ArtifactFileSha256: typeof KERR_V433_ARTIFACT_FILE_SHA256_V434; v433OracleFileSha256: typeof KERR_V433_ORACLE_FILE_SHA256_V434; v433EvidenceFileSha256: typeof KERR_V433_EVIDENCE_FILE_SHA256_V434; v433PointerFileSha256: typeof KERR_V433_POINTER_FILE_SHA256_V434; pythonOracleFileSha256: string; admissionContractFileSha256: string; fixtureFileSha256: string }>; pythonOracleArtifactSha256: string; view: KerrMeasuredAdmissionViewV434; deterministicReplay: true; networkAttempted: false; measuredImportAttempted: false; measuredPackPresent: false; denseShardExecuted: false; scienceResponseApplicationCount: 0; artifactSha256: string }>;
export type KerrMeasuredAdmissionSummaryV434 = Readonly<{ version: typeof KERR_HIGH_ENERGY_MEASURED_ADMISSION_SUMMARY_VERSION_V434; status: KerrMeasuredAdmissionViewV434["status"]; artifactSha256: string; gates: KerrMeasuredAdmissionViewV434["gates"]; fixture: KerrMeasuredAdmissionViewV434["fixture"]; counts: KerrMeasuredAdmissionViewV434["counts"]; products: KerrMeasuredAdmissionViewV434["products"]; authorityBoundary: KerrMeasuredAdmissionViewV434["authorityBoundary"]; scienceBoundary: KerrMeasuredAdmissionViewV434["scienceBoundary"]; denseCampaignStatus: "incomplete-0-of-49"; fullArtifactAvailable: true; boundary: "bounded-admission-gates-counts-and-missing-requirements-no-pack-identities-or-raw-artifacts-in-react-state" }>;
export type KerrMeasuredAdmissionApiV434 = Readonly<{ version: typeof KERR_HIGH_ENERGY_MEASURED_ADMISSION_API_VERSION_V434; available: boolean; reason: "ready" | "lite-boundary" | "local-shadow-only" | "evidence-corrupt" | "request-failed"; summary: KerrMeasuredAdmissionSummaryV434 | null }>;

function canonicalize(value: unknown): unknown { if (Array.isArray(value)) return value.map(canonicalize); if (!value || typeof value !== "object") return value; return Object.fromEntries(Object.entries(value as Record<string, unknown>).filter(([key]) => !TRANSIENT.has(key)).sort(([left], [right]) => left.localeCompare(right)).map(([key, entry]) => [key, canonicalize(entry)])); }
export const canonicalShaV434 = (value: unknown): string => createHash("sha256").update(JSON.stringify(canonicalize(value))).digest("hex");
const overlap = (left: readonly string[], right: readonly string[]) => left.some((value) => right.includes(value));

export function validateKerrHighEnergyMeasuredAuthorityPackV434(pack: KerrMeasuredAdmissionPackV434): KerrMeasuredAdmissionValidationV434 {
  const errors: string[] = [];
  if (pack.version !== "v434-kerr-high-energy-measured-authority-pack-v1") errors.push("pack-version");
  if (Object.values(pack.identity).some((value) => !SHA.test(value))) errors.push("identity-sha");
  if (pack.channelLayout.analyzerAngleCount !== 4 || pack.channelLayout.detectorChannelCount !== 6 || pack.channelLayout.flattenedCount !== 24) errors.push("channel-layout");
  if (!SHA.test(pack.channelLayout.channelOrderSha256)) errors.push("channel-order-sha");
  if (!pack.responseCalibration.campaignIds.length || !pack.likelihoodFit.campaignIds.length || !pack.independentHoldout.campaignIds.length) errors.push("campaign-identity");
  if (overlap(pack.responseCalibration.campaignIds, pack.likelihoodFit.campaignIds) || overlap(pack.responseCalibration.campaignIds, pack.independentHoldout.campaignIds) || overlap(pack.likelihoodFit.campaignIds, pack.independentHoldout.campaignIds)) errors.push("campaign-overlap");
  if (overlap(pack.responseCalibration.rawEventFileSha256, pack.likelihoodFit.rawEventFileSha256) || overlap(pack.responseCalibration.rawEventFileSha256, pack.independentHoldout.rawEventFileSha256) || overlap(pack.likelihoodFit.rawEventFileSha256, pack.independentHoldout.rawEventFileSha256)) errors.push("raw-event-overlap");
  if (overlap(pack.likelihoodFit.sourceIds, pack.independentHoldout.sourceIds)) errors.push("holdout-source-overlap");
  if ([...pack.responseCalibration.rawEventFileSha256, ...pack.likelihoodFit.rawEventFileSha256, ...pack.independentHoldout.rawEventFileSha256].some((value) => !SHA.test(value))) errors.push("raw-event-sha");
  if (pack.independentHoldout.observedCountCellCount < 24 || pack.independentHoldout.replicateCount < 2 || !SHA.test(pack.independentHoldout.observedCountsArtifactSha256) || !SHA.test(pack.independentHoldout.processingParametersSha256)) errors.push("holdout-content");
  if (!pack.preregistration.frozenBeforeHoldoutOpened || !SHA.test(pack.preregistration.artifactSha256) || !["negative-binomial", "poisson-lognormal"].includes(pack.preregistration.likelihoodFamily)) errors.push("preregistration");
  if (!["independent-acquisition-design", "measured-cross-covariance"].includes(pack.crossBlockIndependence.method) || !SHA.test(pack.crossBlockIndependence.proofArtifactSha256) || !pack.crossBlockIndependence.responseAndLikelihoodRawArtifactsDisjoint) errors.push("cross-block-independence");
  if (pack.crossBlockIndependence.method === "measured-cross-covariance" && pack.crossBlockIndependence.replicateCount < 64) errors.push("cross-block-replicates");
  if (pack.thresholdPolicy.source !== "instrument-requirements-or-declared-uncertainty" || pack.thresholdPolicy.postHocThresholdTuning || !pack.thresholdPolicy.multipleComparisonControl || !pack.thresholdPolicy.effectSizeAndConfidenceInterval || !SHA.test(pack.thresholdPolicy.artifactSha256)) errors.push("threshold-policy");
  const valid = errors.length === 0;
  const measuredEligible = valid && pack.sourceKind === "measured-authority-candidate" && pack.measuredAttestation === "real-measured-response-likelihood-and-independent-holdout-not-synthetic-or-example";
  return Object.freeze({ valid, measuredEligible, scienceAdmissionGranted: false, errors: Object.freeze(errors), checks: Object.freeze({ identitySha: !errors.includes("identity-sha"), channelLayout: !errors.includes("channel-layout") && !errors.includes("channel-order-sha"), campaignDisjointness: !errors.includes("campaign-overlap"), rawEventDisjointness: !errors.includes("raw-event-overlap") && !errors.includes("raw-event-sha"), holdoutIndependence: !errors.includes("holdout-source-overlap") && !errors.includes("holdout-content"), preregistration: !errors.includes("preregistration"), crossBlockIndependence: !errors.includes("cross-block-independence") && !errors.includes("cross-block-replicates"), thresholdPolicy: !errors.includes("threshold-policy") }), boundary: "structural-validation-never-grants-science-admission-independent-measured-validation-and-review-required" });
}

export function parseKerrMeasuredAdmissionOracleV434(value: unknown): KerrMeasuredAdmissionOracleV434 { const source = value as Partial<KerrMeasuredAdmissionOracleV434> | null; if (!source || source.version !== "v434-kerr-high-energy-measured-admission-python-oracle-v1" || source.status !== "qualified-measured-authority-admission-firewall-fixture-only-no-measured-pack-science-admission-blocked" || source.sourceV433ArtifactSha256 !== KERR_V433_ARTIFACT_SHA256_V434 || source.mutationResults?.length !== 12 || source.mutationResults.some((result) => result.rejected !== true || !result.errors.length) || source.counts?.requiredGateCount !== 9 || source.counts.rejectedMutationCount !== 12 || source.counts.measuredPackCount !== 0 || source.counts.scienceResponseApplicationCount !== 0 || source.qualification?.validatorQualified !== true || source.qualification.mutationFirewallQualified !== true || source.qualification.measuredPackQualified !== false || source.qualification.scienceAdmissionQualified !== false || source.networkAttempted !== false || source.measuredImportAttempted !== false || source.denseShardExecuted !== false || !SHA.test(source.artifactSha256 ?? "")) throw new Error("v434-oracle-identity"); return value as KerrMeasuredAdmissionOracleV434; }

export function createKerrMeasuredAdmissionViewV434(oracleValue: unknown, contract: KerrMeasuredAdmissionContractV434): KerrMeasuredAdmissionViewV434 {
  const oracle = parseKerrMeasuredAdmissionOracleV434(oracleValue);
  if (contract.version !== "v434-kerr-high-energy-measured-admission-contract-v1" || contract.status !== "admission-firewall-ready-no-measured-pack" || contract.maximumPackBytes !== 67108864 || contract.requiredIdentityShaCount !== 5 || contract.requiredGates.length !== 9 || contract.admission.structuralValidationAloneInsufficient !== true || contract.admission.fixtureNeverAdmissible !== true || contract.admission.independentMeasuredValidationRequired !== true || contract.admission.independentReviewRequired !== true || contract.admission.automaticRetryForbidden !== true || contract.admission.currentStatus !== "blocked-no-measured-authority-pack" || contract.admission.scienceResponseApplicationCount !== 0 || contract.formalProductPointer !== "v263" || contract.denseCampaignStatus !== "incomplete-0-of-49") throw new Error("v434-contract");
  const report = validateKerrHighEnergyMeasuredAuthorityPackV434(oracle.fixture);
  const difference = canonicalShaV434(report) === canonicalShaV434(oracle.fixtureReport) ? 0 : Number.POSITIVE_INFINITY;
  if (!report.valid || report.measuredEligible || report.scienceAdmissionGranted || difference !== 0) throw new Error("v434-cross-language-fixture");
  return Object.freeze({ version: KERR_HIGH_ENERGY_MEASURED_ADMISSION_VERSION_V434, status: oracle.status, source: Object.freeze({ v433ArtifactSha256: KERR_V433_ARTIFACT_SHA256_V434, v433OracleSha256: KERR_V433_ORACLE_SHA256_V434, v433EvidenceSha256: KERR_V433_EVIDENCE_SHA256_V434, v433PointerSha256: KERR_V433_POINTER_SHA256_V434 }), gates: Object.freeze({ requiredGateCount: 9 as const, passedFixtureGateCount: 8 as const, independentReviewStatus: "not-run" as const, allRequiredBeforeAdmission: true as const, structuralValidationAloneInsufficient: true as const }), fixture: Object.freeze({ status: "validated-nonpublishable-validator-fixture" as const, structurallyValid: true as const, measuredEligible: false as const, scienceAdmissionGranted: false as const, mutationCount: 12 as const, rejectedMutationCount: 12 as const, maximumPythonTypeScriptDifference: difference }), counts: oracle.counts, products: Object.freeze({ json: "available-admission-summary-and-boundary" as const, oracle: "available-validator-conformance-fixture" as const, contract: "available-measured-admission-contract" as const, fixture: "available-nonpublishable-validator-fixture" as const, csv: "available-gate-status-table" as const, fits: "available-admission-status-no-detector-image" as const, png: "available-admission-firewall-diagram-not-instrument-performance" as const }), authorityBoundary: Object.freeze({ packSchemaAuthorityGranted: true as const, provenanceFirewallAuthorityGranted: true as const, disjointnessValidatorAuthorityGranted: true as const, preregistrationValidatorAuthorityGranted: true as const, crossBlockIndependenceValidatorAuthorityGranted: true as const, fixturePerformanceAuthorityGranted: false as const, measuredPackPresent: false as const, measuredResponseAuthorityGranted: false as const, measuredLikelihoodAuthorityGranted: false as const, independentMeasuredHoldoutQualified: false as const, independentReviewQualified: false as const, scienceAdmissionGranted: false as const, scienceResponseApplicationCount: 0 as const, detectorAuthorityGranted: false as const, denseAuthorityGranted: false as const, unavailableIsNotZero: true as const }), scienceBoundary: Object.freeze({ status: "blocked-no-measured-authority-pack" as const, admitted: false as const, missingRequirements: Object.freeze(["measured-response-authority", "measured-likelihood-authority", "independent-measured-holdout", "cross-block-independence-proof", "independent-review"] as const), scienceResponseApplicationCount: 0 as const }), denseCampaignStatus: "incomplete-0-of-49", browserQualification: "not-run", boundary: "measured-authority-admission-validator-qualified-no-measured-pack-response-likelihood-holdout-cross-block-proof-independent-review-science-admission-or-dense-authority" });
}

export function parseKerrMeasuredAdmissionArtifactV434(value: unknown): KerrMeasuredAdmissionArtifactV434 { const source = value as Partial<KerrMeasuredAdmissionArtifactV434> | null; if (!source || source.version !== KERR_HIGH_ENERGY_MEASURED_ADMISSION_ARTIFACT_VERSION_V434 || source.status !== "qualified-measured-authority-admission-firewall-fixture-only-no-measured-pack-science-admission-blocked" || source.view?.counts.measuredPackCount !== 0 || source.view.counts.scienceResponseApplicationCount !== 0 || source.view.authorityBoundary.measuredPackPresent !== false || source.view.authorityBoundary.scienceAdmissionGranted !== false || source.view.scienceBoundary.admitted !== false || source.deterministicReplay !== true || source.networkAttempted !== false || source.measuredImportAttempted !== false || source.measuredPackPresent !== false || source.denseShardExecuted !== false || source.scienceResponseApplicationCount !== 0 || !SHA.test(source.pythonOracleArtifactSha256 ?? "") || !SHA.test(source.artifactSha256 ?? "")) throw new Error("v434-artifact-identity"); return value as KerrMeasuredAdmissionArtifactV434; }
export function createKerrMeasuredAdmissionSummaryV434(value: unknown): KerrMeasuredAdmissionSummaryV434 { const artifact = parseKerrMeasuredAdmissionArtifactV434(value), view = artifact.view; return Object.freeze({ version: KERR_HIGH_ENERGY_MEASURED_ADMISSION_SUMMARY_VERSION_V434, status: view.status, artifactSha256: artifact.artifactSha256, gates: view.gates, fixture: view.fixture, counts: view.counts, products: view.products, authorityBoundary: view.authorityBoundary, scienceBoundary: view.scienceBoundary, denseCampaignStatus: view.denseCampaignStatus, fullArtifactAvailable: true, boundary: "bounded-admission-gates-counts-and-missing-requirements-no-pack-identities-or-raw-artifacts-in-react-state" }); }
export function parseKerrMeasuredAdmissionApiV434(value: unknown): KerrMeasuredAdmissionApiV434 { const source = value as Partial<KerrMeasuredAdmissionApiV434> | null; if (!source || source.version !== KERR_HIGH_ENERGY_MEASURED_ADMISSION_API_VERSION_V434) throw new Error("v434-api-version"); if (source.available === true && source.reason === "ready" && source.summary) { if (source.summary.version !== KERR_HIGH_ENERGY_MEASURED_ADMISSION_SUMMARY_VERSION_V434 || !SHA.test(source.summary.artifactSha256) || source.summary.counts.measuredPackCount !== 0 || source.summary.counts.scienceResponseApplicationCount !== 0 || source.summary.authorityBoundary.scienceAdmissionGranted !== false || source.summary.scienceBoundary.admitted !== false || Object.hasOwn(source.summary, "identity") || Object.hasOwn(source.summary, "rawEventFileSha256")) throw new Error("v434-api-summary"); return source as KerrMeasuredAdmissionApiV434; } if (source.available === false && source.summary === null && ["lite-boundary", "local-shadow-only", "evidence-corrupt", "request-failed"].includes(source.reason ?? "")) return source as KerrMeasuredAdmissionApiV434; throw new Error("v434-api-identity"); }
