export const KERR_CALIBRATION_AUTHORITY_GAP_VERSION_V544 = "v544-kerr-calibration-authority-gap-artifact-v1" as const;
export const KERR_CALIBRATION_AUTHORITY_GAP_API_VERSION_V544 = "v544-kerr-calibration-authority-gap-api-v1" as const;
export const KERR_CALIBRATION_AUTHORITY_GAP_HUD_PROFILE_ID_V544 = "science-cinematic-v9r3-v544" as const;
const SHA = /^[0-9a-f]{64}$/;
const TRANSIENT = new Set(["generatedAt", "artifactSha256", "payloadSha256", "evidenceSha256", "pointerSha256", "stageChainSha256", "columnSha256", "receiptSha256", "resultSha256", "environmentSha256", "preflightSha256", "matrixSha256", "isolatedReceiptSha256", "executionMatrixSha256"]);
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const canonicalize = (value: unknown): unknown => Array.isArray(value) ? value.map(canonicalize) : !isRecord(value) ? value : Object.fromEntries(Object.entries(value).filter(([key]) => !TRANSIENT.has(key)).sort(([left], [right]) => left.localeCompare(right)).map(([key, entry]) => [key, canonicalize(entry)]));
export const canonicalKerrCalibrationAuthorityGapV544 = (value: unknown) => JSON.stringify(canonicalize(value));

export type KerrCalibrationAuthorityRequirementIdV544 = "identity" | "plate-scale" | "distortion" | "psf" | "pixel-response" | "provenance" | "collecting-area" | "exposure-record" | "measured-spectral-response" | "observed-detector-frame";
export type KerrCalibrationAuthorityRequirementV544 = Readonly<{ id: KerrCalibrationAuthorityRequirementIdV544; tier: "six-file-intake" | "supplemental-science-authority"; sourceContract: string; covers: readonly string[]; currentStatus: "missing"; ready: false; syntheticFallbackAllowed: false; rowSha256: string }>;
export type KerrCalibrationAuthorityGapArtifactV544 = Readonly<{
  version: typeof KERR_CALIBRATION_AUTHORITY_GAP_VERSION_V544;
  status: "calibration-topology-qualified-six-file-intake-insufficient-science-raster-blocked";
  source: Readonly<Record<"v361PlanSha256" | "v364PackSha256" | "v458ArtifactSha256" | "v503ArtifactSha256" | "v504ArtifactSha256" | "v511ArtifactSha256" | "v536ArtifactSha256" | "v543EvidenceSha256" | "v543PointerSha256" | "v314StateSha256", string>>;
  dimensionalContract: Readonly<{ sourceObservable: string; electronExpectationEquation: string; responseAppliedExactlyOnce: true; collectingAreaGeometricOnly: true; gainAppliedAfterElectronExpectation: true; psfAndDistortionAppliedBeforeRasterQualification: true; missingQuantityPolicy: "null-not-zero" }>;
  requirements: readonly KerrCalibrationAuthorityRequirementV544[];
  transitionAudit: readonly Readonly<{ id: "measured-intake" | "radiance-to-electrons" | "electrons-to-adu" | "adu-to-science-raster"; status: "blocked"; missingAuthorityIds: readonly KerrCalibrationAuthorityRequirementIdV544[]; sixFileIntakeAloneSufficient: false | true; authorityGranted: false }>[];
  sufficiency: Readonly<{ sixFileIntakeRequired: true; sixFileIntakeSufficientForIndependentValidation: true; sixFileIntakeSufficientForRadianceToElectrons: false; sixFileIntakeSufficientForElectronToAdu: false; sixFileIntakeSufficientForScienceRaster: false; supplementalAuthorityCount: 4; observedFrameRequired: true; denseAggregateCannotSubstituteCalibration: true }>;
  counts: Readonly<{ authorityRequirementCount: 10; intakeRequirementCount: 6; supplementalRequirementCount: 4; readyRequirementCount: 0; missingRequirementCount: 10; v458ReadyFileCount: 0; v458RequiredFileCount: 6; measuredCalibrationFiles: 0; sciencePixelRows: 0; fitsImageCount: 0; pngImageCount: 0 }>;
  qualification: Readonly<{ calibrationTopologyQualified: true; schemaReconciliationQualified: true; doubleCountingFirewallQualified: true; syntheticAuthorityFirewallQualified: true; measuredDetectorAuthorityGranted: false; electronExpectationQualified: false; scienceRasterQualified: false; crossEnvironmentScienceQualified: false }>;
  boundary: Readonly<{ missingFilesGenerated: false; measuredValuesInvented: false; pixelValuesInvented: false; sciencePayloadMutationAllowed: false; cinematicScienceWritebackAllowed: false; denseCampaignStatus: "incomplete-0-of-49"; browserQualification: "not-run"; formalProductPointer: "v263"; formalDefaultKernel: "legacy-eih-1pn" }>;
  export: Readonly<{ matrixPath: string; matrixFileSha256: string; rowCount: 10 }>;
  sourceManifest: readonly Readonly<{ path: string; sha256: string }>[]; sourceSha256: string; artifactSha256: string;
}>;
export type KerrCalibrationAuthorityGapApiV544 = Readonly<{ version: typeof KERR_CALIBRATION_AUTHORITY_GAP_API_VERSION_V544; available: boolean; reason: "ready" | "lite-boundary" | "local-shadow-only" | "evidence-corrupt"; summary: KerrCalibrationAuthorityGapArtifactV544 | null }>;

type SourceV544 = Readonly<{
  v361: Readonly<{ status: string; counts: Readonly<{ acquisitionTaskCount: number }>; measuredPerformanceClaimed: boolean; artifactSha256: string }>;
  v364: Readonly<{ status: string; counts: Readonly<{ measuredDataRowCount: number }>; files: readonly Readonly<{ admissibleAsMeasured: boolean }>[]; artifactSha256: string }>;
  v458: Readonly<{ contract: Readonly<{ requiredFileCount: number }>; inspect: Readonly<{ readyFileCount: number }>; productionAdmission: Readonly<{ measuredDetectorAuthorityGranted: boolean }>; artifactSha256: string }>;
  v503: Readonly<{ contract: Readonly<{ requiredFileCount: number }>; decision: Readonly<{ readyFileCount: number; admitted: boolean }>; artifactSha256: string }>;
  v504: Readonly<{ contract: Readonly<{ whitelistFileCount: number }>; observation: Readonly<{ readyFileCount: number }>; decision: Readonly<{ scienceRasterAllowed: boolean }>; artifactSha256: string }>;
  v511: Readonly<{ counts: Readonly<{ requiredMeasuredCalibrationFiles: number; measuredCalibrationFiles: number }>; qualification: Readonly<{ scienceRasterQualified: boolean }>; dimensionalContract: Readonly<{ responseAppliedExactlyOnce: boolean }>; artifactSha256: string }>;
  v536: Readonly<{ counts: Readonly<{ pixelSampleCount: number; rasterPixelCount: number }>; qualification: Readonly<{ scienceRasterQualified: boolean }>; artifactSha256: string }>;
  v543EvidenceSha256: string; v543PointerSha256: string; v314StateSha256: string;
}>;
const role = (id: KerrCalibrationAuthorityRequirementIdV544, tier: KerrCalibrationAuthorityRequirementV544["tier"], sourceContract: string, covers: readonly string[]): Omit<KerrCalibrationAuthorityRequirementV544, "rowSha256"> => Object.freeze({ id, tier, sourceContract, covers: Object.freeze([...covers]), currentStatus: "missing", ready: false, syntheticFallbackAllowed: false });
const BASE_REQUIREMENTS = Object.freeze([
  role("identity", "six-file-intake", "v458:identity.json", ["instrument-detector-campaign-identity"]),
  role("plate-scale", "six-file-intake", "v458:plate-scale.csv", ["pixel-solid-angle-after-independent-validation"]),
  role("distortion", "six-file-intake", "v458:distortion.json", ["continuous-coordinate-to-detector-frame"]),
  role("psf", "six-file-intake", "v458:psf.json", ["pre-raster-point-spread-function"]),
  role("pixel-response", "six-file-intake", "v458:pixel-response.json", ["gain", "read-noise", "dark-current", "full-well", "adc-range"]),
  role("provenance", "six-file-intake", "v458:provenance.json", ["five-input-sha-linkage", "source-license-snapshot", "operator-attestation"]),
  role("collecting-area", "supplemental-science-authority", "v511:radiance-to-electrons", ["geometric-collecting-area"]),
  role("exposure-record", "supplemental-science-authority", "v511:radiance-to-electrons", ["exposure-duration", "observation-identity"]),
  role("measured-spectral-response", "supplemental-science-authority", "v511:radiance-to-electrons", ["bandpass-throughput-versus-wavelength"]),
  role("observed-detector-frame", "supplemental-science-authority", "v511:adu-to-science-raster", ["observed-adu-or-electron-frame", "mask-and-saturation-state"]),
] as const);
export function deriveKerrCalibrationAuthorityGapV544(source: SourceV544, rowSha: (value: unknown) => string) {
  if (source.v361.status !== "qualified-synthetic-calibration-acquisition-design-measured-input-still-blocked" || source.v361.counts.acquisitionTaskCount !== 9 || source.v361.measuredPerformanceClaimed !== false) throw new Error("v544-v361-boundary");
  if (source.v364.status !== "qualified-empty-acquisition-pack-and-validator-measured-data-unavailable" || source.v364.counts.measuredDataRowCount !== 0 || source.v364.files.some((file) => file.admissibleAsMeasured !== false)) throw new Error("v544-v364-boundary");
  if (source.v458.contract.requiredFileCount !== 6 || source.v458.inspect.readyFileCount !== 0 || source.v458.productionAdmission.measuredDetectorAuthorityGranted !== false) throw new Error("v544-v458-boundary");
  if (source.v503.contract.requiredFileCount !== 6 || source.v503.decision.readyFileCount !== 0 || source.v503.decision.admitted !== false) throw new Error("v544-v503-boundary");
  if (source.v504.contract.whitelistFileCount !== 6 || source.v504.observation.readyFileCount !== 0 || source.v504.decision.scienceRasterAllowed !== false) throw new Error("v544-v504-boundary");
  if (source.v511.counts.requiredMeasuredCalibrationFiles !== 6 || source.v511.counts.measuredCalibrationFiles !== 0 || source.v511.qualification.scienceRasterQualified !== false || source.v511.dimensionalContract.responseAppliedExactlyOnce !== true) throw new Error("v544-v511-boundary");
  if (source.v536.counts.pixelSampleCount !== 0 || source.v536.counts.rasterPixelCount !== 0 || source.v536.qualification.scienceRasterQualified !== false) throw new Error("v544-v536-boundary");
  const requirements = BASE_REQUIREMENTS.map((entry) => Object.freeze({ ...entry, rowSha256: rowSha(entry) }));
  const transitionAudit = Object.freeze([
    Object.freeze({ id: "measured-intake" as const, status: "blocked" as const, missingAuthorityIds: Object.freeze(requirements.slice(0, 6).map((entry) => entry.id)), sixFileIntakeAloneSufficient: true as const, authorityGranted: false as const }),
    Object.freeze({ id: "radiance-to-electrons" as const, status: "blocked" as const, missingAuthorityIds: Object.freeze(["plate-scale", "collecting-area", "exposure-record", "measured-spectral-response"] as KerrCalibrationAuthorityRequirementIdV544[]), sixFileIntakeAloneSufficient: false as const, authorityGranted: false as const }),
    Object.freeze({ id: "electrons-to-adu" as const, status: "blocked" as const, missingAuthorityIds: Object.freeze(["pixel-response"] as KerrCalibrationAuthorityRequirementIdV544[]), sixFileIntakeAloneSufficient: false as const, authorityGranted: false as const }),
    Object.freeze({ id: "adu-to-science-raster" as const, status: "blocked" as const, missingAuthorityIds: Object.freeze(["distortion", "psf", "pixel-response", "observed-detector-frame"] as KerrCalibrationAuthorityRequirementIdV544[]), sixFileIntakeAloneSufficient: false as const, authorityGranted: false as const }),
  ]);
  return Object.freeze({ requirements: Object.freeze(requirements), transitionAudit });
}
export function parseKerrCalibrationAuthorityGapArtifactV544(value: unknown): KerrCalibrationAuthorityGapArtifactV544 { if (!isRecord(value) || value.version !== KERR_CALIBRATION_AUTHORITY_GAP_VERSION_V544 || value.status !== "calibration-topology-qualified-six-file-intake-insufficient-science-raster-blocked" || !SHA.test(String(value.artifactSha256)) || !SHA.test(String(value.sourceSha256))) throw new Error("v544-artifact-boundary"); const artifact = value as unknown as KerrCalibrationAuthorityGapArtifactV544; if (!Array.isArray(artifact.requirements) || artifact.requirements.length !== 10 || artifact.requirements.filter((entry) => entry.tier === "six-file-intake").length !== 6 || artifact.requirements.filter((entry) => entry.tier === "supplemental-science-authority").length !== 4 || artifact.requirements.some((entry) => entry.ready || entry.syntheticFallbackAllowed || !SHA.test(entry.rowSha256))) throw new Error("v544-requirements"); if (artifact.sufficiency.sixFileIntakeSufficientForScienceRaster !== false || artifact.counts.readyRequirementCount !== 0 || artifact.qualification.scienceRasterQualified !== false || artifact.boundary.formalProductPointer !== "v263" || artifact.boundary.formalDefaultKernel !== "legacy-eih-1pn" || artifact.boundary.denseCampaignStatus !== "incomplete-0-of-49") throw new Error("v544-boundary"); return artifact; }
export function parseKerrCalibrationAuthorityGapApiV544(value: unknown): KerrCalibrationAuthorityGapApiV544 { if (!isRecord(value) || value.version !== KERR_CALIBRATION_AUTHORITY_GAP_API_VERSION_V544 || typeof value.available !== "boolean" || !["ready", "lite-boundary", "local-shadow-only", "evidence-corrupt"].includes(String(value.reason))) throw new Error("v544-api-boundary"); if (value.available) parseKerrCalibrationAuthorityGapArtifactV544(value.summary); else if (value.summary !== null) throw new Error("v544-api-unavailable-summary"); return value as unknown as KerrCalibrationAuthorityGapApiV544; }
export type KerrCalibrationAuthorityGapHudModeV544 = "science" | "cinematic";
const scienceProfile = Object.freeze({ id: KERR_CALIBRATION_AUTHORITY_GAP_HUD_PROFILE_ID_V544, mode: "science" as const, panel: "#030d11", panelRaised: "#071920", ink: "#e9fcff", muted: "#789aa3", qualified: "#77efbc", warning: "#f2c373", unavailable: "#ff8dac", scienceBoundary: Object.freeze({ linearDisplay: true, bloomIntensity: 0 as const, colorGradeIntensity: 0 as const, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }), cinematicSeed: null });
const cinematicProfile = Object.freeze({ ...scienceProfile, mode: "cinematic" as const, panel: "#130a07", panelRaised: "#24140e", ink: "#fff5e5", muted: "#b89a80", qualified: "#8eebc2", warning: "#f5c071", unavailable: "#ff96b0", scienceBoundary: Object.freeze({ linearDisplay: false, bloomIntensity: 0.038, colorGradeIntensity: 0.026, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }), cinematicSeed: "orbit-atlas-v544-calibration-gap-seed-01" });
export function resolveKerrCalibrationAuthorityGapHudProfileV544(mode: KerrCalibrationAuthorityGapHudModeV544) { return mode === "science" ? scienceProfile : cinematicProfile; }
export function createKerrCalibrationAuthorityGapHudEncodingV544(artifact: KerrCalibrationAuthorityGapArtifactV544, mode: KerrCalibrationAuthorityGapHudModeV544) { return Object.freeze({ version: "v544-calibration-authority-gap-hud-v1" as const, profileId: KERR_CALIBRATION_AUTHORITY_GAP_HUD_PROFILE_ID_V544, mode, artifactKey: artifact.artifactSha256, requirements: artifact.requirements, transitionAudit: artifact.transitionAudit, intakeRequirementCount: 6 as const, supplementalRequirementCount: 4 as const, readyRequirementCount: 0 as const, scienceRasterQualified: false as const, imageHduCount: 0 as const, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }); }
export function compareKerrCalibrationAuthorityGapHudEncodingsV544(science: ReturnType<typeof createKerrCalibrationAuthorityGapHudEncodingV544>, cinematic: ReturnType<typeof createKerrCalibrationAuthorityGapHudEncodingV544>) { if (science.mode !== "science" || cinematic.mode !== "cinematic" || science.artifactKey !== cinematic.artifactKey || JSON.stringify(science.requirements) !== JSON.stringify(cinematic.requirements) || JSON.stringify(science.transitionAudit) !== JSON.stringify(cinematic.transitionAudit)) throw new Error("v544-hud-boundary"); return Object.freeze({ requirementsStable: true as const, transitionAuditStable: true as const, scienceQualificationStable: true as const, scientificFieldMutation: false as const }); }
