"use client";
import { acquireAtlasResource } from "./atlasResourceLifecycle";
import { parseKerrSupplementalCalibrationIntakeApiV545, type KerrSupplementalCalibrationIntakeArtifactV545 } from "./kerrSupplementalCalibrationIntakeV545";
type SnapshotV545 = Readonly<{ status: "idle" | "loading" | "ready" | "unavailable"; reason: string | null; requestCount: 0 | 1; responseBytes: number; summary: KerrSupplementalCalibrationIntakeArtifactV545 | null }>;
const INITIAL: SnapshotV545 = Object.freeze({ status: "idle", reason: null, requestCount: 0, responseBytes: 0, summary: null }), listeners = new Set<() => void>(); let snapshot = INITIAL; let requestPromise: Promise<KerrSupplementalCalibrationIntakeArtifactV545> | null = null; const publish = (next: SnapshotV545) => { snapshot = Object.freeze(next); listeners.forEach((listener) => listener()); };
export function loadKerrSupplementalCalibrationIntakeSummaryV545(): Promise<KerrSupplementalCalibrationIntakeArtifactV545> { if (requestPromise) return requestPromise; publish({ status: "loading", reason: null, requestCount: 1, responseBytes: 0, summary: null }); requestPromise = fetch("/api/atlas/relativity-evidence/v545/supplemental-calibration-intake", { cache: "no-store" }).then(async (response) => { const body = await response.text(), responseBytes = new TextEncoder().encode(body).byteLength; if (responseBytes > 128 * 1024) throw new Error("response-too-large"); const api = parseKerrSupplementalCalibrationIntakeApiV545(JSON.parse(body)); if (!response.ok || !api.available || !api.summary) throw new Error(`v545-supplemental-intake-${api.reason}`); publish({ status: "ready", reason: null, requestCount: 1, responseBytes, summary: api.summary }); return api.summary; }).catch((error: unknown) => { publish({ status: "unavailable", reason: error instanceof Error ? error.message : "request-failed", requestCount: 1, responseBytes: snapshot.responseBytes, summary: null }); throw error; }); return requestPromise; }
export const getKerrSupplementalCalibrationIntakeSnapshotV545 = () => snapshot;
export function subscribeKerrSupplementalCalibrationIntakeV545(listener: () => void): () => void { listeners.add(listener); const release = acquireAtlasResource("subscription", "relativity-lab", "v545-supplemental-calibration-intake", { owner: "v545-supplemental-calibration-intake", estimatedBytes: 0 }); let done = false; return () => { if (done) return; done = true; listeners.delete(listener); release(); }; }
export function getKerrSupplementalCalibrationIntakeTelemetryV545() { return Object.freeze({ listenerCount: listeners.size, requestCount: snapshot.requestCount, status: snapshot.status }); }
export function resetKerrSupplementalCalibrationIntakeClientForTestsV545(): void { if (listeners.size) throw new Error("v545-listener-leak"); snapshot = INITIAL; requestPromise = null; }
