"use client";
import { acquireAtlasResource } from "./atlasResourceLifecycle";
import { parseKerrSparseCoordinateProductsApiV557, type KerrSparseCoordinateProductsArtifactV557 } from "./kerrSparseCoordinateProductsV557";
type SnapshotV557 = Readonly<{ status: "idle" | "loading" | "ready" | "unavailable"; reason: string | null; requestCount: 0 | 1; responseBytes: number; summary: KerrSparseCoordinateProductsArtifactV557 | null }>;
const INITIAL: SnapshotV557 = Object.freeze({ status: "idle", reason: null, requestCount: 0, responseBytes: 0, summary: null }); const listeners = new Set<() => void>(); let snapshot = INITIAL; let requestPromise: Promise<KerrSparseCoordinateProductsArtifactV557> | null = null; const publish = (next: SnapshotV557) => { snapshot = Object.freeze(next); listeners.forEach((listener) => listener()); };
export function loadKerrSparseCoordinateProductsSummaryV557(): Promise<KerrSparseCoordinateProductsArtifactV557> { if (requestPromise) return requestPromise; publish({ status: "loading", reason: null, requestCount: 1, responseBytes: 0, summary: null }); requestPromise = fetch("/api/atlas/relativity-evidence/v557/sparse-coordinate-products", { cache: "no-store" }).then(async (response) => { const body = await response.text(), responseBytes = new TextEncoder().encode(body).byteLength; if (responseBytes > 128 * 1024) throw new Error("response-too-large"); const api = parseKerrSparseCoordinateProductsApiV557(JSON.parse(body)); if (!response.ok || !api.available || !api.summary) throw new Error(`v557-coordinate-${api.reason}`); publish({ status: "ready", reason: null, requestCount: 1, responseBytes, summary: api.summary }); return api.summary; }).catch((error: unknown) => { publish({ status: "unavailable", reason: error instanceof Error ? error.message : "request-failed", requestCount: 1, responseBytes: snapshot.responseBytes, summary: null }); throw error; }); return requestPromise; }
export const getKerrSparseCoordinateProductsSnapshotV557 = () => snapshot;
export function subscribeKerrSparseCoordinateProductsV557(listener: () => void): () => void { listeners.add(listener); const release = acquireAtlasResource("subscription", "relativity-lab", "v557-coordinate-products", { owner: "v557-coordinate-products", estimatedBytes: 0 }); let done = false; return () => { if (done) return; done = true; listeners.delete(listener); release(); }; }
export const getKerrSparseCoordinateProductsTelemetryV557 = () => Object.freeze({ listenerCount: listeners.size, requestCount: snapshot.requestCount, status: snapshot.status });
export function resetKerrSparseCoordinateProductsClientForTestsV557(): void { if (listeners.size) throw new Error("v557-coordinate-listener-leak"); snapshot = INITIAL; requestPromise = null; }
