export const KERR_REDSHIFT_CONTRAST_LATTICE_VERSION_V489 = "v489-kerr-redshift-contrast-lattice-artifact-v1" as const;
export const KERR_REDSHIFT_CONTRAST_LATTICE_API_VERSION_V489 = "v489-kerr-redshift-contrast-lattice-api-v1" as const;
export interface KerrRedshiftContrastNodeV489 { rayId: string; redshiftFactor: number; shiftClass: "blueshift" | "redshift"; logShift: number; logShiftUncertaintyUpperBound: number; uncertaintyCombinationPolicy: "linear-sum-correlation-between-rays-unknown"; sourceRayIdentitySha256: string; }
export interface KerrRedshiftContrastCellV489 { rowIndex: number; columnIndex: number; fromRayId: string; toRayId: string; factorRatio: number; logContrast: number; logContrastUncertaintyUpperBound: number; uncertaintyCombinationPolicy: "exact-self-identity" | "linear-sum-correlation-between-rays-unknown"; }
export interface KerrRedshiftContrastLatticeArtifactV489 {
  version: typeof KERR_REDSHIFT_CONTRAST_LATTICE_VERSION_V489; status: "dimensionless-redshift-contrast-qualified-physical-observables-blocked-browser-pending";
  contract: Readonly<{ rayCount: 4; landmarkCount: 20; directedContrastCount: 16; independentPairCount: 6; landmarkRatioAuditCount: 30; cycleAuditCount: 24; coordinateSystem: "dimensionless-log-redshift-contrast"; uncertaintyCombinationPolicy: "linear-sum-correlation-between-rays-unknown"; rssAllowed: false; statisticalOneSigmaAuthorityGranted: false; diagnosticVectorPlotOnly: true; maximumResponseBytes: number; localShadowOnly: true; formalProductPointer: "v263"; }>;
  nodes: readonly KerrRedshiftContrastNodeV489[]; centeredNodes: readonly Readonly<{ rayId: string; centeredLogShift: number; centeredFactor: number }>[]; matrix: readonly KerrRedshiftContrastCellV489[];
  pairs: readonly Readonly<{ pairId: string; fromRayId: string; toRayId: string; factorRatio: number; logContrast: number; logContrastUncertaintyUpperBound: number; uncertaintyCombinationPolicy: string; landmarkAudits: readonly unknown[] }>[];
  payloadSha256: string; vectorDiagnostic: Readonly<{ path: string; mediaType: "image/svg+xml; charset=utf-8"; width: 1440; height: 900; fileSha256: string; deterministic: true; linearDisplay: true; bloomIntensity: 0; colorGradeIntensity: 0; scientificFieldMutationAllowed: false }>;
  audit: Readonly<{ maximumAntisymmetryResidual: number; maximumCycleClosureResidual: number; maximumLandmarkLogContrastResidual: number; centeredSumResidual: number; directedContrastCount: 16; independentPairCount: 6; landmarkRatioAuditCount: 30; cycleAuditCount: 24; matrixElementCountCopied: 0; detectorObservableRows: 0; observedIntensityRows: 0; sciencePixelRows: 0; fitsProducts: 0; pngProducts: 0 }>;
  boundary: Readonly<{ dimensionlessRedshiftContrastAuthorityGranted: true; crossRayStatisticalCovarianceAuthorityGranted: false; absoluteFrequencyAuthorityGranted: false; physicalBandpassAuthorityGranted: false; observedIntensityAuthorityGranted: false; statisticalLikelihoodAuthorityGranted: false; scienceRasterAuthorityGranted: false; denseCampaignStatus: "incomplete-0-of-49"; browserQualification: "not-run" }>;
  sourceSha256: string; artifactSha256: string; formalProductPointer: "v263"; formalDefaultKernel: "legacy-eih-1pn";
}
export type KerrRedshiftContrastLatticeSummaryV489 = Readonly<{ version: typeof KERR_REDSHIFT_CONTRAST_LATTICE_VERSION_V489; status: KerrRedshiftContrastLatticeArtifactV489["status"]; nodes: KerrRedshiftContrastLatticeArtifactV489["nodes"]; centeredNodes: KerrRedshiftContrastLatticeArtifactV489["centeredNodes"]; matrix: KerrRedshiftContrastLatticeArtifactV489["matrix"]; payloadSha256: string; artifactSha256: string; svgSha256: string; svgHref: string; audit: KerrRedshiftContrastLatticeArtifactV489["audit"]; boundary: KerrRedshiftContrastLatticeArtifactV489["boundary"] }>;
export type KerrRedshiftContrastLatticeApiV489 = Readonly<{ version: typeof KERR_REDSHIFT_CONTRAST_LATTICE_API_VERSION_V489; available: boolean; reason: string; summary: KerrRedshiftContrastLatticeSummaryV489 | null }>;
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const isSha = (value: unknown): value is string => typeof value === "string" && /^[a-f0-9]{64}$/.test(value);
const finite = (value: unknown): value is number => typeof value === "number" && Number.isFinite(value);
export function canonicalKerrRedshiftContrastLatticeV489(value: unknown): string { const transient = new Set(["generatedAt", "artifactSha256", "payloadSha256", "stageChainSha256", "evidenceSha256", "pointerSha256"]); const normalize = (entry: unknown): unknown => Array.isArray(entry) ? entry.map(normalize) : !isRecord(entry) ? entry : Object.fromEntries(Object.entries(entry).filter(([key]) => !transient.has(key)).sort(([left], [right]) => left < right ? -1 : left > right ? 1 : 0).map(([key, nested]) => [key, normalize(nested)])); return JSON.stringify(normalize(value)); }
export function parseKerrRedshiftContrastLatticeArtifactV489(value: unknown): KerrRedshiftContrastLatticeArtifactV489 {
  if (!isRecord(value) || value.version !== KERR_REDSHIFT_CONTRAST_LATTICE_VERSION_V489 || value.status !== "dimensionless-redshift-contrast-qualified-physical-observables-blocked-browser-pending" || !isRecord(value.contract) || value.contract.rayCount !== 4 || value.contract.directedContrastCount !== 16 || value.contract.independentPairCount !== 6 || value.contract.landmarkRatioAuditCount !== 30 || value.contract.cycleAuditCount !== 24 || value.contract.rssAllowed !== false || value.contract.statisticalOneSigmaAuthorityGranted !== false || !Array.isArray(value.nodes) || value.nodes.length !== 4 || !Array.isArray(value.centeredNodes) || value.centeredNodes.length !== 4 || !Array.isArray(value.matrix) || value.matrix.length !== 16 || !Array.isArray(value.pairs) || value.pairs.length !== 6 || !isSha(value.payloadSha256) || !isSha(value.artifactSha256) || !isRecord(value.vectorDiagnostic) || !isSha(value.vectorDiagnostic.fileSha256) || !isRecord(value.audit) || value.audit.landmarkRatioAuditCount !== 30 || value.audit.cycleAuditCount !== 24 || !finite(value.audit.maximumCycleClosureResidual) || value.audit.sciencePixelRows !== 0 || !isRecord(value.boundary) || value.boundary.dimensionlessRedshiftContrastAuthorityGranted !== true || value.boundary.statisticalLikelihoodAuthorityGranted !== false || value.boundary.scienceRasterAuthorityGranted !== false || value.boundary.denseCampaignStatus !== "incomplete-0-of-49" || value.boundary.browserQualification !== "not-run" || value.formalProductPointer !== "v263" || value.formalDefaultKernel !== "legacy-eih-1pn") throw new Error("v489-lattice-boundary");
  return value as unknown as KerrRedshiftContrastLatticeArtifactV489;
}
export function createKerrRedshiftContrastLatticeSummaryV489(value: unknown): KerrRedshiftContrastLatticeSummaryV489 { const artifact = parseKerrRedshiftContrastLatticeArtifactV489(value); return Object.freeze({ version: artifact.version, status: artifact.status, nodes: artifact.nodes, centeredNodes: artifact.centeredNodes, matrix: artifact.matrix, payloadSha256: artifact.payloadSha256, artifactSha256: artifact.artifactSha256, svgSha256: artifact.vectorDiagnostic.fileSha256, svgHref: "/api/atlas/relativity-evidence/v489/redshift-contrast-lattice?format=svg", audit: artifact.audit, boundary: artifact.boundary }); }
export function parseKerrRedshiftContrastLatticeSummaryV489(value: unknown): KerrRedshiftContrastLatticeSummaryV489 { if (!isRecord(value) || value.version !== KERR_REDSHIFT_CONTRAST_LATTICE_VERSION_V489 || !Array.isArray(value.nodes) || value.nodes.length !== 4 || !Array.isArray(value.centeredNodes) || value.centeredNodes.length !== 4 || !Array.isArray(value.matrix) || value.matrix.length !== 16 || !isSha(value.payloadSha256) || !isSha(value.artifactSha256) || !isSha(value.svgSha256) || value.svgHref !== "/api/atlas/relativity-evidence/v489/redshift-contrast-lattice?format=svg" || !isRecord(value.audit) || value.audit.sciencePixelRows !== 0 || !isRecord(value.boundary) || value.boundary.scienceRasterAuthorityGranted !== false) throw new Error("v489-summary-boundary"); return value as unknown as KerrRedshiftContrastLatticeSummaryV489; }
export function parseKerrRedshiftContrastLatticeApiV489(value: unknown): KerrRedshiftContrastLatticeApiV489 { if (!isRecord(value) || value.version !== KERR_REDSHIFT_CONTRAST_LATTICE_API_VERSION_V489 || typeof value.available !== "boolean" || typeof value.reason !== "string") throw new Error("v489-api-shape"); if (value.available) parseKerrRedshiftContrastLatticeSummaryV489(value.summary); else if (value.summary !== null) throw new Error("v489-api-unavailable-summary"); return value as unknown as KerrRedshiftContrastLatticeApiV489; }
