"use client";

import { acquireAtlasResource } from "./atlasResourceLifecycle";
import { parseKerrReplayIsolatedPreflightApiV543, type KerrReplayIsolatedPreflightArtifactV543 } from "./kerrReplayIsolatedPreflightV543";
type SnapshotV543 = Readonly<{ status: "idle" | "loading" | "ready" | "unavailable"; reason: string | null; requestCount: 0 | 1; responseBytes: number; summary: KerrReplayIsolatedPreflightArtifactV543 | null }>;
const INITIAL: SnapshotV543 = Object.freeze({ status: "idle", reason: null, requestCount: 0, responseBytes: 0, summary: null }), listeners = new Set<() => void>(); let snapshot = INITIAL; let requestPromise: Promise<KerrReplayIsolatedPreflightArtifactV543> | null = null;
const publish = (next: SnapshotV543) => { snapshot = Object.freeze(next); listeners.forEach((listener) => listener()); };
export function loadKerrReplayIsolatedPreflightSummaryV543(): Promise<KerrReplayIsolatedPreflightArtifactV543> { if (requestPromise) return requestPromise; publish({ status: "loading", reason: null, requestCount: 1, responseBytes: 0, summary: null }); requestPromise = fetch("/api/atlas/relativity-evidence/v543/isolated-preflight", { cache: "no-store" }).then(async (response) => { const body = await response.text(), responseBytes = new TextEncoder().encode(body).byteLength; if (responseBytes > 128 * 1024) throw new Error("response-too-large"); const api = parseKerrReplayIsolatedPreflightApiV543(JSON.parse(body)); if (!response.ok || !api.available || !api.summary) throw new Error(`v543-isolated-preflight-${api.reason}`); publish({ status: "ready", reason: null, requestCount: 1, responseBytes, summary: api.summary }); return api.summary; }).catch((error: unknown) => { publish({ status: "unavailable", reason: error instanceof Error ? error.message : "request-failed", requestCount: 1, responseBytes: snapshot.responseBytes, summary: null }); throw error; }); return requestPromise; }
export const getKerrReplayIsolatedPreflightSnapshotV543 = () => snapshot;
export function subscribeKerrReplayIsolatedPreflightV543(listener: () => void): () => void { listeners.add(listener); const release = acquireAtlasResource("subscription", "relativity-lab", "v543-isolated-preflight", { owner: "v543-isolated-preflight", estimatedBytes: 0 }); let done = false; return () => { if (done) return; done = true; listeners.delete(listener); release(); }; }
export function getKerrReplayIsolatedPreflightTelemetryV543() { return Object.freeze({ listenerCount: listeners.size, requestCount: snapshot.requestCount, status: snapshot.status }); }
export function resetKerrReplayIsolatedPreflightClientForTestsV543(): void { if (listeners.size) throw new Error("v543-listener-leak"); snapshot = INITIAL; requestPromise = null; }
