export const KERR_MEASURED_SIDECAR_ADMISSION_VERSION_V549 = "v549-kerr-measured-sidecar-admission-v1" as const;
export const KERR_MEASURED_SIDECAR_ADMISSION_API_VERSION_V549 = "v549-kerr-measured-sidecar-admission-api-v1" as const;
export const KERR_MEASURED_SIDECAR_HUD_PROFILE_ID_V549 = "science-cinematic-v9r8-v549" as const;
const SHA = /^[0-9a-f]{64}$/;
const TRANSIENT = new Set(["generatedAt", "artifactSha256", "payloadSha256", "evidenceSha256", "pointerSha256", "stageChainSha256", "columnSha256", "receiptSha256", "resultSha256", "environmentSha256", "preflightSha256", "matrixSha256", "isolatedReceiptSha256", "executionMatrixSha256", "schemaPackSha256"]);
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const canonicalize = (value: unknown): unknown => Array.isArray(value) ? value.map(canonicalize) : !isRecord(value) ? value : Object.fromEntries(Object.entries(value).filter(([key]) => !TRANSIENT.has(key)).sort(([left], [right]) => left.localeCompare(right)).map(([key, entry]) => [key, canonicalize(entry)]));
export const canonicalKerrMeasuredSidecarAdmissionV549 = (value: unknown) => JSON.stringify(canonicalize(value));
export type KerrMeasuredSidecarAdmissionArtifactV549 = Readonly<{
  version: typeof KERR_MEASURED_SIDECAR_ADMISSION_VERSION_V549;
  status: "measured-sidecar-schema-qualified-synthetic-fixtures-nonauthoritative-inputs-missing";
  source: Readonly<Record<"v420WcsArtifactSha256" | "v465DetectorContractSha256" | "v548ArtifactSha256" | "v548EvidenceSha256" | "v548PointerSha256" | "v314StateSha256", string>>;
  contract: Readonly<{ sidecarCount: 2; sidecarFileNames: readonly ["detector-response.json", "wcs-orientation.json"]; exactFileNamesRequired: true; crossFileInstrumentIdentityRequired: true; crossFileDetectorIdentityRequired: true; crossFileCampaignIdentityRequired: true; canonicalSourceShaRequired: true; finiteNumericFieldsRequired: true; explicitUnitsRequired: true; explicitApplicabilityRequired: true; measuredContentClassRequiredForAuthority: true; syntheticFixtureValidationOnly: true; syntheticFixtureMayGrantAuthority: false; productionScopeAllowed: false; pixelValuesAllowed: false; networkAllowed: false; automaticRetryAllowed: false }>;
  schemas: Readonly<{ detectorResponse: Readonly<{ sourceAuthority: "v465"; fieldCount: 13; fields: readonly string[]; responseUnits: "electron-per-ADU"; inputUnits: "ADU"; saturationUnits: "electron"; measuredFilePresent: false }>; wcsOrientation: Readonly<{ sourceAuthority: "v420"; fieldCount: 23; fields: readonly string[]; axisUnits: "geometrized-GM-over-c-squared"; pixelConvention: "FITS-one-based-continuous-pixel-centers"; projection: "LINEAR"; measuredFilePresent: false }> }>;
  syntheticFixtures: Readonly<{ pairCount: 1; detectorFixtureQualified: true; wcsFixtureQualified: true; crossIdentityQualified: true; sourceShaQualified: true; authorityGranted: false; sciencePixelCount: 0; fixturePixelValueCount: 0; receiptPath: string; receiptFileSha256: string; receiptCanonicalSha256: string }>;
  mutationAudit: Readonly<{ mutationCount: 10; rejectedMutationCount: 10; mutations: readonly string[] }>;
  admission: Readonly<{ detectorMeasuredSidecarPresent: false; wcsMeasuredSidecarPresent: false; measuredPairComplete: false; measuredAuthorityGranted: false; scienceRasterQualified: false; reason: "measured-sidecars-missing" }>;
  counts: Readonly<{ requiredSidecarCount: 2; measuredSidecarCount: 0; syntheticFixturePairCount: 1; qualifiedSyntheticFixtureCount: 2; measuredAuthorityGrantCount: 0; observedFrameCount: 0; sciencePixelCount: 0; fitsImageHduCount: 0; pngImageCount: 0 }>;
  qualification: Readonly<{ detectorResponseSchemaQualified: true; wcsOrientationSchemaQualified: true; crossIdentityFirewallQualified: true; syntheticAuthorityFirewallQualified: true; adversarialMutationRejectionQualified: true; measuredSidecarPairQualified: false; measuredAuthorityGranted: false; scienceRasterQualified: false; productionPromotionQualified: false }>;
  boundary: Readonly<{ fixtureContainsPixelValues: false; measuredValuesInvented: false; sciencePayloadMutationAllowed: false; cinematicScienceWritebackAllowed: false; denseCampaignStatus: "incomplete-0-of-49"; browserQualification: "not-run"; formalProductPointer: "v263"; formalDefaultKernel: "legacy-eih-1pn" }>;
  sourceManifest: readonly Readonly<{ path: string; sha256: string }>[]; sourceSha256: string; artifactSha256: string;
}>;
export type KerrMeasuredSidecarAdmissionApiV549 = Readonly<{ version: typeof KERR_MEASURED_SIDECAR_ADMISSION_API_VERSION_V549; available: boolean; reason: "ready" | "lite-boundary" | "local-shadow-only" | "evidence-corrupt"; summary: KerrMeasuredSidecarAdmissionArtifactV549 | null }>;
export function parseKerrMeasuredSidecarAdmissionV549(value: unknown): KerrMeasuredSidecarAdmissionArtifactV549 { if (!isRecord(value) || value.version !== KERR_MEASURED_SIDECAR_ADMISSION_VERSION_V549 || value.status !== "measured-sidecar-schema-qualified-synthetic-fixtures-nonauthoritative-inputs-missing" || !SHA.test(String(value.artifactSha256)) || !SHA.test(String(value.sourceSha256))) throw new Error("v549-artifact-boundary"); const artifact = value as unknown as KerrMeasuredSidecarAdmissionArtifactV549; if (artifact.contract.sidecarCount !== 2 || artifact.contract.sidecarFileNames[0] !== "detector-response.json" || artifact.contract.sidecarFileNames[1] !== "wcs-orientation.json" || artifact.contract.syntheticFixtureMayGrantAuthority !== false || artifact.contract.productionScopeAllowed !== false || artifact.contract.pixelValuesAllowed !== false || artifact.schemas.detectorResponse.fieldCount !== 13 || artifact.schemas.detectorResponse.measuredFilePresent !== false || artifact.schemas.wcsOrientation.fieldCount !== 23 || artifact.schemas.wcsOrientation.measuredFilePresent !== false || artifact.syntheticFixtures.pairCount !== 1 || artifact.syntheticFixtures.detectorFixtureQualified !== true || artifact.syntheticFixtures.wcsFixtureQualified !== true || artifact.syntheticFixtures.crossIdentityQualified !== true || artifact.syntheticFixtures.authorityGranted !== false || artifact.syntheticFixtures.fixturePixelValueCount !== 0 || !SHA.test(artifact.syntheticFixtures.receiptFileSha256) || !SHA.test(artifact.syntheticFixtures.receiptCanonicalSha256) || artifact.mutationAudit.mutationCount !== 10 || artifact.mutationAudit.rejectedMutationCount !== 10 || artifact.admission.measuredPairComplete !== false || artifact.admission.measuredAuthorityGranted !== false || artifact.admission.scienceRasterQualified !== false || artifact.counts.measuredSidecarCount !== 0 || artifact.counts.sciencePixelCount !== 0 || artifact.qualification.measuredSidecarPairQualified !== false || artifact.qualification.measuredAuthorityGranted !== false || artifact.boundary.fixtureContainsPixelValues !== false || artifact.boundary.measuredValuesInvented !== false || artifact.boundary.denseCampaignStatus !== "incomplete-0-of-49" || artifact.boundary.formalProductPointer !== "v263" || artifact.boundary.formalDefaultKernel !== "legacy-eih-1pn") throw new Error("v549-qualification-boundary"); return artifact; }
export function parseKerrMeasuredSidecarAdmissionApiV549(value: unknown): KerrMeasuredSidecarAdmissionApiV549 { if (!isRecord(value) || value.version !== KERR_MEASURED_SIDECAR_ADMISSION_API_VERSION_V549 || typeof value.available !== "boolean" || !["ready", "lite-boundary", "local-shadow-only", "evidence-corrupt"].includes(String(value.reason))) throw new Error("v549-api-boundary"); if (value.available) parseKerrMeasuredSidecarAdmissionV549(value.summary); else if (value.summary !== null) throw new Error("v549-api-unavailable-summary"); return value as unknown as KerrMeasuredSidecarAdmissionApiV549; }
export type KerrMeasuredSidecarHudModeV549 = "science" | "cinematic";
const scienceProfile = Object.freeze({ id: KERR_MEASURED_SIDECAR_HUD_PROFILE_ID_V549, mode: "science" as const, panel: "#030c12", panelRaised: "#071824", ink: "#effcff", muted: "#7896a7", qualified: "#7ceec3", warning: "#f2c371", unavailable: "#ff88a8", scienceBoundary: Object.freeze({ linearDisplay: true, bloomIntensity: 0 as const, colorGradeIntensity: 0 as const, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }), cinematicSeed: null });
const cinematicProfile = Object.freeze({ ...scienceProfile, mode: "cinematic" as const, panel: "#150907", panelRaised: "#27140e", ink: "#fff5e8", muted: "#bd9a80", qualified: "#93ecc6", warning: "#f5bf6e", unavailable: "#ff92ae", scienceBoundary: Object.freeze({ linearDisplay: false, bloomIntensity: 0.03, colorGradeIntensity: 0.019, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }), cinematicSeed: "orbit-atlas-v549-sidecar-admission-seed-01" });
export const resolveKerrMeasuredSidecarHudProfileV549 = (mode: KerrMeasuredSidecarHudModeV549) => mode === "science" ? scienceProfile : cinematicProfile;
export function createKerrMeasuredSidecarHudEncodingV549(artifact: KerrMeasuredSidecarAdmissionArtifactV549, mode: KerrMeasuredSidecarHudModeV549) { return Object.freeze({ version: "v549-measured-sidecar-hud-v1" as const, profileId: KERR_MEASURED_SIDECAR_HUD_PROFILE_ID_V549, mode, artifactKey: artifact.artifactSha256, receiptKey: artifact.syntheticFixtures.receiptCanonicalSha256, sidecarFileNames: artifact.contract.sidecarFileNames, detectorFields: artifact.schemas.detectorResponse.fields, wcsFields: artifact.schemas.wcsOrientation.fields, measuredAuthorityGranted: false as const, scienceRasterQualified: false as const, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }); }
export function compareKerrMeasuredSidecarHudEncodingsV549(science: ReturnType<typeof createKerrMeasuredSidecarHudEncodingV549>, cinematic: ReturnType<typeof createKerrMeasuredSidecarHudEncodingV549>) { if (science.mode !== "science" || cinematic.mode !== "cinematic" || science.artifactKey !== cinematic.artifactKey || science.receiptKey !== cinematic.receiptKey || JSON.stringify(science.sidecarFileNames) !== JSON.stringify(cinematic.sidecarFileNames) || JSON.stringify(science.detectorFields) !== JSON.stringify(cinematic.detectorFields) || JSON.stringify(science.wcsFields) !== JSON.stringify(cinematic.wcsFields)) throw new Error("v549-hud-boundary"); return Object.freeze({ schemasStable: true as const, receiptStable: true as const, authorityStable: true as const, rasterQualificationStable: true as const, scientificFieldMutation: false as const }); }
