export const KERR_BLIND_AUTHORITY_REVIEW_VERSION_V547 = "v547-kerr-blind-authority-review-artifact-v1" as const;
export const KERR_BLIND_AUTHORITY_REVIEW_API_VERSION_V547 = "v547-kerr-blind-authority-review-api-v1" as const;
export const KERR_BLIND_AUTHORITY_REVIEW_HUD_PROFILE_ID_V547 = "science-cinematic-v9r6-v547" as const;
const SHA = /^[0-9a-f]{64}$/;
const TRANSIENT = new Set(["generatedAt", "artifactSha256", "payloadSha256", "evidenceSha256", "pointerSha256", "stageChainSha256", "columnSha256", "receiptSha256", "resultSha256", "environmentSha256", "preflightSha256", "matrixSha256", "isolatedReceiptSha256", "executionMatrixSha256", "schemaPackSha256", "denialReceiptSha256"]);
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const canonicalize = (value: unknown): unknown => Array.isArray(value) ? value.map(canonicalize) : !isRecord(value) ? value : Object.fromEntries(Object.entries(value).filter(([key]) => !TRANSIENT.has(key)).sort(([left], [right]) => left.localeCompare(right)).map(([key, entry]) => [key, canonicalize(entry)]));
export const canonicalKerrBlindAuthorityReviewV547 = (value: unknown) => JSON.stringify(canonicalize(value));

export type KerrBlindReviewDecisionV547 = Readonly<{
  version: "v547-blind-review-decision-v1";
  reviewerId: string;
  reviewerOrdinal: 1 | 2;
  reviewKeyId: string;
  reviewKeyScope: "synthetic-fixture-denial-only";
  publicKeySpkiBase64: string;
  candidateReceiptSha256: string;
  candidateContentClass: "synthetic-validation-fixture";
  blindFieldNames: readonly ["status", "candidate.contentClass", "checks", "qualification", "boundary", "resultSha256"];
  pixelValuesExposed: false;
  decision: "deny-synthetic-control";
  authorityScope: "none";
  reasonCode: "synthetic-fixture-cannot-grant-authority";
  signatureAlgorithm: "Ed25519";
  signatureBase64: string;
}>;
export const canonicalKerrBlindReviewDecisionV547 = (value: KerrBlindReviewDecisionV547 | Omit<KerrBlindReviewDecisionV547, "signatureBase64">) => JSON.stringify(Object.fromEntries(Object.entries(value).filter(([key]) => key !== "signatureBase64").sort(([left], [right]) => left.localeCompare(right))));

export type KerrBlindAuthorityReviewArtifactV547 = Readonly<{
  version: typeof KERR_BLIND_AUTHORITY_REVIEW_VERSION_V547;
  status: "blind-review-protocol-qualified-synthetic-denial-qualified-measured-candidate-missing";
  source: Readonly<Record<"v546ArtifactSha256" | "v546ReceiptSha256" | "v546EvidenceSha256" | "v546PointerSha256" | "v314StateSha256", string>>;
  contract: Readonly<{ protocolVersion: "v547-two-reviewer-blind-authority-v1"; requiredReviewerCount: 2; distinctReviewerIdentitiesRequired: true; distinctReviewKeysRequired: true; detachedEd25519SignaturesRequired: true; candidateReceiptCanonicalShaRequired: true; blindReviewPixelValuesForbidden: true; unanimousGrantRequiredForMeasuredCandidate: true; maximumGrantScope: "local-shadow-science-raster-candidate"; productionGrantAllowed: false; syntheticFixtureGrantAllowed: false; fixtureKeysMayGrantMeasuredAuthority: false; automaticRetryAllowed: false; networkAllowed: false }>;
  measuredEligibility: Readonly<{ requiredContentClass: "measured-science-candidate"; requiredReceiptStatus: "measured-candidate-semantically-qualified-awaiting-blind-authority-review"; requiredSemanticValidatorVersion: "v546-independent-fits-validation-receipt-v1"; measuredCandidatePresent: false; trustedMeasuredReviewerRegistryPresent: false; unanimousMeasuredGrantPresent: false; authorityDecision: "blocked-inputs-missing" }>;
  syntheticDenialFixture: Readonly<{ candidateReceiptSha256: string; candidateContentClass: "synthetic-validation-fixture"; reviewerDecisions: readonly [KerrBlindReviewDecisionV547, KerrBlindReviewDecisionV547]; signatureVerifiedCount: 2; distinctReviewerCount: 2; distinctReviewKeyCount: 2; blindedFieldSetQualified: true; pixelValuesExposed: false; unanimousDenialQualified: true; syntheticAuthorityGranted: false; measuredAuthorityGranted: false; fixturePrivateKeysPublished: false }>;
  mutationAudit: Readonly<{ mutationCount: 8; rejectedMutationCount: 8; mutations: readonly string[] }>;
  counts: Readonly<{ measuredCandidateCount: 0; measuredReviewDecisionCount: 0; measuredAuthorityGrantCount: 0; syntheticDenialFixtureCount: 1; verifiedFixtureSignatureCount: 2; publishedFitsFileCount: 0; publishedPixelValueCount: 0; scienceRasterCount: 0 }>;
  qualification: Readonly<{ blindReviewProtocolQualified: true; detachedSignatureVerifierQualified: true; syntheticGrantFirewallQualified: true; productionScopeFirewallQualified: true; syntheticDenialFixtureQualified: true; measuredCandidateSemanticallyQualified: false; measuredAuthorityGranted: false; scienceRasterQualified: false; productionPromotionQualified: false }>;
  boundary: Readonly<{ reviewPayloadContainsPixelValues: false; fixturePrivateKeysPublished: false; measuredValuesInvented: false; sciencePayloadMutationAllowed: false; cinematicScienceWritebackAllowed: false; denseCampaignStatus: "incomplete-0-of-49"; browserQualification: "not-run"; formalProductPointer: "v263"; formalDefaultKernel: "legacy-eih-1pn" }>;
  sourceManifest: readonly Readonly<{ path: string; sha256: string }>[];
  sourceSha256: string;
  artifactSha256: string;
}>;
export type KerrBlindAuthorityReviewApiV547 = Readonly<{ version: typeof KERR_BLIND_AUTHORITY_REVIEW_API_VERSION_V547; available: boolean; reason: "ready" | "lite-boundary" | "local-shadow-only" | "evidence-corrupt"; summary: KerrBlindAuthorityReviewArtifactV547 | null }>;

function parseDecision(value: unknown): KerrBlindReviewDecisionV547 {
  if (!isRecord(value) || value.version !== "v547-blind-review-decision-v1" || ![1, 2].includes(Number(value.reviewerOrdinal)) || value.reviewKeyScope !== "synthetic-fixture-denial-only" || !SHA.test(String(value.reviewKeyId)) || !SHA.test(String(value.candidateReceiptSha256)) || value.candidateContentClass !== "synthetic-validation-fixture" || value.pixelValuesExposed !== false || value.decision !== "deny-synthetic-control" || value.authorityScope !== "none" || value.reasonCode !== "synthetic-fixture-cannot-grant-authority" || value.signatureAlgorithm !== "Ed25519" || typeof value.signatureBase64 !== "string" || value.signatureBase64.length < 80) throw new Error("v547-decision-boundary");
  return value as unknown as KerrBlindReviewDecisionV547;
}
export function parseKerrBlindAuthorityReviewArtifactV547(value: unknown): KerrBlindAuthorityReviewArtifactV547 {
  if (!isRecord(value) || value.version !== KERR_BLIND_AUTHORITY_REVIEW_VERSION_V547 || value.status !== "blind-review-protocol-qualified-synthetic-denial-qualified-measured-candidate-missing" || !SHA.test(String(value.artifactSha256)) || !SHA.test(String(value.sourceSha256))) throw new Error("v547-artifact-boundary");
  const artifact = value as unknown as KerrBlindAuthorityReviewArtifactV547, [left, right] = artifact.syntheticDenialFixture.reviewerDecisions.map(parseDecision) as [KerrBlindReviewDecisionV547, KerrBlindReviewDecisionV547];
  if (artifact.contract.requiredReviewerCount !== 2 || artifact.contract.detachedEd25519SignaturesRequired !== true || artifact.contract.blindReviewPixelValuesForbidden !== true || artifact.contract.maximumGrantScope !== "local-shadow-science-raster-candidate" || artifact.contract.productionGrantAllowed !== false || artifact.contract.syntheticFixtureGrantAllowed !== false || artifact.contract.fixtureKeysMayGrantMeasuredAuthority !== false || artifact.measuredEligibility.measuredCandidatePresent !== false || artifact.measuredEligibility.trustedMeasuredReviewerRegistryPresent !== false || artifact.measuredEligibility.unanimousMeasuredGrantPresent !== false || artifact.measuredEligibility.authorityDecision !== "blocked-inputs-missing" || left.reviewerId === right.reviewerId || left.reviewKeyId === right.reviewKeyId || artifact.syntheticDenialFixture.signatureVerifiedCount !== 2 || artifact.syntheticDenialFixture.distinctReviewerCount !== 2 || artifact.syntheticDenialFixture.distinctReviewKeyCount !== 2 || artifact.syntheticDenialFixture.pixelValuesExposed !== false || artifact.syntheticDenialFixture.syntheticAuthorityGranted !== false || artifact.syntheticDenialFixture.measuredAuthorityGranted !== false || artifact.syntheticDenialFixture.fixturePrivateKeysPublished !== false || artifact.mutationAudit.mutationCount !== 8 || artifact.mutationAudit.rejectedMutationCount !== 8 || new Set(artifact.mutationAudit.mutations).size !== 8 || artifact.counts.measuredCandidateCount !== 0 || artifact.counts.measuredAuthorityGrantCount !== 0 || artifact.counts.publishedFitsFileCount !== 0 || artifact.counts.publishedPixelValueCount !== 0 || artifact.counts.scienceRasterCount !== 0 || artifact.qualification.blindReviewProtocolQualified !== true || artifact.qualification.detachedSignatureVerifierQualified !== true || artifact.qualification.measuredAuthorityGranted !== false || artifact.qualification.scienceRasterQualified !== false || artifact.boundary.reviewPayloadContainsPixelValues !== false || artifact.boundary.fixturePrivateKeysPublished !== false || artifact.boundary.measuredValuesInvented !== false || artifact.boundary.denseCampaignStatus !== "incomplete-0-of-49" || artifact.boundary.formalProductPointer !== "v263" || artifact.boundary.formalDefaultKernel !== "legacy-eih-1pn") throw new Error("v547-qualification-boundary");
  return artifact;
}
export function parseKerrBlindAuthorityReviewApiV547(value: unknown): KerrBlindAuthorityReviewApiV547 { if (!isRecord(value) || value.version !== KERR_BLIND_AUTHORITY_REVIEW_API_VERSION_V547 || typeof value.available !== "boolean" || !["ready", "lite-boundary", "local-shadow-only", "evidence-corrupt"].includes(String(value.reason))) throw new Error("v547-api-boundary"); if (value.available) parseKerrBlindAuthorityReviewArtifactV547(value.summary); else if (value.summary !== null) throw new Error("v547-api-unavailable-summary"); return value as unknown as KerrBlindAuthorityReviewApiV547; }

export type KerrBlindAuthorityReviewHudModeV547 = "science" | "cinematic";
const scienceProfile = Object.freeze({ id: KERR_BLIND_AUTHORITY_REVIEW_HUD_PROFILE_ID_V547, mode: "science" as const, panel: "#030c12", panelRaised: "#071824", ink: "#effcff", muted: "#7797a7", qualified: "#7beec2", warning: "#f2c271", unavailable: "#ff88a8", scienceBoundary: Object.freeze({ linearDisplay: true, bloomIntensity: 0 as const, colorGradeIntensity: 0 as const, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }), cinematicSeed: null });
const cinematicProfile = Object.freeze({ ...scienceProfile, mode: "cinematic" as const, panel: "#150907", panelRaised: "#27140e", ink: "#fff5e8", muted: "#bd9b80", qualified: "#92ecc5", warning: "#f5bf6e", unavailable: "#ff92ae", scienceBoundary: Object.freeze({ linearDisplay: false, bloomIntensity: 0.032, colorGradeIntensity: 0.021, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }), cinematicSeed: "orbit-atlas-v547-blind-review-seed-01" });
export const resolveKerrBlindAuthorityReviewHudProfileV547 = (mode: KerrBlindAuthorityReviewHudModeV547) => mode === "science" ? scienceProfile : cinematicProfile;
export function createKerrBlindAuthorityReviewHudEncodingV547(artifact: KerrBlindAuthorityReviewArtifactV547, mode: KerrBlindAuthorityReviewHudModeV547) { return Object.freeze({ version: "v547-blind-authority-review-hud-v1" as const, profileId: KERR_BLIND_AUTHORITY_REVIEW_HUD_PROFILE_ID_V547, mode, artifactKey: artifact.artifactSha256, candidateReceiptKey: artifact.syntheticDenialFixture.candidateReceiptSha256, reviewerKeyIds: artifact.syntheticDenialFixture.reviewerDecisions.map((entry) => entry.reviewKeyId), signatureVerifiedCount: 2 as const, mutationRejectionCount: 8 as const, measuredCandidateCount: 0 as const, measuredAuthorityGranted: false as const, scienceRasterQualified: false as const, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }); }
export function compareKerrBlindAuthorityReviewHudEncodingsV547(science: ReturnType<typeof createKerrBlindAuthorityReviewHudEncodingV547>, cinematic: ReturnType<typeof createKerrBlindAuthorityReviewHudEncodingV547>) { if (science.mode !== "science" || cinematic.mode !== "cinematic" || science.artifactKey !== cinematic.artifactKey || science.candidateReceiptKey !== cinematic.candidateReceiptKey || JSON.stringify(science.reviewerKeyIds) !== JSON.stringify(cinematic.reviewerKeyIds) || science.measuredAuthorityGranted !== cinematic.measuredAuthorityGranted || science.scienceRasterQualified !== cinematic.scienceRasterQualified) throw new Error("v547-hud-boundary"); return Object.freeze({ signaturesStable: true as const, authorityStable: true as const, rasterQualificationStable: true as const, scientificFieldMutation: false as const }); }
