"use client";
import { acquireAtlasResource } from "./atlasResourceLifecycle";
import { parseKerrObservationQuantityProvenanceApiV548, type KerrObservationQuantityProvenanceAdmissionArtifactV548 } from "./kerrObservationQuantityProvenanceAdmissionV548";
type SnapshotV548 = Readonly<{ status: "idle" | "loading" | "ready" | "unavailable"; reason: string | null; requestCount: 0 | 1; responseBytes: number; summary: KerrObservationQuantityProvenanceAdmissionArtifactV548 | null }>;
const INITIAL: SnapshotV548 = Object.freeze({ status: "idle", reason: null, requestCount: 0, responseBytes: 0, summary: null }), listeners = new Set<() => void>(); let snapshot = INITIAL; let requestPromise: Promise<KerrObservationQuantityProvenanceAdmissionArtifactV548> | null = null; const publish = (next: SnapshotV548) => { snapshot = Object.freeze(next); listeners.forEach((listener) => listener()); };
export function loadKerrObservationQuantityProvenanceSummaryV548(): Promise<KerrObservationQuantityProvenanceAdmissionArtifactV548> { if (requestPromise) return requestPromise; publish({ status: "loading", reason: null, requestCount: 1, responseBytes: 0, summary: null }); requestPromise = fetch("/api/atlas/relativity-evidence/v548/observation-quantity-provenance", { cache: "no-store" }).then(async (response) => { const body = await response.text(), responseBytes = new TextEncoder().encode(body).byteLength; if (responseBytes > 128 * 1024) throw new Error("response-too-large"); const api = parseKerrObservationQuantityProvenanceApiV548(JSON.parse(body)); if (!response.ok || !api.available || !api.summary) throw new Error(`v548-provenance-${api.reason}`); publish({ status: "ready", reason: null, requestCount: 1, responseBytes, summary: api.summary }); return api.summary; }).catch((error: unknown) => { publish({ status: "unavailable", reason: error instanceof Error ? error.message : "request-failed", requestCount: 1, responseBytes: snapshot.responseBytes, summary: null }); throw error; }); return requestPromise; }
export const getKerrObservationQuantityProvenanceSnapshotV548 = () => snapshot;
export function subscribeKerrObservationQuantityProvenanceV548(listener: () => void): () => void { listeners.add(listener); const release = acquireAtlasResource("subscription", "relativity-lab", "v548-observation-quantity-provenance", { owner: "v548-observation-quantity-provenance", estimatedBytes: 0 }); let done = false; return () => { if (done) return; done = true; listeners.delete(listener); release(); }; }
export function getKerrObservationQuantityProvenanceTelemetryV548() { return Object.freeze({ listenerCount: listeners.size, requestCount: snapshot.requestCount, status: snapshot.status }); }
export function resetKerrObservationQuantityProvenanceClientForTestsV548(): void { if (listeners.size) throw new Error("v548-listener-leak"); snapshot = INITIAL; requestPromise = null; }
