"use client";
import { acquireAtlasResource } from "./atlasResourceLifecycle";
import { parseKerrMeasuredSidecarAdmissionApiV549, type KerrMeasuredSidecarAdmissionArtifactV549 } from "./kerrMeasuredSidecarAdmissionV549";
type SnapshotV549 = Readonly<{ status: "idle" | "loading" | "ready" | "unavailable"; reason: string | null; requestCount: 0 | 1; responseBytes: number; summary: KerrMeasuredSidecarAdmissionArtifactV549 | null }>;
const INITIAL: SnapshotV549 = Object.freeze({ status: "idle", reason: null, requestCount: 0, responseBytes: 0, summary: null }), listeners = new Set<() => void>(); let snapshot = INITIAL; let requestPromise: Promise<KerrMeasuredSidecarAdmissionArtifactV549> | null = null; const publish = (next: SnapshotV549) => { snapshot = Object.freeze(next); listeners.forEach((listener) => listener()); };
export function loadKerrMeasuredSidecarAdmissionSummaryV549(): Promise<KerrMeasuredSidecarAdmissionArtifactV549> { if (requestPromise) return requestPromise; publish({ status: "loading", reason: null, requestCount: 1, responseBytes: 0, summary: null }); requestPromise = fetch("/api/atlas/relativity-evidence/v549/measured-sidecar-admission", { cache: "no-store" }).then(async (response) => { const body = await response.text(), responseBytes = new TextEncoder().encode(body).byteLength; if (responseBytes > 128 * 1024) throw new Error("response-too-large"); const api = parseKerrMeasuredSidecarAdmissionApiV549(JSON.parse(body)); if (!response.ok || !api.available || !api.summary) throw new Error(`v549-sidecar-${api.reason}`); publish({ status: "ready", reason: null, requestCount: 1, responseBytes, summary: api.summary }); return api.summary; }).catch((error: unknown) => { publish({ status: "unavailable", reason: error instanceof Error ? error.message : "request-failed", requestCount: 1, responseBytes: snapshot.responseBytes, summary: null }); throw error; }); return requestPromise; }
export const getKerrMeasuredSidecarAdmissionSnapshotV549 = () => snapshot;
export function subscribeKerrMeasuredSidecarAdmissionV549(listener: () => void): () => void { listeners.add(listener); const release = acquireAtlasResource("subscription", "relativity-lab", "v549-measured-sidecar-admission", { owner: "v549-measured-sidecar-admission", estimatedBytes: 0 }); let done = false; return () => { if (done) return; done = true; listeners.delete(listener); release(); }; }
export function getKerrMeasuredSidecarAdmissionTelemetryV549() { return Object.freeze({ listenerCount: listeners.size, requestCount: snapshot.requestCount, status: snapshot.status }); }
export function resetKerrMeasuredSidecarAdmissionClientForTestsV549(): void { if (listeners.size) throw new Error("v549-listener-leak"); snapshot = INITIAL; requestPromise = null; }
