import { createHash } from "node:crypto";

import { parseKerrAxialPolarizationVectorArtifactV421, type KerrAxialPolarizationVectorArtifactV421 } from "./kerrAxialPolarizationVectorCatalogV421";

export const KERR_ORIENTATION_BASIS_VERSION_V422 = "v422-kerr-polarization-orientation-basis-v1" as const;
export const KERR_ORIENTATION_BASIS_ARTIFACT_VERSION_V422 = "v422-kerr-polarization-orientation-basis-artifact-v1" as const;
export const KERR_ORIENTATION_BASIS_SUMMARY_VERSION_V422 = "v422-kerr-polarization-orientation-basis-summary-v1" as const;
export const KERR_ORIENTATION_BASIS_RESPONSE_VERSION_V422 = "v422-kerr-polarization-orientation-basis-response-v1" as const;
export const KERR_V421_ARTIFACT_SHA256_V422 = "34ac72927c251fb22d436bfba04fdbee757cd410c0708e60c00043be7e029f44" as const;
export const KERR_V421_FILE_SHA256_V422 = "9b0165ba2af5781e734d34bb814dbb4793bdee76c0cdec7412aca6f558550a40" as const;

type RayIndex = 12 | 13 | 14 | 15;
type RayId = "disk-00" | "disk-01" | "disk-02" | "disk-03";
type UnavailableMeasurements = Readonly<{ stokesI: null; stokesQ: null; stokesU: null; stokesV: null; normalizedQ: null; normalizedU: null; linearPolarizationFraction: null; polarizationAmplitude: null }>;
export type KerrPolarizationOrientationBasisRowV422 = Readonly<{
  rayIndex: RayIndex;
  rayId: RayId;
  spinA: number;
  authorityEvpaDeg: number;
  continuousCoordinate: Readonly<{ pixelX: number; pixelY: number; semantics: "FITS-1-based-continuous-source-coordinate-not-pixel-sample" }>;
  orientationBasis: Readonly<{ qHat: number; uHat: number; normResidual: number; recoveredAxialEvpaResidualDeg: number; plus180BasisResidual: number; v421TensorDifference: number; semantics: "unit-double-angle-orientation-basis-not-normalized-Stokes-measurement" }>;
  applicabilityMask: Readonly<{ orientationAvailable: true; evpaApplicable: true; polarizationAmplitudeAvailable: false; stokesMeasurementAvailable: false; densePixelSampleAvailable: false; code: "orientation-basis-only-authority-source" }>;
  measurements: UnavailableMeasurements;
  interpolationAllowed: false;
  nearestPixelAssignmentAllowed: false;
}>;
export type KerrPolarizationOrientationBasisViewV422 = Readonly<{
  version: typeof KERR_ORIENTATION_BASIS_VERSION_V422;
  status: "qualified-four-source-mask-aware-orientation-basis-no-stokes-or-raster-values";
  source: Readonly<{ v421ArtifactSha256: typeof KERR_V421_ARTIFACT_SHA256_V422 }>;
  semantics: Readonly<{ qHat: "cos-two-chi-unit-orientation-basis-not-Q-over-I"; uHat: "sin-two-chi-unit-orientation-basis-not-U-over-I"; radius: "unity-by-definition-not-polarization-fraction"; axialPeriodDeg: 180 }>;
  maskContract: Readonly<{ scope: "four-continuous-authority-source-records"; orientationAvailableCount: 4; stokesMeasurementAvailableCount: 0; densePixelSampleAvailableCount: 0; unavailableIsNotZero: true; missingValue: null; fillValue: null }>;
  rasterAdmission: Readonly<{ width: 384; height: 384; coordinateContractAvailable: true; rasterMaskGenerated: false; sciencePixelValueCount: 0; nearestPixelAssignmentAllowed: false; interpolationAllowed: false; unsampledPixelState: "unavailable-not-zero" }>;
  rows: readonly KerrPolarizationOrientationBasisRowV422[];
  maxima: Readonly<{ basisNormResidual: number; recoveredAxialEvpaResidualDeg: number; plus180BasisResidual: number; v421TensorDifference: number; pythonOracleDifference: number }>;
  thresholds: Readonly<{ basisNormResidual: 1e-12; recoveredAxialEvpaResidualDeg: 1e-12; plus180BasisResidual: 1e-12; v421TensorDifference: 1e-12; pythonOracleDifference: 1e-12 }>;
  products: Readonly<{ json: "available-orientation-basis-catalog"; csv: "available-orientation-basis-catalog"; fitsBinaryTable: "available-WCS-coordinate-plus-orientation-basis-table-no-image-data"; png: "available-orientation-basis-compass-diagnostic-not-science-raster"; fitsImage: "unavailable-no-raster-science-values"; stokesCube: "unavailable-no-I-Q-U-V-measurements" }>;
  scienceCinematicBoundary: Readonly<{ science: "authority-EVPA-derived-unit-orientation-basis-and-applicability-mask"; cinematic: "may-style-compass-grid-and-source-markers-only"; basisMutationAllowed: false; measurementSynthesisAllowed: false; unavailableToZeroCoercionAllowed: false }>;
  denseCampaignStatus: "incomplete-0-of-49";
  browserQualification: "not-run";
  boundary: "four-source-orientation-basis-only-no-normalized-Stokes-amplitude-raster-mask-or-dense-image";
}>;
export type KerrPolarizationOrientationBasisArtifactV422 = Readonly<{ version: typeof KERR_ORIENTATION_BASIS_ARTIFACT_VERSION_V422; generatedAt: string; status: KerrPolarizationOrientationBasisViewV422["status"]; sourceFiles: Readonly<{ v421FileSha256: typeof KERR_V421_FILE_SHA256_V422; pythonOracleFileSha256: string }>; pythonOracleArtifactSha256: string; view: KerrPolarizationOrientationBasisViewV422; deterministicReplay: true; networkAttempted: false; denseShardExecuted: false; rasterMaskGenerated: false; stokesMeasurementGenerated: false; artifactSha256: string }>;
export type KerrPolarizationOrientationBasisSummaryV422 = Readonly<{ version: typeof KERR_ORIENTATION_BASIS_SUMMARY_VERSION_V422; status: KerrPolarizationOrientationBasisViewV422["status"]; artifactSha256: string; semantics: KerrPolarizationOrientationBasisViewV422["semantics"]; maskContract: KerrPolarizationOrientationBasisViewV422["maskContract"]; rasterAdmission: KerrPolarizationOrientationBasisViewV422["rasterAdmission"]; rows: readonly KerrPolarizationOrientationBasisRowV422[]; maxima: KerrPolarizationOrientationBasisViewV422["maxima"]; products: KerrPolarizationOrientationBasisViewV422["products"]; denseCampaignStatus: "incomplete-0-of-49"; fullArtifactAvailable: true; boundary: "bounded-four-source-orientation-summary-no-raster-array-in-react-state" }>;
export type KerrPolarizationOrientationBasisResponseV422 = Readonly<{ version: typeof KERR_ORIENTATION_BASIS_RESPONSE_VERSION_V422; available: boolean; reason: "ready" | "lite-boundary" | "local-shadow-only" | "evidence-corrupt" | "request-failed"; summary: KerrPolarizationOrientationBasisSummaryV422 | null }>;

type PythonOracle = Readonly<{ version: string; status: string; rows: readonly Readonly<{ rayIndex: number; qHat: number; uHat: number; basisNormResidual: number; recoveredAxialEvpaResidualDeg: number; plus180BasisResidual: number; v421TensorDifference: number; continuousPixelX: number; continuousPixelY: number }>[]; maxima: Readonly<Record<string, number>>; artifactSha256: string }>;
const SHA = /^[a-f0-9]{64}$/;
const transient = new Set(["generatedAt", "artifactSha256"]);
function canonicalize(value: unknown): unknown { if (Array.isArray(value)) return value.map(canonicalize); if (!value || typeof value !== "object") return value; return Object.fromEntries(Object.entries(value as Record<string, unknown>).filter(([key]) => !transient.has(key)).sort(([left], [right]) => left.localeCompare(right)).map(([key, entry]) => [key, canonicalize(entry)])); }
export const canonicalShaV422 = (value: unknown): string => createHash("sha256").update(JSON.stringify(canonicalize(value))).digest("hex");
const axialDifference = (left: number, right: number) => { const difference = Math.abs(left - right) % 180; return Math.min(difference, 180 - difference); };

export function createKerrPolarizationOrientationBasisViewV422(v421Value: unknown, oracleValue: unknown): KerrPolarizationOrientationBasisViewV422 {
  const source: KerrAxialPolarizationVectorArtifactV421 = parseKerrAxialPolarizationVectorArtifactV421(v421Value);
  const oracle = oracleValue as PythonOracle;
  if (source.artifactSha256 !== KERR_V421_ARTIFACT_SHA256_V422 || oracle.version !== "v422-kerr-polarization-orientation-basis-python-oracle-v1" || oracle.status !== "qualified-independent-double-angle-orientation-basis-no-stokes-measurement" || !SHA.test(oracle.artifactSha256) || oracle.rows?.length !== 4 || !oracle.maxima || Object.values(oracle.maxima).some((value) => !Number.isFinite(value) || value >= 1e-12)) throw new Error("v422-source-lock");
  let pythonOracleDifference = 0;
  const rows = source.view.rows.map((entry): KerrPolarizationOrientationBasisRowV422 => {
    const oracleRow = oracle.rows.find((row) => row.rayIndex === entry.rayIndex);
    if (!oracleRow) throw new Error(`v422-oracle-row:${entry.rayId}`);
    const chi = entry.authorityEvpaDeg * Math.PI / 180;
    const qHat = Math.cos(2 * chi), uHat = Math.sin(2 * chi);
    const recovered = 0.5 * Math.atan2(uHat, qHat) * 180 / Math.PI;
    const plus180Q = Math.cos(2 * (chi + Math.PI)), plus180U = Math.sin(2 * (chi + Math.PI));
    const continuousPixelX = (entry.presentationGlyph.negative.pixelX + entry.presentationGlyph.positive.pixelX) / 2;
    const continuousPixelY = (entry.presentationGlyph.negative.pixelY + entry.presentationGlyph.positive.pixelY) / 2;
    const orientationBasis = Object.freeze({ qHat, uHat, normResidual: Math.abs(Math.hypot(qHat, uHat) - 1), recoveredAxialEvpaResidualDeg: axialDifference(recovered, entry.authorityEvpaDeg), plus180BasisResidual: Math.max(Math.abs(qHat - plus180Q), Math.abs(uHat - plus180U)), v421TensorDifference: Math.max(Math.abs(qHat - entry.axialOrientationTensor.cosTwoChi), Math.abs(uHat - entry.axialOrientationTensor.sinTwoChi)), semantics: "unit-double-angle-orientation-basis-not-normalized-Stokes-measurement" as const });
    pythonOracleDifference = Math.max(pythonOracleDifference, Math.abs(qHat - oracleRow.qHat), Math.abs(uHat - oracleRow.uHat), Math.abs(continuousPixelX - oracleRow.continuousPixelX), Math.abs(continuousPixelY - oracleRow.continuousPixelY));
    return Object.freeze({ rayIndex: entry.rayIndex, rayId: entry.rayId, spinA: entry.spinA, authorityEvpaDeg: entry.authorityEvpaDeg, continuousCoordinate: Object.freeze({ pixelX: continuousPixelX, pixelY: continuousPixelY, semantics: "FITS-1-based-continuous-source-coordinate-not-pixel-sample" }), orientationBasis, applicabilityMask: Object.freeze({ orientationAvailable: true, evpaApplicable: true, polarizationAmplitudeAvailable: false, stokesMeasurementAvailable: false, densePixelSampleAvailable: false, code: "orientation-basis-only-authority-source" }), measurements: Object.freeze({ stokesI: null, stokesQ: null, stokesU: null, stokesV: null, normalizedQ: null, normalizedU: null, linearPolarizationFraction: null, polarizationAmplitude: null }), interpolationAllowed: false, nearestPixelAssignmentAllowed: false });
  });
  const maxima = Object.freeze({ basisNormResidual: Math.max(...rows.map((row) => row.orientationBasis.normResidual)), recoveredAxialEvpaResidualDeg: Math.max(...rows.map((row) => row.orientationBasis.recoveredAxialEvpaResidualDeg)), plus180BasisResidual: Math.max(...rows.map((row) => row.orientationBasis.plus180BasisResidual)), v421TensorDifference: Math.max(...rows.map((row) => row.orientationBasis.v421TensorDifference)), pythonOracleDifference });
  if (Object.values(maxima).some((value) => value >= 1e-12)) throw new Error(`v422-basis-gate:${JSON.stringify(maxima)}`);
  return Object.freeze({ version: KERR_ORIENTATION_BASIS_VERSION_V422, status: "qualified-four-source-mask-aware-orientation-basis-no-stokes-or-raster-values", source: Object.freeze({ v421ArtifactSha256: KERR_V421_ARTIFACT_SHA256_V422 }), semantics: Object.freeze({ qHat: "cos-two-chi-unit-orientation-basis-not-Q-over-I", uHat: "sin-two-chi-unit-orientation-basis-not-U-over-I", radius: "unity-by-definition-not-polarization-fraction", axialPeriodDeg: 180 }), maskContract: Object.freeze({ scope: "four-continuous-authority-source-records", orientationAvailableCount: 4, stokesMeasurementAvailableCount: 0, densePixelSampleAvailableCount: 0, unavailableIsNotZero: true, missingValue: null, fillValue: null }), rasterAdmission: Object.freeze({ width: 384, height: 384, coordinateContractAvailable: true, rasterMaskGenerated: false, sciencePixelValueCount: 0, nearestPixelAssignmentAllowed: false, interpolationAllowed: false, unsampledPixelState: "unavailable-not-zero" }), rows: Object.freeze(rows), maxima, thresholds: Object.freeze({ basisNormResidual: 1e-12, recoveredAxialEvpaResidualDeg: 1e-12, plus180BasisResidual: 1e-12, v421TensorDifference: 1e-12, pythonOracleDifference: 1e-12 }), products: Object.freeze({ json: "available-orientation-basis-catalog", csv: "available-orientation-basis-catalog", fitsBinaryTable: "available-WCS-coordinate-plus-orientation-basis-table-no-image-data", png: "available-orientation-basis-compass-diagnostic-not-science-raster", fitsImage: "unavailable-no-raster-science-values", stokesCube: "unavailable-no-I-Q-U-V-measurements" }), scienceCinematicBoundary: Object.freeze({ science: "authority-EVPA-derived-unit-orientation-basis-and-applicability-mask", cinematic: "may-style-compass-grid-and-source-markers-only", basisMutationAllowed: false, measurementSynthesisAllowed: false, unavailableToZeroCoercionAllowed: false }), denseCampaignStatus: "incomplete-0-of-49", browserQualification: "not-run", boundary: "four-source-orientation-basis-only-no-normalized-Stokes-amplitude-raster-mask-or-dense-image" });
}

export function parseKerrPolarizationOrientationBasisArtifactV422(value: unknown): KerrPolarizationOrientationBasisArtifactV422 { const source = value && typeof value === "object" && !Array.isArray(value) ? value as Partial<KerrPolarizationOrientationBasisArtifactV422> : null; if (!source || source.version !== KERR_ORIENTATION_BASIS_ARTIFACT_VERSION_V422 || source.status !== "qualified-four-source-mask-aware-orientation-basis-no-stokes-or-raster-values" || source.sourceFiles?.v421FileSha256 !== KERR_V421_FILE_SHA256_V422 || !SHA.test(source.sourceFiles.pythonOracleFileSha256 ?? "") || !SHA.test(source.pythonOracleArtifactSha256 ?? "") || source.view?.rows?.length !== 4 || source.view.maskContract.stokesMeasurementAvailableCount !== 0 || source.view.rasterAdmission.rasterMaskGenerated !== false || source.view.rows.some((row) => Object.values(row.measurements).some((entry) => entry !== null) || row.applicabilityMask.stokesMeasurementAvailable !== false || row.nearestPixelAssignmentAllowed !== false || row.interpolationAllowed !== false) || source.deterministicReplay !== true || source.networkAttempted !== false || source.denseShardExecuted !== false || source.rasterMaskGenerated !== false || source.stokesMeasurementGenerated !== false || !SHA.test(source.artifactSha256 ?? "")) throw new Error("v422-artifact-identity"); return value as KerrPolarizationOrientationBasisArtifactV422; }
export function createKerrPolarizationOrientationBasisSummaryV422(value: unknown): KerrPolarizationOrientationBasisSummaryV422 { const artifact = parseKerrPolarizationOrientationBasisArtifactV422(value); return Object.freeze({ version: KERR_ORIENTATION_BASIS_SUMMARY_VERSION_V422, status: artifact.status, artifactSha256: artifact.artifactSha256, semantics: artifact.view.semantics, maskContract: artifact.view.maskContract, rasterAdmission: artifact.view.rasterAdmission, rows: artifact.view.rows, maxima: artifact.view.maxima, products: artifact.view.products, denseCampaignStatus: "incomplete-0-of-49", fullArtifactAvailable: true, boundary: "bounded-four-source-orientation-summary-no-raster-array-in-react-state" }); }
export function parseKerrPolarizationOrientationBasisSummaryV422(value: unknown): KerrPolarizationOrientationBasisSummaryV422 { const source = value && typeof value === "object" && !Array.isArray(value) ? value as Partial<KerrPolarizationOrientationBasisSummaryV422> : null; if (!source || source.version !== KERR_ORIENTATION_BASIS_SUMMARY_VERSION_V422 || !SHA.test(source.artifactSha256 ?? "") || source.rows?.length !== 4 || source.maskContract?.stokesMeasurementAvailableCount !== 0 || source.rasterAdmission?.rasterMaskGenerated !== false || source.products?.stokesCube !== "unavailable-no-I-Q-U-V-measurements" || source.boundary !== "bounded-four-source-orientation-summary-no-raster-array-in-react-state") throw new Error("v422-summary-identity"); return value as KerrPolarizationOrientationBasisSummaryV422; }
export function parseKerrPolarizationOrientationBasisResponseV422(value: unknown): KerrPolarizationOrientationBasisResponseV422 { const source = value && typeof value === "object" && !Array.isArray(value) ? value as Partial<KerrPolarizationOrientationBasisResponseV422> : null; if (!source || source.version !== KERR_ORIENTATION_BASIS_RESPONSE_VERSION_V422) throw new Error("v422-response-version"); if (source.available === true && source.reason === "ready" && source.summary) return Object.freeze({ ...source, summary: parseKerrPolarizationOrientationBasisSummaryV422(source.summary) }) as KerrPolarizationOrientationBasisResponseV422; if (source.available === false && source.summary === null && ["lite-boundary", "local-shadow-only", "evidence-corrupt", "request-failed"].includes(source.reason ?? "")) return source as KerrPolarizationOrientationBasisResponseV422; throw new Error("v422-response-identity"); }
export function serializeKerrPolarizationOrientationBasisCsvV422(view: KerrPolarizationOrientationBasisViewV422): string { const header = ["ray_index", "ray_id", "spin_a", "authority_evpa_deg", "continuous_pixel_x_fits1", "continuous_pixel_y_fits1", "orientation_q_hat", "orientation_u_hat", "orientation_available", "stokes_measurement_available", "stokes_I", "stokes_Q", "stokes_U", "stokes_V", "normalized_Q", "normalized_U", "linear_polarization_fraction", "polarization_amplitude", "nearest_pixel_assignment_allowed", "interpolation_allowed"]; const rows = view.rows.map((row) => [row.rayIndex, row.rayId, row.spinA, row.authorityEvpaDeg, row.continuousCoordinate.pixelX, row.continuousCoordinate.pixelY, row.orientationBasis.qHat, row.orientationBasis.uHat, row.applicabilityMask.orientationAvailable, row.applicabilityMask.stokesMeasurementAvailable, "", "", "", "", "", "", "", "", row.nearestPixelAssignmentAllowed, row.interpolationAllowed]); return `${[header, ...rows].map((row) => row.join(",")).join("\n")}\n`; }
