"use client";
import { acquireAtlasResource } from "./atlasResourceLifecycle"; import { parseKerrScienceBandContrastArtifactV348, type KerrScienceBandContrastArtifactV348 } from "./kerrScienceBandContrastV348";
export const KERR_SCIENCE_BAND_CONTRAST_CLIENT_VERSION_V348 = "v348-kerr-science-band-contrast-client-v1" as const; export type KerrScienceBandContrastClientSnapshotV348 = Readonly<{ version: typeof KERR_SCIENCE_BAND_CONTRAST_CLIENT_VERSION_V348; cacheEntries: number; inFlightCount: number; referenceCount: number; fetchCount: number; boundary: "preview-intent-single-flight-exact-response-sha-bounded-json-release-baseline" }>; export type AcquiredKerrScienceBandContrastV348 = Readonly<{ artifact: KerrScienceBandContrastArtifactV348; release: () => void }>;
type Entry = { promise: Promise<Readonly<{ artifact: KerrScienceBandContrastArtifactV348; bytes: Uint8Array; responseSha256: string }>>; artifact: KerrScienceBandContrastArtifactV348 | null; pending: number; references: number; releaseCache: (() => void) | null }; let entry: Entry | null = null; let fetchCount = 0; const LIMIT = 64 * 1024;
function canonicalize(value: unknown): unknown { if (Array.isArray(value)) return value.map(canonicalize); if (!value || typeof value !== "object") return value; return Object.fromEntries(Object.entries(value as Record<string, unknown>).filter(([key]) => !["generatedAt", "artifactSha256"].includes(key)).sort(([left], [right]) => left.localeCompare(right)).map(([key, item]) => [key, canonicalize(item)])); } async function exactSha(bytes: Uint8Array | string): Promise<string> { const source = typeof bytes === "string" ? new TextEncoder().encode(bytes) : bytes; const digest = await crypto.subtle.digest("SHA-256", source.slice().buffer); return Array.from(new Uint8Array(digest), (value) => value.toString(16).padStart(2, "0")).join(""); }
async function load(): Promise<Readonly<{ artifact: KerrScienceBandContrastArtifactV348; bytes: Uint8Array; responseSha256: string }>> { fetchCount += 1; const response = await fetch("/api/atlas/relativity-evidence/v348/diagnostic", { cache: "no-store" }); const length = Number(response.headers.get("content-length")); const etag = response.headers.get("etag")?.replaceAll('"', "") ?? ""; if (!response.ok || response.headers.get("content-type")?.split(";", 1)[0] !== "application/json" || !Number.isSafeInteger(length) || length <= 0 || length > LIMIT || response.headers.get("x-atlas-band-contrast") !== "v348") throw new Error("v348-diagnostic-response-identity"); const bytes = new Uint8Array(await response.arrayBuffer()); if (bytes.byteLength !== length || await exactSha(bytes) !== etag) throw new Error("v348-diagnostic-response-sha"); const artifact = parseKerrScienceBandContrastArtifactV348(JSON.parse(new TextDecoder().decode(bytes))); if (await exactSha(JSON.stringify(canonicalize(artifact))) !== artifact.artifactSha256) throw new Error("v348-diagnostic-canonical-sha"); return { artifact, bytes, responseSha256: etag }; }
function cleanup(current: Entry): void { if (current.pending !== 0 || current.references !== 0) return; current.releaseCache?.(); current.releaseCache = null; current.artifact = null; if (entry === current) entry = null; }
function getEntry(): Entry { if (entry) return entry; const current: Entry = { promise: undefined as unknown as Entry["promise"], artifact: null, pending: 0, references: 0, releaseCache: null }; current.promise = load().then((result) => { current.artifact = result.artifact; current.releaseCache = acquireAtlasResource("typed-array-cache", "relativity-lab", "v348:band-contrast:verified-json", { owner: "v348-band-contrast", estimatedBytes: result.bytes.byteLength, contentSha256: result.responseSha256, manifestSha256: result.artifact.artifactSha256 }); return result; }).catch((error: unknown) => { if (entry === current) entry = null; throw error; }); entry = current; return current; }
export async function acquireKerrScienceBandContrastV348(options: Readonly<{ signal?: AbortSignal }> = {}): Promise<AcquiredKerrScienceBandContrastV348> { if (options.signal?.aborted) throw new DOMException("Band contrast acquisition aborted", "AbortError"); const current = getEntry(); current.pending += 1; let result: Awaited<Entry["promise"]>; try { result = await current.promise; } finally { current.pending = Math.max(0, current.pending - 1); } if (options.signal?.aborted) { cleanup(current); throw new DOMException("Band contrast acquisition aborted", "AbortError"); } current.references += 1; let released = false; return Object.freeze({ artifact: result.artifact, release: () => { if (released) return; released = true; current.references = Math.max(0, current.references - 1); cleanup(current); } }); }
export function getKerrScienceBandContrastClientSnapshotV348(): KerrScienceBandContrastClientSnapshotV348 { return Object.freeze({ version: KERR_SCIENCE_BAND_CONTRAST_CLIENT_VERSION_V348, cacheEntries: entry ? 1 : 0, inFlightCount: entry && entry.artifact == null ? 1 : 0, referenceCount: entry?.references ?? 0, fetchCount, boundary: "preview-intent-single-flight-exact-response-sha-bounded-json-release-baseline" }); }
export function resetKerrScienceBandContrastClientV348ForTests(): void { if (entry && (entry.pending !== 0 || entry.references !== 0)) throw new Error("v348-reset-with-live-consumer"); entry?.releaseCache?.(); entry = null; fetchCount = 0; }
