"use client";
import { acquireAtlasResource } from "./atlasResourceLifecycle";
import { parseKerrBlindAuthorityReviewApiV547, type KerrBlindAuthorityReviewArtifactV547 } from "./kerrBlindAuthorityReviewV547";
type SnapshotV547 = Readonly<{ status: "idle" | "loading" | "ready" | "unavailable"; reason: string | null; requestCount: 0 | 1; responseBytes: number; summary: KerrBlindAuthorityReviewArtifactV547 | null }>;
const INITIAL: SnapshotV547 = Object.freeze({ status: "idle", reason: null, requestCount: 0, responseBytes: 0, summary: null }), listeners = new Set<() => void>(); let snapshot = INITIAL; let requestPromise: Promise<KerrBlindAuthorityReviewArtifactV547> | null = null; const publish = (next: SnapshotV547) => { snapshot = Object.freeze(next); listeners.forEach((listener) => listener()); };
export function loadKerrBlindAuthorityReviewSummaryV547(): Promise<KerrBlindAuthorityReviewArtifactV547> { if (requestPromise) return requestPromise; publish({ status: "loading", reason: null, requestCount: 1, responseBytes: 0, summary: null }); requestPromise = fetch("/api/atlas/relativity-evidence/v547/blind-authority-review", { cache: "no-store" }).then(async (response) => { const body = await response.text(), responseBytes = new TextEncoder().encode(body).byteLength; if (responseBytes > 128 * 1024) throw new Error("response-too-large"); const api = parseKerrBlindAuthorityReviewApiV547(JSON.parse(body)); if (!response.ok || !api.available || !api.summary) throw new Error(`v547-blind-review-${api.reason}`); publish({ status: "ready", reason: null, requestCount: 1, responseBytes, summary: api.summary }); return api.summary; }).catch((error: unknown) => { publish({ status: "unavailable", reason: error instanceof Error ? error.message : "request-failed", requestCount: 1, responseBytes: snapshot.responseBytes, summary: null }); throw error; }); return requestPromise; }
export const getKerrBlindAuthorityReviewSnapshotV547 = () => snapshot;
export function subscribeKerrBlindAuthorityReviewV547(listener: () => void): () => void { listeners.add(listener); const release = acquireAtlasResource("subscription", "relativity-lab", "v547-blind-authority-review", { owner: "v547-blind-authority-review", estimatedBytes: 0 }); let done = false; return () => { if (done) return; done = true; listeners.delete(listener); release(); }; }
export function getKerrBlindAuthorityReviewTelemetryV547() { return Object.freeze({ listenerCount: listeners.size, requestCount: snapshot.requestCount, status: snapshot.status }); }
export function resetKerrBlindAuthorityReviewClientForTestsV547(): void { if (listeners.size) throw new Error("v547-listener-leak"); snapshot = INITIAL; requestPromise = null; }
