"use client";
import { acquireAtlasResource } from "./atlasResourceLifecycle";
import { parseKerrObservationAuthorityJoinApiV553, type KerrObservationAuthorityJoinApiV553, type KerrObservationAuthorityJoinArtifactV553 } from "./kerrObservationAuthorityJoinV553";
export type KerrObservationAuthorityJoinSnapshotV553 = Readonly<{ status: "idle" | "loading" | "ready" | "unavailable"; reason: string | null; requestCount: 0 | 1; responseBytes: number; summary: KerrObservationAuthorityJoinArtifactV553 | null }>;
const INITIAL: KerrObservationAuthorityJoinSnapshotV553 = Object.freeze({ status: "idle", reason: null, requestCount: 0, responseBytes: 0, summary: null }); const listeners = new Set<() => void>(); let snapshot = INITIAL; let requestPromise: Promise<KerrObservationAuthorityJoinArtifactV553> | null = null; const publish = (next: KerrObservationAuthorityJoinSnapshotV553) => { snapshot = Object.freeze(next); listeners.forEach((listener) => listener()); };
export function loadKerrObservationAuthorityJoinSummaryV553(): Promise<KerrObservationAuthorityJoinArtifactV553> { if (requestPromise) return requestPromise; publish({ status: "loading", reason: null, requestCount: 1, responseBytes: 0, summary: null }); requestPromise = fetch("/api/atlas/relativity-evidence/v553/observation-authority-join", { cache: "no-store" }).then(async (response) => { const body = await response.text(), responseBytes = new TextEncoder().encode(body).byteLength; if (responseBytes > 128 * 1024) throw new Error("response-too-large"); const api: KerrObservationAuthorityJoinApiV553 = parseKerrObservationAuthorityJoinApiV553(JSON.parse(body)); if (!response.ok || !api.available || !api.summary) throw new Error(`v553-join-${api.reason}`); publish({ status: "ready", reason: null, requestCount: 1, responseBytes, summary: api.summary }); return api.summary; }).catch((error: unknown) => { publish({ status: "unavailable", reason: error instanceof Error ? error.message : "request-failed", requestCount: 1, responseBytes: snapshot.responseBytes, summary: null }); throw error; }); return requestPromise; }
export const getKerrObservationAuthorityJoinSnapshotV553 = () => snapshot;
export function subscribeKerrObservationAuthorityJoinV553(listener: () => void): () => void { listeners.add(listener); const release = acquireAtlasResource("subscription", "relativity-lab", "v553-observation-authority-join", { owner: "v553-observation-authority-join", estimatedBytes: 0 }); let done = false; return () => { if (done) return; done = true; listeners.delete(listener); release(); }; }
export const getKerrObservationAuthorityJoinTelemetryV553 = () => Object.freeze({ listenerCount: listeners.size, requestCount: snapshot.requestCount, status: snapshot.status });
export function resetKerrObservationAuthorityJoinClientForTestsV553(): void { if (listeners.size) throw new Error("v553-listener-leak"); snapshot = INITIAL; requestPromise = null; }
