import { createHash } from "node:crypto";
import { KERR_POLARIMETER_INVERSION_FIXTURE_V412, solveKerrPolarimeterInversionV412, type MatrixV412, type StokesVectorV412 } from "./kerrPolarimeterInversionV412";

export const KERR_POLARIMETER_SPECTRAL_RESPONSE_VERSION_V413 = "v413-kerr-polarimeter-spectral-response-v1" as const;
export const KERR_POLARIMETER_SPECTRAL_ARTIFACT_VERSION_V413 = "v413-kerr-polarimeter-spectral-response-artifact-v1" as const;
export const KERR_POLARIMETER_SPECTRAL_SUMMARY_VERSION_V413 = "v413-kerr-polarimeter-spectral-response-summary-v1" as const;
export const KERR_POLARIMETER_SPECTRAL_RESPONSE_API_VERSION_V413 = "v413-kerr-polarimeter-spectral-response-api-v1" as const;
export const KERR_POLARIMETER_INVERSION_ARTIFACT_SHA256_V412 = "4a7c2cada728e33f84ca464fb13f3cebf586b03adb2c394da5cddddcf4ea8a1a" as const;

export type KerrPolarimeterSpectralNodeV413 = Readonly<{ wavelengthM: number; responseMatrix: MatrixV412; responseElementCovariance: MatrixV412; rawArtifactSha256: string }>;
export type KerrPolarimeterSpectralIntervalV413 = Readonly<{ lowerWavelengthM: number; upperWavelengthM: number; adjacentCrossCovariance: MatrixV412; rawArtifactSha256: string }>;
export type KerrPolarimeterSpectralPackV413 = Readonly<{ version: typeof KERR_POLARIMETER_SPECTRAL_RESPONSE_VERSION_V413; sourceKind: "test-fixture" | "measured-import"; nodes: readonly KerrPolarimeterSpectralNodeV413[]; intervals: readonly KerrPolarimeterSpectralIntervalV413[]; interpolation: "piecewise-linear-response-with-explicit-adjacent-cross-covariance"; extrapolation: "forbidden" }>;
export type KerrPolarimeterSpectralSampleV413 = Readonly<{ wavelengthM: number; intervalIndex: number; interpolationWeight: number; reconstructedStokes: StokesVectorV412; responseConditionNumber: number; fisherConditionNumber: number; responseCovarianceMinimumEigenvalue: number; stokesRecoveryAbsoluteMaximum: number; calibrationJacobianFiniteDifferenceMaximum: number }>;
export type KerrPolarimeterSpectralViewV413 = Readonly<{ version: "v413-kerr-polarimeter-spectral-view-v1"; status: "qualified-spectral-interpolation-fixture-only-cross-covariance-required-for-measured-authority"; sourceKind: "test-fixture"; nodeCount: 5; intervalCount: 4; sampleCount: 33; wavelengthDomainM: readonly [4e-7, 8e-7]; samples: readonly KerrPolarimeterSpectralSampleV413[]; metrics: Readonly<{ maximumStokesRecoveryAbsolute: number; maximumResponseConditionNumber: number; maximumFisherConditionNumber: number; minimumInterpolatedCovarianceEigenvalue: number; maximumCalibrationJacobianFiniteDifference: number; maximumEndpointResponseDifference: number; maximumEndpointCovarianceDifference: number; crossCovarianceBlockMinimumEigenvalue: number }>; interpolation: KerrPolarimeterSpectralPackV413["interpolation"]; extrapolation: "forbidden"; uncertaintyBoundary: "cross-node-covariance-explicit-no-zero-correlation-assumption"; measuredPackPresent: false; measuredAuthorityGranted: false; publishable: false; boundary: "five-node-thirty-three-sample-fixture-validation-no-measured-spectral-response-authority" }>;
export type KerrPolarimeterSpectralArtifactV413 = Readonly<{ version: typeof KERR_POLARIMETER_SPECTRAL_ARTIFACT_VERSION_V413; generatedAt: string; status: KerrPolarimeterSpectralViewV413["status"]; source: Readonly<{ v412InversionArtifactSha256: typeof KERR_POLARIMETER_INVERSION_ARTIFACT_SHA256_V412; pythonOracleArtifactSha256: string }>; pack: KerrPolarimeterSpectralPackV413; view: KerrPolarimeterSpectralViewV413; oracleComparison: Readonly<{ maximumResponseAbsolute: number; maximumCovarianceAbsolute: number; maximumStokesAbsolute: number; maximumConditionNumberRelative: number }>; deterministicReplay: true; measuredPackPresent: false; measuredAuthorityGranted: false; networkAttempted: false; denseShardExecuted: false; browserQualification: "not-run"; boundary: "spectral-interpolation-and-cross-covariance-fixture-qualified-measured-authority-unavailable"; artifactSha256: string }>;
export type KerrPolarimeterSpectralSummaryV413 = Readonly<{ version: typeof KERR_POLARIMETER_SPECTRAL_SUMMARY_VERSION_V413; status: KerrPolarimeterSpectralViewV413["status"]; artifactSha256: string; v412InversionArtifactSha256: typeof KERR_POLARIMETER_INVERSION_ARTIFACT_SHA256_V412; nodeCount: 5; intervalCount: 4; sampleCount: 33; wavelengthDomainM: readonly [4e-7, 8e-7]; metrics: KerrPolarimeterSpectralViewV413["metrics"]; oracleComparison: KerrPolarimeterSpectralArtifactV413["oracleComparison"]; extrapolation: "forbidden"; measuredPackPresent: false; measuredAuthorityGranted: false; fullArtifactAvailable: true; browserQualification: "not-run"; boundary: "summary-only-no-thirty-three-sample-or-matrix-arrays-in-react-state" }>;
export type KerrPolarimeterSpectralResponseApiV413 = Readonly<{ version: typeof KERR_POLARIMETER_SPECTRAL_RESPONSE_API_VERSION_V413; available: boolean; reason: "ready" | "lite-boundary" | "local-shadow-only" | "evidence-corrupt" | "request-failed"; summary: KerrPolarimeterSpectralSummaryV413 | null }>;

const SHA = /^[a-f0-9]{64}$/;
const finiteMatrix = (matrix: MatrixV412, rows: number, columns: number) => Array.isArray(matrix) && matrix.length === rows && matrix.every((row) => Array.isArray(row) && row.length === columns && row.every(Number.isFinite));
const freezeMatrix = (matrix: MatrixV412): MatrixV412 => Object.freeze(matrix.map((row) => Object.freeze([...row])));
const transpose = (matrix: MatrixV412): number[][] => matrix[0].map((_, column) => matrix.map((row) => row[column]));
const add = (...matrices: MatrixV412[]): number[][] => matrices[0].map((row, rowIndex) => row.map((_, columnIndex) => matrices.reduce((sum, matrix) => sum + matrix[rowIndex][columnIndex], 0)));
const scale = (matrix: MatrixV412, factor: number): number[][] => matrix.map((row) => row.map((value) => value * factor));
const maximumDifference = (left: MatrixV412, right: MatrixV412) => Math.max(...left.flatMap((row, rowIndex) => row.map((value, columnIndex) => Math.abs(value - right[rowIndex][columnIndex]))));
const matrixVector = (matrix: MatrixV412, vector: StokesVectorV412): StokesVectorV412 => Object.freeze(matrix.map((row) => row.reduce((sum, value, index) => sum + value * vector[index], 0)) as [number, number, number, number]);

function symmetricEigenvalues(matrix: MatrixV412): number[] { const values = matrix.map((row) => [...row]); const size = values.length; for (let iteration = 0; iteration < size * size * 128; iteration += 1) { let p = 0; let q = 1; let maximum = 0; for (let row = 0; row < size; row += 1) for (let column = row + 1; column < size; column += 1) if (Math.abs(values[row][column]) > maximum) { maximum = Math.abs(values[row][column]); p = row; q = column; } if (maximum < 1e-16) break; const angle = 0.5 * Math.atan2(2 * values[p][q], values[q][q] - values[p][p]), cosine = Math.cos(angle), sine = Math.sin(angle), app = values[p][p], aqq = values[q][q], apq = values[p][q]; values[p][p] = cosine * cosine * app - 2 * sine * cosine * apq + sine * sine * aqq; values[q][q] = sine * sine * app + 2 * sine * cosine * apq + cosine * cosine * aqq; values[p][q] = values[q][p] = 0; for (let index = 0; index < size; index += 1) if (index !== p && index !== q) { const aip = values[index][p], aiq = values[index][q]; values[index][p] = values[p][index] = cosine * aip - sine * aiq; values[index][q] = values[q][index] = sine * aip + cosine * aiq; } } return values.map((row, index) => row[index]).sort((left, right) => right - left); }
const blockCovariance = (lower: MatrixV412, upper: MatrixV412, cross: MatrixV412): number[][] => [...lower.map((row, index) => [...row, ...cross[index]]), ...upper.map((row, index) => [...transpose(cross)[index], ...row])];

export function parseKerrPolarimeterSpectralPackV413(value: unknown): KerrPolarimeterSpectralPackV413 { const source = value && typeof value === "object" && !Array.isArray(value) ? value as Partial<KerrPolarimeterSpectralPackV413> : null; if (!source || source.version !== KERR_POLARIMETER_SPECTRAL_RESPONSE_VERSION_V413 || !["test-fixture", "measured-import"].includes(source.sourceKind ?? "") || source.interpolation !== "piecewise-linear-response-with-explicit-adjacent-cross-covariance" || source.extrapolation !== "forbidden" || !Array.isArray(source.nodes) || source.nodes.length < 5 || source.nodes.length > 256 || !Array.isArray(source.intervals) || source.intervals.length !== source.nodes.length - 1) throw new Error("v413-pack-identity"); const nodes = source.nodes, intervals = source.intervals; let previous = 0; nodes.forEach((node) => { if (!(node.wavelengthM > previous) || !finiteMatrix(node.responseMatrix, 4, 4) || !finiteMatrix(node.responseElementCovariance, 16, 16) || !SHA.test(node.rawArtifactSha256) || symmetricEigenvalues(node.responseElementCovariance)[15] < -1e-12) throw new Error("v413-node"); previous = node.wavelengthM; }); intervals.forEach((interval, index) => { if (interval.lowerWavelengthM !== nodes[index].wavelengthM || interval.upperWavelengthM !== nodes[index + 1].wavelengthM || !finiteMatrix(interval.adjacentCrossCovariance, 16, 16) || !SHA.test(interval.rawArtifactSha256) || symmetricEigenvalues(blockCovariance(nodes[index].responseElementCovariance, nodes[index + 1].responseElementCovariance, interval.adjacentCrossCovariance))[31] < -1e-12) throw new Error("v413-cross-covariance"); }); return value as KerrPolarimeterSpectralPackV413; }

export function interpolateParsedKerrPolarimeterResponseMatrixV413(pack: KerrPolarimeterSpectralPackV413, wavelengthM: number) { if (!Number.isFinite(wavelengthM) || wavelengthM < pack.nodes[0].wavelengthM || wavelengthM > pack.nodes[pack.nodes.length - 1].wavelengthM) throw new Error("v413-extrapolation-forbidden"); let intervalIndex = pack.intervals.findIndex((interval) => wavelengthM >= interval.lowerWavelengthM && wavelengthM <= interval.upperWavelengthM); if (intervalIndex < 0) intervalIndex = pack.intervals.length - 1; const lower = pack.nodes[intervalIndex], upper = pack.nodes[intervalIndex + 1], weight = (wavelengthM - lower.wavelengthM) / (upper.wavelengthM - lower.wavelengthM), lowerWeight = 1 - weight; return Object.freeze({ wavelengthM, intervalIndex, interpolationWeight: weight, responseMatrix: freezeMatrix(add(scale(lower.responseMatrix, lowerWeight), scale(upper.responseMatrix, weight))) }); }
export function interpolateParsedKerrPolarimeterSpectralResponseV413(pack: KerrPolarimeterSpectralPackV413, wavelengthM: number) { const response = interpolateParsedKerrPolarimeterResponseMatrixV413(pack, wavelengthM), lower = pack.nodes[response.intervalIndex], upper = pack.nodes[response.intervalIndex + 1], interval = pack.intervals[response.intervalIndex], weight = response.interpolationWeight, lowerWeight = 1 - weight, responseElementCovariance = add(scale(lower.responseElementCovariance, lowerWeight ** 2), scale(upper.responseElementCovariance, weight ** 2), scale(interval.adjacentCrossCovariance, lowerWeight * weight), scale(transpose(interval.adjacentCrossCovariance), lowerWeight * weight)), minimumEigenvalue = symmetricEigenvalues(responseElementCovariance)[15]; if (minimumEigenvalue < -1e-12) throw new Error("v413-interpolated-covariance"); return Object.freeze({ ...response, responseElementCovariance: freezeMatrix(responseElementCovariance), responseCovarianceMinimumEigenvalue: minimumEigenvalue }); }
export function interpolateKerrPolarimeterSpectralResponseV413(packValue: unknown, wavelengthM: number) { return interpolateParsedKerrPolarimeterSpectralResponseV413(parseKerrPolarimeterSpectralPackV413(packValue), wavelengthM); }

const H = "b".repeat(64); const base = freezeMatrix([[0.5, 0.4, 0, 0], [0.5, -0.4, 0, 0], [0.5, 0, 0.4, 0.2], [0.5, 0, -0.4, 0.2]]);
const nodeMatrix = (nodeIndex: number): MatrixV412 => { const delta = nodeIndex - 2; const adjustments = [[0.005, 0.003, 0.001, 0], [-0.004, 0.002, -0.001, 0], [0.002, 0.001, -0.002, 0.0005], [-0.003, -0.001, -0.002, -0.0005]]; return freezeMatrix(base.map((row, rowIndex) => row.map((value, columnIndex) => value + delta * adjustments[rowIndex][columnIndex]))); };
const nodeCovariance = (nodeIndex: number): MatrixV412 => freezeMatrix(Array.from({ length: 16 }, (_, row) => Array.from({ length: 16 }, (_, column) => row === column ? 1e-8 * (1 + nodeIndex * 0.05) * (1 + row * 0.01) : 0)));
export const KERR_POLARIMETER_SPECTRAL_FIXTURE_V413: KerrPolarimeterSpectralPackV413 = (() => { const nodes = Array.from({ length: 5 }, (_, index) => Object.freeze({ wavelengthM: 4e-7 + index * 1e-7, responseMatrix: nodeMatrix(index), responseElementCovariance: nodeCovariance(index), rawArtifactSha256: H })); const intervals = Array.from({ length: 4 }, (_, index) => Object.freeze({ lowerWavelengthM: nodes[index].wavelengthM, upperWavelengthM: nodes[index + 1].wavelengthM, adjacentCrossCovariance: freezeMatrix(Array.from({ length: 16 }, (_, row) => Array.from({ length: 16 }, (_, column) => row === column ? 0.2 * Math.sqrt(nodes[index].responseElementCovariance[row][row] * nodes[index + 1].responseElementCovariance[row][row]) : 0))), rawArtifactSha256: H })); return Object.freeze({ version: KERR_POLARIMETER_SPECTRAL_RESPONSE_VERSION_V413, sourceKind: "test-fixture" as const, nodes: Object.freeze(nodes), intervals: Object.freeze(intervals), interpolation: "piecewise-linear-response-with-explicit-adjacent-cross-covariance" as const, extrapolation: "forbidden" as const }); })();

export function createKerrPolarimeterSpectralViewV413(packValue: unknown): KerrPolarimeterSpectralViewV413 { const pack = parseKerrPolarimeterSpectralPackV413(packValue); if (pack.sourceKind !== "test-fixture" || pack.nodes.length !== 5 || pack.nodes[0].wavelengthM !== 4e-7 || pack.nodes[4].wavelengthM !== 8e-7) throw new Error("v413-fixture-boundary"); const truth = Object.freeze([1, 0.08, -0.05, 0.01] as const); const samples: KerrPolarimeterSpectralSampleV413[] = []; let maximumEndpointResponseDifference = 0, maximumEndpointCovarianceDifference = 0, crossCovarianceBlockMinimumEigenvalue = Number.POSITIVE_INFINITY; pack.intervals.forEach((interval, index) => { crossCovarianceBlockMinimumEigenvalue = Math.min(crossCovarianceBlockMinimumEigenvalue, symmetricEigenvalues(blockCovariance(pack.nodes[index].responseElementCovariance, pack.nodes[index + 1].responseElementCovariance, interval.adjacentCrossCovariance))[31]); }); for (let index = 0; index < 33; index += 1) { const wavelengthM = 4e-7 + index * (4e-7 / 32); const interpolated = interpolateParsedKerrPolarimeterSpectralResponseV413(pack, wavelengthM); const observationVector = matrixVector(interpolated.responseMatrix, truth); const inversion = solveKerrPolarimeterInversionV412({ sourceKind: "test-fixture", responseMatrix: interpolated.responseMatrix, observationVector, observationCovariance: KERR_POLARIMETER_INVERSION_FIXTURE_V412.observationCovariance, responseElementCovariance: interpolated.responseElementCovariance }); const stokesRecoveryAbsoluteMaximum = Math.max(...inversion.reconstructedStokes.map((value, component) => Math.abs(value - truth[component]))); samples.push(Object.freeze({ wavelengthM, intervalIndex: interpolated.intervalIndex, interpolationWeight: interpolated.interpolationWeight, reconstructedStokes: inversion.reconstructedStokes, responseConditionNumber: inversion.metrics.responseConditionNumber, fisherConditionNumber: inversion.metrics.fisherConditionNumber, responseCovarianceMinimumEigenvalue: interpolated.responseCovarianceMinimumEigenvalue, stokesRecoveryAbsoluteMaximum, calibrationJacobianFiniteDifferenceMaximum: inversion.metrics.calibrationJacobianFiniteDifferenceMaximum })); if (index % 8 === 0) { const nodeIndex = index / 8; maximumEndpointResponseDifference = Math.max(maximumEndpointResponseDifference, maximumDifference(interpolated.responseMatrix, pack.nodes[nodeIndex].responseMatrix)); maximumEndpointCovarianceDifference = Math.max(maximumEndpointCovarianceDifference, maximumDifference(interpolated.responseElementCovariance, pack.nodes[nodeIndex].responseElementCovariance)); } }
  const metrics = Object.freeze({ maximumStokesRecoveryAbsolute: Math.max(...samples.map((sample) => sample.stokesRecoveryAbsoluteMaximum)), maximumResponseConditionNumber: Math.max(...samples.map((sample) => sample.responseConditionNumber)), maximumFisherConditionNumber: Math.max(...samples.map((sample) => sample.fisherConditionNumber)), minimumInterpolatedCovarianceEigenvalue: Math.min(...samples.map((sample) => sample.responseCovarianceMinimumEigenvalue)), maximumCalibrationJacobianFiniteDifference: Math.max(...samples.map((sample) => sample.calibrationJacobianFiniteDifferenceMaximum)), maximumEndpointResponseDifference, maximumEndpointCovarianceDifference, crossCovarianceBlockMinimumEigenvalue }); if (metrics.maximumStokesRecoveryAbsolute >= 1e-10 || metrics.maximumResponseConditionNumber >= 1e4 || metrics.maximumFisherConditionNumber >= 1e8 || metrics.minimumInterpolatedCovarianceEigenvalue < -1e-12 || metrics.maximumCalibrationJacobianFiniteDifference >= 1e-8 || maximumEndpointResponseDifference !== 0 || maximumEndpointCovarianceDifference !== 0 || crossCovarianceBlockMinimumEigenvalue < -1e-12) throw new Error(`v413-gate:${JSON.stringify(metrics)}`); return Object.freeze({ version: "v413-kerr-polarimeter-spectral-view-v1", status: "qualified-spectral-interpolation-fixture-only-cross-covariance-required-for-measured-authority", sourceKind: "test-fixture", nodeCount: 5, intervalCount: 4, sampleCount: 33, wavelengthDomainM: Object.freeze([4e-7, 8e-7] as const), samples: Object.freeze(samples), metrics, interpolation: pack.interpolation, extrapolation: "forbidden", uncertaintyBoundary: "cross-node-covariance-explicit-no-zero-correlation-assumption", measuredPackPresent: false, measuredAuthorityGranted: false, publishable: false, boundary: "five-node-thirty-three-sample-fixture-validation-no-measured-spectral-response-authority" }); }

const canonicalize = (value: unknown): unknown => Array.isArray(value) ? value.map(canonicalize) : !value || typeof value !== "object" ? value : Object.fromEntries(Object.entries(value as Record<string, unknown>).filter(([key]) => !["generatedAt", "artifactSha256"].includes(key)).sort(([a], [b]) => a.localeCompare(b)).map(([key, entry]) => [key, canonicalize(entry)])); export const canonicalShaV413 = (value: unknown) => createHash("sha256").update(JSON.stringify(canonicalize(value))).digest("hex");
export function parseKerrPolarimeterSpectralArtifactV413(value: unknown): KerrPolarimeterSpectralArtifactV413 { const source = value && typeof value === "object" && !Array.isArray(value) ? value as Partial<KerrPolarimeterSpectralArtifactV413> : null; if (!source || source.version !== KERR_POLARIMETER_SPECTRAL_ARTIFACT_VERSION_V413 || source.status !== "qualified-spectral-interpolation-fixture-only-cross-covariance-required-for-measured-authority" || source.source?.v412InversionArtifactSha256 !== KERR_POLARIMETER_INVERSION_ARTIFACT_SHA256_V412 || !SHA.test(source.source.pythonOracleArtifactSha256) || !source.pack || parseKerrPolarimeterSpectralPackV413(source.pack) !== source.pack || source.view?.sampleCount !== 33 || source.view.nodeCount !== 5 || source.view.intervalCount !== 4 || source.view.samples?.length !== 33 || source.view.measuredAuthorityGranted !== false || Math.max(...Object.values(source.oracleComparison ?? {})) >= 1e-10 || source.deterministicReplay !== true || source.measuredPackPresent !== false || source.measuredAuthorityGranted !== false || source.networkAttempted !== false || source.denseShardExecuted !== false || source.browserQualification !== "not-run" || source.boundary !== "spectral-interpolation-and-cross-covariance-fixture-qualified-measured-authority-unavailable" || !SHA.test(source.artifactSha256 ?? "")) throw new Error("v413-artifact-identity"); return value as KerrPolarimeterSpectralArtifactV413; }
export function createKerrPolarimeterSpectralSummaryV413(value: unknown): KerrPolarimeterSpectralSummaryV413 { const artifact = parseKerrPolarimeterSpectralArtifactV413(value); return Object.freeze({ version: KERR_POLARIMETER_SPECTRAL_SUMMARY_VERSION_V413, status: artifact.status, artifactSha256: artifact.artifactSha256, v412InversionArtifactSha256: artifact.source.v412InversionArtifactSha256, nodeCount: 5 as const, intervalCount: 4 as const, sampleCount: 33 as const, wavelengthDomainM: artifact.view.wavelengthDomainM, metrics: artifact.view.metrics, oracleComparison: artifact.oracleComparison, extrapolation: "forbidden" as const, measuredPackPresent: false as const, measuredAuthorityGranted: false as const, fullArtifactAvailable: true as const, browserQualification: "not-run" as const, boundary: "summary-only-no-thirty-three-sample-or-matrix-arrays-in-react-state" as const }); }
export function parseKerrPolarimeterSpectralSummaryV413(value: unknown): KerrPolarimeterSpectralSummaryV413 { const source = value && typeof value === "object" && !Array.isArray(value) ? value as Partial<KerrPolarimeterSpectralSummaryV413> : null; if (!source || source.version !== KERR_POLARIMETER_SPECTRAL_SUMMARY_VERSION_V413 || source.status !== "qualified-spectral-interpolation-fixture-only-cross-covariance-required-for-measured-authority" || !SHA.test(source.artifactSha256 ?? "") || source.v412InversionArtifactSha256 !== KERR_POLARIMETER_INVERSION_ARTIFACT_SHA256_V412 || source.nodeCount !== 5 || source.intervalCount !== 4 || source.sampleCount !== 33 || source.wavelengthDomainM?.join(",") !== "4e-7,8e-7" || !source.metrics || !source.oracleComparison || source.extrapolation !== "forbidden" || source.measuredPackPresent !== false || source.measuredAuthorityGranted !== false || source.fullArtifactAvailable !== true || source.browserQualification !== "not-run" || source.boundary !== "summary-only-no-thirty-three-sample-or-matrix-arrays-in-react-state" || Object.hasOwn(source, "samples") || Object.hasOwn(source, "view")) throw new Error("v413-summary-identity"); return value as KerrPolarimeterSpectralSummaryV413; }
export function parseKerrPolarimeterSpectralResponseApiV413(value: unknown): KerrPolarimeterSpectralResponseApiV413 { const source = value && typeof value === "object" && !Array.isArray(value) ? value as Partial<KerrPolarimeterSpectralResponseApiV413> : null; if (!source || source.version !== KERR_POLARIMETER_SPECTRAL_RESPONSE_API_VERSION_V413) throw new Error("v413-response-version"); if (source.available === true && source.reason === "ready" && source.summary) return { version: KERR_POLARIMETER_SPECTRAL_RESPONSE_API_VERSION_V413, available: true, reason: "ready", summary: parseKerrPolarimeterSpectralSummaryV413(source.summary) }; if (source.available === false && source.summary === null && ["lite-boundary", "local-shadow-only", "evidence-corrupt", "request-failed"].includes(source.reason ?? "")) return source as KerrPolarimeterSpectralResponseApiV413; throw new Error("v413-response-identity"); }
