"use client";
import { acquireAtlasResource } from "./atlasResourceLifecycle";
import { parseKerrLicenseConfirmationAdmissionApiV551, type KerrLicenseConfirmationAdmissionArtifactV551 } from "./kerrLicenseConfirmationAdmissionV551";
type SnapshotV551 = Readonly<{ status: "idle" | "loading" | "ready" | "unavailable"; reason: string | null; requestCount: 0 | 1; responseBytes: number; summary: KerrLicenseConfirmationAdmissionArtifactV551 | null }>;
const INITIAL: SnapshotV551 = Object.freeze({ status: "idle", reason: null, requestCount: 0, responseBytes: 0, summary: null }), listeners = new Set<() => void>(); let snapshot = INITIAL; let requestPromise: Promise<KerrLicenseConfirmationAdmissionArtifactV551> | null = null; const publish = (next: SnapshotV551) => { snapshot = Object.freeze(next); listeners.forEach((listener) => listener()); };
export function loadKerrLicenseConfirmationSummaryV551(): Promise<KerrLicenseConfirmationAdmissionArtifactV551> { if (requestPromise) return requestPromise; publish({ status: "loading", reason: null, requestCount: 1, responseBytes: 0, summary: null }); requestPromise = fetch("/api/atlas/relativity-evidence/v551/license-confirmation", { cache: "no-store" }).then(async (response) => { const body = await response.text(), responseBytes = new TextEncoder().encode(body).byteLength; if (responseBytes > 128 * 1024) throw new Error("response-too-large"); const api = parseKerrLicenseConfirmationAdmissionApiV551(JSON.parse(body)); if (!response.ok || !api.available || !api.summary) throw new Error(`v551-license-${api.reason}`); publish({ status: "ready", reason: null, requestCount: 1, responseBytes, summary: api.summary }); return api.summary; }).catch((error: unknown) => { publish({ status: "unavailable", reason: error instanceof Error ? error.message : "request-failed", requestCount: 1, responseBytes: snapshot.responseBytes, summary: null }); throw error; }); return requestPromise; }
export const getKerrLicenseConfirmationSnapshotV551 = () => snapshot;
export function subscribeKerrLicenseConfirmationV551(listener: () => void): () => void { listeners.add(listener); const release = acquireAtlasResource("subscription", "relativity-lab", "v551-license-confirmation", { owner: "v551-license-confirmation", estimatedBytes: 0 }); let done = false; return () => { if (done) return; done = true; listeners.delete(listener); release(); }; }
export function getKerrLicenseConfirmationTelemetryV551() { return Object.freeze({ listenerCount: listeners.size, requestCount: snapshot.requestCount, status: snapshot.status }); }
export function resetKerrLicenseConfirmationClientForTestsV551(): void { if (listeners.size) throw new Error("v551-listener-leak"); snapshot = INITIAL; requestPromise = null; }
