export const KERR_RESPONSE_AWARE_PORTABLE_CRATE_VERSION_V539 = "v539-kerr-response-aware-portable-crate-v1" as const;
export const KERR_RESPONSE_AWARE_PORTABLE_CRATE_API_VERSION_V539 = "v539-kerr-response-aware-portable-crate-api-v1" as const;
export const KERR_RESPONSE_AWARE_PORTABLE_CRATE_HUD_PROFILE_ID_V539 = "science-cinematic-v8r8-v539" as const;
export const KERR_RESPONSE_AWARE_PORTABLE_CRATE_MEMBER_PATHS_V539 = Object.freeze(["README.md", "data/column-schema.csv", "data/response-aware-sparse-table.fits", "manifest-sha256.txt", "metadata/v537-fits-atlas.json", "metadata/v538-column-schema-atlas.json", "metadata/v538-evidence.json", "metadata/v538-pointer.json", "ro-crate-metadata.json"] as const);
export type KerrResponseAwarePortableCrateMemberPathV539 = typeof KERR_RESPONSE_AWARE_PORTABLE_CRATE_MEMBER_PATHS_V539[number];
export type KerrResponseAwarePortableCrateMemberV539 = Readonly<{ path: KerrResponseAwarePortableCrateMemberPathV539; sha256: string; bytes: number; mediaType: "text/plain" | "text/csv" | "application/fits" | "application/json"; role: "readme" | "science-data" | "integrity-manifest" | "provenance" | "descriptor" }>;
export type KerrResponseAwarePortableCrateArtifactV539 = Readonly<{
  version: typeof KERR_RESPONSE_AWARE_PORTABLE_CRATE_VERSION_V539;
  generatedAt: string;
  status: "portable-content-addressed-sparse-science-crate-qualified";
  source: Readonly<{ v537ArtifactSha256: string; v537FitsFileSha256: string; v538ArtifactSha256: string; v538EvidenceSha256: string; v538PointerSha256: string }>;
  contract: Readonly<{ deterministicZipRequired: true; fixedMemberOrderRequired: true; fixedTimestampRequired: true; fixedPermissionsRequired: true; storedCompressionRequired: true; memberSha256Required: true; manifestReplayRequired: true; roCrateMetadataSelfAuditRequired: true; absolutePathsForbidden: true; networkDependencyForbidden: true }>;
  crate: Readonly<{ path: "dist/science/kerr-response-aware-portable-crate-v539/orbit-atlas-kerr-response-aware-v539.zip"; fileSha256: string; bytes: number; memberCount: 9; manifestCoveredMemberCount: 8; totalUncompressedBytes: number; compression: "stored"; fixedTimestamp: "2026-08-02T00:00:00"; fixedMode: "100644"; abByteIdentical: true; zipCrcReplayQualified: true; manifestReplayQualified: true; roCrateContext: "https://w3id.org/ro/crate/1.1/context"; roCrateSelfAuditQualified: true }>;
  members: readonly KerrResponseAwarePortableCrateMemberV539[];
  counts: Readonly<{ scienceDataMemberCount: 2; provenanceMemberCount: 4; descriptorMemberCount: 1; readmeMemberCount: 1; integrityManifestMemberCount: 1; fitsBinaryTableCount: 1; fitsImageHduCount: 0; pixelSampleCount: 0; rasterPixelCount: 0; physicalUncertaintyValueCount: 0; pngImageCount: 0 }>;
  qualification: Readonly<{ portableCrateQualified: true; deterministicReplayQualified: true; memberIntegrityQualified: true; offlineReplayQualified: true; metadataGraphSelfAuditQualified: true; scienceImageQualified: false; physicalUncertaintyQualified: false; productionPackageQualified: false }>;
  boundary: Readonly<{ crateIsLocalShadowResearchArtifact: true; crateIsNotProductionPackage: true; crateDoesNotCreateNewMeasurement: true; crateDoesNotCreatePixelSamples: true; measuredCalibrationFiles: 0; requiredMeasuredCalibrationFiles: 6; sciencePayloadMutationAllowed: false; cinematicScienceWritebackAllowed: false; networkAttempted: false; denseCampaignStatus: "incomplete-0-of-49"; browserQualification: "not-run"; formalProductPointer: "v263"; formalDefaultKernel: "legacy-eih-1pn" }>;
  sourceManifest: readonly Readonly<{ path: string; sha256: string }>[];
  sourceSha256: string;
  artifactSha256: string;
}>;
export type KerrResponseAwarePortableCrateSummaryV539 = Omit<KerrResponseAwarePortableCrateArtifactV539, "generatedAt" | "sourceManifest" | "sourceSha256">;
export type KerrResponseAwarePortableCrateApiV539 = Readonly<{ version: typeof KERR_RESPONSE_AWARE_PORTABLE_CRATE_API_VERSION_V539; available: boolean; reason: "ready" | "lite-boundary" | "local-shadow-only" | "evidence-corrupt"; summary: KerrResponseAwarePortableCrateSummaryV539 | null }>;
export type KerrResponseAwarePortableCrateHudModeV539 = "science" | "cinematic";

const SHA = /^[a-f0-9]{64}$/;
const TRANSIENT = new Set(["generatedAt", "artifactSha256", "payloadSha256", "evidenceSha256", "pointerSha256", "stageChainSha256", "columnSha256"]);
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const compare = (left: string, right: string) => left < right ? -1 : left > right ? 1 : 0;
const canonicalize = (value: unknown): unknown => Array.isArray(value) ? value.map(canonicalize) : !isRecord(value) ? value : Object.fromEntries(Object.entries(value).filter(([key]) => !TRANSIENT.has(key)).sort(([left], [right]) => compare(left, right)).map(([key, entry]) => [key, canonicalize(entry)]));
export const canonicalKerrResponseAwarePortableCrateV539 = (value: unknown) => JSON.stringify(canonicalize(value));

function validCore(value: Partial<KerrResponseAwarePortableCrateArtifactV539>): boolean {
  const crate = value.crate;
  const counts = value.counts;
  const boundary = value.boundary;
  return value.version === KERR_RESPONSE_AWARE_PORTABLE_CRATE_VERSION_V539 && value.status === "portable-content-addressed-sparse-science-crate-qualified"
    && Object.values(value.source ?? {}).length === 5 && Object.values(value.source ?? {}).every((entry) => SHA.test(entry))
    && value.contract?.deterministicZipRequired === true && value.contract.fixedMemberOrderRequired === true && value.contract.fixedTimestampRequired === true && value.contract.fixedPermissionsRequired === true
    && value.contract.storedCompressionRequired === true && value.contract.memberSha256Required === true && value.contract.manifestReplayRequired === true && value.contract.roCrateMetadataSelfAuditRequired === true
    && value.contract.absolutePathsForbidden === true && value.contract.networkDependencyForbidden === true
    && crate?.path === "dist/science/kerr-response-aware-portable-crate-v539/orbit-atlas-kerr-response-aware-v539.zip" && SHA.test(crate.fileSha256)
    && Number.isSafeInteger(crate.bytes) && crate.bytes > 0 && crate.bytes <= 1024 * 1024 && crate.memberCount === 9 && crate.manifestCoveredMemberCount === 8
    && Number.isSafeInteger(crate.totalUncompressedBytes) && crate.totalUncompressedBytes > 0 && crate.compression === "stored" && crate.fixedTimestamp === "2026-08-02T00:00:00" && crate.fixedMode === "100644"
    && crate.abByteIdentical === true && crate.zipCrcReplayQualified === true && crate.manifestReplayQualified === true && crate.roCrateContext === "https://w3id.org/ro/crate/1.1/context" && crate.roCrateSelfAuditQualified === true
    && value.members?.length === 9 && value.members.every((member, index) => member.path === KERR_RESPONSE_AWARE_PORTABLE_CRATE_MEMBER_PATHS_V539[index] && SHA.test(member.sha256) && Number.isSafeInteger(member.bytes) && member.bytes > 0 && !member.path.startsWith("/") && !member.path.split("/").includes(".."))
    && value.members.reduce((sum, member) => sum + member.bytes, 0) === crate.totalUncompressedBytes
    && counts?.scienceDataMemberCount === 2 && counts.provenanceMemberCount === 4 && counts.descriptorMemberCount === 1 && counts.readmeMemberCount === 1 && counts.integrityManifestMemberCount === 1
    && counts.fitsBinaryTableCount === 1 && counts.fitsImageHduCount === 0 && counts.pixelSampleCount === 0 && counts.rasterPixelCount === 0 && counts.physicalUncertaintyValueCount === 0 && counts.pngImageCount === 0
    && value.qualification?.portableCrateQualified === true && value.qualification.deterministicReplayQualified === true && value.qualification.memberIntegrityQualified === true && value.qualification.offlineReplayQualified === true
    && value.qualification.metadataGraphSelfAuditQualified === true && value.qualification.scienceImageQualified === false && value.qualification.physicalUncertaintyQualified === false && value.qualification.productionPackageQualified === false
    && boundary?.crateIsLocalShadowResearchArtifact === true && boundary.crateIsNotProductionPackage === true && boundary.crateDoesNotCreateNewMeasurement === true && boundary.crateDoesNotCreatePixelSamples === true
    && boundary.measuredCalibrationFiles === 0 && boundary.requiredMeasuredCalibrationFiles === 6 && boundary.sciencePayloadMutationAllowed === false && boundary.cinematicScienceWritebackAllowed === false && boundary.networkAttempted === false
    && boundary.denseCampaignStatus === "incomplete-0-of-49" && boundary.browserQualification === "not-run" && boundary.formalProductPointer === "v263" && boundary.formalDefaultKernel === "legacy-eih-1pn"
    && SHA.test(value.artifactSha256 ?? "");
}
export function parseKerrResponseAwarePortableCrateArtifactV539(value: unknown): KerrResponseAwarePortableCrateArtifactV539 { if (!isRecord(value) || !validCore(value as Partial<KerrResponseAwarePortableCrateArtifactV539>)) throw new Error("v539-portable-crate-boundary"); const artifact = value as unknown as KerrResponseAwarePortableCrateArtifactV539; if (!Array.isArray(artifact.sourceManifest) || artifact.sourceManifest.some((entry) => !entry.path || !SHA.test(entry.sha256)) || !SHA.test(artifact.sourceSha256)) throw new Error("v539-portable-crate-manifest"); return artifact; }
export function createKerrResponseAwarePortableCrateSummaryV539(value: unknown): KerrResponseAwarePortableCrateSummaryV539 { const artifact = parseKerrResponseAwarePortableCrateArtifactV539(value); const summary = { ...artifact } as Record<string, unknown>; delete summary.generatedAt; delete summary.sourceManifest; delete summary.sourceSha256; return Object.freeze(summary) as unknown as KerrResponseAwarePortableCrateSummaryV539; }
export function parseKerrResponseAwarePortableCrateApiV539(value: unknown): KerrResponseAwarePortableCrateApiV539 { if (!isRecord(value) || value.version !== KERR_RESPONSE_AWARE_PORTABLE_CRATE_API_VERSION_V539 || typeof value.available !== "boolean" || !["ready", "lite-boundary", "local-shadow-only", "evidence-corrupt"].includes(String(value.reason))) throw new Error("v539-api-boundary"); if (value.available) { if (!isRecord(value.summary) || !validCore(value.summary as Partial<KerrResponseAwarePortableCrateArtifactV539>)) throw new Error("v539-api-summary"); } else if (value.summary !== null) throw new Error("v539-api-unavailable-summary"); return value as unknown as KerrResponseAwarePortableCrateApiV539; }

const scienceProfile = Object.freeze({ id: KERR_RESPONSE_AWARE_PORTABLE_CRATE_HUD_PROFILE_ID_V539, mode: "science" as const, panel: "#02080a", panelRaised: "#07131a", ink: "#effdff", muted: "#78959c", qualified: "#74f4c5", unavailable: "#ff91ad", localShadowOnly: true as const, defaultApplied: false as const, scienceBoundary: Object.freeze({ linearDisplay: true, bloomIntensity: 0, colorGradeIntensity: 0, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }), cinematicSeed: null as string | null });
const cinematicProfile = Object.freeze({ ...scienceProfile, mode: "cinematic" as const, panel: "#100907", panelRaised: "#1b130f", ink: "#fff7ea", muted: "#b09a84", qualified: "#8ff5ca", unavailable: "#ff96b2", scienceBoundary: Object.freeze({ linearDisplay: false, bloomIntensity: 0.05, colorGradeIntensity: 0.035, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }), cinematicSeed: "orbit-atlas-v539-portable-crate-seed-01" });
export const resolveKerrResponseAwarePortableCrateHudProfileV539 = (mode: KerrResponseAwarePortableCrateHudModeV539) => mode === "science" ? scienceProfile : cinematicProfile;
export function createKerrResponseAwarePortableCrateHudEncodingV539(summary: KerrResponseAwarePortableCrateSummaryV539, mode: KerrResponseAwarePortableCrateHudModeV539) { if (!SHA.test(summary.artifactSha256) || !SHA.test(summary.crate.fileSha256)) throw new Error("v539-hud-source"); return Object.freeze({ version: "v539-response-aware-portable-crate-hud-v1" as const, profileId: KERR_RESPONSE_AWARE_PORTABLE_CRATE_HUD_PROFILE_ID_V539, mode, scientificPayloadKey: summary.source.v537ArtifactSha256, columnSchemaKey: summary.source.v538ArtifactSha256, crateArtifactKey: summary.artifactSha256, crateFileKey: summary.crate.fileSha256, members: summary.members, memberCount: 9 as const, manifestCoveredMemberCount: 8 as const, imageHduCount: 0 as const, pixelSampleCount: 0 as const, numericScientificStyleInputCount: 0 as const, scientificFieldMutation: false as const }); }
export function compareKerrResponseAwarePortableCrateHudEncodingsV539(science: ReturnType<typeof createKerrResponseAwarePortableCrateHudEncodingV539>, cinematic: ReturnType<typeof createKerrResponseAwarePortableCrateHudEncodingV539>) { if (science.mode !== "science" || cinematic.mode !== "cinematic" || science.scientificPayloadKey !== cinematic.scientificPayloadKey || science.columnSchemaKey !== cinematic.columnSchemaKey || science.crateArtifactKey !== cinematic.crateArtifactKey || science.crateFileKey !== cinematic.crateFileKey || JSON.stringify(science.members) !== JSON.stringify(cinematic.members)) throw new Error("v539-hud-boundary"); return Object.freeze({ scientificPayloadStable: true as const, columnSchemaStable: true as const, portableCrateStable: true as const, memberInventoryStable: true as const, memberCount: 9 as const, imageHduCount: 0 as const, pixelSampleCount: 0 as const, scientificFieldMutation: false as const }); }
