import { validateObservationGeometryMeasurementsV370, type ObservationGeometryCollectingAreaRowV370, type ObservationGeometryPlateScaleRowV370, type ObservationGeometryValidationV370 } from "./observationGeometryPackV370";

export const OBSERVATION_GEOMETRY_COMPILER_VERSION_V371 = "v371-observation-geometry-measured-compiler-v1" as const;
const SHA256 = /^[a-f0-9]{64}$/; const ISO_UTC = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/;
export type ObservationGeometryIdentityV371 = Readonly<{ version: "v371-observation-geometry-identity-v1"; measuredAcquisition: true; instrumentSerialOrCampaignId: string; observatoryOrLaboratory: string; measuredAtUtc: string; attestation: Readonly<{ statement: "real-measured-observation-geometry-not-synthetic-or-example"; operatorOrArchive: string; signedAtUtc: string }> }>;
export type ObservationGeometryProvenanceV371 = Readonly<{ version: "v371-observation-geometry-provenance-v1"; sourceUrl: string; licenseOrTerms: string; identityFileSha256: string; collectingAreaFileSha256: string; plateScaleFileSha256: string; processingParametersSha256: string }>;
export type ObservationGeometryCompilationV371 = Readonly<{ version: typeof OBSERVATION_GEOMETRY_COMPILER_VERSION_V371; status: "compiled-test-fixture-nonpublishable" | "compiled-measured-geometry-candidate-awaiting-independent-validation"; sourceKind: "test-fixture" | "measured-import"; validation: ObservationGeometryValidationV370; geometryDraft: Readonly<{ version: "v369-measured-observation-geometry-v1"; sourceKind: "measured-instrument-geometry"; instrumentSerialOrCampaignId: string; collectingAreaM2: number; pixelSolidAngleSr: number; provenance: Readonly<{ sourceUrl: string; licenseOrTerms: string }> }>; sourceFileSha256: Readonly<{ identity: string; collectingArea: string; plateScale: string }>; candidatePublishable: boolean; runtimeGeometryPublished: false; measuredAuthorityGranted: false; independentScientificValidation: "pending"; boundary: "compiler-produces-candidate-only-no-runtime-geometry-authority-or-science-promotion" }>;

function object(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("v371-object"); return value as Record<string, unknown>; }
function text(value: unknown, label: string): string { if (typeof value !== "string" || value.trim().length < 3 || value.length > 512) throw new Error(`v371-text:${label}`); return value; }
export function parseObservationGeometryIdentityV371(value: unknown): ObservationGeometryIdentityV371 { const source = object(value), attestation = object(source.attestation); if (source.version !== "v371-observation-geometry-identity-v1" || source.measuredAcquisition !== true || attestation.statement !== "real-measured-observation-geometry-not-synthetic-or-example" || !ISO_UTC.test(String(source.measuredAtUtc ?? "")) || !ISO_UTC.test(String(attestation.signedAtUtc ?? ""))) throw new Error("v371-identity-boundary"); text(source.instrumentSerialOrCampaignId, "serial"); text(source.observatoryOrLaboratory, "observatory"); text(attestation.operatorOrArchive, "operator"); return value as ObservationGeometryIdentityV371; }
export function parseObservationGeometryProvenanceV371(value: unknown): ObservationGeometryProvenanceV371 { const source = object(value); if (source.version !== "v371-observation-geometry-provenance-v1" || !/^https:\/\//.test(String(source.sourceUrl ?? "")) || !text(source.licenseOrTerms, "license") || ![source.identityFileSha256, source.collectingAreaFileSha256, source.plateScaleFileSha256, source.processingParametersSha256].every((entry) => typeof entry === "string" && SHA256.test(entry))) throw new Error("v371-provenance"); return value as ObservationGeometryProvenanceV371; }
function parseCsv(source: string, expectedHeader: readonly string[]): string[][] { if (Buffer.byteLength(source, "utf8") > 2 * 1024 * 1024 || source.includes("\0")) throw new Error("v371-csv-size-or-nul"); const lines = source.replaceAll("\r\n", "\n").trimEnd().split("\n"); if (lines[0]?.split(",").join("|") !== expectedHeader.join("|")) throw new Error("v371-csv-header"); return lines.slice(1).filter((line) => line.trim()).map((line) => { const fields = line.split(","); if (fields.length !== expectedHeader.length) throw new Error("v371-csv-columns"); return fields; }); }
const finite = (value: string, label: string) => { const number = Number(value); if (!Number.isFinite(number)) throw new Error(`v371-number:${label}`); return number; };
export function parseObservationGeometryCollectingAreaCsvV371(source: string): ObservationGeometryCollectingAreaRowV370[] { return parseCsv(source, ["measurementId", "repeatIndex", "illuminatedAreaM2", "obscuredAreaM2", "effectiveAreaUncertaintyM2", "rawArtifactSha256"]).map((row) => ({ measurementId: text(row[0], "area-id"), repeatIndex: finite(row[1], "area-repeat"), illuminatedAreaM2: finite(row[2], "illuminated-area"), obscuredAreaM2: finite(row[3], "obscured-area"), effectiveAreaUncertaintyM2: finite(row[4], "area-uncertainty"), rawArtifactSha256: row[5] })); }
export function parseObservationGeometryPlateScaleCsvV371(source: string): ObservationGeometryPlateScaleRowV370[] { return parseCsv(source, ["measurementId", "repeatIndex", "referenceAngleArcsec", "measuredPixelSeparation", "pixelSeparationUncertainty", "rawArtifactSha256"]).map((row) => ({ measurementId: text(row[0], "scale-id"), repeatIndex: finite(row[1], "scale-repeat"), referenceAngleArcsec: finite(row[2], "reference-angle"), measuredPixelSeparation: finite(row[3], "pixel-separation"), pixelSeparationUncertainty: finite(row[4], "pixel-uncertainty"), rawArtifactSha256: row[5] })); }
export function compileObservationGeometryV371(args: Readonly<{ identity: ObservationGeometryIdentityV371; provenance: ObservationGeometryProvenanceV371; collectingAreaRows: readonly ObservationGeometryCollectingAreaRowV370[]; plateScaleRows: readonly ObservationGeometryPlateScaleRowV370[]; sourceKind: "test-fixture" | "measured-import"; sourceFileSha256: Readonly<{ identity: string; collectingArea: string; plateScale: string }> }>): ObservationGeometryCompilationV371 { parseObservationGeometryIdentityV371(args.identity); parseObservationGeometryProvenanceV371(args.provenance); if (args.provenance.identityFileSha256 !== args.sourceFileSha256.identity || args.provenance.collectingAreaFileSha256 !== args.sourceFileSha256.collectingArea || args.provenance.plateScaleFileSha256 !== args.sourceFileSha256.plateScale || !Object.values(args.sourceFileSha256).every((entry) => SHA256.test(entry))) throw new Error("v371-source-file-sha"); const validation = validateObservationGeometryMeasurementsV370({ sourceKind: args.sourceKind === "measured-import" ? "measured" : "test-fixture", collectingAreaRows: args.collectingAreaRows, plateScaleRows: args.plateScaleRows }); if (!validation.passed) throw new Error(`v371-validation:${validation.failures.join(",")}`); const candidatePublishable = args.sourceKind === "measured-import" && validation.qualificationEligible; return Object.freeze({ version: OBSERVATION_GEOMETRY_COMPILER_VERSION_V371, status: candidatePublishable ? "compiled-measured-geometry-candidate-awaiting-independent-validation" : "compiled-test-fixture-nonpublishable", sourceKind: args.sourceKind, validation, geometryDraft: Object.freeze({ version: "v369-measured-observation-geometry-v1", sourceKind: "measured-instrument-geometry", instrumentSerialOrCampaignId: args.identity.instrumentSerialOrCampaignId, collectingAreaM2: validation.derived.collectingAreaM2, pixelSolidAngleSr: validation.derived.pixelSolidAngleSr, provenance: Object.freeze({ sourceUrl: args.provenance.sourceUrl, licenseOrTerms: args.provenance.licenseOrTerms }) }), sourceFileSha256: Object.freeze({ ...args.sourceFileSha256 }), candidatePublishable, runtimeGeometryPublished: false, measuredAuthorityGranted: false, independentScientificValidation: "pending", boundary: "compiler-produces-candidate-only-no-runtime-geometry-authority-or-science-promotion" }); }
