export const VISUAL_CALIBRATION = {
  sky: {
    exposure: 0.76,
    contrast: 0.8,
    tinyStarIntensity: 0.0022,
    fastExposure: 0.56,
    fastContrast: 0.72,
    fastTinyStarIntensity: 0.00055,
    previewExposure: 0.62,
    previewContrast: 0.72,
    previewTinyStarIntensity: 0.001,
    milkyWayContrast: 0.78,
    deepUniverseExposure: 0.58,
    deepUniverseContrast: 0.72,
    dustLaneContrast: 1.35,
    coreCompression: 0.44,
    observationTone: 0.84,
  },
  stars: {
    brightHaloScale: 0.86,
    colorIndexStrength: 0.82,
    deterministicSeed: 4277009102,
    densitySolar: 0.62,
    densityMilkyWay: 1,
    densityAtlas: 1.18,
  },
  nebulae: {
    galaxyDustOpacity: 0.028,
    galaxyDustLaneOpacity: 0.044,
    deepSkyCoreOpacityScale: 0.5,
    deepSkyDeferredOpacityScale: 0.4,
    deepSkyShellOpacityScale: 0.68,
    deepSkySolarLodOpacity: 0.54,
    deepSkyMidLodOpacity: 0.66,
    deepSkyFarLodOpacity: 0.78,
    previewSaturation: 0.88,
    qualitySaturation: 0.94,
  },
  sun: {
    haloScale: 3.86,
    coronaAlpha: 0.155,
  },
  planets: {
    rimIntensity: 0.82,
    cloudIntensity: 0.88,
    nightLightIntensity: 0.78,
  },
  closeups: {
    sun: {
      exposure: 0.86,
      haloScale: 0.98,
      coronaLayerAlpha: 0.205,
      flareOpacity: 0.145,
      limbDarkening: 0.3,
      shadowSoftness: 0.74,
    },
    earth: {
      roughness: 0.68,
      normalScale: 1.42,
      envMapIntensity: 0.28,
      nightIntensity: 0.78,
      cloudDayOpacity: 0.5,
      cloudNightOpacity: 0.16,
      atmosphereIntensity: 0.36,
      fillIntensity: 0.2,
      rimIntensity: 1.02,
      terminatorFeather: 0.32,
      cloudSilverLining: 0.13,
      nightTerminatorCutoff: 0.16,
      shadowSoftness: 0.66,
    },
    moon: {
      roughness: 0.96,
      normalScale: 1.7,
      envMapIntensity: 0.1,
      fillIntensity: 0.04,
      rimIntensity: 0.54,
      microDetail: 0.22,
      shadowSoftness: 0.68,
    },
    jupiter: {
      roughness: 0.62,
      normalScale: 0.82,
      envMapIntensity: 0.18,
      fillIntensity: 0.045,
      rimIntensity: 0.54,
      bandContrast: 0.18,
      stormContrast: 0.14,
      shadowSoftness: 0.56,
    },
    saturn: {
      roughness: 0.66,
      normalScale: 0.72,
      envMapIntensity: 0.17,
      fillIntensity: 0.038,
      rimIntensity: 0.52,
      ringLitOpacity: 0.7,
      ringDarkOpacity: 0.3,
      ringPhaseContrast: 0.24,
      shadowSoftness: 0.62,
    },
  },
  rings: {
    saturnOpacity: 0.66,
    cassiniDivisionOpacity: 0.18,
  },
  orbits: {
    referenceOpacity: 0.38,
    trailOpacity: 0.82,
    glowScale: 0.26,
    contextOpacity: 0.7,
    activeOpacity: 1,
    missionOpacity: 0.92,
  },
} as const;
