"""
Export JPL Horizons state vectors + reference JSON for next-web.

Writes:
  - next-web/app/data/ephemerisGenerated.ts  (positions/velocities + epoch)
  - next-web/public/data/horizons_reference.json  (runtime / tooling)
  - next-web/app/data/horizonsReference.ts  (label Δr/Δv vs same snapshot)

Run from repo root (requires astroquery, network):
  python solar_sim/export_ephemeris_nextweb.py

Optional: EPOCH_JD=2451545.0 python ...  for fixed J2000.0 TDB
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

_SOLAR_SIM = Path(__file__).resolve().parent
if str(_SOLAR_SIM) not in sys.path:
    sys.path.insert(0, str(_SOLAR_SIM))

from horizons_ephemeris import FRONTEND_BODIES, fetch_solar_system_state_vectors  # noqa: E402
from nasa_planetary_masses_kg import FRONTEND_BODY_IDS  # noqa: E402

_REPO = _SOLAR_SIM.parent
_NEXT = _REPO / "solar_sim" / "next-web"
_TS_OUT = _NEXT / "app" / "data" / "ephemerisGenerated.ts"
_JSON_OUT = _NEXT / "public" / "data" / "horizons_reference.json"
_REF_TS_OUT = _NEXT / "app" / "data" / "horizonsReference.ts"


def _fmt_f(x: float) -> str:
    return repr(float(x))


def main() -> None:
    epoch_env = os.environ.get("EPOCH_JD")
    epoch = float(epoch_env) if epoch_env else None

    df, meta = fetch_solar_system_state_vectors(
        epoch=epoch,
        origin="sun",
        refplane="ecliptic",
        aberrations="geometric",
        bodies=list(FRONTEND_BODIES),
    )

    if len(df) != len(FRONTEND_BODY_IDS):
        raise RuntimeError("Body count mismatch vs FRONTEND_BODY_IDS")

    jd = float(meta["epoch_jd_tdb"])
    rows_ts = []
    bodies_json = []

    for i, bid in enumerate(FRONTEND_BODY_IDS):
        r = df.iloc[i]
        x, y, z = float(r["x_au"]), float(r["y_au"]), float(r["z_au"])
        vx, vy, vz = (
            float(r["vx_au_d"]),
            float(r["vy_au_d"]),
            float(r["vz_au_d"]),
        )
        rows_ts.append(
            f"""  {{
    id: "{bid}",
    positionAu: [{_fmt_f(x)}, {_fmt_f(y)}, {_fmt_f(z)}] as const,
    velocityAuPerDay: [{_fmt_f(vx)}, {_fmt_f(vy)}, {_fmt_f(vz)}] as const,
  }}"""
        )
        bodies_json.append(
            {
                "id": bid,
                "x_au": x,
                "y_au": y,
                "z_au": z,
                "vx_au_d": vx,
                "vy_au_d": vy,
                "vz_au_d": vz,
            }
        )

    ts_content = f"""/**
 * AUTO-GENERATED by `solar_sim/export_ephemeris_nextweb.py` — do not edit by hand.
 * Source: NASA JPL Horizons via astroquery, origin=sun, refplane=ecliptic, geometric.
 */

export const EPHEMERIS_EPOCH_JD_TDB = {jd} as const;

export type EphemerisRow = {{
  id: string;
  positionAu: readonly [number, number, number];
  velocityAuPerDay: readonly [number, number, number];
}};

export const EPHEMERIS_ROWS: readonly EphemerisRow[] = [
{",".join(rows_ts)}
] as const;
"""

    _TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    _TS_OUT.write_text(ts_content, encoding="utf-8")

    _JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "epochJdTdb": jd,
        "origin": meta.get("origin"),
        "refplane": meta.get("refplane"),
        "aberrations": meta.get("aberrations"),
        "source": meta.get("source"),
        "bodies": bodies_json,
    }
    _JSON_OUT.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    origin_ts = str(meta.get("origin") or "sun")
    ref_body_blocks = []
    for b in bodies_json:
        ref_body_blocks.append(
            f"""    {{
      id: "{b['id']}",
      x_au: {_fmt_f(b['x_au'])},
      y_au: {_fmt_f(b['y_au'])},
      z_au: {_fmt_f(b['z_au'])},
      vx_au_d: {_fmt_f(b['vx_au_d'])},
      vy_au_d: {_fmt_f(b['vy_au_d'])},
      vz_au_d: {_fmt_f(b['vz_au_d'])},
    }}"""
        )
    ref_ts = f"""/**
 * AUTO-GENERATED by `solar_sim/export_ephemeris_nextweb.py` — do not edit by hand.
 * Horizons snapshot at epochJdTdb (AU, AU/day), same rows as `public/data/horizons_reference.json`.
 */

export type HorizonsRefBody = {{
  id: string;
  x_au: number;
  y_au: number;
  z_au: number;
  vx_au_d: number;
  vy_au_d: number;
  vz_au_d: number;
}};

export const HORIZONS_REFERENCE = {{
  epochJdTdb: {jd},
  origin: "{origin_ts}" as const,
  bodies: [
{",".join(ref_body_blocks)}
  ] as const satisfies readonly HorizonsRefBody[],
}};

const _byId = new Map<string, HorizonsRefBody>(
  HORIZONS_REFERENCE.bodies.map((b) => [b.id, b])
);

export function horizonsRefForId(id: string): HorizonsRefBody | undefined {{
  return _byId.get(id);
}}
"""
    _REF_TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    _REF_TS_OUT.write_text(ref_ts, encoding="utf-8")

    print("Wrote", _TS_OUT)
    print("Wrote", _JSON_OUT)
    print("Wrote", _REF_TS_OUT)


if __name__ == "__main__":
    main()
