"use client";

import AtlasSceneHost from "./AtlasSceneHost";
import type { AtlasRuntimeWorkbenchSurfaceScope } from "./AtlasRuntimeWorkbenchSurface";

export default function AtlasRuntimeSceneLayer({
  scope,
}: {
  scope: AtlasRuntimeWorkbenchSurfaceScope;
}) {
  const {
    atlasSceneMode, selectedExoplanetSystemId, simDaysRef, isPlaying, daysPerSecond,
    physicsRef, relativityEnabledRef, precisionTierRef, floatingOriginRef, onSelectBody,
    orbitAtlas, onAtlasBodyCanvasPick, onBodyCanvasPick, onBrightStarFocus,
    requestGaiaStarFocus, requestCatalogObjectFocus, selectedBodyIndex,
    cameraBodyFocusRequest, cameraOriginResetNonce, bodyMetricsRef,
    simulationDiagnosticsRef, earthMoonView, telemetrySeriesRef, kerrBlackHole,
    visualEnhance, viewSettings, selectedCelestialCatalogId, selectedStellarSearchDocument,
    atlasPerformanceBudgetSummary, presentation, selectedBodyCloseupActive,
    atlasSkyCloseupProfile, selectedBodyLightingProfile, atlasCinematicCameraProfile,
    atlasCinematicSkyCompositionProfile, atlasCinematicBackgroundNoiseProfile,
    atlasCinematicTargetSeparationProfile, atlasBackgroundDepthProfile,
    atlasBackgroundSubjectVisibilityProfile, atlasReferenceGradeCompositeProfile,
    atlasReferenceGradeSkyLayerProfile, atlasReferenceGradeStarfieldProfile,
    atlasReferenceGradeSubjectMatteProfile, atlasReferenceGradePlanetMaterialProfile,
    atlasSelectedBodyMaterialProfile, atlasSelectedBodyAtmosphereDepthProfile,
    atlasSelectedBodyTerminatorProfile, atlasSelectedBodyRingProfile,
    atlasSelectedBodyKeyLightProfile, atlasSelectedBodyDepthLightingProfile,
    atlasSelectedBodyColorGradeProfile, atlasSelectedBodyGasGiantArtProfile,
    atlasSelectedBodySaturnRingArtProfile, atlasSelectedBodyEarthCloudNightProfile,
    atlasSelectedBodySolarSurfaceProfile, atlasGlobalColorGradeProfile,
    atlasBackgroundArtGradeProfile, atlasCinematicBackdropStarfieldProfile,
    atlasCinematicBackdropNebulaProfile, atlasCinematicBackdropNegativeSpaceProfile,
    atlasSparseDeepSpaceStarfieldProfile, atlasSparseDeepSpaceMilkyWayProfile,
    atlasSparseDeepSpaceNebulaProfile, atlasSparseDeepSpaceNegativeSpaceProfile,
    atlasCloseupCompositionProfile, atlasCloseupPanelAvoidanceProfile,
    atlasCloseupRingShowcaseProfile, atlasCinematicLightingSummary, handleCanvasReady,
    setSkyReady, handleCoreBodiesReady, lagrangeSpawnNonceRef, integrationSuspendedRef,
    timeTravelScrubURef, timeTravelScrubbingRef, physicsHistoryRef, clearFocusLock,
    launchMode, localLaunchActive, localLaunchActiveRef, handleLocalLaunchHandoff,
    handleLaunchAbort, localTelemetryRef, launchConfigRef, atlasRuntimeQualityTier,
  } = scope;

  return (
    <div className="absolute inset-0 touch-none" data-atlas-runtime-domain="scene-overlay">
      <AtlasSceneHost
        simulation={{
          sceneMode: atlasSceneMode,
          exoplanetSystemId: selectedExoplanetSystemId,
          simDaysRef,
          isPlaying,
          daysPerSecond,
          physicsRef,
          relativityEnabledRef,
          precisionTierRef,
          floatingOriginRef,
          onSelectBody,
          onBodyCanvasPick: orbitAtlas ? onAtlasBodyCanvasPick : onBodyCanvasPick,
          onSelectBrightStar: onBrightStarFocus,
          onSelectGaiaStar: requestGaiaStarFocus,
          onSelectCatalogObject: requestCatalogObjectFocus,
          selectedBodyIndex,
          cameraBodyFocusRequest,
          cameraOriginResetNonce,
          bodyMetricsRef,
          simulationDiagnosticsRef,
          earthMoonView,
          telemetrySeriesRef,
          kerrBlackHole,
          visualEnhance,
          viewSettings,
          selectedCelestialCatalogId,
          selectedStellarSearchDocument,
          catalogLabelBudget: atlasPerformanceBudgetSummary.deepSkyLabelBudget,
          presentationMode: presentation.presentationMode,
          atlasScaleMode: presentation.scaleMode,
          atlasRenderBudget: presentation.renderBudget,
          selectedBodyCloseupActive,
          skyCloseupProfile: atlasSkyCloseupProfile,
          selectedBodyLightingProfile,
          cinematicCameraProfile: atlasCinematicCameraProfile,
          cinematicSkyCompositionProfile: atlasCinematicSkyCompositionProfile,
          cinematicBackgroundNoiseProfile: atlasCinematicBackgroundNoiseProfile,
          cinematicTargetSeparationProfile: atlasCinematicTargetSeparationProfile,
          backgroundDepthProfile: atlasBackgroundDepthProfile,
          backgroundSubjectVisibilityProfile: atlasBackgroundSubjectVisibilityProfile,
          referenceGradeCompositeProfile: atlasReferenceGradeCompositeProfile,
          referenceGradeSkyLayerProfile: atlasReferenceGradeSkyLayerProfile,
          referenceGradeStarfieldProfile: atlasReferenceGradeStarfieldProfile,
          referenceGradeSubjectMatteProfile: atlasReferenceGradeSubjectMatteProfile,
          referenceGradePlanetMaterialProfile: atlasReferenceGradePlanetMaterialProfile,
          selectedBodyMaterialProfile: atlasSelectedBodyMaterialProfile,
          selectedBodyAtmosphereDepthProfile: atlasSelectedBodyAtmosphereDepthProfile,
          selectedBodyTerminatorProfile: atlasSelectedBodyTerminatorProfile,
          selectedBodyRingProfile: atlasSelectedBodyRingProfile,
          selectedBodyKeyLightProfile: atlasSelectedBodyKeyLightProfile,
          selectedBodyDepthLightingProfile: atlasSelectedBodyDepthLightingProfile,
          selectedBodyColorGradeProfile: atlasSelectedBodyColorGradeProfile,
          selectedBodyGasGiantArtProfile: atlasSelectedBodyGasGiantArtProfile,
          selectedBodySaturnRingArtProfile: atlasSelectedBodySaturnRingArtProfile,
          selectedBodyEarthCloudNightProfile: atlasSelectedBodyEarthCloudNightProfile,
          selectedBodySolarSurfaceProfile: atlasSelectedBodySolarSurfaceProfile,
          globalColorGradeProfile: atlasGlobalColorGradeProfile,
          backgroundArtGradeProfile: atlasBackgroundArtGradeProfile,
          cinematicBackdropStarfieldProfile: atlasCinematicBackdropStarfieldProfile,
          cinematicBackdropNebulaProfile: atlasCinematicBackdropNebulaProfile,
          cinematicBackdropNegativeSpaceProfile: atlasCinematicBackdropNegativeSpaceProfile,
          sparseDeepSpaceStarfieldProfile: atlasSparseDeepSpaceStarfieldProfile,
          sparseDeepSpaceMilkyWayProfile: atlasSparseDeepSpaceMilkyWayProfile,
          sparseDeepSpaceNebulaProfile: atlasSparseDeepSpaceNebulaProfile,
          sparseDeepSpaceNegativeSpaceProfile: atlasSparseDeepSpaceNegativeSpaceProfile,
          closeupCompositionProfile: atlasCloseupCompositionProfile,
          closeupPanelAvoidanceProfile: atlasCloseupPanelAvoidanceProfile,
          closeupRingShowcaseProfile: atlasCloseupRingShowcaseProfile,
          cinematicPostFxProfile: atlasCinematicLightingSummary.postFxProfile,
          onCanvasReady: handleCanvasReady,
          onSkyReady: setSkyReady,
          onCoreBodiesReady: handleCoreBodiesReady,
          lagrangeSpawnNonceRef,
          integrationSuspendedRef,
          timeTravelScrubURef,
          timeTravelScrubbingRef,
          physicsHistoryRef,
          onCanvasPointerMissed: clearFocusLock,
          launchMode,
          localLaunchActive,
          localLaunchActiveRef,
          onLocalLaunchHandoff: handleLocalLaunchHandoff,
          onLocalLaunchAbort: handleLaunchAbort,
          localTelemetryRef,
          launchConfigRef,
          runtimeQualityTier: atlasRuntimeQualityTier,
        }}
      />
    </div>
  );
}

