"use client";
import { useEffect, useMemo, useState } from "react";
import { publishAtlasScienceImageRoiTelemetryV347 } from "../lib/atlasScienceImageRoiTelemetryV347";
import { acquireKerrScienceImageRoiExportV347, type KerrScienceImageRoiExportFormatV347 } from "../lib/kerrScienceImageRoiExportV347";
import { summarizeKerrScienceImageRoiV347 } from "../lib/kerrScienceImageRoiV347";
import type { KerrScienceImageBandV346, KerrScienceImagePixelProbeArtifactV346 } from "../lib/kerrScienceImagePixelProbeV346";

const BANDS = ["visible", "euv", "soft-x-ray"] as const; const RAYS = [12, 13, 14, 15] as const; const LABELS = { visible: "VIS", euv: "EUV", "soft-x-ray": "SXR" } as const;
function scientific(value: number): string { return value.toExponential(6); }
export default function KerrScienceImageRoiSurfaceV347({ artifact }: Readonly<{ artifact: KerrScienceImagePixelProbeArtifactV346 }>) {
  const [band, setBand] = useState<KerrScienceImageBandV346>("visible"); const [start, setStart] = useState<12 | 13 | 14 | 15>(12); const [end, setEnd] = useState<12 | 13 | 14 | 15>(15); const summary = useMemo(() => summarizeKerrScienceImageRoiV347(artifact, band, start, end), [artifact, band, end, start]);
  useEffect(() => { publishAtlasScienceImageRoiTelemetryV347(summary); return () => { publishAtlasScienceImageRoiTelemetryV347(null); }; }, [summary]);
  const changeStart = (value: 12 | 13 | 14 | 15) => { setStart(value); if (RAYS.indexOf(value) > RAYS.indexOf(end)) setEnd(value); }; const changeEnd = (value: 12 | 13 | 14 | 15) => { setEnd(value); if (RAYS.indexOf(value) < RAYS.indexOf(start)) setStart(value); };
  const download = (format: KerrScienceImageRoiExportFormatV347) => { const acquired = acquireKerrScienceImageRoiExportV347(summary, artifact.artifactSha256, format); const anchor = document.createElement("a"); anchor.href = acquired.objectUrl; anchor.download = acquired.filename; anchor.click(); queueMicrotask(() => { acquired.release(); publishAtlasScienceImageRoiTelemetryV347(summary); }); };
  return <section className="mt-2 rounded border border-violet-100/10 bg-[linear-gradient(135deg,rgba(25,18,45,0.42),rgba(4,10,18,0.55))] p-2" data-atlas-science-image-roi-v347 data-atlas-science-image-roi-id={summary.roiId}>
    <div className="flex flex-wrap items-end justify-between gap-2"><div><div className="text-[7px] uppercase tracking-[0.16em] text-violet-100/48">Index ROI v347</div><div className="mt-0.5 text-[10px] text-violet-50/80">Compensated radiance aggregation</div></div><div className="text-right text-[7px] text-white/30">single band · contiguous rays<br />not aperture photometry</div></div>
    <div className="mt-2 grid gap-1.5 sm:grid-cols-[1fr_auto_auto]" role="group" aria-label="Scientific index ROI selection"><div className="grid grid-cols-3 gap-1">{BANDS.map((item) => <button key={item} type="button" onClick={() => setBand(item)} className={item === band ? "atlas-accessible-focus rounded border border-violet-100/30 bg-violet-100/[0.12] px-2 py-1 text-[7px] text-violet-50" : "atlas-accessible-focus rounded border border-white/[0.07] px-2 py-1 text-[7px] text-white/40"}>{LABELS[item]}</button>)}</div><label className="text-[7px] text-white/35">Ray start<select aria-label="ROI ray start" value={start} onChange={(event) => changeStart(Number(event.target.value) as 12 | 13 | 14 | 15)} className="ml-1 rounded border border-white/10 bg-black/40 px-1 py-1 text-violet-50">{RAYS.map((ray) => <option key={ray}>{ray}</option>)}</select></label><label className="text-[7px] text-white/35">Ray end<select aria-label="ROI ray end" value={end} onChange={(event) => changeEnd(Number(event.target.value) as 12 | 13 | 14 | 15)} className="ml-1 rounded border border-white/10 bg-black/40 px-1 py-1 text-violet-50">{RAYS.map((ray) => <option key={ray}>{ray}</option>)}</select></label></div>
    <div className="mt-2 grid gap-1 sm:grid-cols-4"><div className="rounded border border-white/[0.06] bg-black/15 p-1.5"><span className="text-white/28">Σ I indexed</span><br /><span className="text-violet-50/82">{scientific(summary.radianceSumWM2Sr)}</span><br /><span className="text-[6px] text-white/25">W m⁻² sr⁻¹ · not flux</span></div><div className="rounded border border-white/[0.06] bg-black/15 p-1.5"><span className="text-white/28">Linear interval</span><br /><span className="text-violet-50/82">{scientific(summary.radianceLowerSumWM2Sr)}</span><br /><span className="text-violet-50/55">{scientific(summary.radianceUpperSumWM2Sr)}</span></div><div className="rounded border border-white/[0.06] bg-black/15 p-1.5"><span className="text-white/28">Weighted g</span><br /><span className="text-violet-50/82">{summary.radianceWeightedRedshift.toFixed(8)}</span><br /><span className="text-[6px] text-white/25">range {summary.redshiftRange[0].toFixed(4)}–{summary.redshiftRange[1].toFixed(4)}</span></div><div className="rounded border border-white/[0.06] bg-black/15 p-1.5"><span className="text-white/28">u / I</span><br /><span className="text-violet-50/82">{scientific(summary.conservativeLinearRelativeEnvelope)}</span><br /><span className="text-[6px] text-white/25">linear · no RSS</span></div></div>
    <div className="mt-2 flex flex-wrap items-center justify-between gap-1 border-t border-white/[0.06] pt-1.5 text-[7px] text-white/30"><span>Neumaier float64 · solid angle unavailable · celestial WCS unavailable</span><span className="flex gap-1"><button type="button" onClick={() => download("json")} className="atlas-accessible-focus rounded border border-violet-100/15 px-1.5 py-0.5 text-violet-50/65">JSON</button><button type="button" onClick={() => download("csv")} className="atlas-accessible-focus rounded border border-violet-100/15 px-1.5 py-0.5 text-violet-50/65">CSV</button></span></div>
  </section>;
}
