"use client";
import Image from "next/image";
import { useState, useSyncExternalStore, type CSSProperties } from "react";
import { getKerrRedshiftContrastLatticeSnapshotV489, loadKerrRedshiftContrastLatticeSummaryV489, subscribeKerrRedshiftContrastLatticeV489 } from "../lib/kerrRedshiftContrastLatticeClientV489";
export default function KerrRedshiftContrastLatticeV489() {
  const state = useSyncExternalStore(subscribeKerrRedshiftContrastLatticeV489, getKerrRedshiftContrastLatticeSnapshotV489, getKerrRedshiftContrastLatticeSnapshotV489); const [mode, setMode] = useState<"science" | "cinematic">("science"); const summary = state.summary;
  const style = { "--v489-accent": mode === "science" ? "#72eaff" : "#ffad68", "--v489-wash": mode === "science" ? "rgba(63,218,255,.07)" : "rgba(255,125,66,.09)" } as CSSProperties;
  return <section className="relative mt-7 overflow-hidden rounded-[32px] border border-white/10 bg-[#020607] p-5 text-white shadow-[0_70px_220px_rgba(0,0,0,.8)] sm:p-8" data-atlas-kerr-redshift-contrast-lattice-v489 data-atlas-v489-mode={mode} data-atlas-v489-request-count={state.requestCount} data-atlas-v489-science-writeback="false" data-atlas-v489-science-raster="false" data-atlas-v489-scene-revision-delta="0" style={style}>
    <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_74%_12%,var(--v489-wash),transparent_44%)]"/>
    <header className="relative flex flex-wrap items-end justify-between gap-5 border-b border-white/10 pb-6"><div><div className="font-mono text-[9px] uppercase tracking-[.42em] text-[var(--v489-accent)]/60">V489 / relative redshift contrast lattice</div><h2 className="mt-4 font-serif text-4xl tracking-[.035em] text-white/90 sm:text-6xl">Ratios survive where calibration does not</h2><p className="mt-4 max-w-3xl font-mono text-[10px] leading-6 text-white/42">Pairwise log-redshift contrasts cancel the unspecified reference frequency. Cross-ray correlation remains unknown, so uncertainty upper bounds are added linearly and never interpreted as 1-sigma.</p></div><div className="flex border border-white/12 bg-black/55 p-1 font-mono text-[8px] uppercase tracking-[.2em]">{(["science","cinematic"] as const).map((entry)=><button className={mode===entry?"bg-[var(--v489-accent)] px-4 py-2.5 text-black":"px-4 py-2.5 text-white/30"} key={entry} onClick={()=>setMode(entry)} type="button">{entry}</button>)}</div></header>
    {state.status==="idle"?<div className="relative mt-6 border border-dashed border-[var(--v489-accent)]/20 bg-white/[.02] p-5"><div className="font-mono text-[10px] text-white/45">The 16-cell contrast lattice is not auto-loaded.</div><button className="atlas-accessible-focus mt-4 border border-[var(--v489-accent)]/35 bg-[var(--v489-wash)] px-4 py-2 font-mono text-[9px] uppercase tracking-[.16em] text-[var(--v489-accent)]" onClick={()=>void loadKerrRedshiftContrastLatticeSummaryV489().catch(()=>undefined)} type="button">Load verified contrast lattice</button></div>:null}
    {state.status==="loading"?<div className="relative mt-6 font-mono text-[10px] text-white/50">Verifying lattice and SVG SHA...</div>:null}{state.status==="unavailable"?<div className="relative mt-6 font-mono text-[10px] text-amber-100/60">Contrast lattice unavailable / {state.reason??"request-failed"}</div>:null}
    {summary?<><div className="relative mt-6 grid grid-cols-2 gap-px border border-white/10 bg-white/10 font-mono sm:grid-cols-4"><Stat label="directed cells" value="16"/><Stat label="independent pairs" value="6"/><Stat label="landmark audits" value="30"/><Stat label="cycle audits" value="24"/></div><figure className="relative mt-5 overflow-hidden border border-white/10 bg-black/35 p-2 sm:p-4"><Image alt="Four by four matrix of dimensionless pairwise log redshift contrasts and centered log-shift bars; no intensity is encoded" className="block h-auto w-full" height={900} src={summary.svgHref} unoptimized width={1440}/><figcaption className="border-t border-white/8 px-2 pt-3 font-mono text-[8px] leading-4 text-white/32">Cell hue encodes contrast sign and opacity encodes absolute dimensionless log contrast. It never encodes radiance or detector counts. Science and Cinematic shells share this exact SVG SHA.</figcaption></figure><div className="relative mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{summary.nodes.map((node)=><article className="border border-white/10 bg-white/[.025] p-4" key={node.rayId}><div className="font-serif text-2xl text-white/80">{node.rayId}</div><div className="mt-3 font-mono text-[9px] text-[var(--v489-accent)]/70">log g {node.logShift.toFixed(7)}</div><div className="mt-2 font-mono text-[8px] text-white/30">u(log g) ≤ {node.logShiftUncertaintyUpperBound.toExponential(3)}<br/>linear bound / correlation unknown</div></article>)}</div><footer className="relative mt-6 flex flex-wrap justify-between gap-3 border-t border-white/10 pt-5 font-mono text-[8px] text-white/30"><span>payload {summary.payloadSha256.slice(0,18)}... / cycles {summary.audit.maximumCycleClosureResidual.toExponential(3)}</span><span className="flex gap-2"><a className="border border-white/12 px-3 py-1.5" href={`${summary.svgHref}&download=svg`}>export SVG</a><a className="border border-white/12 px-3 py-1.5" href="/api/atlas/relativity-evidence/v489/redshift-contrast-lattice?download=lattice">export provenance</a></span></footer></>:null}
  </section>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="bg-[#05090a] px-4 py-3 text-center"><div className="text-[7px] uppercase tracking-[.18em] text-white/25">{label}</div><div className="mt-1 font-serif text-xl text-white/75">{value}</div></div>}
