"use client";
import { useEffect, useState, useSyncExternalStore, type CSSProperties } from "react";
import Image from "next/image";
import { getKerrSparseScienceImageProductsSnapshotV556, loadKerrSparseScienceImageProductsSummaryV556, subscribeKerrSparseScienceImageProductsV556 } from "../lib/kerrSparseScienceImageProductsClientV556";
import { createKerrSparseScienceImageProductsHudEncodingV556, resolveKerrSparseScienceImageProductsHudProfileV556, type KerrSparseScienceImageProductsHudModeV556 } from "../lib/kerrSparseScienceImageProductsV556";

const ENDPOINT = "/api/atlas/relativity-evidence/v556/sparse-science-products";
export default function KerrSparseScienceImageProductsV556() {
  const [mode, setMode] = useState<KerrSparseScienceImageProductsHudModeV556>("science");
  const state = useSyncExternalStore(subscribeKerrSparseScienceImageProductsV556, getKerrSparseScienceImageProductsSnapshotV556, getKerrSparseScienceImageProductsSnapshotV556);
  const artifact = state.summary, profile = resolveKerrSparseScienceImageProductsHudProfileV556(mode), encoding = artifact ? createKerrSparseScienceImageProductsHudEncodingV556(artifact, mode) : null;
  useEffect(() => { void loadKerrSparseScienceImageProductsSummaryV556().catch(() => undefined); }, []);
  const style = { "--v556-panel": profile.panel, "--v556-raised": profile.raised, "--v556-ink": profile.ink, "--v556-muted": profile.muted, "--v556-qualified": profile.qualified, "--v556-warning": profile.warning, "--v556-unavailable": profile.unavailable } as CSSProperties;
  return <section style={style} className="relative mt-7 overflow-hidden rounded-[36px] border border-white/10 bg-[var(--v556-panel)] p-6 font-mono text-[var(--v556-ink)]" data-atlas-sparse-science-products-v556 data-atlas-v556-mode={mode} data-atlas-v556-products={encoding?.productCount ?? 0} data-atlas-v556-dense-qualified="false" data-atlas-v556-measured-qualified="false" data-atlas-v556-canvas-created="false" data-atlas-v556-scene-revision-delta="0">
    <header className="border-b border-white/10 pb-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[9px] uppercase tracking-[.4em] text-[var(--v556-muted)]">V556 / Scientific Image Products</div><h2 className="mt-3 max-w-4xl font-serif text-3xl">同一组 RGBA 字节，跨 PNG 与 FITS 可逆回读</h2></div><div className="flex border border-white/10">{(["science", "cinematic"] as const).map((item) => <button key={item} type="button" aria-pressed={mode === item} className={mode === item ? "bg-white/10 px-3 py-2 text-[8px] text-white" : "px-3 py-2 text-[8px] text-[var(--v556-muted)]"} onClick={() => setMode(item)}>{item}</button>)}</div></div><p className="mt-3 text-[10px] leading-6 text-[var(--v556-muted)]">PNG 与 FITS 都逐字节恢复 v555 的 256×256 RGBA。无缩放、无色彩分级、无随机噪声；dense 仍为 0/49，measured pixels 仍为 0。</p></header>
    {!artifact ? <div className="mt-5 text-[10px] text-[var(--v556-muted)]">{state.status === "unavailable" ? `科学图像产品不可用：${state.reason ?? "request-failed"}` : "正在读取本地产品证据…"}</div> : <>
      <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,320px)_1fr]"><div className="overflow-hidden rounded-2xl border border-white/10 bg-black"><Image unoptimized src={`${ENDPOINT}?download=png`} alt="v556 稀疏 Kerr 权威射线科学图像" width={256} height={256} className="h-auto w-full [image-rendering:pixelated]" /></div><div className="grid content-start gap-2 sm:grid-cols-2 xl:grid-cols-3"><Metric label="products" value="2" /><Metric label="pixel bytes" value="262,144" /><Metric label="validators" value="2 / 2" /><Metric label="mutations rejected" value="8 / 8" /><Metric label="dense campaign" value="0 / 49" unavailable /><Metric label="measured pixels" value="0" unavailable /></div></div>
      <div className="mt-5 grid gap-2 sm:grid-cols-2"><HashRow label="source RGBA" value={artifact.source.rasterSha256} /><HashRow label="payload" value={artifact.source.payloadSha256} /><HashRow label="PNG" value={artifact.products.find((product) => product.id === "png")!.fileSha256} /><HashRow label="FITS" value={artifact.products.find((product) => product.id === "fits")!.fileSha256} /></div>
      <footer className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-4 text-[8px] text-[var(--v556-muted)]"><span>sparse products qualified · dense image incomplete · observed image blocked · formal v263</span><div className="flex flex-wrap gap-2"><Download id="png" label="PNG" /><Download id="fits" label="FITS" /><Download id="manifest" label="Manifest" /><Download id="receipt" label="Receipt" /><Download id="validator" label="Validator" /></div></footer>
    </>}
  </section>;
}
function Metric({ label, value, unavailable = false }: { label: string; value: string; unavailable?: boolean }) { return <div className="border border-white/10 bg-[var(--v556-raised)] p-3"><div className="text-[8px] uppercase tracking-[.16em] text-[var(--v556-muted)]">{label}</div><div className={unavailable ? "mt-2 text-base text-[var(--v556-unavailable)]" : "mt-2 text-lg text-[var(--v556-qualified)]"}>{value}</div></div>; }
function HashRow({ label, value }: { label: string; value: string }) { return <div className="border border-white/10 bg-black/20 p-3"><div className="text-[8px] uppercase text-[var(--v556-muted)]">{label}</div><div className="mt-2 break-all text-[8px] text-white/75">{value}</div></div>; }
function Download({ id, label }: { id: "manifest" | "png" | "fits" | "receipt" | "validator"; label: string }) { return <a className="border border-white/15 px-3 py-2 text-white/70" href={`${ENDPOINT}?download=${id}`}>{label}</a>; }
