"use client";

import { useEffect, useState, useSyncExternalStore, type CSSProperties } from "react";

import { getKerrResponseAwarePortableCrateSnapshotV539, loadKerrResponseAwarePortableCrateSummaryV539, subscribeKerrResponseAwarePortableCrateV539 } from "../lib/kerrResponseAwarePortableCrateClientV539";
import { createKerrResponseAwarePortableCrateHudEncodingV539, resolveKerrResponseAwarePortableCrateHudProfileV539, type KerrResponseAwarePortableCrateHudModeV539 } from "../lib/kerrResponseAwarePortableCrateV539";

const shortSha = (value: string) => `${value.slice(0, 10)}…${value.slice(-8)}`;
export default function KerrResponseAwarePortableCrateV539() {
  const [mode, setMode] = useState<KerrResponseAwarePortableCrateHudModeV539>("science");
  const state = useSyncExternalStore(subscribeKerrResponseAwarePortableCrateV539, getKerrResponseAwarePortableCrateSnapshotV539, getKerrResponseAwarePortableCrateSnapshotV539);
  const profile = resolveKerrResponseAwarePortableCrateHudProfileV539(mode), summary = state.summary, encoding = summary ? createKerrResponseAwarePortableCrateHudEncodingV539(summary, mode) : null;
  useEffect(() => { void loadKerrResponseAwarePortableCrateSummaryV539().catch(() => undefined); }, []);
  const style = { "--v539-panel": profile.panel, "--v539-raised": profile.panelRaised, "--v539-ink": profile.ink, "--v539-muted": profile.muted, "--v539-qualified": profile.qualified, "--v539-unavailable": profile.unavailable } as CSSProperties;
  return <section style={style} className="relative mt-7 overflow-hidden rounded-[48px] border border-white/10 bg-[var(--v539-panel)] p-6 font-mono text-[var(--v539-ink)]" data-atlas-response-aware-portable-crate-v539 data-atlas-v539-mode={mode} data-atlas-v539-member-count={encoding?.memberCount ?? 0} data-atlas-v539-image-hdus="0" data-atlas-v539-pixel-samples="0" data-atlas-v539-canvas-created="false" data-atlas-v539-scene-revision-delta="0">
    <div className="pointer-events-none absolute inset-0 opacity-30 [background-image:radial-gradient(circle_at_20%_10%,rgba(116,244,197,.16),transparent_28%),linear-gradient(rgba(125,211,252,.05)_1px,transparent_1px),linear-gradient(90deg,rgba(125,211,252,.05)_1px,transparent_1px)] [background-size:auto,42px_42px,42px_42px]" />
    <header className="relative border-b border-white/10 pb-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[9px] uppercase tracking-[.44em] text-[var(--v539-muted)]">V539 / Science Cinematic V8.8</div><h2 className="mt-4 max-w-4xl font-serif text-4xl">带走的不只是文件，而是一条可离线重放的证据链</h2></div><div className="flex border border-white/10">{(["science", "cinematic"] as const).map((item) => <button key={item} type="button" aria-pressed={mode === item} className={mode === item ? "bg-white/10 px-3 py-2 text-[8px] text-white" : "px-3 py-2 text-[8px] text-[var(--v539-muted)]"} onClick={() => setMode(item)}>{item}</button>)}</div></div><p className="mt-4 max-w-4xl text-[10px] leading-6 text-[var(--v539-muted)]">FITS 表、17 列语义、evidence、pointer、成员 manifest 与 RO-Crate 1.1 元数据被封装为固定顺序、时间戳和权限的确定性 ZIP。它仍是 local-shadow 稀疏科研封装，不是 production package 或科学图像。</p></header>
    {!summary ? <div className="relative mt-6 text-[10px] text-[var(--v539-muted)]">{state.status === "unavailable" ? `便携科研 crate 不可用 / ${state.reason ?? "request-failed"}` : "正在读取便携 crate provenance…"}</div> : <>
      <div className="relative mt-6 grid gap-2 sm:grid-cols-3 xl:grid-cols-6"><Metric label="members" value="9" /><Metric label="manifest-covered" value="8" /><Metric label="science data" value="2" /><Metric label="provenance" value="4" /><Metric label="image HDU" value="0" unavailable /><Metric label="pixel samples" value="0" unavailable /></div>
      <div className="relative mt-5 grid gap-3 lg:grid-cols-3">{encoding?.members.map((member) => <article key={member.path} className="rounded-2xl border border-white/10 bg-[var(--v539-raised)] p-4"><div className="flex items-start justify-between gap-3"><span className="break-all text-[10px] text-[var(--v539-qualified)]">{member.path}</span><span className="shrink-0 text-[7px] uppercase text-[var(--v539-muted)]">{member.role}</span></div><div className="mt-3 text-[8px] leading-4 text-[var(--v539-muted)]"><div>{member.mediaType} · {member.bytes.toLocaleString()} B</div><div className="mt-1">SHA {shortSha(member.sha256)}</div></div></article>)}</div>
      <div className="relative mt-5 grid gap-4 rounded-2xl border border-white/10 bg-black/20 p-4 text-[9px] leading-5 text-[var(--v539-muted)] lg:grid-cols-[1fr_auto] lg:items-center"><div><span className="text-[var(--v539-qualified)]">A/B byte-identical</span> · ZIP CRC replay · manifest 8/8 · metadata graph self-audit · stored compression · fixed `100644`. Physical uncertainty 0/6、dense 0/49、production false。</div><div className="flex flex-wrap gap-2"><a className="border border-white/15 px-3 py-2 text-[8px] text-white/70" href="/api/atlas/relativity-evidence/v539/response-aware-portable-crate?download=crate">下载科研 crate</a><a className="border border-white/15 px-3 py-2 text-[8px] text-white/70" href="/api/atlas/relativity-evidence/v539/response-aware-portable-crate?download=atlas">下载 crate provenance</a></div></div>
    </>}
  </section>;
}
function Metric({ label, value, unavailable = false }: { label: string; value: string; unavailable?: boolean }) { return <div className="border border-white/10 bg-black/20 p-3"><div className="text-[8px] uppercase tracking-[.16em] text-[var(--v539-muted)]">{label}</div><div className={unavailable ? "mt-2 text-lg text-[var(--v539-unavailable)]" : "mt-2 text-lg text-[var(--v539-qualified)]"}>{value}</div></div>; }
