"use client";
import { useEffect, useSyncExternalStore } from "react";
import { getKerrHighEnergyResponseUncertaintySnapshotV429, loadKerrHighEnergyResponseUncertaintySummaryV429, subscribeKerrHighEnergyResponseUncertaintyV429 } from "../lib/kerrHighEnergyResponseUncertaintyClientV429";

const EXPORTS = [["SUMMARY JSON", "json", "前向算子、协议与 authority 边界"], ["FULL ORACLE", "oracle", "完整非发布 Jacobian 与协方差 fixture"], ["HOLDOUT PROTOCOL", "protocol", "未来独立实测验证要求；当前未运行"], ["DIAGONAL CSV", "csv", "24 条预测与不确定度对角项，无观测残差"], ["BUDGET FITS", "fits", "响应、重分布与总协方差 fixture"], ["ARCHITECTURE PNG", "png", "不确定度传播图；不是探测器图像"]] as const;
export default function KerrHighEnergyResponseUncertaintyV429() {
  const state = useSyncExternalStore(subscribeKerrHighEnergyResponseUncertaintyV429, getKerrHighEnergyResponseUncertaintySnapshotV429, getKerrHighEnergyResponseUncertaintySnapshotV429);
  useEffect(() => { void loadKerrHighEnergyResponseUncertaintySummaryV429().catch(() => undefined); }, []);
  const summary = state.summary, metrics = summary?.fixture.metrics;
  return <section className="relative mt-3 overflow-hidden border border-violet-100/14 bg-[radial-gradient(circle_at_78%_16%,rgba(139,92,246,.08),transparent_28%),linear-gradient(132deg,rgba(4,6,13,.995),rgba(7,7,17,.99)_56%,rgba(13,8,3,.985))] p-3 font-mono text-white/52" data-atlas-kerr-high-energy-response-uncertainty-v429 data-atlas-v429-status={state.status} data-atlas-v429-observed-counts="0" data-atlas-v429-measured-holdouts="0" data-atlas-v429-measured-validation-runs="0" data-atlas-v429-residual-metrics="0" data-atlas-v429-measured-response-authority="false" data-atlas-v429-science-response-applications="0" data-atlas-v429-summary-only-in-react-state="true" data-atlas-v429-canvas-created="false" aria-live="polite">
    <div aria-hidden="true" className="pointer-events-none absolute inset-0 opacity-25 [background-image:linear-gradient(90deg,transparent_49.7%,rgba(196,181,253,.055)_50%,transparent_50.3%),repeating-linear-gradient(0deg,transparent_0_18px,rgba(167,139,250,.02)_19px,transparent_20px_38px)]" />
    <header className="relative flex flex-wrap items-start justify-between gap-3 border-b border-white/7 pb-3"><div><div className="text-[6px] uppercase tracking-[.34em] text-violet-100/43">V429 · response uncertainty interferometer</div><h4 className="mt-1 font-['Bahnschrift_Condensed','DIN_Condensed',sans-serif] text-[21px] font-light uppercase tracking-[.18em] text-violet-50/92">Covariance propagation chamber</h4><p className="mt-1 max-w-[116ch] text-[6px] leading-relaxed text-white/38">将 photon flux、Q/U、effective area、调制、角零点、重分布与 background 映射为 4×6 预测计数；解析 Jacobian 由复步导数独立校验，并传播完整响应与 simplex 协方差。没有实测 holdout 时不计算残差。</p></div><div className="flex items-center gap-2 border border-violet-100/14 bg-violet-100/[.025] px-2.5 py-1.5"><span className={`h-1.5 w-1.5 rounded-full ${state.status === "ready" ? "bg-lime-200/75 shadow-[0_0_14px_rgba(190,242,100,.3)]" : state.status === "loading" ? "animate-pulse bg-amber-200/65" : "bg-rose-200/65"}`} /><div><div className="text-[5px] uppercase tracking-[.12em] text-white/22">uncertainty channel</div><div className="mt-0.5 text-[6px] uppercase text-violet-100/62">{state.status}</div></div></div></header>
    {!summary ? <div className="relative mt-3 border-l-2 border-violet-100/24 bg-violet-100/[.02] px-3 py-2 text-[6px] text-violet-50/48">{state.status === "loading" || state.status === "idle" ? "正在读取响应不确定度证据…" : `响应不确定度证据不可用 · ${state.reason ?? "request-failed"}`}</div> : <>
      <div className="relative mt-3 grid gap-3 xl:grid-cols-[minmax(0,1.45fr)_320px]"><div className="grid gap-3"><div className="grid gap-px bg-white/6 md:grid-cols-4">{[["SOURCE", "flux + normalized Q/U", "6 bins"], ["RESPONSE", "area / μ / angle / bg", "24 parameters"], ["REDISTRIBUTION", "row-stochastic R + Cᴿ", "36 elements"], ["PREDICTION", "4 angles × 6 channels", "24 counts"]].map(([title, detail, count], index) => <article key={title} className="min-h-28 bg-black/42 p-2.5"><div className="flex justify-between"><span className="text-[7px] text-violet-100/58">0{index + 1}</span><span className="text-[5px] text-cyan-100/42">FIXTURE MATH</span></div><div className="mt-4 text-[7px] tracking-[.1em] text-violet-50/64">{title}</div><div className="mt-1 text-[5px] text-white/27">{detail}</div><div className="mt-3 text-[5px] text-cyan-100/45">{count}</div></article>)}</div><div className="grid gap-3 lg:grid-cols-[1.15fr_.85fr]"><div className="border border-violet-100/10 bg-black/28 p-3"><div className="text-[5px] uppercase tracking-[.16em] text-violet-100/38">Propagation identity</div><div className="mt-3 space-y-2 text-[6px] text-white/38"><Formula>y = exposure × [(flux × area × polarization) R + background]</Formula><Formula>Cᵧ,response = J Cresponse Jᵀ</Formula><Formula>Cᵧ,R = Σᵦ Jᵦ Cᵦᴿ Jᵦᵀ</Formula><Formula>Cᵧ,total = Cᵧ,response + Cᵧ,R</Formula></div></div><div className="border border-amber-100/12 bg-amber-100/[.025] p-3"><div className="text-[5px] uppercase tracking-[.16em] text-amber-100/42">Independent holdout gate</div><div className="mt-3 grid gap-px bg-white/6">{[["protocol", "READY"], ["observed counts", "0"], ["holdout datasets", "0"], ["residual metrics", "0"], ["measured validation", "NOT RUN"]].map(([label, value]) => <div key={label} className="flex justify-between bg-black/35 px-2 py-1.5 text-[5px]"><span className="text-white/27">{label}</span><span className={value === "READY" ? "text-lime-100/55" : "text-amber-100/52"}>{value}</span></div>)}</div></div></div></div>
        <aside className="grid content-start gap-px bg-white/6 sm:grid-cols-2 xl:grid-cols-1"><Metric label="J parameter Δ" value={metrics?.maximumAnalyticComplexStepParameterJacobianDifference.toExponential(2) ?? "—"} tone="lime" /><Metric label="J redistribution Δ" value={metrics?.maximumAnalyticComplexStepRedistributionJacobianDifference.toExponential(2) ?? "—"} tone="lime" /><Metric label="covariance symmetry" value={metrics?.maximumOutputCovarianceSymmetryAbsolute.toExponential(2) ?? "—"} tone="cyan" /><Metric label="decomposition Δ" value={metrics?.maximumCovarianceDecompositionResidual.toExponential(2) ?? "—"} tone="cyan" /><Metric label="Python / TS relative" value={summary.fixture.maximumPythonRelativeDifference.toExponential(2)} tone="lime" /><Metric label="predicted counts" value="24 · FIXTURE" tone="violet" /><Metric label="measured authority" value="UNAVAILABLE" tone="rose" /><Metric label="science applications" value="0" tone="rose" /><Metric label="dense campaign" value="0 / 49" tone="amber" /></aside></div>
      <div className="relative mt-3 grid gap-px bg-white/6 sm:grid-cols-2 lg:grid-cols-3">{EXPORTS.map(([label, format, detail]) => <a key={format} href={`/api/atlas/relativity-evidence/v429/high-energy-response-uncertainty?download=${format}`} download className="atlas-accessible-focus bg-black/42 px-2.5 py-2 transition-colors hover:bg-violet-100/[.05]"><div className="text-[7px] text-violet-100/62">{label}</div><div className="mt-0.5 text-[5px] leading-relaxed text-white/26">{detail}</div></a>)}</div><footer className="relative mt-2 flex flex-wrap items-center justify-between gap-2 border-t border-white/7 pt-2 text-[5px] text-white/28"><span>analytic Jacobian · complex-step oracle · full covariance decomposition</span><span className="text-amber-100/45">fixture performance / measured holdout / residual closure unavailable</span></footer>
    </>}
  </section>;
}
function Formula({ children }: Readonly<{ children: string }>) { return <div className="border-l-2 border-violet-100/18 bg-violet-100/[.02] px-2 py-1.5 text-violet-50/50">{children}</div>; }
function Metric({ label, value, tone }: Readonly<{ label: string; value: string; tone: "violet" | "cyan" | "lime" | "amber" | "rose" }>) { const color = tone === "violet" ? "text-violet-100/58" : tone === "cyan" ? "text-cyan-100/58" : tone === "lime" ? "text-lime-100/58" : tone === "amber" ? "text-amber-100/58" : "text-rose-100/58"; return <div className="bg-black/42 px-2.5 py-2"><div className="text-[5px] uppercase tracking-[.1em] text-white/23">{label}</div><div className={`mt-0.5 text-[7px] ${color}`}>{value}</div></div>; }
