"use client";

import { useEffect, useSyncExternalStore } from "react";
import {
  getKerrInstrumentSpectralAdmissionSnapshotV425,
  loadKerrInstrumentSpectralAdmissionSummaryV425,
  subscribeKerrInstrumentSpectralAdmissionV425,
} from "../lib/kerrInstrumentSpectralAdmissionClientV425";

const EXPORTS = [["ADMISSION JSON", "json"], ["DOMAIN CSV", "csv"], ["TABLE FITS", "fits"], ["DOMAIN PNG", "png"]] as const;
const COLORS = ["#67e8f9", "#5eead4", "#fbbf24"] as const;
const xForNm = (value: number) => 38 + (Math.log10(value) + 1) / 4 * 524;

export default function KerrInstrumentSpectralAdmissionV425() {
  const state = useSyncExternalStore(subscribeKerrInstrumentSpectralAdmissionV425, getKerrInstrumentSpectralAdmissionSnapshotV425, getKerrInstrumentSpectralAdmissionSnapshotV425);
  useEffect(() => { void loadKerrInstrumentSpectralAdmissionSummaryV425().catch(() => undefined); }, []);
  const summary = state.summary;
  return <section className="relative mt-3 overflow-hidden border border-rose-100/15 bg-[radial-gradient(circle_at_82%_18%,rgba(251,113,133,.07),transparent_28%),radial-gradient(circle_at_14%_78%,rgba(34,211,238,.045),transparent_30%),linear-gradient(137deg,rgba(8,3,5,.995),rgba(2,9,12,.99)_58%,rgba(3,7,9,.99))] px-3 py-3 font-mono" data-atlas-kerr-spectral-admission-v425 data-atlas-v425-status={state.status} data-atlas-v425-response-eligible-count="0" data-atlas-v425-response-matrix-applications="0" data-atlas-v425-extrapolation="forbidden" data-atlas-v425-measurement-authority="false" data-atlas-v425-summary-only-in-react-state="true" data-atlas-v425-canvas-created="false" aria-live="polite">
    <div aria-hidden="true" className="pointer-events-none absolute inset-0 opacity-25 [background-image:repeating-linear-gradient(100deg,transparent_0_18px,rgba(251,113,133,.025)_19px,transparent_20px_38px)]" />
    <header className="relative grid gap-3 border-b border-white/7 pb-3 lg:grid-cols-[minmax(0,1fr)_auto]"><div><div className="text-[6px] uppercase tracking-[.32em] text-rose-100/43">V425 · spectral-domain quarantine rail</div><h4 className="mt-0.5 font-['Bahnschrift_Condensed','DIN_Condensed',sans-serif] text-[20px] font-light uppercase tracking-[.17em] text-rose-50/92">Instrument applicability firewall</h4><p className="mt-1 max-w-[112ch] text-[6px] leading-relaxed text-white/38">v424 的三档预测位于约 0.300–29.98 nm，而 v413 非理想响应 fixture 仅覆盖 400–800 nm。24/24 条源预测都被拒绝跨波段外推；理想调制代数仍保留，但不被冒充为真实 HWP/Wollaston 仪器响应。</p></div><div className="flex items-center gap-2 self-start border border-rose-100/14 bg-rose-100/[.025] px-2.5 py-1.5"><span className={`h-1.5 w-1.5 rounded-full ${state.status === "ready" ? "bg-rose-200/80 shadow-[0_0_14px_rgba(251,113,133,.3)]" : state.status === "loading" ? "animate-pulse bg-cyan-200/60" : "bg-amber-200/60"}`} /><div><div className="text-[5px] uppercase tracking-[.12em] text-white/22">firewall channel</div><div className="mt-0.5 text-[6px] uppercase text-rose-100/62">{state.status}</div></div></div></header>
    {!summary ? <div className="relative mt-2 border-l-2 border-rose-100/24 px-2 py-1.5 text-[6px] text-rose-50/48">{state.status === "loading" || state.status === "idle" ? "正在读取光谱适用性审计…" : `光谱适用性审计不可用 · ${state.reason ?? "request-failed"}`}</div> : <>
      <div className="relative mt-3 grid gap-3 xl:grid-cols-[minmax(0,1.45fr)_300px]">
        <figure className="relative min-h-[300px] overflow-hidden border border-rose-100/10 bg-black/25 px-3 pb-3 pt-8"><figcaption className="absolute left-3 top-2 text-[5px] uppercase tracking-[.14em] text-rose-100/38">log10 vacuum wavelength · nm · zero overlap</figcaption><svg viewBox="0 0 600 270" className="h-full min-h-[250px] w-full" role="img" aria-label="V424 wavelengths compared with the V413 calibration domain"><line x1="38" y1="150" x2="562" y2="150" stroke="rgba(148,190,194,.38)" strokeWidth="1.4" />{[-1,0,1,2,3].map((power) => { const x=xForNm(10**power); return <g key={power}><line x1={x} y1="142" x2={x} y2="158" stroke="rgba(148,190,194,.4)" /><text x={x-14} y="178" fill="rgba(207,250,254,.38)" fontSize="8">1e{power}</text></g>; })}<rect x={xForNm(400)} y="102" width={xForNm(800)-xForNm(400)} height="96" fill="rgba(190,242,100,.12)" stroke="rgba(190,242,100,.65)" /><text x={xForNm(400)-12} y="90" fill="rgba(217,249,157,.72)" fontSize="8">V413 400–800 nm</text>{summary.bandSummaries.map((band,index) => { const x=xForNm(band.vacuumWavelengthNm); return <g key={band.observedFrequencyHz}><line x1={x} y1="54" x2={x} y2="206" stroke={COLORS[index]} strokeWidth="2.3" /><path d={`M ${x} 45 l -6 12 h 12 z`} fill={COLORS[index]} /><text x={x-22} y="30" fill={COLORS[index]} fontSize="8">{band.vacuumWavelengthNm.toPrecision(4)} nm</text><text x={x-20} y="224" fill={COLORS[index]} fontSize="7">{band.photonEnergyEv.toPrecision(4)} eV</text></g>; })}<line x1={xForNm(29.9792458)+8} y1="120" x2={xForNm(400)-8} y2="120" stroke="rgba(251,191,36,.75)" strokeWidth="1.5" /><text x={(xForNm(29.9792458)+xForNm(400))/2-56} y="110" fill="rgba(253,230,138,.7)" fontSize="7">NO DOMAIN OVERLAP</text></svg><div className="absolute bottom-2 left-3 text-[5px] text-white/25">理想算子可作为模型；非理想仪器投影必须等待匹配波段的实测响应。</div></figure>
        <aside className="grid content-start gap-px bg-white/6 sm:grid-cols-2 xl:grid-cols-1"><Metric label="sources audited" value="24 / 24" tone="cyan" /><Metric label="response eligible" value="0 / 24" tone="rose" /><Metric label="matrix applications" value="0" tone="rose" /><Metric label="nearest domain gap" value={`${summary.metrics.nearestLowerBoundaryGapFactor.toFixed(2)}×`} tone="amber" /><Metric label="farthest domain gap" value={`${summary.metrics.farthestLowerBoundaryGapFactor.toFixed(2)}×`} tone="amber" /><Metric label="Python oracle Δ" value={summary.metrics.maximumPythonOracleRelativeDifference.toExponential(1)} tone="lime" /><Metric label="extrapolation" value="FORBIDDEN" tone="rose" /><Metric label="dense authority" value="0 / 49" tone="amber" /></aside>
      </div>
      <div className="relative mt-3 grid gap-px bg-white/6 sm:grid-cols-2 lg:grid-cols-4">{EXPORTS.map(([label,format]) => <a key={format} href={`/api/atlas/relativity-evidence/v425/spectral-admission?download=${format}`} download className="atlas-accessible-focus bg-black/42 px-2.5 py-2 transition-colors hover:bg-rose-100/[.05]"><div className="text-[7px] text-rose-100/60">{label}</div><div className="mt-0.5 text-[5px] text-white/25">{format === "fits" ? "频率/波长/能量 admission table，无 image HDU" : format === "png" ? "对数波长域诊断，不是探测器图像" : "24-row fail-closed provenance"}</div></a>)}</div>
      <footer className="relative mt-2 flex flex-wrap items-center justify-between gap-2 border-t border-white/7 pt-2 text-[5px] text-white/28"><span>λ=c/f · E=hf · exact SI constants</span><span className="text-rose-100/48">response unavailable ≠ zero response · browser not run</span></footer>
    </>}
  </section>;
}
function Metric({label,value,tone}:Readonly<{label:string;value:string;tone:"cyan"|"rose"|"amber"|"lime"}>){const color=tone==="cyan"?"text-cyan-100/58":tone==="rose"?"text-rose-100/58":tone==="amber"?"text-amber-100/56":"text-lime-100/56";return <div className="bg-black/40 px-2.5 py-2"><div className="text-[5px] uppercase tracking-[.1em] text-white/23">{label}</div><div className={`mt-0.5 text-[7px] ${color}`}>{value}</div></div>;}
