"use client";

import { useEffect, useSyncExternalStore } from "react";
import { getKerrMeasuredAdmissionSnapshotV434, loadKerrMeasuredAdmissionSummaryV434, subscribeKerrMeasuredAdmissionV434 } from "../lib/kerrHighEnergyMeasuredAdmissionClientV434";

const EXPORTS = [
  ["ADMISSION JSON", "json", "摘要、门禁和缺失要求"], ["VALIDATOR ORACLE", "oracle", "固定 fixture 与 12 类拒绝 mutation"], ["CONTRACT", "contract", "实测 authority pack 合同"], ["FIXTURE", "fixture", "仅用于 validator，不是实测数据"], ["GATE CSV", "csv", "九项 gate 状态"], ["STATUS FITS", "fits", "准入状态，不是探测器图像"], ["FIREWALL MAP", "png", "准入防火墙图，不是仪器性能图"],
] as const;

export default function KerrHighEnergyMeasuredAdmissionV434() {
  const state = useSyncExternalStore(subscribeKerrMeasuredAdmissionV434, getKerrMeasuredAdmissionSnapshotV434, getKerrMeasuredAdmissionSnapshotV434);
  useEffect(() => { void loadKerrMeasuredAdmissionSummaryV434().catch(() => undefined); }, []);
  const summary = state.summary;
  return <section className="relative mt-3 overflow-hidden border border-amber-100/14 bg-[radial-gradient(circle_at_8%_8%,rgba(251,191,36,.09),transparent_28%),radial-gradient(circle_at_92%_18%,rgba(34,211,238,.06),transparent_24%),linear-gradient(132deg,rgba(10,7,3,.995),rgba(9,8,5,.99)_54%,rgba(3,9,10,.985))] p-3 font-mono text-white/54" data-atlas-kerr-high-energy-measured-admission-v434 data-atlas-v434-status={state.status} data-atlas-v434-required-gates="9" data-atlas-v434-passed-fixture-gates="8" data-atlas-v434-measured-pack="false" data-atlas-v434-science-admitted="false" data-atlas-v434-summary-only-in-react-state="true" data-atlas-v434-canvas-created="false" aria-live="polite">
    <div aria-hidden="true" className="pointer-events-none absolute inset-0 opacity-30 [background-image:linear-gradient(90deg,transparent_49.8%,rgba(251,191,36,.04)_50%,transparent_50.2%),repeating-linear-gradient(0deg,transparent_0_18px,rgba(34,211,238,.018)_19px,transparent_20px_39px)]" />
    <header className="relative flex flex-wrap items-start justify-between gap-3 border-b border-white/7 pb-3"><div><div className="text-[6px] uppercase tracking-[.34em] text-amber-100/45">V434 · measured authority admission firewall</div><h4 className="mt-1 font-['Bahnschrift_Condensed','DIN_Condensed',sans-serif] text-[21px] font-light uppercase tracking-[.18em] text-amber-50/92">The gate stays closed</h4><p className="mt-1 max-w-[116ch] text-[6px] leading-relaxed text-white/38">v428 容器安全、v429 独立 holdout 协议与 v433 联合 covariance 已合并成单一准入合同。结构验证只能证明 pack 可审计，不能把 fixture 或占位指标变成 measured authority。</p></div><Status status={state.status} /></header>
    {!summary ? <div className="relative mt-3 border-l-2 border-amber-100/24 bg-amber-100/[.025] px-3 py-2 text-[6px] text-amber-50/48">{state.status === "loading" || state.status === "idle" ? "正在读取 measured admission firewall…" : `准入证据不可用 · ${state.reason ?? "request-failed"}`}</div> : <>
      <div className="relative mt-3 grid gap-3 xl:grid-cols-[minmax(0,1.35fr)_320px]"><div className="grid gap-3"><div className="grid gap-px bg-white/6 sm:grid-cols-3">{[["fixture validator", `${summary.gates.passedFixtureGateCount} / 8`, "cyan"], ["required gates", `${summary.gates.requiredGateCount}`, "lime"], ["independent review", summary.gates.independentReviewStatus.toUpperCase(), "amber"]].map(([label, value, tone]) => <Metric key={label} label={label} value={value} tone={tone as "lime" | "cyan" | "amber"} />)}</div><div className="grid gap-3 md:grid-cols-2">{summary.scienceBoundary.missingRequirements.map((requirement, index) => <article key={requirement} className="relative border border-amber-100/12 bg-black/36 p-3"><div className="absolute left-0 top-0 h-full w-px bg-amber-200/50" /><div className="flex items-center justify-between"><span className="text-[6px] uppercase tracking-[.18em] text-white/28">0{index + 1} · missing requirement</span><span className="text-[5px] text-amber-100/60">BLOCKED</span></div><h5 className="mt-3 text-[10px] tracking-[.08em] text-amber-50/72">{requirement.replaceAll("-", " ")}</h5><p className="mt-2 text-[6px] leading-relaxed text-white/34">没有实测 artifact、独立 provenance 和 review sign-off 前，这一项不产生 Science admission。</p></article>)}</div><div className="border border-cyan-100/10 bg-black/26 p-3"><div className="text-[5px] uppercase tracking-[.16em] text-cyan-100/42">Validator firewall</div><div className="mt-3 grid gap-2 text-[6px] text-white/40"><Step index="01" text="identity / channel layout / SHA 先锁定" /><Step index="02" text="calibration、fit、holdout campaign 与 raw event 必须互斥" /><Step index="03" text="preregistered likelihood 与 cross-block proof 不允许 post-hoc 调参" /><Step index="04" text="最终还需要 independent measured review；fixture 永远不可晋级" /></div></div></div><aside className="grid content-start gap-px bg-white/6 sm:grid-cols-2 xl:grid-cols-1"><Metric label="measured packs" value="0" tone="amber" /><Metric label="measured response" value="UNAVAILABLE" tone="amber" /><Metric label="measured likelihood" value="UNAVAILABLE" tone="amber" /><Metric label="independent holdout" value="UNAVAILABLE" tone="amber" /><Metric label="cross-block proof" value="UNAVAILABLE" tone="amber" /><Metric label="Science applications" value="0" tone="amber" /><Metric label="dense campaign" value="0 / 49" tone="amber" /><div className="bg-black/40 px-3 py-3"><div className="text-[5px] uppercase tracking-[.14em] text-white/24">admission status</div><div className="mt-2 text-[14px] font-light uppercase tracking-[.12em] text-rose-100/76">Blocked</div><div className="mt-1 text-[5px] leading-relaxed text-white/30">structural validator qualified · measured authority absent</div></div></aside></div>
      <div className="relative mt-3 grid gap-px bg-white/6 sm:grid-cols-2 lg:grid-cols-4">{EXPORTS.map(([label, format, detail]) => <a key={format} href={`/api/atlas/relativity-evidence/v434/measured-admission?download=${format}`} download className="atlas-accessible-focus bg-black/42 px-2.5 py-2 transition-colors hover:bg-amber-100/[.05]"><div className="text-[7px] text-amber-100/62">{label}</div><div className="mt-0.5 text-[5px] leading-relaxed text-white/27">{detail}</div></a>)}</div><footer className="relative mt-2 flex flex-wrap items-center justify-between gap-2 border-t border-white/7 pt-2 text-[5px] text-white/28"><span>v433 joint nuisance boundary · CPU authority · no network · no measured import attempt</span><span className="text-rose-100/52">fixture ≠ instrument · blocked ≠ zero data</span></footer>
    </>}
  </section>;
}

function Status({ status }: Readonly<{ status: string }>) { return <div className="flex items-center gap-2 border border-amber-100/14 bg-amber-100/[.025] px-2.5 py-1.5"><span className={`h-1.5 w-1.5 rounded-full ${status === "ready" ? "bg-amber-200/75 shadow-[0_0_14px_rgba(251,191,36,.3)]" : status === "loading" ? "animate-pulse bg-cyan-200/65" : "bg-rose-200/70"}`} /><div><div className="text-[5px] uppercase tracking-[.12em] text-white/22">admission channel</div><div className="mt-0.5 text-[6px] uppercase text-amber-100/62">{status}</div></div></div>; }
function Step({ index, text }: Readonly<{ index: string; text: string }>) { return <div className="flex gap-2 border-l-2 border-cyan-100/16 bg-cyan-100/[.02] px-2 py-1.5"><span className="text-cyan-100/42">{index}</span><span>{text}</span></div>; }
function Metric({ label, value, tone }: Readonly<{ label: string; value: string; tone: "lime" | "cyan" | "amber" }>) { const color = tone === "lime" ? "text-lime-100/60" : tone === "cyan" ? "text-cyan-100/60" : "text-amber-100/60"; return <div className="bg-black/42 px-2.5 py-2"><div className="text-[5px] uppercase tracking-[.1em] text-white/23">{label}</div><div className={`mt-0.5 text-[7px] ${color}`}>{value}</div></div>; }
