"use client";

import { useEffect, useState } from "react";
import { parseKerrScienceBandObservationArtifactV350, type KerrScienceBandObservationArtifactV350 } from "../lib/kerrScienceBandObservationV350";

type State = "loading" | "ready" | "unavailable" | "error";
export default function KerrScienceBandObservationSurfaceV350() {
  const [artifact, setArtifact] = useState<KerrScienceBandObservationArtifactV350 | null>(null); const [state, setState] = useState<State>("loading");
  useEffect(() => { const controller = new AbortController(); void fetch("/api/atlas/relativity-evidence/v350/observation", { cache: "no-store", signal: controller.signal }).then(async (response) => { const value = await response.json() as { available?: boolean; reason?: string; artifact?: unknown }; if (response.ok && value.available === false && value.reason === "lite-boundary") return null; if (!response.ok || value.available !== true || !value.artifact) throw new Error(value.reason ?? "v350-observation-unavailable"); return parseKerrScienceBandObservationArtifactV350(value.artifact); }).then((value) => { if (controller.signal.aborted) return; if (!value) { setState("unavailable"); return; } setArtifact(value); setState("ready"); }).catch(() => { if (!controller.signal.aborted) setState("error"); }); return () => controller.abort(); }, []);
  const maxEnergy = artifact ? Math.max(...artifact.rows.map((row) => row.energyRadianceWM2Sr)) : null;
  return <section className="relative mt-2 overflow-hidden rounded-[10px] border border-cyan-100/15 bg-[linear-gradient(145deg,rgba(4,20,29,.94),rgba(5,9,17,.98)_68%,rgba(9,18,29,.96))] p-3 font-mono text-[8px] text-white/52" data-atlas-kerr-band-observation-v350 data-atlas-kerr-band-observation-status={state}>
    <div className="relative flex flex-wrap items-end justify-between gap-2"><div><div className="text-[7px] uppercase tracking-[0.2em] text-cyan-100/46">Band observation v350</div><div className="mt-0.5 text-[13px] tracking-[0.045em] text-cyan-50/90">Units / applicability / provenance</div></div><div className="text-right text-[7px] text-cyan-100/64">{artifact?.denseCampaignStatus ?? "dense unavailable"}<br /><span className="text-white/28">{state === "ready" ? "read-only artifact" : state}</span></div></div>
    {state === "ready" && artifact ? <><div className="relative mt-3 grid gap-1.5 sm:grid-cols-3">{artifact.definitions.map((band) => <div key={band.id} className="rounded border border-white/[0.08] bg-black/20 px-2 py-2"><div className="text-[7px] uppercase text-white/30">{band.label}</div><div className="mt-1 text-[10px] text-cyan-50/84">{band.physicalRangeLabel}</div><div className="mt-1 text-[7px] text-white/38">{band.energyRadianceUnit}<br />{band.syntheticExpectationUnit}</div></div>)}</div><div className="relative mt-2 grid gap-1.5 sm:grid-cols-4"><div className="rounded border border-white/[0.08] bg-black/20 px-2 py-2"><div className="text-[7px] uppercase text-white/30">rows</div><div className="mt-1 text-[12px] text-cyan-50/84">{artifact.counts.rowCount}</div><div className="text-[7px] text-white/32">4 rays × 3 bands</div></div><div className="rounded border border-white/[0.08] bg-black/20 px-2 py-2"><div className="text-[7px] uppercase text-white/30">energy radiance</div><div className="mt-1 text-[10px] text-emerald-50/84">AVAILABLE</div><div className="text-[7px] text-white/32">max {maxEnergy?.toExponential(3)} W m⁻² sr⁻¹</div></div><div className="rounded border border-white/[0.08] bg-black/20 px-2 py-2"><div className="text-[7px] uppercase text-white/30">detector counts</div><div className="mt-1 text-[10px] text-amber-50/84">UNAVAILABLE</div><div className="text-[7px] text-white/32">synthetic expectation only</div></div><div className="rounded border border-white/[0.08] bg-black/20 px-2 py-2"><div className="text-[7px] uppercase text-white/30">celestial flux</div><div className="mt-1 text-[10px] text-amber-50/84">UNAVAILABLE</div><div className="text-[7px] text-white/32">WCS / solid angle boundary</div></div></div><div className="relative mt-2 border-t border-white/[0.06] pt-2 text-[7px] text-white/32">Source chain · v348 ratio artifact · v346 indexed probe · v332 synthetic instrument · authority SHA {artifact.source.fullShortAuthoritySha256.slice(0, 12)}… · never cinematic color input</div></> : <div className="relative mt-3 rounded border border-white/[0.08] bg-black/20 px-2 py-2 text-[8px] text-white/42">{state === "loading" ? "Loading bounded observation provenance…" : state === "error" ? "Observation provenance unavailable; fail closed." : "Lite boundary: observation layer unavailable."}</div>}
  </section>;
}
