"use client";

import { useEffect, useSyncExternalStore, type CSSProperties } from "react";
import { getKerrIdealPolarimeterSnapshotV410, loadKerrIdealPolarimeterSummaryV410, subscribeKerrIdealPolarimeterV410 } from "../lib/kerrIdealPolarimeterClientV410";
const exp = (value: number) => value === 0 ? "0" : value.toExponential(2);

export default function KerrIdealPolarimeterSurfaceV410() {
  const state = useSyncExternalStore(subscribeKerrIdealPolarimeterV410, getKerrIdealPolarimeterSnapshotV410, getKerrIdealPolarimeterSnapshotV410); useEffect(() => { void loadKerrIdealPolarimeterSummaryV410().catch(() => undefined); }, []); const summary = state.summary;
  return <section className="relative mt-3 overflow-hidden border border-fuchsia-100/12 bg-[radial-gradient(circle_at_20%_-10%,rgba(232,121,249,.075),transparent_30%),radial-gradient(circle_at_92%_100%,rgba(56,189,248,.06),transparent_34%),linear-gradient(111deg,rgba(11,5,15,.97),rgba(3,7,12,.96)_58%,rgba(4,13,15,.91))] px-3 py-3 font-mono" data-atlas-kerr-ideal-polarimeter-v410 data-atlas-v410-status={state.status} data-atlas-v410-summary-only-in-react-state="true" data-atlas-v410-modulation-rows-in-react-state="false" data-atlas-v410-detector-electrons-available="false" data-atlas-v410-measured-polarimeter-qualified="false" data-atlas-v410-science-buffer-mutation="false" data-atlas-v410-cinematic-buffer-mutation="false" data-atlas-v410-canvas-created="false" aria-live="polite">
    <div aria-hidden="true" className="pointer-events-none absolute inset-0 opacity-25 [background-image:repeating-linear-gradient(118deg,transparent_0_47px,rgba(232,121,249,.03)_48px,transparent_49px_96px)]" />
    <header className="relative grid gap-3 border-b border-white/7 pb-2.5 lg:grid-cols-[minmax(0,1fr)_auto]"><div><div className="text-[6px] uppercase tracking-[.25em] text-fuchsia-100/43">V410 · ideal HWP + Wollaston operator</div><h4 className="mt-0.5 font-['Bahnschrift_Condensed','DIN_Condensed',sans-serif] text-[19px] font-light uppercase tracking-[.16em] text-fuchsia-50/88">Dual-beam modulation bench</h4><p className="mt-1 max-w-[94ch] text-[6px] leading-relaxed text-white/34">四个半波片角度将 v409 的 I/Q/U 映射为 ordinary / extraordinary 双束，再独立重建线偏振。该层验证测量代数，不代表真实偏振仪标定或电子计数。</p></div><div className="flex items-center gap-2 self-start border border-fuchsia-100/14 bg-fuchsia-100/[.025] px-2.5 py-1.5"><span className={`h-1.5 w-1.5 rounded-full ${state.status === "ready" ? "bg-lime-200/70 shadow-[0_0_14px_rgba(190,242,100,.34)]" : state.status === "loading" ? "animate-pulse bg-fuchsia-200/60" : "bg-amber-200/60"}`} /><div><div className="text-[5px] uppercase tracking-[.12em] text-white/22">operator channel</div><div className="mt-0.5 text-[6px] uppercase text-fuchsia-100/60">{state.status}</div></div></div></header>
    {!summary ? <div className="relative mt-2 border-l-2 border-fuchsia-100/22 px-2 py-1.5 text-[6px] text-fuchsia-50/44">{state.status === "loading" || state.status === "idle" ? "读取理想双束调制摘要…" : `双束调制摘要不可用 · ${state.reason ?? "request-failed"}`}</div> : <>
      <div className="relative mt-2 grid gap-px bg-white/6 xl:grid-cols-[minmax(230px,.52fr)_minmax(0,1.48fr)]">
        <div className="bg-black/36 px-3 py-2.5"><div className="text-[5px] uppercase tracking-[.14em] text-white/24">four-state analyzer</div><div className="mt-3 grid grid-cols-4 gap-2">{summary.operator.hwpAnglesDeg.map((angle, index) => <div key={angle} className="grid place-items-center gap-1"><div className="relative grid h-9 w-9 place-items-center rounded-full border border-fuchsia-100/14 bg-fuchsia-100/[.025]"><span className="absolute h-px w-7 bg-gradient-to-r from-transparent via-fuchsia-100/70 to-transparent" style={{ transform: `rotate(${angle}deg)` }} /><span className="h-1 w-1 rounded-full bg-cyan-100/65" /></div><span className="text-[5px] text-fuchsia-100/48">θ{index} {angle}°</span></div>)}</div><div className="mt-3 border-t border-white/7 pt-2 font-['Cambria_Math','Times_New_Roman',serif] text-[8px] leading-relaxed text-cyan-50/56">F(θ) = q cos 4θ + u sin 4θ</div><div className="mt-1 text-[5px] leading-relaxed text-white/25">Patat &amp; Romaniello · DOI 10.1086/497581 · equations 1–7 verified</div></div>
        <div className="grid gap-px bg-white/6 sm:grid-cols-2 xl:grid-cols-4">{summary.representativeRays.map((ray) => { const style = { "--atlas-v410-asymmetry": `${Math.min(100, ray.maximumBeamAsymmetry * 4000)}%`, "--atlas-v410-evpa": `${ray.evpaDeg}deg` } as CSSProperties; return <article key={ray.rayId} style={style} className="relative overflow-hidden bg-black/36 px-2.5 py-2.5" data-atlas-v410-ray={ray.rayId}><div aria-hidden="true" className="absolute inset-x-0 bottom-0 h-[2px] bg-gradient-to-r from-fuchsia-300/70 via-cyan-200/45 to-transparent" style={{ width: "var(--atlas-v410-asymmetry)" }} /><div className="flex items-center justify-between"><span className="text-[7px] text-fuchsia-50/72">{ray.rayId}</span><span className="text-[5px] text-white/24">p {(ray.linearFraction * 100).toFixed(3)}%</span></div><div className="mt-3 grid grid-cols-[40px_1fr] items-center gap-2"><div className="relative grid h-9 w-9 place-items-center rounded-full border border-cyan-100/12"><span className="absolute h-px w-7 bg-cyan-100/65" style={{ transform: "rotate(var(--atlas-v410-evpa))" }} /><span className="h-1 w-1 rounded-full bg-fuchsia-100/75" /></div><div className="grid gap-0.5 text-[5px]"><span className="text-white/22">EVPA <b className="font-normal text-cyan-100/55">{ray.evpaDeg.toFixed(2)}°</b></span><span className="text-white/22">beam Δ <b className="font-normal text-fuchsia-100/55">{(ray.maximumBeamAsymmetry * 100).toFixed(3)}%</b></span><span className="text-white/22">u <b className="font-normal text-lime-100/50">{exp(ray.maximumPolarizationOnlyUncertainty)}</b></span></div></div></article>; })}</div>
      </div>
      <div className="relative mt-px grid gap-px bg-white/6 sm:grid-cols-2 lg:grid-cols-4"><Metric label="modulation rows" value="96" tone="fuchsia" /><Metric label="beam intensities" value="192" tone="cyan" /><Metric label="max normalized residual" value={exp(Math.max(summary.maxima.qNormalizedAbsolute, summary.maxima.uNormalizedAbsolute))} tone="lime" /><Metric label="detector electrons" value="UNAVAILABLE" tone="amber" /></div>
      <div className="relative mt-px border-l-2 border-amber-200/30 bg-amber-100/[.025] px-2.5 py-2 text-[5px] leading-relaxed text-amber-50/46">缺少：HWP 波长依赖延迟、双束透过率比、消光比、角度零点、仪器 Mueller matrix 与 covariance。v368 measured detector authority 同样未就绪；不使用 synthetic fallback。</div>
      <footer className="relative mt-2 flex flex-wrap items-center justify-between gap-2 text-[5px] text-white/27"><span>Stokes V unavailable · no photon/electron counts · no observed exposure · no dense image</span><a href="/api/atlas/relativity-evidence/v410/ideal-polarimeter?download=1" download className="atlas-accessible-focus border border-fuchsia-100/15 bg-fuchsia-100/[.025] px-2 py-1 uppercase tracking-[.08em] text-fuchsia-100/55">下载 96-row artifact</a></footer>
    </>}
  </section>;
}
function Metric({ label, value, tone }: Readonly<{ label: string; value: string; tone: "fuchsia" | "cyan" | "lime" | "amber" }>) { const color = tone === "fuchsia" ? "text-fuchsia-100/58" : tone === "cyan" ? "text-cyan-100/55" : tone === "lime" ? "text-lime-100/54" : "text-amber-100/55"; return <div className="bg-black/36 px-2.5 py-1.5"><div className="text-[5px] uppercase tracking-[.11em] text-white/23">{label}</div><div className={`mt-0.5 text-[7px] ${color}`}>{value}</div></div>; }
