"use client";

import { useEffect, useSyncExternalStore } from "react";
import { getKerrPolarimeterInversionSnapshotV412, loadKerrPolarimeterInversionSummaryV412, subscribeKerrPolarimeterInversionV412 } from "../lib/kerrPolarimeterInversionClientV412";

const exp = (value: number) => value === 0 ? "0" : value.toExponential(2);
const CELLS = Object.freeze(Array.from({ length: 16 }, (_, index) => ({ row: Math.floor(index / 4), column: index % 4 })));

export default function KerrPolarimeterInversionSurfaceV412() {
  const state = useSyncExternalStore(subscribeKerrPolarimeterInversionV412, getKerrPolarimeterInversionSnapshotV412, getKerrPolarimeterInversionSnapshotV412); useEffect(() => { void loadKerrPolarimeterInversionSummaryV412().catch(() => undefined); }, []); const summary = state.summary;
  return <section className="relative mt-3 overflow-hidden border border-cyan-100/14 bg-[radial-gradient(ellipse_at_18%_0%,rgba(34,211,238,.075),transparent_31%),radial-gradient(ellipse_at_88%_100%,rgba(190,242,100,.045),transparent_32%),linear-gradient(118deg,rgba(2,10,13,.98),rgba(4,6,9,.97)_58%,rgba(8,8,3,.94))] px-3 py-3 font-mono" data-atlas-kerr-polarimeter-inversion-v412 data-atlas-v412-status={state.status} data-atlas-v412-summary-only-in-react-state="true" data-atlas-v412-matrices-in-react-state="false" data-atlas-v412-measured-inversion-executed="false" data-atlas-v412-authority-granted="false" data-atlas-v412-science-buffer-mutation="false" data-atlas-v412-cinematic-buffer-mutation="false" data-atlas-v412-canvas-created="false" aria-live="polite">
    <div aria-hidden="true" className="pointer-events-none absolute inset-0 opacity-30 [background-image:repeating-linear-gradient(132deg,transparent_0_53px,rgba(103,232,249,.025)_54px,transparent_55px_108px)]" />
    <header className="relative grid gap-3 border-b border-white/7 pb-2.5 lg:grid-cols-[minmax(0,1fr)_auto]"><div><div className="text-[6px] uppercase tracking-[.27em] text-cyan-100/43">V412 · generalized Mueller inversion</div><h4 className="mt-0.5 font-['Bahnschrift_Condensed','DIN_Condensed',sans-serif] text-[19px] font-light uppercase tracking-[.16em] text-cyan-50/90">Stokes reconstruction engine</h4><p className="mt-1 max-w-[96ch] text-[6px] leading-relaxed text-white/36">独立 TypeScript 与 Python 路径验证 4×4 响应反演、广义加权解和一阶 covariance 传播。当前只对确定性 fixture 合格；没有真实标定包时不会生成实测 Stokes authority。</p></div><div className="flex items-center gap-2 self-start border border-cyan-100/14 bg-cyan-100/[.025] px-2.5 py-1.5"><span className={`h-1.5 w-1.5 rounded-full ${state.status === "ready" ? "bg-cyan-200/75 shadow-[0_0_14px_rgba(103,232,249,.3)]" : state.status === "loading" ? "animate-pulse bg-lime-200/60" : "bg-amber-200/60"}`} /><div><div className="text-[5px] uppercase tracking-[.12em] text-white/22">inversion channel</div><div className="mt-0.5 text-[6px] uppercase text-cyan-100/62">{state.status}</div></div></div></header>
    {!summary ? <div className="relative mt-2 border-l-2 border-cyan-100/24 px-2 py-1.5 text-[6px] text-cyan-50/48">{state.status === "loading" || state.status === "idle" ? "读取反演门禁摘要…" : `反演摘要不可用 · ${state.reason ?? "request-failed"}`}</div> : <>
      <div className="relative mt-2 grid gap-px bg-white/6 xl:grid-cols-[minmax(220px,.55fr)_minmax(0,1.45fr)]"><article className="bg-black/38 px-3 py-3"><div className="flex items-center justify-between"><div><div className="text-[5px] uppercase tracking-[.15em] text-white/24">response lattice</div><div className="mt-1 text-[8px] text-cyan-100/62">M · S → D</div></div><span className="text-[5px] uppercase text-lime-100/48">fixture qualified</span></div><div className="mt-3 grid w-fit grid-cols-4 gap-1 border border-cyan-100/10 bg-cyan-100/[.018] p-2">{CELLS.map((cell) => <span key={`${cell.row}-${cell.column}`} className={`h-5 w-5 border ${cell.row === cell.column ? "border-lime-100/24 bg-lime-100/[.07]" : "border-cyan-100/12 bg-cyan-100/[.025]"}`} />)}</div><div className="mt-3 text-[5px] leading-relaxed text-white/28">measurement covariance 与 calibration covariance 分开保存；未证明独立性，因此不输出虚假的单一总误差。</div></article><article className="grid gap-px bg-white/6 sm:grid-cols-2 lg:grid-cols-3"><Metric label="response κ₁" value={summary.metrics.responseConditionNumber.toFixed(2)} tone="cyan" /><Metric label="Fisher κ₁" value={summary.metrics.fisherConditionNumber.toExponential(2)} tone="cyan" /><Metric label="inverse residual" value={exp(summary.metrics.responseInverseResidualMaximum)} tone="lime" /><Metric label="weighted/direct Δ" value={exp(summary.metrics.weightedDirectDifferenceMaximum)} tone="lime" /><Metric label="Jacobian FD Δ" value={exp(summary.metrics.calibrationJacobianFiniteDifferenceMaximum)} tone="lime" /><Metric label="measured authority" value="BLOCKED" tone="amber" /></article></div>
      <div className="relative mt-px grid gap-px bg-white/6 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Python Stokes Δ" value={exp(summary.oracleComparison.maximumReconstructedStokesAbsolute)} tone="lime" /><Metric label="measurement Cov Δ" value={exp(summary.oracleComparison.maximumMeasurementCovarianceAbsolute)} tone="lime" /><Metric label="calibration Cov Δ" value={exp(summary.oracleComparison.maximumCalibrationCovarianceAbsolute)} tone="lime" /><Metric label="condition Δrel" value={exp(summary.oracleComparison.maximumConditionNumberRelative)} tone="lime" /></div>
      <footer className="relative mt-2 flex flex-wrap items-center justify-between gap-2 border-t border-white/7 pt-2 text-[5px] text-white/28"><span>Fixture-only · no measured pack · no Science/Cinematic mutation · no dense image</span><a href="/api/atlas/relativity-evidence/v412/polarimeter-inversion?download=1" download className="atlas-accessible-focus border border-cyan-100/16 bg-cyan-100/[.025] px-2 py-1 uppercase tracking-[.09em] text-cyan-100/58">下载完整 inversion artifact</a></footer>
    </>}
  </section>;
}

function Metric({ label, value, tone }: Readonly<{ label: string; value: string; tone: "lime" | "cyan" | "amber" }>) { const color = tone === "lime" ? "text-lime-100/58" : tone === "cyan" ? "text-cyan-100/56" : "text-amber-100/58"; return <div className="bg-black/38 px-2.5 py-2"><div className="text-[5px] uppercase tracking-[.11em] text-white/23">{label}</div><div className={`mt-0.5 text-[7px] ${color}`}>{value}</div></div>; }
