"use client";
import { useEffect, useSyncExternalStore } from "react";
import { getKerrPredictedStokesSnapshotV423, loadKerrPredictedStokesSummaryV423, subscribeKerrPredictedStokesV423 } from "../lib/kerrPredictedStokesAdmissionClientV423";
const EXPORTS = [["PREDICTION JSON", "json"], ["STOKES CSV", "csv"], ["WCS FITS", "fits"], ["DIAGNOSTIC PNG", "png"]] as const; const COLORS = ["#67e8f9", "#5eead4", "#bef264", "#fbbf24"] as const; const scientific = (value: number) => value === 0 ? "0" : value.toExponential(2);
export default function KerrPredictedStokesAdmissionV423() {
  const state = useSyncExternalStore(subscribeKerrPredictedStokesV423, getKerrPredictedStokesSnapshotV423, getKerrPredictedStokesSnapshotV423); useEffect(() => { void loadKerrPredictedStokesSummaryV423().catch(() => undefined); }, []); const summary = state.summary; const reference = summary?.referenceRows.filter((row) => row.transportMethod === "walker-penrose") ?? [];
  return <section className="relative mt-3 overflow-hidden border border-cyan-100/15 bg-[radial-gradient(circle_at_78%_30%,rgba(34,211,238,.075),transparent_30%),radial-gradient(circle_at_18%_70%,rgba(190,242,100,.035),transparent_28%),linear-gradient(132deg,rgba(1,8,11,.995),rgba(3,8,10,.99)_58%,rgba(10,7,2,.98))] px-3 py-3 font-mono" data-atlas-kerr-predicted-stokes-v423 data-atlas-v423-status={state.status} data-atlas-v423-model-prediction="qualified" data-atlas-v423-measurement-authority="false" data-atlas-v423-detector-authority="false" data-atlas-v423-pixel-authority="false" data-atlas-v423-raster-authority="false" data-atlas-v423-circular-v="unavailable" data-atlas-v423-summary-only-in-react-state="true" data-atlas-v423-canvas-created="false" aria-live="polite">
    <header className="relative grid gap-3 border-b border-white/7 pb-3 lg:grid-cols-[minmax(0,1fr)_auto]"><div><div className="text-[6px] uppercase tracking-[.31em] text-cyan-100/43">V423 · prediction / measurement firewall</div><h4 className="mt-0.5 font-['Bahnschrift_Condensed','DIN_Condensed',sans-serif] text-[20px] font-light uppercase tracking-[.17em] text-cyan-50/92">WCS-linked predicted Stokes</h4><p className="mt-1 max-w-[110ch] text-[6px] leading-relaxed text-white/38">v406 的薄盘与真空传播模型现已按相同 ray identity 接入 v422 连续 WCS 坐标。这里发布 24 条模型预测 I/Q/U，而不是观测数据；V、探测器投影、电子计数、像素采样、raster 与 dense 权威继续不可用。</p></div><div className="flex items-center gap-2 self-start border border-cyan-100/14 bg-cyan-100/[.025] px-2.5 py-1.5"><span className={`h-1.5 w-1.5 rounded-full ${state.status === "ready" ? "bg-cyan-200/75 shadow-[0_0_14px_rgba(103,232,249,.3)]" : state.status === "loading" ? "animate-pulse bg-amber-200/60" : "bg-rose-200/60"}`} /><div><div className="text-[5px] uppercase tracking-[.12em] text-white/22">prediction channel</div><div className="mt-0.5 text-[6px] uppercase text-cyan-100/62">{state.status}</div></div></div></header>
    {!summary ? <div className="relative mt-2 border-l-2 border-cyan-100/24 px-2 py-1.5 text-[6px] text-cyan-50/48">{state.status === "loading" || state.status === "idle" ? "正在读取预测 Stokes admission…" : `预测 Stokes 不可用 · ${state.reason ?? "request-failed"}`}</div> : <>
      <div className="relative mt-3 grid gap-3 xl:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_270px]">
        <figure className="relative aspect-square border border-cyan-100/10 bg-[linear-gradient(rgba(103,232,249,.04)_1px,transparent_1px),linear-gradient(90deg,rgba(103,232,249,.04)_1px,transparent_1px)] bg-[size:12.5%_12.5%]"><figcaption className="absolute left-2 top-2 z-10 text-[5px] uppercase tracking-[.12em] text-cyan-100/36">1e17 Hz · WP · continuous WCS</figcaption><svg viewBox="0 0 384 384" className="absolute inset-0 h-full w-full" role="img" aria-label="Four WCS-linked predicted Stokes sources at the reference frequency">{reference.map((row, index) => { const x = row.continuousCoordinate.pixelX - .5, y = 384.5 - row.continuousCoordinate.pixelY, chi = row.evpaDeg * Math.PI / 180, dx = Math.sin(chi) * 18, dy = -Math.cos(chi) * 18, radius = 4 + 22 * row.predictedSpectralStokes.i; return <g key={row.rayId}><line x1={x - dx} y1={y - dy} x2={x + dx} y2={y + dy} stroke={COLORS[index]} strokeWidth="2.2" vectorEffect="non-scaling-stroke" /><circle cx={x} cy={y} r={radius} fill="rgba(251,191,36,.9)" stroke={COLORS[index]} strokeWidth=".8" vectorEffect="non-scaling-stroke" /><text x={x + 8} y={y + 9} fill={COLORS[index]} fontSize="7">{row.rayId}</text></g>; })}</svg><div className="absolute bottom-2 left-2 text-[5px] text-white/25">marker luminance/size = predicted-I display aid only</div></figure>
        <figure className="relative aspect-square border border-lime-100/10 bg-black/25"><figcaption className="absolute left-2 top-2 z-10 text-[5px] uppercase tracking-[.12em] text-lime-100/36">normalized q/i · u/i · pL=0.12 model</figcaption><svg viewBox="0 0 200 200" className="absolute inset-0 h-full w-full" role="img" aria-label="Normalized predicted Q over I and U over I compass"><circle cx="100" cy="100" r="80" fill="none" stroke="rgba(190,242,100,.24)" strokeWidth=".8" /><line x1="20" y1="100" x2="180" y2="100" stroke="rgba(190,242,100,.14)" strokeWidth=".6" /><line x1="100" y1="20" x2="100" y2="180" stroke="rgba(190,242,100,.14)" strokeWidth=".6" />{reference.map((row, index) => { const x = 100 + row.normalizedOrientation.qOverI / .12 * 80, y = 100 - row.normalizedOrientation.uOverI / .12 * 80; return <g key={row.rayId}><line x1="100" y1="100" x2={x} y2={y} stroke={COLORS[index]} strokeOpacity=".42" strokeWidth=".7" /><circle cx={x} cy={y} r="3.2" fill={COLORS[index]} stroke="#f7fee7" strokeWidth=".5" /></g>; })}</svg><div className="absolute bottom-9 left-2 grid gap-0.5 text-[4px] leading-none">{reference.map((row, index) => <div key={row.rayId} className="flex items-center gap-1.5" style={{ color: COLORS[index] }}><span className="h-1.5 w-1.5 rounded-full" style={{ backgroundColor: COLORS[index] }} />{row.rayId} · I {row.predictedSpectralStokes.i.toExponential(3)}</div>)}</div><div className="absolute bottom-2 left-2 right-2 border-l border-amber-100/20 pl-2 text-[5px] text-amber-100/42">半径 0.12 来自模型假设，不是仪器测量。</div></figure>
        <aside className="grid content-start gap-px bg-white/6 sm:grid-cols-2 xl:grid-cols-1"><Metric label="prediction rows" value="24 QUALIFIED" tone="cyan" /><Metric label="measured rows" value="0 AVAILABLE" tone="amber" /><Metric label="q/i basis Δ" value={scientific(summary.maxima.normalizedQBasisResidual)} tone="lime" /><Metric label="u/i basis Δ" value={scientific(summary.maxima.normalizedUBasisResidual)} tone="lime" /><Metric label="physical cone" value="0 VIOLATIONS" tone="lime" /><Metric label="dense authority" value="0 / 49" tone="amber" /></aside>
      </div>
      <div className="relative mt-3 grid gap-px bg-white/6 sm:grid-cols-2 lg:grid-cols-4">{EXPORTS.map(([label, format]) => <a key={format} href={`/api/atlas/relativity-evidence/v423/predicted-stokes?download=${format}`} download className="atlas-accessible-focus bg-black/42 px-2.5 py-2 transition-colors hover:bg-cyan-100/[.05]"><div className="text-[7px] text-cyan-100/60">{label}</div><div className="mt-0.5 text-[5px] text-white/25">{format === "fits" ? "WCS + prediction table，无 image HDU" : format === "png" ? "稀疏预测诊断，不是科学 raster" : "24-row model prediction provenance"}</div></a>)}</div>
      <footer className="relative mt-2 flex flex-wrap items-center justify-between gap-2 border-t border-white/7 pt-2 text-[5px] text-white/28"><span>{summary.units.spectralStokes} · prediction ≠ measurement</span><span className="text-amber-100/42">V / detector / pixel / raster unavailable · browser not run</span></footer>
    </>}
  </section>;
}
function Metric({ label, value, tone }: Readonly<{ label: string; value: string; tone: "cyan" | "lime" | "amber" }>) { const color = tone === "cyan" ? "text-cyan-100/58" : tone === "lime" ? "text-lime-100/56" : "text-amber-100/54"; return <div className="bg-black/40 px-2.5 py-2"><div className="text-[5px] uppercase tracking-[.1em] text-white/23">{label}</div><div className={`mt-0.5 text-[7px] ${color}`}>{value}</div></div>; }
