"use client";

import { useEffect, useSyncExternalStore } from "react";
import { getKerrHighEnergyLikelihoodStressSnapshotV431, loadKerrHighEnergyLikelihoodStressSummaryV431, subscribeKerrHighEnergyLikelihoodStressV431 } from "../lib/kerrHighEnergyLikelihoodStressClientV431";

const LABELS = Object.freeze({
  "poisson-nominal": "Nominal Poisson",
  "negative-binomial-overdispersion": "Overdispersion",
  "correlated-common-mode": "Common mode",
  "background-mixture": "Background mixture",
  "nonparalyzable-dead-time": "Dead time",
  "pileup-channel-migration": "Pileup migration",
} as const);
const EXPORTS = [["SUMMARY JSON", "json", "六场景有界指标与 authority 边界"], ["FULL ORACLE", "oracle", "固定种子 synthetic holdout；非实测数据"], ["ROUTING CONTRACT", "contract", "基于 provenance 的预注册 likelihood 路由"], ["SCENARIO CSV", "csv", "六类压力诊断摘要"], ["SUMMARY FITS", "fits", "合成压力结果；无探测器图像"], ["ROUTING MAP", "png", "likelihood 压力图；不是仪器性能图"]] as const;

export default function KerrHighEnergyLikelihoodStressV431() {
  const state = useSyncExternalStore(subscribeKerrHighEnergyLikelihoodStressV431, getKerrHighEnergyLikelihoodStressSnapshotV431, getKerrHighEnergyLikelihoodStressSnapshotV431);
  useEffect(() => { void loadKerrHighEnergyLikelihoodStressSummaryV431().catch(() => undefined); }, []);
  const summary = state.summary;
  return <section className="relative mt-3 overflow-hidden border border-cyan-100/14 bg-[radial-gradient(circle_at_8%_8%,rgba(45,212,191,.09),transparent_26%),radial-gradient(circle_at_91%_11%,rgba(244,63,94,.065),transparent_24%),linear-gradient(132deg,rgba(3,8,11,.995),rgba(5,9,12,.99)_52%,rgba(13,5,7,.985))] p-3 font-mono text-white/52" data-atlas-kerr-high-energy-likelihood-stress-v431 data-atlas-v431-status={state.status} data-atlas-v431-scenarios="6" data-atlas-v431-synthetic-count-cells="73728" data-atlas-v431-measured-observed-counts="0" data-atlas-v431-alternative-likelihoods-qualified="0" data-atlas-v431-measured-authority="false" data-atlas-v431-summary-only-in-react-state="true" data-atlas-v431-canvas-created="false" aria-live="polite">
    <div aria-hidden="true" className="pointer-events-none absolute inset-0 opacity-30 [background-image:linear-gradient(118deg,transparent_0_46%,rgba(45,212,191,.045)_46.2%,transparent_46.4%),repeating-linear-gradient(0deg,transparent_0_17px,rgba(255,255,255,.017)_18px,transparent_19px_36px)]" />
    <header className="relative flex flex-wrap items-start justify-between gap-3 border-b border-white/7 pb-3"><div><div className="text-[6px] uppercase tracking-[.34em] text-cyan-100/44">V431 · likelihood assumption wind tunnel</div><h4 className="mt-1 font-['Bahnschrift_Condensed','DIN_Condensed',sans-serif] text-[21px] font-light uppercase tracking-[.18em] text-cyan-50/92">Provenance-first routing firewall</h4><p className="mt-1 max-w-[116ch] text-[6px] leading-relaxed text-white/38">六类固定种子合成场景检验 Poisson 假设在过度离散、相关噪声、背景混合、dead-time 与 pileup 下如何失效。likelihood family 必须先由采集 provenance 和预注册合同决定，残差只能审计，不能事后替模型做选择。</p></div><Status status={state.status} /></header>
    {!summary ? <div className="relative mt-3 border-l-2 border-cyan-100/24 bg-cyan-100/[.025] px-3 py-2 text-[6px] text-cyan-50/48">{state.status === "loading" || state.status === "idle" ? "正在读取 likelihood 压力证据…" : `likelihood 压力证据不可用 · ${state.reason ?? "request-failed"}`}</div> : <>
      <div className="relative mt-3 grid gap-3 xl:grid-cols-[minmax(0,1.5fr)_300px]">
        <div className="grid gap-3">
          <div className="grid gap-px bg-white/6 sm:grid-cols-2 lg:grid-cols-3">{summary.scenarios.map((scenario, index) => { const metrics = scenario.holdoutMetrics, retain = scenario.expectedPoissonDisposition === "retain"; return <article key={scenario.id} className="relative min-h-36 overflow-hidden bg-black/42 p-2.5" data-atlas-v431-scenario={scenario.id}><div aria-hidden="true" className={`absolute inset-x-0 top-0 h-px ${retain ? "bg-lime-200/55" : "bg-rose-200/45"}`} /><div className="flex items-center justify-between"><span className="text-[7px] text-cyan-100/58">0{index + 1}</span><span className={`text-[5px] ${retain ? "text-lime-100/58" : "text-rose-100/56"}`}>{retain ? "RETAIN POISSON" : "REJECT BEFORE FIT"}</span></div><div className="mt-3 text-[8px] tracking-[.08em] text-cyan-50/70">{LABELS[scenario.id]}</div><div className="mt-1 truncate text-[5px] text-white/28">→ {scenario.requiredLikelihoodFamily}</div><div className="mt-4 grid grid-cols-3 gap-px bg-white/6"><Mini label="coverage" value={metrics.poissonPredictiveCoverage90.toFixed(3)} /><Mini label="variance" value={metrics.meanVarianceToPoissonRatio.toFixed(2)} /><Mini label="corr" value={metrics.meanAbsoluteOffDiagonalResidualCorrelation.toFixed(3)} /></div><div className="mt-2 flex justify-between text-[5px]"><span className="text-white/24">max bias {metrics.maximumAbsoluteStandardizedMeanBias.toFixed(2)}σ</span><span className="text-lime-100/42">A/B Δ {scenario.maximumPythonRelativeDifference.toExponential(1)}</span></div></article>; })}</div>
          <div className="grid gap-3 lg:grid-cols-[1.1fr_.9fr]"><div className="border border-cyan-100/10 bg-black/28 p-3"><div className="text-[5px] uppercase tracking-[.16em] text-cyan-100/42">Selection order</div><div className="mt-3 grid gap-2 text-[6px] text-white/42"><Step index="01" text="读取 acquisition provenance 与响应状态" /><Step index="02" text="在看到 residual 之前锁定 likelihood family" /><Step index="03" text="计算 deviance、coverage、correlation 与 closure" /><Step index="04" text="残差只审计；禁止 post-hoc family switch" /></div></div><div className="border border-rose-100/12 bg-rose-100/[.025] p-3"><div className="text-[5px] uppercase tracking-[.16em] text-rose-100/44">Authority firewall</div><div className="mt-3 grid gap-px bg-white/6">{[["stress math", "QUALIFIED"], ["routing firewall", "QUALIFIED"], ["alternative likelihoods", "0 QUALIFIED"], ["measured counts", "0"], ["instrument authority", "UNAVAILABLE"]].map(([label, value]) => <div key={label} className="flex justify-between bg-black/35 px-2 py-1.5 text-[5px]"><span className="text-white/27">{label}</span><span className={value === "QUALIFIED" ? "text-lime-100/55" : "text-rose-100/52"}>{value}</span></div>)}</div></div></div>
        </div>
        <aside className="grid content-start gap-px bg-white/6 sm:grid-cols-2 xl:grid-cols-1"><Metric label="stress scenarios" value="6" tone="cyan" /><Metric label="calibration replicates" value="1,536" tone="teal" /><Metric label="synthetic holdout" value="1,536" tone="teal" /><Metric label="synthetic count cells" value="73,728" tone="cyan" /><Metric label="nominal Poisson" value="1 RETAIN" tone="lime" /><Metric label="stressed Poisson" value="5 REJECT" tone="rose" /><Metric label="measured validation" value="NOT RUN" tone="amber" /><Metric label="dense campaign" value="0 / 49" tone="amber" /></aside>
      </div>
      <div className="relative mt-3 grid gap-px bg-white/6 sm:grid-cols-2 lg:grid-cols-3">{EXPORTS.map(([label, format, detail]) => <a key={format} href={`/api/atlas/relativity-evidence/v431/high-energy-likelihood-stress?download=${format}`} download className="atlas-accessible-focus bg-black/42 px-2.5 py-2 transition-colors hover:bg-cyan-100/[.05]"><div className="text-[7px] text-cyan-100/62">{label}</div><div className="mt-0.5 text-[5px] leading-relaxed text-white/27">{detail}</div></a>)}</div>
      <footer className="relative mt-2 flex flex-wrap items-center justify-between gap-2 border-t border-white/7 pt-2 text-[5px] text-white/28"><span>independent synthetic split · Python / TypeScript cross-check · deterministic replay</span><span className="text-rose-100/45">stress discrimination ≠ alternative likelihood or instrument qualification</span></footer>
    </>}
  </section>;
}

function Status({ status }: Readonly<{ status: string }>) { return <div className="flex items-center gap-2 border border-cyan-100/14 bg-cyan-100/[.025] px-2.5 py-1.5"><span className={`h-1.5 w-1.5 rounded-full ${status === "ready" ? "bg-lime-200/75 shadow-[0_0_14px_rgba(190,242,100,.3)]" : status === "loading" ? "animate-pulse bg-amber-200/65" : "bg-rose-200/65"}`} /><div><div className="text-[5px] uppercase tracking-[.12em] text-white/22">stress channel</div><div className="mt-0.5 text-[6px] uppercase text-cyan-100/62">{status}</div></div></div>; }
function Mini({ label, value }: Readonly<{ label: string; value: string }>) { return <div className="bg-black/36 px-1.5 py-1"><div className="text-[4px] uppercase text-white/20">{label}</div><div className="mt-0.5 text-[6px] text-cyan-100/50">{value}</div></div>; }
function Step({ index, text }: Readonly<{ index: string; text: string }>) { return <div className="flex gap-2 border-l-2 border-cyan-100/16 bg-cyan-100/[.02] px-2 py-1.5"><span className="text-cyan-100/42">{index}</span><span>{text}</span></div>; }
function Metric({ label, value, tone }: Readonly<{ label: string; value: string; tone: "cyan" | "teal" | "lime" | "rose" | "amber" }>) { const colors = { cyan: "text-cyan-100/60", teal: "text-teal-100/60", lime: "text-lime-100/60", rose: "text-rose-100/60", amber: "text-amber-100/60" } as const; return <div className="bg-black/42 px-2.5 py-2"><div className="text-[5px] uppercase tracking-[.1em] text-white/23">{label}</div><div className={`mt-0.5 text-[7px] ${colors[tone]}`}>{value}</div></div>; }
