"use client";

import { useEffect, useState, useSyncExternalStore, type CSSProperties } from "react";
import { getKerrResponseAwareReplayKitSnapshotV541, loadKerrResponseAwareReplayKitSummaryV541, subscribeKerrResponseAwareReplayKitV541 } from "../lib/kerrResponseAwareReplayKitClientV541";
import { createKerrResponseAwareReplayKitHudEncodingV541, resolveKerrResponseAwareReplayKitHudProfileV541, type KerrResponseAwareReplayKitHudModeV541 } from "../lib/kerrResponseAwareReplayKitV541";

const shortSha = (value: string) => `${value.slice(0, 9)}…${value.slice(-7)}`;
export default function KerrResponseAwareReplayKitV541() {
  const [mode, setMode] = useState<KerrResponseAwareReplayKitHudModeV541>("science"), state = useSyncExternalStore(subscribeKerrResponseAwareReplayKitV541, getKerrResponseAwareReplayKitSnapshotV541, getKerrResponseAwareReplayKitSnapshotV541), profile = resolveKerrResponseAwareReplayKitHudProfileV541(mode), summary = state.summary, encoding = summary ? createKerrResponseAwareReplayKitHudEncodingV541(summary, mode) : null;
  useEffect(() => { void loadKerrResponseAwareReplayKitSummaryV541().catch(() => undefined); }, []);
  const style = { "--v541-panel": profile.panel, "--v541-raised": profile.panelRaised, "--v541-ink": profile.ink, "--v541-muted": profile.muted, "--v541-qualified": profile.qualified, "--v541-unavailable": profile.unavailable } as CSSProperties;
  return <section style={style} className="relative mt-7 overflow-hidden rounded-[48px] border border-white/10 bg-[var(--v541-panel)] p-6 font-mono text-[var(--v541-ink)]" data-atlas-response-aware-replay-kit-v541 data-atlas-v541-mode={mode} data-atlas-v541-kit-members={encoding?.memberCount ?? 0} data-atlas-v541-subprocesses={encoding?.subprocessCount ?? 0} data-atlas-v541-network-attempts="0" data-atlas-v541-image-hdus="0" data-atlas-v541-canvas-created="false" data-atlas-v541-scene-revision-delta="0">
    <div className="pointer-events-none absolute inset-0 opacity-40 [background-image:radial-gradient(circle_at_14%_8%,rgba(116,244,197,.2),transparent_24%),radial-gradient(circle_at_90%_15%,rgba(125,211,252,.15),transparent_28%),linear-gradient(rgba(125,211,252,.04)_1px,transparent_1px),linear-gradient(90deg,rgba(125,211,252,.04)_1px,transparent_1px)] [background-size:auto,auto,48px_48px,48px_48px]" />
    <header className="relative border-b border-white/10 pb-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[9px] uppercase tracking-[.44em] text-[var(--v541-muted)]">V541 / Science Cinematic V9.0</div><h2 className="mt-4 max-w-4xl font-serif text-4xl">验证器、数据和环境锁现在属于同一个可下载物</h2></div><div className="flex border border-white/10">{(["science", "cinematic"] as const).map((item) => <button key={item} type="button" aria-pressed={mode === item} className={mode === item ? "bg-white/10 px-3 py-2 text-[8px] text-white" : "px-3 py-2 text-[8px] text-[var(--v541-muted)]"} onClick={() => setMode(item)}>{item}</button>)}</div></div><p className="mt-4 max-w-4xl text-[10px] leading-6 text-[var(--v541-muted)]">Replay kit 内含 v539 crate、v540 receipt、独立 Python validator、环境 manifest 与精确 runtime lock。它在两个临时目录中以独立子进程重放成功；当前只资格化锁定环境，不夸大跨环境可移植性。</p></header>
    {!summary ? <div className="relative mt-6 text-[10px] text-[var(--v541-muted)]">{state.status === "unavailable" ? `独立 replay kit 不可用 / ${state.reason ?? "request-failed"}` : "正在读取 replay kit evidence…"}</div> : <>
      <div className="relative mt-6 grid gap-2 sm:grid-cols-3 xl:grid-cols-6"><Metric label="kit members" value="7" /><Metric label="manifest" value="6 / 6" /><Metric label="subprocess" value="2 / 2" /><Metric label="workspace imports" value="0" /><Metric label="network" value="0" /><Metric label="cross-env" value="not qualified" unavailable /></div>
      <div className="relative mt-5 grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><div className="grid gap-3 sm:grid-cols-2">{encoding?.members.map((member) => <article key={member.path} className="rounded-2xl border border-white/10 bg-[var(--v541-raised)] p-4"><div className="break-all text-[9px] text-[var(--v541-qualified)]">{member.path}</div><div className="mt-2 flex justify-between text-[8px] text-[var(--v541-muted)]"><span>{member.role}</span><span>{member.bytes.toLocaleString()} B</span></div><div className="mt-1 text-[8px] text-[var(--v541-muted)]">{shortSha(member.sha256)}</div></article>)}</div><aside className="rounded-2xl border border-white/10 bg-black/20 p-5"><div className="text-[8px] uppercase tracking-[.22em] text-[var(--v541-muted)]">Exact runtime lock</div><div className="mt-5 grid gap-2 text-[9px]"><Row label="Python" value={summary.environment.runtime.pythonVersion} /><Row label="NumPy" value={summary.environment.runtime.numpyVersion} /><Row label="Astropy" value={summary.environment.runtime.astropyVersion} /><Row label="zlib" value={summary.environment.runtime.zlibVersion} /><Row label="validator SHA" value={shortSha(summary.environment.validatorFileSha256)} /><Row label="result SHA" value={shortSha(summary.validation.result.resultSha256)} /></div><div className="mt-5 border border-[var(--v541-unavailable)]/20 bg-[var(--v541-unavailable)]/[.04] p-3 text-[8px] leading-5 text-[var(--v541-unavailable)]">版本必须精确匹配。尚未通过其他 Python、NumPy、Astropy 或操作系统环境的资格验证。</div></aside></div>
      <footer className="relative mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-4 text-[8px] text-[var(--v541-muted)]"><span>Science payload immutable · image HDU 0 · uncertainty 0/6 · dense 0/49 · production false</span><div className="flex flex-wrap gap-2"><a className="border border-white/15 px-3 py-2 text-white/70" href="/api/atlas/relativity-evidence/v541/response-aware-replay-kit?download=kit">下载 replay kit</a><a className="border border-white/15 px-3 py-2 text-white/70" href="/api/atlas/relativity-evidence/v541/response-aware-replay-kit?download=result">下载 validation receipt</a><a className="border border-white/15 px-3 py-2 text-white/70" href="/api/atlas/relativity-evidence/v541/response-aware-replay-kit?download=atlas">下载 provenance</a></div></footer>
    </>}
  </section>;
}
function Metric({ label, value, unavailable = false }: { label: string; value: string; unavailable?: boolean }) { return <div className="border border-white/10 bg-black/20 p-3"><div className="text-[8px] uppercase tracking-[.16em] text-[var(--v541-muted)]">{label}</div><div className={unavailable ? "mt-2 text-base text-[var(--v541-unavailable)]" : "mt-2 text-lg text-[var(--v541-qualified)]"}>{value}</div></div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-3 border-b border-white/5 py-2"><span className="text-[var(--v541-muted)]">{label}</span><span>{value}</span></div>; }
