"use client";

import { useEffect, useState, useSyncExternalStore, type CSSProperties } from "react";

import { getKerrResponseAwareFitsColumnSchemaSnapshotV538, loadKerrResponseAwareFitsColumnSchemaSummaryV538, subscribeKerrResponseAwareFitsColumnSchemaV538 } from "../lib/kerrResponseAwareFitsColumnSchemaClientV538";
import { createKerrResponseAwareFitsColumnSchemaHudEncodingV538, resolveKerrResponseAwareFitsColumnSchemaHudProfileV538, type KerrResponseAwareFitsColumnSchemaHudModeV538 } from "../lib/kerrResponseAwareFitsColumnSchemaV538";

export default function KerrResponseAwareFitsColumnSchemaV538() {
  const [mode, setMode] = useState<KerrResponseAwareFitsColumnSchemaHudModeV538>("science");
  const state = useSyncExternalStore(subscribeKerrResponseAwareFitsColumnSchemaV538, getKerrResponseAwareFitsColumnSchemaSnapshotV538, getKerrResponseAwareFitsColumnSchemaSnapshotV538);
  const profile = resolveKerrResponseAwareFitsColumnSchemaHudProfileV538(mode);
  const summary = state.summary;
  const encoding = summary ? createKerrResponseAwareFitsColumnSchemaHudEncodingV538(summary, mode) : null;
  useEffect(() => { void loadKerrResponseAwareFitsColumnSchemaSummaryV538().catch(() => undefined); }, []);
  const style = { "--v538-panel": profile.panel, "--v538-raised": profile.panelRaised, "--v538-ink": profile.ink, "--v538-muted": profile.muted, "--v538-qualified": profile.qualified, "--v538-unavailable": profile.unavailable } as CSSProperties;
  return <section style={style} className="relative mt-7 overflow-hidden rounded-[48px] border border-white/10 bg-[var(--v538-panel)] p-6 font-mono text-[var(--v538-ink)]" data-atlas-response-aware-fits-column-schema-v538 data-atlas-v538-mode={mode} data-atlas-v538-qualified-columns={encoding?.qualifiedColumnCount ?? 0} data-atlas-v538-physical-uncertainty-values="0" data-atlas-v538-image-hdus="0" data-atlas-v538-canvas-created="false" data-atlas-v538-scene-revision-delta="0">
    <div className="pointer-events-none absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(125,211,252,.06)_1px,transparent_1px),linear-gradient(90deg,rgba(125,211,252,.06)_1px,transparent_1px)] [background-size:38px_38px]" />
    <header className="relative border-b border-white/10 pb-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[9px] uppercase tracking-[.44em] text-[var(--v538-muted)]">V538 / Science Cinematic V8.7</div><h2 className="mt-4 max-w-4xl font-serif text-4xl">每一列都有单位、适用性与缺失语义</h2></div><div className="flex border border-white/10">{(["science", "cinematic"] as const).map((item) => <button key={item} type="button" aria-pressed={mode === item} className={mode === item ? "bg-white/10 px-3 py-2 text-[8px] text-white" : "px-3 py-2 text-[8px] text-[var(--v538-muted)]"} onClick={() => setMode(item)}>{item}</button>)}</div></div><p className="mt-4 max-w-4xl text-[10px] leading-6 text-[var(--v538-muted)]">结构正确并不等于语义明确。v538 锁定 17 列的 TFORM、TUNIT、物理含义、适用范围、缺失值规则和数值域；`false` 不再可能被误读为零不确定度或零亮度像素。</p></header>
    {!summary ? <div className="relative mt-6 text-[10px] text-[var(--v538-muted)]">{state.status === "unavailable" ? `列语义证据不可用 / ${state.reason ?? "request-failed"}` : "正在读取列语义 provenance…"}</div> : <>
      <div className="relative mt-6 grid gap-2 sm:grid-cols-3 xl:grid-cols-6"><Metric label="qualified columns" value="17 / 17" /><Metric label="physical units" value="6" /><Metric label="dimensionless" value="6" /><Metric label="identifier / flags" value="5" /><Metric label="uncertainty values" value="0" unavailable /><Metric label="image HDU" value="0" unavailable /></div>
      <div className="relative mt-5 grid gap-3 xl:grid-cols-2">{encoding?.columns.map((column) => <article key={column.name} className="grid gap-3 rounded-2xl border border-white/10 bg-[var(--v538-raised)] p-4 sm:grid-cols-[120px_1fr]"><div><div className="text-sm text-[var(--v538-qualified)]">{column.name}</div><div className="mt-1 text-[8px] text-[var(--v538-muted)]">TFORM {column.format}</div><div className="text-[8px] text-[var(--v538-muted)]">TUNIT {column.fitsUnit ?? "—"}</div></div><div><p className="text-[9px] leading-5">{column.semantic}</p><div className="mt-2 grid gap-1 text-[8px] text-[var(--v538-muted)]"><span>unit · {column.unitSemantic}</span><span>applies · {column.applicability}</span><span>missing · {column.missingness}</span><span>domain · {column.domain}</span></div></div></article>)}</div>
      <footer className="relative mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-4 text-[8px] text-[var(--v538-muted)]"><span>q̂² + û² residual {summary.invariants.maximumOrientationUnitNormResidual.toExponential(3)} · limit 1e−15 · calibration 0/6 · dense 0/49</span><div className="flex gap-2"><a className="border border-white/15 px-3 py-2 text-white/70" href="/api/atlas/relativity-evidence/v538/response-aware-fits-column-schema?download=csv">下载列语义 CSV</a><a className="border border-white/15 px-3 py-2 text-white/70" href="/api/atlas/relativity-evidence/v538/response-aware-fits-column-schema?download=atlas">下载 provenance JSON</a></div></footer>
    </>}
  </section>;
}

function Metric({ label, value, unavailable = false }: { label: string; value: string; unavailable?: boolean }) { return <div className="border border-white/10 bg-black/20 p-3"><div className="text-[8px] uppercase tracking-[.16em] text-[var(--v538-muted)]">{label}</div><div className={unavailable ? "mt-2 text-lg text-[var(--v538-unavailable)]" : "mt-2 text-lg text-[var(--v538-qualified)]"}>{value}</div></div>; }
