"use client";

import { useEffect, useState, useSyncExternalStore, type CSSProperties } from "react";
import { getKerrReplayCompatibilitySnapshotV542, loadKerrReplayCompatibilitySummaryV542, subscribeKerrReplayCompatibilityV542 } from "../lib/kerrReplayCompatibilityClientV542";
import { createKerrReplayCompatibilityHudEncodingV542, resolveKerrReplayCompatibilityHudProfileV542, type KerrReplayCompatibilityHudModeV542 } from "../lib/kerrReplayCompatibilityV542";

const shortSha = (value: string) => `${value.slice(0, 9)}…${value.slice(-7)}`;
const cellLabel: Readonly<Record<string, string>> = Object.freeze({ "observed-current-environment": "当前锁定环境", "same-dependencies-other-os": "同依赖 / 其他系统", "different-python": "其他 Python", "different-science-dependencies": "其他科学依赖" });

export default function KerrReplayCompatibilityV542() {
  const [mode, setMode] = useState<KerrReplayCompatibilityHudModeV542>("science");
  const state = useSyncExternalStore(subscribeKerrReplayCompatibilityV542, getKerrReplayCompatibilitySnapshotV542, getKerrReplayCompatibilitySnapshotV542);
  const profile = resolveKerrReplayCompatibilityHudProfileV542(mode), artifact = state.summary, encoding = artifact ? createKerrReplayCompatibilityHudEncodingV542(artifact, mode) : null;
  useEffect(() => { void loadKerrReplayCompatibilitySummaryV542().catch(() => undefined); }, []);
  const style = { "--v542-panel": profile.panel, "--v542-raised": profile.panelRaised, "--v542-ink": profile.ink, "--v542-muted": profile.muted, "--v542-qualified": profile.qualified, "--v542-warning": profile.warning, "--v542-unavailable": profile.unavailable } as CSSProperties;
  return <section style={style} className="relative mt-7 overflow-hidden rounded-[48px] border border-white/10 bg-[var(--v542-panel)] p-6 font-mono text-[var(--v542-ink)]" data-atlas-replay-compatibility-v542 data-atlas-v542-mode={mode} data-atlas-v542-executed-environments={encoding?.executedEnvironmentCount ?? 0} data-atlas-v542-preflight-subprocesses={encoding?.preflightSubprocessCount ?? 0} data-atlas-v542-science-dependency-imports="0" data-atlas-v542-cross-environment-qualified="false" data-atlas-v542-canvas-created="false" data-atlas-v542-scene-revision-delta="0">
    <div className="pointer-events-none absolute inset-0 opacity-45 [background-image:radial-gradient(circle_at_14%_8%,rgba(124,244,198,.2),transparent_24%),radial-gradient(circle_at_90%_18%,rgba(95,210,255,.16),transparent_28%),linear-gradient(rgba(110,220,255,.045)_1px,transparent_1px),linear-gradient(90deg,rgba(110,220,255,.045)_1px,transparent_1px)] [background-size:auto,auto,46px_46px,46px_46px]" />
    <header className="relative border-b border-white/10 pb-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[9px] uppercase tracking-[.44em] text-[var(--v542-muted)]">V542 / Science Cinematic V9.1</div><h2 className="mt-4 max-w-4xl font-serif text-4xl">先证明包装安全，再谈科学重放资格</h2></div><div className="flex border border-white/10">{(["science", "cinematic"] as const).map((item) => <button key={item} type="button" aria-pressed={mode === item} className={mode === item ? "bg-white/10 px-3 py-2 text-[8px] text-white" : "px-3 py-2 text-[8px] text-[var(--v542-muted)]"} onClick={() => setMode(item)}>{item}</button>)}</div></div><p className="mt-4 max-w-4xl text-[10px] leading-6 text-[var(--v542-muted)]">纯标准库预检验证 ZIP、manifest、路径安全与环境锁，不导入 NumPy/Astropy。FITS 语义与科研复核仍必须使用 v541 锁定环境；未实际运行的 Python 或操作系统绝不自动获得资格。</p></header>
    {!artifact ? <div className="relative mt-6 text-[10px] text-[var(--v542-muted)]">{state.status === "unavailable" ? `兼容性证据不可用 / ${state.reason ?? "request-failed"}` : "正在读取兼容性证据…"}</div> : <>
      <div className="relative mt-6 grid gap-2 sm:grid-cols-3 xl:grid-cols-6"><Metric label="stdlib preflight" value="2 / 2" /><Metric label="kit manifest" value="6 / 6" /><Metric label="crate manifest" value="8 / 8" /><Metric label="science imports" value="0" /><Metric label="executed env" value="1" /><Metric label="cross-env" value="not qualified" unavailable /></div>
      <div className="relative mt-5 grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><div className="grid gap-3 sm:grid-cols-2">{encoding?.cells.map((cell) => <article key={cell.id} className="rounded-2xl border border-white/10 bg-[var(--v542-raised)] p-4"><div className="flex items-center justify-between gap-3"><span className="text-[9px] text-white">{cellLabel[cell.id] ?? cell.id}</span><span className={cell.executed ? "text-[8px] text-[var(--v542-qualified)]" : "text-[8px] text-[var(--v542-unavailable)]"}>{cell.executed ? "executed" : "not run"}</span></div><div className="mt-3 text-[8px] leading-5 text-[var(--v542-muted)]">{cell.runtimeRelation}</div><div className="mt-2 border-t border-white/5 pt-2 text-[8px] text-[var(--v542-warning)]">{cell.scienceReplay}</div></article>)}</div><aside className="rounded-2xl border border-white/10 bg-black/20 p-5"><div className="text-[8px] uppercase tracking-[.22em] text-[var(--v542-muted)]">Observed exact tuple</div><div className="mt-5 grid gap-2 text-[9px]"><Row label="OS" value={`${artifact.preflight.observedRuntime.osFamily} / ${artifact.preflight.observedRuntime.machine}`} /><Row label="Python" value={artifact.preflight.observedRuntime.pythonVersion} /><Row label="NumPy metadata" value={artifact.preflight.observedRuntime.numpyVersion} /><Row label="Astropy metadata" value={artifact.preflight.observedRuntime.astropyVersion} /><Row label="preflight SHA" value={shortSha(artifact.preflight.preflightSha256)} /><Row label="matrix SHA" value={shortSha(artifact.compatibility.matrixSha256)} /></div><div className="mt-5 border border-[var(--v542-warning)]/20 bg-[var(--v542-warning)]/[.04] p-3 text-[8px] leading-5 text-[var(--v542-warning)]">标准库预检只签发包装完整性。它不会解析 FITS、不会执行科学重放，也不会把“合同上可能兼容”当作“已经验证”。</div></aside></div>
      <footer className="relative mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-4 text-[8px] text-[var(--v542-muted)]"><span>Science payload immutable · image HDU 0 · calibration 0/6 · dense 0/49 · production false</span><div className="flex flex-wrap gap-2"><a className="border border-white/15 px-3 py-2 text-white/70" href="/api/atlas/relativity-evidence/v542/replay-compatibility?download=validator">下载标准库预检器</a><a className="border border-white/15 px-3 py-2 text-white/70" href="/api/atlas/relativity-evidence/v542/replay-compatibility?download=matrix">下载兼容矩阵</a><a className="border border-white/15 px-3 py-2 text-white/70" href="/api/atlas/relativity-evidence/v542/replay-compatibility?download=preflight">下载预检回执</a></div></footer>
    </>}
  </section>;
}
function Metric({ label, value, unavailable = false }: { label: string; value: string; unavailable?: boolean }) { return <div className="border border-white/10 bg-black/20 p-3"><div className="text-[8px] uppercase tracking-[.16em] text-[var(--v542-muted)]">{label}</div><div className={unavailable ? "mt-2 text-base text-[var(--v542-unavailable)]" : "mt-2 text-lg text-[var(--v542-qualified)]"}>{value}</div></div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-3 border-b border-white/5 py-2"><span className="text-[var(--v542-muted)]">{label}</span><span>{value}</span></div>; }
