"use client";

import { useEffect, useState, useSyncExternalStore, type CSSProperties } from "react";
import { getKerrReplayIsolatedPreflightSnapshotV543, loadKerrReplayIsolatedPreflightSummaryV543, subscribeKerrReplayIsolatedPreflightV543 } from "../lib/kerrReplayIsolatedPreflightClientV543";
import { createKerrReplayIsolatedPreflightHudEncodingV543, resolveKerrReplayIsolatedPreflightHudProfileV543, type KerrReplayIsolatedPreflightHudModeV543 } from "../lib/kerrReplayIsolatedPreflightV543";
const shortSha = (value: string) => `${value.slice(0, 9)}…${value.slice(-7)}`;
const labels: Readonly<Record<string, string>> = Object.freeze({ "locked-runtime-science-replay": "锁定科研环境", "isolated-no-site-packages": "隔离标准库环境", "same-lock-other-os": "同依赖 / 其他系统", "different-python": "其他 Python", "different-science-dependencies": "其他科学依赖" });
export default function KerrReplayIsolatedPreflightV543() { const [mode, setMode] = useState<KerrReplayIsolatedPreflightHudModeV543>("science"), state = useSyncExternalStore(subscribeKerrReplayIsolatedPreflightV543, getKerrReplayIsolatedPreflightSnapshotV543, getKerrReplayIsolatedPreflightSnapshotV543), artifact = state.summary, profile = resolveKerrReplayIsolatedPreflightHudProfileV543(mode), encoding = artifact ? createKerrReplayIsolatedPreflightHudEncodingV543(artifact, mode) : null; useEffect(() => { void loadKerrReplayIsolatedPreflightSummaryV543().catch(() => undefined); }, []); const style = { "--v543-panel": profile.panel, "--v543-raised": profile.panelRaised, "--v543-ink": profile.ink, "--v543-muted": profile.muted, "--v543-qualified": profile.qualified, "--v543-warning": profile.warning, "--v543-unavailable": profile.unavailable } as CSSProperties; return <section style={style} className="relative mt-7 overflow-hidden rounded-[48px] border border-white/10 bg-[var(--v543-panel)] p-6 font-mono text-[var(--v543-ink)]" data-atlas-replay-isolated-preflight-v543 data-atlas-v543-mode={mode} data-atlas-v543-executed-environments={encoding?.executedEnvironmentCount ?? 0} data-atlas-v543-science-qualified-environments={encoding?.scienceQualifiedEnvironmentCount ?? 0} data-atlas-v543-science-dependency-imports="0" data-atlas-v543-cross-environment-science-qualified="false" data-atlas-v543-canvas-created="false" data-atlas-v543-scene-revision-delta="0">
  <div className="pointer-events-none absolute inset-0 opacity-45 [background-image:radial-gradient(circle_at_12%_8%,rgba(120,240,189,.2),transparent_24%),radial-gradient(circle_at_91%_16%,rgba(90,206,255,.16),transparent_27%),linear-gradient(rgba(105,215,255,.045)_1px,transparent_1px),linear-gradient(90deg,rgba(105,215,255,.045)_1px,transparent_1px)] [background-size:auto,auto,44px_44px,44px_44px]" />
  <header className="relative border-b border-white/10 pb-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[9px] uppercase tracking-[.44em] text-[var(--v543-muted)]">V543 / Science Cinematic V9.2</div><h2 className="mt-4 max-w-4xl font-serif text-4xl">没有 site-packages，包装证据仍然成立</h2></div><div className="flex border border-white/10">{(["science", "cinematic"] as const).map((item) => <button key={item} type="button" aria-pressed={mode === item} className={mode === item ? "bg-white/10 px-3 py-2 text-[8px] text-white" : "px-3 py-2 text-[8px] text-[var(--v543-muted)]"} onClick={() => setMode(item)}>{item}</button>)}</div></div><p className="mt-4 max-w-4xl text-[10px] leading-6 text-[var(--v543-muted)]">两次真实的 <code>python -I -S</code> 子进程证明标准库预检不依赖 NumPy/Astropy。隔离环境只获得包装资格；FITS 语义与科研重放仍仅由 v541 锁定环境签发。</p></header>
  {!artifact ? <div className="relative mt-6 text-[10px] text-[var(--v543-muted)]">{state.status === "unavailable" ? `隔离预检证据不可用 / ${state.reason ?? "request-failed"}` : "正在读取隔离预检证据…"}</div> : <>
    <div className="relative mt-6 grid gap-2 sm:grid-cols-3 xl:grid-cols-6"><Metric label="isolated runs" value="2 / 2" /><Metric label="executed env" value="2" /><Metric label="package qualified" value="2" /><Metric label="science qualified" value="1" /><Metric label="science imports" value="0" /><Metric label="cross-env science" value="not qualified" unavailable /></div>
    <div className="relative mt-5 grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><div className="grid gap-3 sm:grid-cols-2">{encoding?.cells.map((cell) => <article key={cell.id} className="rounded-2xl border border-white/10 bg-[var(--v543-raised)] p-4"><div className="flex items-center justify-between gap-3"><span className="text-[9px] text-white">{labels[cell.id] ?? cell.id}</span><span className={cell.execution === "not-run" ? "text-[8px] text-[var(--v543-unavailable)]" : "text-[8px] text-[var(--v543-qualified)]"}>{cell.execution}</span></div><div className="mt-3 text-[8px] leading-5 text-[var(--v543-muted)]">{cell.pythonMode} · {cell.dependencyState}</div><div className="mt-2 border-t border-white/5 pt-2 text-[8px] text-[var(--v543-warning)]">{cell.scienceReplay}</div></article>)}</div><aside className="rounded-2xl border border-white/10 bg-black/20 p-5"><div className="text-[8px] uppercase tracking-[.22em] text-[var(--v543-muted)]">Child-process proof</div><div className="mt-5 grid gap-2 text-[9px]"><Row label="isolated flag" value={String(artifact.receipt.execution.pythonIsolatedFlag)} /><Row label="no-site flag" value={String(artifact.receipt.execution.pythonNoSiteFlag)} /><Row label="site paths" value={String(artifact.receipt.execution.sitePackagePathCount)} /><Row label="NumPy metadata" value={artifact.receipt.observedRuntime.numpyVersion} /><Row label="Astropy metadata" value={artifact.receipt.observedRuntime.astropyVersion} /><Row label="receipt SHA" value={shortSha(artifact.receipt.isolatedReceiptSha256)} /><Row label="matrix SHA" value={shortSha(artifact.executionMatrix.executionMatrixSha256)} /></div><div className="mt-5 border border-[var(--v543-warning)]/20 bg-[var(--v543-warning)]/[.04] p-3 text-[8px] leading-5 text-[var(--v543-warning)]">包装可移植不等于科研可移植。隔离单元明确记录 science replay unavailable；其他操作系统仍未执行。</div></aside></div>
    <footer className="relative mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-4 text-[8px] text-[var(--v543-muted)]"><span>Science payload immutable · image HDU 0 · calibration 0/6 · dense 0/49 · production false</span><div className="flex flex-wrap gap-2"><a className="border border-white/15 px-3 py-2 text-white/70" href="/api/atlas/relativity-evidence/v543/isolated-preflight?download=runner">下载隔离 runner</a><a className="border border-white/15 px-3 py-2 text-white/70" href="/api/atlas/relativity-evidence/v543/isolated-preflight?download=matrix">下载执行矩阵</a><a className="border border-white/15 px-3 py-2 text-white/70" href="/api/atlas/relativity-evidence/v543/isolated-preflight?download=receipt">下载隔离回执</a></div></footer>
  </>}
 </section>; }
function Metric({ label, value, unavailable = false }: { label: string; value: string; unavailable?: boolean }) { return <div className="border border-white/10 bg-black/20 p-3"><div className="text-[8px] uppercase tracking-[.16em] text-[var(--v543-muted)]">{label}</div><div className={unavailable ? "mt-2 text-base text-[var(--v543-unavailable)]" : "mt-2 text-lg text-[var(--v543-qualified)]"}>{value}</div></div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-3 border-b border-white/5 py-2"><span className="text-[var(--v543-muted)]">{label}</span><span>{value}</span></div>; }
