"use client";
import { useEffect, useState } from "react";
import { parseKerrSpectralConfidenceScaleArtifactV357, type KerrSpectralConfidenceScaleArtifactV357 } from "../lib/kerrSpectralConfidenceScaleV357";

export default function KerrSpectralConfidenceScaleSurfaceV357() {
  const [artifact, setArtifact] = useState<KerrSpectralConfidenceScaleArtifactV357 | null>(null); const [state, setState] = useState<"loading" | "ready" | "unavailable" | "error">("loading");
  useEffect(() => { const controller = new AbortController(); void fetch("/api/atlas/relativity-evidence/v357/confidence-scale", { cache: "no-store", signal: controller.signal }).then(async (response) => { const value = await response.json() as { available?: boolean; reason?: string; artifact?: unknown }; if (response.ok && value.available === false && value.reason === "lite-boundary") return null; if (!response.ok || value.available !== true || !value.artifact) throw new Error("v357-scale-unavailable"); return parseKerrSpectralConfidenceScaleArtifactV357(value.artifact); }).then((value) => { if (controller.signal.aborted) return; if (!value) { setState("unavailable"); return; } setArtifact(value); setState("ready"); }).catch(() => { if (!controller.signal.aborted) setState("error"); }); return () => controller.abort(); }, []);
  return <section className="mt-2 rounded-[10px] border border-rose-100/15 bg-[linear-gradient(145deg,rgba(37,8,21,.92),rgba(7,9,16,.98))] p-3 font-mono text-[8px] text-white/52" data-atlas-confidence-scale-v357 data-atlas-confidence-scale-status={state}><div className="flex flex-wrap items-end justify-between gap-2"><div><div className="text-[7px] uppercase tracking-[.2em] text-rose-100/46">Envelope scale v357</div><div className="mt-0.5 text-[13px] text-rose-50/90">1σ / 2σ / 3σ geometry convention</div></div><div className="text-right text-[7px] text-rose-100/60">{artifact?.denseCampaignStatus ?? "dense unavailable"}<br />{state}</div></div>{artifact ? <><div className="mt-3 grid gap-1.5 sm:grid-cols-4"><Metric label="levels" value={artifact.scaleConvention.levels.join(" / ")} detail="sigma geometry" /><Metric label="ellipses" value={String(artifact.counts.ellipseLevelCount)} detail="4 rays × 3 pairs × 3" /><Metric label="radius" value={Math.max(artifact.maxima.ellipseRadiusMaximumDifference, artifact.maxima.ellipsoidRadiusMaximumDifference).toExponential(2)} detail="scale residual" /><Metric label="area" value={artifact.maxima.ellipseAreaScaleRelativeDifference.toExponential(2)} detail="sigma² residual" /></div><div className="mt-2 rounded border border-rose-100/10 bg-rose-100/[.025] px-2 py-1.5 text-[7px] text-white/36">Synthetic Gaussian scale convention · not measured confidence · not probability coverage · covariance authority unchanged · never cinematic input</div></> : <div className="mt-2 rounded border border-white/[.08] px-2 py-1.5 text-[8px] text-white/38">{state === "loading" ? "Loading bounded scale audit..." : state === "unavailable" ? "Lite boundary" : "Scale audit unavailable; fail closed."}</div>}</section>;
}
function Metric({ label, value, detail }: Readonly<{ label: string; value: string; detail: string }>) { return <div className="rounded border border-white/[.08] bg-black/20 px-2 py-2"><div className="text-[7px] uppercase text-white/30">{label}</div><div className="mt-1 text-[11px] text-rose-50/84">{value}</div><div className="text-[7px] text-white/30">{detail}</div></div>; }
