"use client";
import { useEffect, useState, useSyncExternalStore, type CSSProperties } from "react";
import { getKerrIndependentFitsValidationSnapshotV546, loadKerrIndependentFitsValidationSummaryV546, subscribeKerrIndependentFitsValidationV546 } from "../lib/kerrIndependentFitsValidationClientV546";
import { createKerrIndependentFitsHudEncodingV546, resolveKerrIndependentFitsHudProfileV546, type KerrIndependentFitsHudModeV546 } from "../lib/kerrIndependentFitsValidationV546";
const shortSha = (value: string) => `${value.slice(0, 9)}…${value.slice(-7)}`;
export default function KerrIndependentFitsValidationV546() {
  const [mode, setMode] = useState<KerrIndependentFitsHudModeV546>("science"), state = useSyncExternalStore(subscribeKerrIndependentFitsValidationV546, getKerrIndependentFitsValidationSnapshotV546, getKerrIndependentFitsValidationSnapshotV546), artifact = state.summary, profile = resolveKerrIndependentFitsHudProfileV546(mode), encoding = artifact ? createKerrIndependentFitsHudEncodingV546(artifact, mode) : null;
  useEffect(() => { void loadKerrIndependentFitsValidationSummaryV546().catch(() => undefined); }, []);
  const style = { "--v546-panel": profile.panel, "--v546-raised": profile.panelRaised, "--v546-ink": profile.ink, "--v546-muted": profile.muted, "--v546-qualified": profile.qualified, "--v546-warning": profile.warning, "--v546-unavailable": profile.unavailable } as CSSProperties;
  return <section style={style} className="relative mt-7 overflow-hidden rounded-[48px] border border-white/10 bg-[var(--v546-panel)] p-6 font-mono text-[var(--v546-ink)]" data-atlas-independent-fits-validation-v546 data-atlas-v546-mode={mode} data-atlas-v546-independent-subprocesses={encoding?.independentSubprocesses ?? 0} data-atlas-v546-measured-authority="false" data-atlas-v546-science-raster-qualified="false" data-atlas-v546-canvas-created="false" data-atlas-v546-scene-revision-delta="0">
    <div className="pointer-events-none absolute inset-0 opacity-45 [background-image:radial-gradient(circle_at_13%_8%,rgba(120,237,192,.18),transparent_24%),radial-gradient(circle_at_89%_18%,rgba(96,202,255,.14),transparent_28%),linear-gradient(rgba(110,210,255,.04)_1px,transparent_1px),linear-gradient(90deg,rgba(110,210,255,.04)_1px,transparent_1px)] [background-size:auto,auto,40px_40px,40px_40px]" />
    <header className="relative border-b border-white/10 pb-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[9px] uppercase tracking-[.44em] text-[var(--v546-muted)]">V546 / Science Cinematic V9.5</div><h2 className="mt-4 max-w-4xl font-serif text-4xl">独立 FITS 语义验证，不把测试图像冒充观测</h2></div><div className="flex border border-white/10">{(["science", "cinematic"] as const).map((item) => <button key={item} type="button" aria-pressed={mode === item} className={mode === item ? "bg-white/10 px-3 py-2 text-[8px] text-white" : "px-3 py-2 text-[8px] text-[var(--v546-muted)]"} onClick={() => setMode(item)}>{item}</button>)}</div></div><p className="mt-4 max-w-4xl text-[10px] leading-6 text-[var(--v546-muted)]">两个隔离 Astropy 子进程验证同一确定性 synthetic control，并拒绝 checksum、身份、单位、曝光、帧元数据、provenance、光谱行数和内容类别八类变异。回执只保存结构与 SHA，不保存像素值，也不授予 measured authority。</p></header>
    {!artifact ? <div className="relative mt-6 text-[10px] text-[var(--v546-muted)]">{state.status === "unavailable" ? `独立 FITS 验证不可用 / ${state.reason ?? "request-failed"}` : "正在读取独立语义回执…"}</div> : <>
      <div className="relative mt-6 grid gap-2 sm:grid-cols-3 xl:grid-cols-6"><Metric label="isolated validators" value="2 / 2" /><Metric label="mutations rejected" value="8 / 8" /><Metric label="synthetic controls" value="1" /><Metric label="published FITS" value="0" unavailable /><Metric label="stored pixels" value="0" unavailable /><Metric label="measured authority" value="false" unavailable /></div>
      <div className="relative mt-5 grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><div className="rounded-2xl border border-white/10 bg-[var(--v546-raised)] p-5"><div className="text-[8px] uppercase tracking-[.22em] text-[var(--v546-muted)]">Semantic receipt</div><div className="mt-4 grid gap-2 sm:grid-cols-2"><Row label="Astropy" value={artifact.environment.astropyVersion} /><Row label="FITS HDU" value="1 primary image" /><Row label="synthetic pixels checked" value={String(artifact.validation.receipt.checks.fitsPixelCount)} /><Row label="pixels retained" value="0" /><Row label="CHECKSUM / DATASUM" value="qualified" /><Row label="A/B canonical" value="identical" /><Row label="network attempts" value="0" /><Row label="temporary leaks" value="0" /></div></div><aside className="rounded-2xl border border-white/10 bg-black/20 p-5"><div className="text-[8px] uppercase tracking-[.22em] text-[var(--v546-muted)]">Authority boundary</div><div className="mt-4 grid gap-2"><Row label="artifact" value={shortSha(artifact.artifactSha256)} /><Row label="receipt" value={shortSha(artifact.validation.receipt.resultSha256)} /><Row label="validator" value={shortSha(artifact.source.validatorFileSha256)} /><Row label="dense campaign" value="0 / 49" /><Row label="formal product" value="v263" /><Row label="default kernel" value="legacy-eih-1pn" /></div><div className="mt-5 border border-[var(--v546-warning)]/20 bg-[var(--v546-warning)]/[.04] p-3 text-[8px] leading-5 text-[var(--v546-warning)]">Synthetic control 只证明验证器能识别合法结构和拒绝错误。真实五文件候选仍缺失；没有 observed FITS、measured pixel 或 science raster 被发布。</div></aside></div>
      <footer className="relative mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-4 text-[8px] text-[var(--v546-muted)]"><span>candidate files 0/5 · measured frames 0 · science pixels 0 · browser qualification not-run</span><div className="flex flex-wrap gap-2"><Download id="receipt" label="验证回执" /><Download id="validator" label="便携 validator" /><Download id="atlas" label="完整 atlas" /></div></footer>
    </>}
  </section>;
}
function Metric({ label, value, unavailable = false }: { label: string; value: string; unavailable?: boolean }) { return <div className="border border-white/10 bg-black/20 p-3"><div className="text-[8px] uppercase tracking-[.16em] text-[var(--v546-muted)]">{label}</div><div className={unavailable ? "mt-2 text-base text-[var(--v546-unavailable)]" : "mt-2 text-lg text-[var(--v546-qualified)]"}>{value}</div></div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-3 border-b border-white/5 py-2 text-[8px]"><span className="text-[var(--v546-muted)]">{label}</span><span>{value}</span></div>; }
function Download({ id, label }: { id: "atlas" | "receipt" | "validator"; label: string }) { return <a className="border border-white/15 px-3 py-2 text-white/70" href={`/api/atlas/relativity-evidence/v546/independent-fits-validation?download=${id}`}>{label}</a>; }
