"use client";
import { useEffect, useState, useSyncExternalStore, type CSSProperties } from "react";
import { getKerrSupplementalCalibrationIntakeSnapshotV545, loadKerrSupplementalCalibrationIntakeSummaryV545, subscribeKerrSupplementalCalibrationIntakeV545 } from "../lib/kerrSupplementalCalibrationIntakeClientV545";
import { createKerrSupplementalCalibrationHudEncodingV545, resolveKerrSupplementalCalibrationHudProfileV545, type KerrSupplementalCalibrationHudModeV545 } from "../lib/kerrSupplementalCalibrationIntakeV545";
const shortSha = (value: string) => `${value.slice(0, 9)}…${value.slice(-7)}`;
export default function KerrSupplementalCalibrationIntakeV545() { const [mode, setMode] = useState<KerrSupplementalCalibrationHudModeV545>("science"), state = useSyncExternalStore(subscribeKerrSupplementalCalibrationIntakeV545, getKerrSupplementalCalibrationIntakeSnapshotV545, getKerrSupplementalCalibrationIntakeSnapshotV545), artifact = state.summary, profile = resolveKerrSupplementalCalibrationHudProfileV545(mode), encoding = artifact ? createKerrSupplementalCalibrationHudEncodingV545(artifact, mode) : null; useEffect(() => { void loadKerrSupplementalCalibrationIntakeSummaryV545().catch(() => undefined); }, []); const style = { "--v545-panel": profile.panel, "--v545-raised": profile.panelRaised, "--v545-ink": profile.ink, "--v545-muted": profile.muted, "--v545-qualified": profile.qualified, "--v545-warning": profile.warning, "--v545-unavailable": profile.unavailable } as CSSProperties; return <section style={style} className="relative mt-7 overflow-hidden rounded-[48px] border border-white/10 bg-[var(--v545-panel)] p-6 font-mono text-[var(--v545-ink)]" data-atlas-supplemental-calibration-intake-v545 data-atlas-v545-mode={mode} data-atlas-v545-files={encoding?.requiredFileCount ?? 0} data-atlas-v545-ready="0" data-atlas-v545-science-raster-qualified="false" data-atlas-v545-canvas-created="false" data-atlas-v545-scene-revision-delta="0">
  <div className="pointer-events-none absolute inset-0 opacity-45 [background-image:radial-gradient(circle_at_12%_8%,rgba(117,237,185,.2),transparent_24%),radial-gradient(circle_at_91%_17%,rgba(91,205,255,.15),transparent_28%),linear-gradient(rgba(104,213,255,.045)_1px,transparent_1px),linear-gradient(90deg,rgba(104,213,255,.045)_1px,transparent_1px)] [background-size:auto,auto,40px_40px,40px_40px]" />
  <header className="relative border-b border-white/10 pb-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[9px] uppercase tracking-[.44em] text-[var(--v545-muted)]">V545 / Science Cinematic V9.4</div><h2 className="mt-4 max-w-4xl font-serif text-4xl">补充科学权威现在有了严格入口</h2></div><div className="flex border border-white/10">{(["science", "cinematic"] as const).map((item) => <button key={item} type="button" aria-pressed={mode === item} className={mode === item ? "bg-white/10 px-3 py-2 text-[8px] text-white" : "px-3 py-2 text-[8px] text-[var(--v545-muted)]"} onClick={() => setMode(item)}>{item}</button>)}</div></div><p className="mt-4 max-w-4xl text-[10px] leading-6 text-[var(--v545-muted)]">五文件 staging 合同覆盖收集面积、曝光、三波段实测响应、观测 FITS 帧和交叉 provenance。预检通过只允许进入独立 Astropy 语义验证；任何 synthetic fixture 永远不能签发科研权威。</p></header>
  {!artifact ? <div className="relative mt-6 text-[10px] text-[var(--v545-muted)]">{state.status === "unavailable" ? `补充校准 intake 不可用 / ${state.reason ?? "request-failed"}` : "正在读取补充校准协议…"}</div> : <>
    <div className="relative mt-6 grid gap-2 sm:grid-cols-3 xl:grid-cols-6"><Metric label="authority roles" value="4" /><Metric label="required files" value="5" /><Metric label="ready" value="0" unavailable /><Metric label="synthetic fixture" value="1 / 1" /><Metric label="mutations rejected" value="8 / 8" /><Metric label="science pixels" value="0" /></div>
    <div className="relative mt-5 grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><div className="grid gap-3 sm:grid-cols-2">{encoding?.files.map((entry) => <article key={entry.id} className="rounded-2xl border border-white/10 bg-[var(--v545-raised)] p-4"><div className="flex items-center justify-between gap-3"><span className="text-[9px] text-white">{entry.fileName}</span><span className="text-[8px] text-[var(--v545-unavailable)]">missing</span></div><div className="mt-3 text-[8px] text-[var(--v545-muted)]">{entry.authorityCategory} · {entry.format}</div><div className="mt-2 text-[8px] text-[var(--v545-warning)]">{entry.schemaVersion}</div></article>)}</div><aside className="rounded-2xl border border-white/10 bg-black/20 p-5"><div className="text-[8px] uppercase tracking-[.22em] text-[var(--v545-muted)]">Admission boundary</div><div className="mt-5 grid gap-2 text-[9px]"><Row label="staging" value="absent" /><Row label="files" value="0 / 5" /><Row label="cross identity" value="pending" /><Row label="four-input SHA" value="pending" /><Row label="FITS semantics" value="pending Astropy" /><Row label="schema SHA" value={shortSha(artifact.schemaPack.schemaPackSha256)} /></div><div className="mt-5 border border-[var(--v545-warning)]/20 bg-[var(--v545-warning)]/[.04] p-3 text-[8px] leading-5 text-[var(--v545-warning)]">FITS magic 与容器尺寸只是预检，不是图像语义验证。Measured candidate 仍须独立校验和显式 authority grant。</div></aside></div>
    <footer className="relative mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-4 text-[8px] text-[var(--v545-muted)]"><span>measured files 0/5 · spectral rows 0 · observed frames 0 · image HDU 0 · dense 0/49</span><a className="border border-white/15 px-3 py-2 text-white/70" href="/api/atlas/relativity-evidence/v545/supplemental-calibration-intake?download=atlas">下载 schema 与 provenance</a></footer>
  </>}
 </section>; }
function Metric({ label, value, unavailable = false }: { label: string; value: string; unavailable?: boolean }) { return <div className="border border-white/10 bg-black/20 p-3"><div className="text-[8px] uppercase tracking-[.16em] text-[var(--v545-muted)]">{label}</div><div className={unavailable ? "mt-2 text-base text-[var(--v545-unavailable)]" : "mt-2 text-lg text-[var(--v545-qualified)]"}>{value}</div></div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-3 border-b border-white/5 py-2"><span className="text-[var(--v545-muted)]">{label}</span><span>{value}</span></div>; }
