"use client";
import { useEffect, useState, useSyncExternalStore, type CSSProperties } from "react";
import { getKerrCalibrationAuthorityGapSnapshotV544, loadKerrCalibrationAuthorityGapSummaryV544, subscribeKerrCalibrationAuthorityGapV544 } from "../lib/kerrCalibrationAuthorityGapClientV544";
import { createKerrCalibrationAuthorityGapHudEncodingV544, resolveKerrCalibrationAuthorityGapHudProfileV544, type KerrCalibrationAuthorityGapHudModeV544 } from "../lib/kerrCalibrationAuthorityGapV544";
const shortSha = (value: string) => `${value.slice(0, 9)}…${value.slice(-7)}`;
export default function KerrCalibrationAuthorityGapV544() { const [mode, setMode] = useState<KerrCalibrationAuthorityGapHudModeV544>("science"), state = useSyncExternalStore(subscribeKerrCalibrationAuthorityGapV544, getKerrCalibrationAuthorityGapSnapshotV544, getKerrCalibrationAuthorityGapSnapshotV544), artifact = state.summary, profile = resolveKerrCalibrationAuthorityGapHudProfileV544(mode), encoding = artifact ? createKerrCalibrationAuthorityGapHudEncodingV544(artifact, mode) : null; useEffect(() => { void loadKerrCalibrationAuthorityGapSummaryV544().catch(() => undefined); }, []); const style = { "--v544-panel": profile.panel, "--v544-raised": profile.panelRaised, "--v544-ink": profile.ink, "--v544-muted": profile.muted, "--v544-qualified": profile.qualified, "--v544-warning": profile.warning, "--v544-unavailable": profile.unavailable } as CSSProperties; return <section style={style} className="relative mt-7 overflow-hidden rounded-[48px] border border-white/10 bg-[var(--v544-panel)] p-6 font-mono text-[var(--v544-ink)]" data-atlas-calibration-authority-gap-v544 data-atlas-v544-mode={mode} data-atlas-v544-requirements={encoding?.requirements.length ?? 0} data-atlas-v544-ready="0" data-atlas-v544-science-raster-qualified="false" data-atlas-v544-canvas-created="false" data-atlas-v544-scene-revision-delta="0">
  <div className="pointer-events-none absolute inset-0 opacity-45 [background-image:radial-gradient(circle_at_12%_8%,rgba(119,239,188,.2),transparent_24%),radial-gradient(circle_at_91%_17%,rgba(92,207,255,.15),transparent_28%),linear-gradient(rgba(105,215,255,.045)_1px,transparent_1px),linear-gradient(90deg,rgba(105,215,255,.045)_1px,transparent_1px)] [background-size:auto,auto,42px_42px,42px_42px]" />
  <header className="relative border-b border-white/10 pb-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[9px] uppercase tracking-[.44em] text-[var(--v544-muted)]">V544 / Science Cinematic V9.3</div><h2 className="mt-4 max-w-4xl font-serif text-4xl">六个校准文件不是一张科学图像</h2></div><div className="flex border border-white/10">{(["science", "cinematic"] as const).map((item) => <button key={item} type="button" aria-pressed={mode === item} className={mode === item ? "bg-white/10 px-3 py-2 text-[8px] text-white" : "px-3 py-2 text-[8px] text-[var(--v544-muted)]"} onClick={() => setMode(item)}>{item}</button>)}</div></div><p className="mt-4 max-w-4xl text-[10px] leading-6 text-[var(--v544-muted)]">v458 的六文件 intake 是必要条件，但还缺收集面积、曝光记录、实测光谱响应和观测帧。v544 将十类权威输入拆成 6+4，阻止将“文件齐全”误报为电子期望、ADU 或科学栅格资格。</p></header>
  {!artifact ? <div className="relative mt-6 text-[10px] text-[var(--v544-muted)]">{state.status === "unavailable" ? `校准权威拓扑不可用 / ${state.reason ?? "request-failed"}` : "正在读取校准权威拓扑…"}</div> : <>
    <div className="relative mt-6 grid gap-2 sm:grid-cols-3 xl:grid-cols-6"><Metric label="authority inputs" value="10" /><Metric label="intake files" value="6" /><Metric label="supplemental" value="4" /><Metric label="ready" value="0" unavailable /><Metric label="science pixels" value="0" /><Metric label="raster" value="blocked" unavailable /></div>
    <div className="relative mt-5 grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><div className="grid gap-3 sm:grid-cols-2">{encoding?.requirements.map((entry) => <article key={entry.id} className="rounded-2xl border border-white/10 bg-[var(--v544-raised)] p-4"><div className="flex items-center justify-between gap-3"><span className="text-[9px] text-white">{entry.id}</span><span className="text-[8px] text-[var(--v544-unavailable)]">missing</span></div><div className="mt-3 text-[8px] text-[var(--v544-muted)]">{entry.tier} · {entry.sourceContract}</div><div className="mt-2 text-[8px] leading-5 text-[var(--v544-warning)]">{entry.covers.join(" · ")}</div><div className="mt-2 text-[8px] text-[var(--v544-muted)]">{shortSha(entry.rowSha256)}</div></article>)}</div><aside className="rounded-2xl border border-white/10 bg-black/20 p-5"><div className="text-[8px] uppercase tracking-[.22em] text-[var(--v544-muted)]">Authority transitions</div><div className="mt-5 grid gap-3">{encoding?.transitionAudit.map((entry) => <div key={entry.id} className="border-b border-white/5 pb-3"><div className="flex justify-between text-[9px]"><span>{entry.id}</span><span className="text-[var(--v544-unavailable)]">blocked</span></div><div className="mt-2 text-[8px] leading-5 text-[var(--v544-muted)]">missing: {entry.missingAuthorityIds.join(", ")}</div></div>)}</div><div className="mt-5 border border-[var(--v544-warning)]/20 bg-[var(--v544-warning)]/[.04] p-3 text-[8px] leading-5 text-[var(--v544-warning)]">稀疏 Kerr authority 或未来 dense aggregate 都不能替代真实仪器校准；缺失量保持 null，不得写成 0。</div></aside></div>
    <footer className="relative mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-4 text-[8px] text-[var(--v544-muted)]"><span>measured calibration 0/6 · supplemental 0/4 · image HDU 0 · dense 0/49 · production false</span><div className="flex gap-2"><a className="border border-white/15 px-3 py-2 text-white/70" href="/api/atlas/relativity-evidence/v544/calibration-authority-gap?download=matrix">下载 6+4 权威矩阵</a><a className="border border-white/15 px-3 py-2 text-white/70" href="/api/atlas/relativity-evidence/v544/calibration-authority-gap?download=atlas">下载 provenance</a></div></footer>
  </>}
 </section>; }
function Metric({ label, value, unavailable = false }: { label: string; value: string; unavailable?: boolean }) { return <div className="border border-white/10 bg-black/20 p-3"><div className="text-[8px] uppercase tracking-[.16em] text-[var(--v544-muted)]">{label}</div><div className={unavailable ? "mt-2 text-base text-[var(--v544-unavailable)]" : "mt-2 text-lg text-[var(--v544-qualified)]"}>{value}</div></div>; }
