"use client";

import { useEffect, useState, useSyncExternalStore, type CSSProperties } from "react";
import { getKerrLicenseConfirmationPacketSnapshotV552, loadKerrLicenseConfirmationPacketSummaryV552, subscribeKerrLicenseConfirmationPacketV552 } from "../lib/kerrLicenseConfirmationPacketClientV552";
import { createKerrLicenseConfirmationPacketHudEncodingV552, resolveKerrLicenseConfirmationPacketHudProfileV552, type KerrLicenseConfirmationPacketHudModeV552 } from "../lib/kerrLicenseConfirmationPacketV552";

export default function KerrLicenseConfirmationV552() {
  const [mode, setMode] = useState<KerrLicenseConfirmationPacketHudModeV552>("science");
  const state = useSyncExternalStore(subscribeKerrLicenseConfirmationPacketV552, getKerrLicenseConfirmationPacketSnapshotV552, getKerrLicenseConfirmationPacketSnapshotV552);
  const artifact = state.summary;
  const profile = resolveKerrLicenseConfirmationPacketHudProfileV552(mode);
  const encoding = artifact ? createKerrLicenseConfirmationPacketHudEncodingV552(artifact, mode) : null;
  useEffect(() => { void loadKerrLicenseConfirmationPacketSummaryV552().catch(() => undefined); }, []);
  const style = { "--v552-panel": profile.panel, "--v552-raised": profile.panelRaised, "--v552-ink": profile.ink, "--v552-muted": profile.muted, "--v552-qualified": profile.qualified, "--v552-warning": profile.warning, "--v552-unavailable": profile.unavailable } as CSSProperties;
  return <section style={style} className="relative mt-7 overflow-hidden rounded-[36px] border border-white/10 bg-[var(--v552-panel)] p-6 font-mono text-[var(--v552-ink)]" data-atlas-license-confirmation-v552 data-atlas-v552-mode={mode} data-atlas-v552-detail-catalog-size="54" data-atlas-v552-measured-authority={String(encoding?.measuredAuthorityGranted ?? false)} data-atlas-v552-science-raster-qualified={String(encoding?.scienceRasterQualified ?? false)} data-atlas-v552-canvas-created="false" data-atlas-v552-scene-revision-delta="0">
    <header className="relative border-b border-white/10 pb-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[9px] uppercase tracking-[.4em] text-[var(--v552-muted)]">V552 / Science Cinematic V10.1</div><h2 className="mt-3 max-w-4xl font-serif text-3xl">许可证确认必须由用户提供</h2></div><div className="flex border border-white/10">{(["science", "cinematic"] as const).map((item) => <button key={item} type="button" aria-pressed={mode === item} className={mode === item ? "bg-white/10 px-3 py-2 text-[8px] text-white" : "px-3 py-2 text-[8px] text-[var(--v552-muted)]"} onClick={() => setMode(item)}>{item}</button>)}</div></div><p className="mt-3 max-w-4xl text-[10px] leading-6 text-[var(--v552-muted)]">当前确认包缺失。系统不会联网、自动下载、创造 reviewer 或把 synthetic terms-only 快照当作真实许可；在七项确认齐全前，measured authority 与科学栅格保持关闭。</p></header>
    {!artifact ? <div className="relative mt-5 text-[10px] text-[var(--v552-muted)]">{state.status === "unavailable" ? `许可证确认不可用：${state.reason ?? "request-failed"}` : "正在读取许可证确认状态…"}</div> : <><div className="relative mt-5 grid gap-2 sm:grid-cols-3 xl:grid-cols-6"><Metric label="成员" value="7" /><Metric label="已确认" value="0" unavailable /><Metric label="缺失" value={String(artifact.validator.missingEntryCount)} unavailable /><Metric label="网络请求" value="0" /><Metric label="回放" value={`${artifact.replay.qualifiedAttemptCount} / ${artifact.replay.independentAttemptCount}`} /><Metric label="measured authority" value="false" unavailable /></div><div className="relative mt-5 grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><div className="grid gap-2 sm:grid-cols-2">{artifact.sourceManifest.slice(0, 7).map((entry) => <article key={entry.path} className="rounded-2xl border border-white/10 bg-[var(--v552-raised)] p-4"><div className="flex items-center justify-between gap-3"><span className="text-[9px] text-white">{entry.path.split("/").pop()}</span><span className="text-[8px] text-[var(--v552-unavailable)]">缺失确认</span></div><div className="mt-3"><Row label="source manifest SHA" value={entry.sha256} /><Row label="license text" value="待用户提供" /><Row label="reviewer attestation" value="待用户提供" /></div></article>)}</div><aside className="rounded-2xl border border-white/10 bg-black/20 p-5"><div className="text-[8px] uppercase tracking-[.22em] text-[var(--v552-muted)]">权限边界</div><div className="mt-4 grid gap-2"><Row label="packet" value="missing" /><Row label="自动抓取" value="禁止" /><Row label="synthetic terms" value="不能确认" /><Row label="science pixels" value="0" /><Row label="dense campaign" value={artifact.boundary.denseCampaignStatus} /></div><div className="mt-5 border border-[var(--v552-warning)]/20 bg-[var(--v552-warning)]/[.04] p-3 text-[8px] leading-5 text-[var(--v552-warning)]">local-shadow 当前只能显示缺口；不能晋级 measured authority、科学图像或正式产品。</div></aside></div><footer className="relative mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-4 text-[8px] text-[var(--v552-muted)]"><span>确认 0/7 · 回放 2/2 · 科学像素 0 · 浏览器资格未运行</span><div className="flex flex-wrap gap-2"><Download id="receipt" label="下载空包回执" /><Download id="atlas" label="下载验证图谱" /></div></footer></>}</section>;
}
function Metric({ label, value, unavailable = false }: { label: string; value: string; unavailable?: boolean }) { return <div className="border border-white/10 bg-black/20 p-3"><div className="text-[8px] uppercase tracking-[.16em] text-[var(--v552-muted)]">{label}</div><div className={unavailable ? "mt-2 text-base text-[var(--v552-unavailable)]" : "mt-2 text-lg text-[var(--v552-qualified)]"}>{value}</div></div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-3 border-b border-white/5 py-2 text-[8px]"><span className="text-[var(--v552-muted)]">{label}</span><span className="max-w-[65%] truncate text-right">{value}</span></div>; }
function Download({ id, label }: { id: "atlas" | "receipt"; label: string }) { return <a className="border border-white/15 px-3 py-2 text-white/70" href={`/api/atlas/relativity-evidence/v552/license-confirmation-packet?download=${id}`}>{label}</a>; }
