"use client";
import { useEffect, useSyncExternalStore, type CSSProperties } from "react";
import { getAtlasCalibrationHudModeSnapshotV506, setAtlasCalibrationHudModeV506, subscribeAtlasCalibrationHudModeV506 } from "../lib/atlasCalibrationHudModeStoreV506";
import { getKerrProductUncertaintyEligibilitySnapshotV513, loadKerrProductUncertaintyEligibilitySummaryV513, subscribeKerrProductUncertaintyEligibilityV513 } from "../lib/kerrProductUncertaintyEligibilityClientV513";
import { compareKerrUncertaintyVisualEncodingsV514, createKerrUncertaintyVisualEncodingV514, resolveKerrUncertaintyVisualProfileV514, type KerrUncertaintyVisualModeV514, type KerrUncertaintyVisualRowV514 } from "../lib/kerrUncertaintyVisualEncodingV514";

export default function KerrUncertaintyVisualABV514() {
  const state = useSyncExternalStore(subscribeKerrProductUncertaintyEligibilityV513, getKerrProductUncertaintyEligibilitySnapshotV513, getKerrProductUncertaintyEligibilitySnapshotV513);
  const mode = useSyncExternalStore(subscribeAtlasCalibrationHudModeV506, getAtlasCalibrationHudModeSnapshotV506, getAtlasCalibrationHudModeSnapshotV506);
  useEffect(() => { void loadKerrProductUncertaintyEligibilitySummaryV513().catch(() => undefined); }, []);
  const summary = state.summary;
  const science = summary ? createKerrUncertaintyVisualEncodingV514(summary, "science") : null;
  const cinematic = summary ? createKerrUncertaintyVisualEncodingV514(summary, "cinematic") : null;
  const comparison = science && cinematic ? compareKerrUncertaintyVisualEncodingsV514(science, cinematic) : null;
  return <section className="relative mt-7 overflow-hidden rounded-[36px] border border-white/10 bg-[#020608] p-5 text-white shadow-[0_60px_200px_rgba(0,0,0,.78)] sm:p-8" data-atlas-kerr-uncertainty-visual-ab-v514 data-atlas-v514-row-count="9" data-atlas-v514-mode-count="2" data-atlas-v514-numeric-style-input-count="0" data-atlas-v514-scientific-payload-stable={String(comparison?.scientificPayloadStable??false)} data-atlas-v514-uncertainty-drives-color="false" data-atlas-v514-uncertainty-drives-bloom="false" data-atlas-v514-uncertainty-drives-exposure="false" data-atlas-v514-scientific-field-mutation="false" data-atlas-v514-canvas-created="false" data-atlas-v514-scene-revision-delta="0"><header className="grid gap-5 border-b border-white/10 pb-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="font-mono text-[9px] uppercase tracking-[.42em] text-cyan-100/45">V514 / Uncertainty visual A/B</div><h2 className="mt-4 max-w-4xl font-serif text-4xl tracking-[.035em] sm:text-5xl">同一份误差证据，两种视觉语气，零数据漂移</h2><p className="mt-4 max-w-3xl font-mono text-[10px] leading-6 text-white/45">颜色、marker 与边框纹理只由资格状态决定；数值大小从不进入样式函数。Science 保持线性与克制，Cinematic 只改变版式语气和固定 seed 氛围。</p></div><div className="flex border border-white/10 bg-black/30 p-1 font-mono">{(["science","cinematic"]as const).map(value=><button type="button" key={value} onClick={()=>setAtlasCalibrationHudModeV506(value)} className={mode.mode===value?"bg-white px-3 py-2 text-[8px] uppercase text-black":"px-3 py-2 text-[8px] uppercase text-white/35"}>{value}</button>)}</div></header>{!science||!cinematic?<div className="mt-6 border-l-2 border-white/20 bg-white/[.025] px-4 py-4 font-mono text-[10px] text-white/45">{state.status==="idle"||state.status==="loading"?"正在读取 uncertainty evidence…":`A/B evidence 不可用 / ${state.reason??"request-failed"}`}</div>:<div className="mt-6 grid gap-4 xl:grid-cols-2"><EncodingPanel encoding={science} active={mode.mode==="science"}/><EncodingPanel encoding={cinematic} active={mode.mode==="cinematic"}/></div>}<footer className="mt-6 grid gap-px border border-white/10 bg-white/10 font-mono sm:grid-cols-5"><Metric label="payload key" value={science?.scientificPayloadKey.slice(0,12)??"pending"}/><Metric label="rows" value="9 / 9"/><Metric label="numeric style inputs" value="0"/><Metric label="scientific mutation" value="false"/><Metric label="default applied" value="false"/></footer></section>;
}
function EncodingPanel({encoding,active}:Readonly<{encoding:NonNullable<ReturnType<typeof createKerrUncertaintyVisualEncodingV514>>;active:boolean}>){const profile=resolveKerrUncertaintyVisualProfileV514(encoding.mode),style={backgroundColor:profile.panel,color:profile.ink,borderColor:active?profile.status.qualified.border:"rgba(255,255,255,.1)"}as CSSProperties;return <article style={style} className="overflow-hidden border p-4 transition-colors" data-atlas-v514-panel-mode={encoding.mode} data-atlas-v514-panel-active={String(active)}><div className="flex items-center justify-between border-b border-white/10 pb-4 font-mono"><div><div className="text-[8px] uppercase tracking-[.25em] opacity-45">{encoding.mode}</div><div className="mt-2 text-lg">{encoding.mode==="science"?"Measurement-first encoding":"Seeded presentation encoding"}</div></div><div className="text-right text-[7px] uppercase opacity-35">{encoding.mode==="science"?"linear · bloom 0":"seeded · no data writeback"}</div></div><div className="mt-4 grid gap-2 sm:grid-cols-3">{encoding.rows.map(row=><VisualRow key={row.id} row={row} mode={encoding.mode}/>)}</div></article>}
function VisualRow({row,mode}:Readonly<{row:KerrUncertaintyVisualRowV514;mode:KerrUncertaintyVisualModeV514}>){const token=resolveKerrUncertaintyVisualProfileV514(mode).status[row.styleKey],style={color:token.ink,borderColor:token.border,borderStyle:token.borderPattern==="solid"?"solid":token.borderPattern==="double"?"double":token.borderPattern==="dotted"?"dotted":"dashed",backgroundColor:token.wash,boxShadow:`0 0 ${Math.round(token.glowOpacity*48)}px ${token.wash}`}as CSSProperties;return <div style={style} className="min-w-0 border p-3 font-mono" data-atlas-v514-style-key={row.styleKey} data-atlas-v514-marker={row.marker} data-atlas-v514-border-pattern={row.borderPattern}><div className="flex items-center gap-2"><span className="inline-block h-2 w-2 border border-current" data-marker-shape={row.marker}/><span className="truncate text-[7px] uppercase tracking-[.12em]">{row.status}</span></div><div className="mt-2 truncate text-[8px] text-white/65">{row.id}</div><div className="mt-2 text-[10px] text-white/85">{row.displayMaximum}</div></div>}
function Metric({label,value}:Readonly<{label:string;value:string}>){return <div className="bg-black/40 px-3 py-3 text-center"><div className="text-[7px] uppercase tracking-[.14em] text-white/25">{label}</div><div className="mt-1 truncate text-[10px] text-white/65">{value}</div></div>}
