"use client";

import Image from "next/image";
import { useState, useSyncExternalStore, type CSSProperties } from "react";
import { getKerrRedshiftDoubleEdgeIdentifiabilitySnapshotV495, loadKerrRedshiftDoubleEdgeIdentifiabilitySummaryV495, subscribeKerrRedshiftDoubleEdgeIdentifiabilityV495 } from "../lib/kerrRedshiftDoubleEdgeIdentifiabilityClientV495";

export default function KerrRedshiftDoubleEdgeIdentifiabilityV495() {
  const state = useSyncExternalStore(subscribeKerrRedshiftDoubleEdgeIdentifiabilityV495, getKerrRedshiftDoubleEdgeIdentifiabilitySnapshotV495, getKerrRedshiftDoubleEdgeIdentifiabilitySnapshotV495);
  const [mode, setMode] = useState<"science" | "cinematic">("science");
  const summary = state.summary;
  const style = { "--v495-accent": mode === "science" ? "#71edff" : "#ffad72", "--v495-wash": mode === "science" ? "rgba(55,218,255,.075)" : "rgba(255,126,65,.095)" } as CSSProperties;
  return <section className="relative mt-7 overflow-hidden rounded-[34px] border border-white/10 bg-[#020607] p-5 text-white shadow-[0_70px_220px_rgba(0,0,0,.8)] sm:p-8" data-atlas-kerr-redshift-double-edge-identifiability-v495 data-atlas-v495-mode={mode} data-atlas-v495-request-count={state.requestCount} data-atlas-v495-statistical-robustness="false" data-atlas-v495-science-writeback="false" data-atlas-v495-science-raster="false" data-atlas-v495-scene-revision-delta="0" style={style}>
    <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_72%_8%,var(--v495-wash),transparent_43%)]" />
    <header className="relative flex flex-wrap items-end justify-between gap-5 border-b border-white/10 pb-6"><div><div className="font-mono text-[9px] uppercase tracking-[.42em] text-[var(--v495-accent)]/65">V495 / double-edge identifiability</div><h1 className="mt-4 font-serif text-4xl tracking-[.035em] text-white/90 sm:text-6xl">Fifteen deletions below the cut</h1><p className="mt-4 max-w-3xl font-mono text-[10px] leading-6 text-white/42">K4 has edge connectivity three. Removing any two contrasts therefore leaves a connected graph: twelve adjacent pairs retain spectrum [0,1,3,4], three disjoint pairs retain [0,2,2,4]. This proves deterministic identifiability below the cut, not statistical noise robustness.</p></div><div className="flex border border-white/12 bg-black/55 p-1 font-mono text-[8px] uppercase tracking-[.2em]">{(["science", "cinematic"] as const).map((entry) => <button className={mode === entry ? "bg-[var(--v495-accent)] px-4 py-2.5 text-black" : "px-4 py-2.5 text-white/30"} key={entry} onClick={() => setMode(entry)} type="button">{entry}</button>)}</div></header>
    {state.status === "idle" ? <div className="relative mt-6 border border-dashed border-[var(--v495-accent)]/20 bg-white/[.02] p-5"><div className="font-mono text-[10px] text-white/45">The 15 detailed matrices remain outside React state. Load only the bounded topology, spectrum and held-edge summary.</div><button className="atlas-accessible-focus mt-4 border border-[var(--v495-accent)]/35 bg-[var(--v495-wash)] px-4 py-2 font-mono text-[9px] uppercase tracking-[.16em] text-[var(--v495-accent)]" onClick={() => void loadKerrRedshiftDoubleEdgeIdentifiabilitySummaryV495().catch(() => undefined)} type="button">Load double-edge audit</button></div> : null}
    {state.status === "loading" ? <div className="relative mt-6 font-mono text-[10px] text-white/50">Verifying two topology classes, spectra, pseudoinverses and SVG SHA...</div> : null}
    {state.status === "unavailable" ? <div className="relative mt-6 font-mono text-[10px] text-amber-100/60">Double-edge audit unavailable / {state.reason ?? "request-failed"}</div> : null}
    {summary ? <><div className="relative mt-6 grid grid-cols-2 gap-px border border-white/10 bg-white/10 font-mono sm:grid-cols-5"><Stat label="all pairs" value="15" /><Stat label="adjacent" value="12" /><Stat label="disjoint" value="3" /><Stat label="min cut" value="3" /><Stat label="retained cycle" value="1" /></div><figure className="relative mt-5 overflow-hidden border border-white/10 bg-black/35 p-2 sm:p-4"><Image alt="Fifteen K4 double-edge deletion cases grouped into adjacent and disjoint spectral classes" className="block h-auto w-full" height={1120} src={summary.svgHref} unoptimized width={1440} /><figcaption className="border-t border-white/8 px-2 pt-3 font-mono text-[8px] leading-4 text-white/32">Both visual modes use the same immutable payload. No detector covariance, jackknife statistic, physical intensity or science raster is synthesized.</figcaption></figure><div className="relative mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{summary.deletionCases.map((entry) => <article className="border border-white/10 bg-white/[.025] p-4" key={entry.caseId}><div className="font-serif text-[17px] text-white/80">{entry.removedEdgeIds.join(" + ")}</div><div className="mt-3 font-mono text-[9px] text-[var(--v495-accent)]/70">{entry.removalClass} / [{entry.eigenvalues.join(", ")}] / condition {entry.expectedConditionNumber}</div><div className="mt-2 font-mono text-[8px] leading-4 text-white/30">spectral residual {entry.eigenvalueResidual.toExponential(2)}<br />held edges {entry.maximumRemovedEdgePredictionResidual.toExponential(2)}<br />cycle space 1</div></article>)}</div><footer className="relative mt-6 flex flex-wrap justify-between gap-3 border-t border-white/10 pt-5 font-mono text-[8px] text-white/30"><span>payload {summary.payloadSha256.slice(0, 18)}... / max held residual {summary.audit.maximumRemovedEdgePredictionResidual.toExponential(3)}</span><span className="flex gap-2"><a className="border border-white/12 px-3 py-1.5" href={`${summary.svgHref}&download=svg`}>export SVG</a><a className="border border-white/12 px-3 py-1.5" href="/api/atlas/relativity-evidence/v495/redshift-double-edge-identifiability?download=audit">export provenance</a></span></footer></> : null}
  </section>;
}
function Stat({ label, value }: { label: string; value: string }) { return <div className="bg-[#05090a] px-4 py-3 text-center"><div className="text-[7px] uppercase tracking-[.18em] text-white/25">{label}</div><div className="mt-1 font-serif text-xl text-white/75">{value}</div></div>; }
