"use client";
import { useEffect, useState } from "react";
import { useAtlasRuntimeStore } from "../lib/atlasRuntimeStore";
import { parseMeasuredPhotonExpectationV369, type MeasuredPhotonExpectationV369 } from "../lib/measuredPhotonExpectationV369";
import { ATLAS_VISUAL_PROFILE_CANDIDATE_V362, resolveAtlasVisualProfileV299 } from "../lib/atlasVisualProfileV299";
import { createAtlasVisualTokenSignatureV300, useAtlasVisualRuntimeConsumerV300 } from "../lib/atlasVisualRuntimeConsumptionV300";
export default function MeasuredPhotonExpectationSurfaceV369() { const profile = useAtlasRuntimeStore((snapshot) => snapshot.visualProfile); if (profile !== ATLAS_VISUAL_PROFILE_CANDIDATE_V362) return null; return <Panel />; }
function Panel() { const profile = resolveAtlasVisualProfileV299(ATLAS_VISUAL_PROFILE_CANDIDATE_V362); useAtlasVisualRuntimeConsumerV300({ profile: profile.id, group: "hud", consumer: "MeasuredPhotonExpectationSurfaceV369", tokenSignature: createAtlasVisualTokenSignatureV300(profile.runtimeTokens.hud) }); const [artifact, setArtifact] = useState<MeasuredPhotonExpectationV369 | null>(null); const [state, setState] = useState<"loading" | "ready" | "unavailable" | "error">("loading"); useEffect(() => { const controller = new AbortController(); void fetch("/api/atlas/relativity-evidence/v369/measured-expectation", { cache: "no-store", signal: controller.signal }).then(async (response) => { const value = await response.json() as { available?: boolean; artifact?: unknown }; if (response.ok && value.available === false) return null; if (!response.ok || value.available !== true || !value.artifact) throw new Error("v369-unavailable"); return parseMeasuredPhotonExpectationV369(value.artifact); }).then((value) => { if (controller.signal.aborted) return; if (!value) { setState("unavailable"); return; } setArtifact(value); setState("ready"); }).catch(() => { if (!controller.signal.aborted) setState("error"); }); return () => controller.abort(); }, []); return <section className="mt-2 rounded-[10px] border border-blue-100/15 bg-[radial-gradient(circle_at_90%_10%,rgba(59,130,246,.12),transparent_34%),linear-gradient(145deg,rgba(5,18,40,.92),rgba(6,8,14,.98))] p-3 font-mono text-[8px] text-white/55" data-atlas-measured-photon-expectation-v369 data-atlas-v369-expectation-available={String(artifact?.measuredExpectationAvailable ?? false)} data-atlas-v369-observed-counts="unavailable" data-atlas-v369-synthetic-fallback="false" data-atlas-v369-science-buffer-mutation="false" data-atlas-v369-cinematic-consumer="false"><div className="flex flex-wrap items-end justify-between gap-2"><div><div className="text-[7px] uppercase tracking-[.2em] text-blue-100/50">Measured photon expectation v369</div><div className="text-[13px] text-blue-50/90">全波段 throughput 卷积与电子误差预算</div></div><div className="text-right text-[7px] text-blue-100/60">{state}<br />{artifact?.status ?? "loading"}</div></div><div className="mt-2 grid grid-cols-2 gap-1.5 sm:grid-cols-4"><Metric label="authority" value={artifact?.authorityGranted ? "QUALIFIED" : "UNAVAILABLE"} /><Metric label="geometry" value={artifact?.observationGeometryQualified ? "QUALIFIED" : "UNAVAILABLE"} /><Metric label="expectations" value={`${artifact?.counts.expectationRowCount ?? 0} / 12`} /><Metric label="observed counts" value="UNAVAILABLE" /></div><div className="mt-2 rounded border border-white/[.08] px-2 py-1.5 text-[7px] leading-3 text-white/38">算子使用 4096/2048 Simpson 全波段卷积，并显式保留 source、dark、background、read-noise 分量。输出只是条件期望和方差，不是观测计数；缺少 authority 或 collecting area / pixel solid angle 时不返回零值或 synthetic 替代。</div></section>; }
function Metric({ label, value }: Readonly<{ label: string; value: string }>) { return <div className="rounded border border-white/[.08] bg-black/20 px-2 py-2"><div className="text-[7px] uppercase text-white/30">{label}</div><div className="mt-1 text-[10px] text-blue-50/78">{value}</div></div>; }
