"use client";
import { useEffect, useMemo, useState, type CSSProperties } from "react";
import { useAtlasRuntimeStore } from "../lib/atlasRuntimeStore";
import { ATLAS_VISUAL_PROFILE_CANDIDATE_V377, resolveAtlasVisualProfileV299 } from "../lib/atlasVisualProfileV299";
import { createAtlasVisualTokenSignatureV300, useAtlasVisualRuntimeConsumerV300 } from "../lib/atlasVisualRuntimeConsumptionV300";
import { parseMeasuredAuthorityAdversarialCampaignV380, type MeasuredAuthorityAdversarialCampaignV380 } from "../lib/measuredAuthorityAdversarialV380";

export default function MeasuredAuthorityAdversarialSurfaceV380() { const profile = useAtlasRuntimeStore((snapshot) => snapshot.visualProfile); if (profile !== ATLAS_VISUAL_PROFILE_CANDIDATE_V377) return null; return <Panel />; }
function Panel() {
  const profile = resolveAtlasVisualProfileV299(ATLAS_VISUAL_PROFILE_CANDIDATE_V377); const tokens = profile.runtimeTokens.hud.measurementLabV11; if (!tokens) throw new Error("v380-v11-token-boundary");
  useAtlasVisualRuntimeConsumerV300({ profile: profile.id, group: "hud", consumer: "MeasuredAuthorityAdversarialSurfaceV380", tokenSignature: createAtlasVisualTokenSignatureV300(profile.runtimeTokens.hud) });
  const [artifact, setArtifact] = useState<MeasuredAuthorityAdversarialCampaignV380 | null>(null); const [phase, setPhase] = useState<"loading" | "ready" | "unavailable">("loading");
  useEffect(() => { const controller = new AbortController(); void fetch("/api/atlas/relativity-evidence/v380/measured-authority-adversarial", { cache: "no-store", signal: controller.signal }).then(async (response) => { const value = await response.json() as { available?: boolean; artifact?: unknown }; if (!response.ok || value.available !== true || !value.artifact) throw new Error("v380-campaign-unavailable"); return parseMeasuredAuthorityAdversarialCampaignV380(value.artifact); }).then((value) => { if (!controller.signal.aborted) { setArtifact(value); setPhase("ready"); } }).catch(() => { if (!controller.signal.aborted) setPhase("unavailable"); }); return () => controller.abort(); }, []);
  const lanes = useMemo(() => ["ingress", "detector", "geometry", "fusion"].map((lane) => ({ lane, cases: artifact?.cases.filter((entry) => entry.lane === lane) ?? [] })), [artifact]);
  const style = { "--atlas-v380-grid": tokens.metrologyGridOpacity, "--atlas-v380-alert": tokens.authorityGateLuminance, "--atlas-v380-scan": tokens.unavailableScanOpacity } as CSSProperties;
  return <section style={style} className="relative mt-2 overflow-hidden rounded-[12px] border border-red-100/14 bg-[linear-gradient(125deg,rgba(5,15,18,.99),rgba(9,9,11,.99)_58%,rgba(28,8,3,.96))] p-3 text-[8px] text-white/55" data-atlas-measured-authority-adversarial-v380 data-atlas-v380-phase={phase} data-atlas-v380-passed={artifact?.passedCaseCount ?? "loading"} data-atlas-v380-authority-promotion="false" data-atlas-v380-observed-counts="false" data-atlas-v380-science-buffer-mutation="false" data-atlas-v380-cinematic-consumer="false">
    <div aria-hidden="true" className="pointer-events-none absolute inset-0 opacity-[var(--atlas-v380-grid)] [background-image:linear-gradient(90deg,rgba(254,202,202,.06)_1px,transparent_1px)] [background-size:8.33%_100%]" />
    <div className="relative flex flex-wrap items-end justify-between gap-3"><div><div className="font-mono text-[7px] uppercase tracking-[.25em] text-red-100/42">v380 · fault injection oscilloscope</div><h3 className="mt-0.5 font-['Bahnschrift_Condensed','Arial_Narrow',sans-serif] text-[17px] font-light uppercase tracking-[.09em] text-cyan-50/88">Every forged path opens the circuit</h3></div><div className="border-l border-red-100/15 pl-3 text-right font-mono text-[7px] uppercase tracking-[.14em] text-red-100/60">{artifact ? `${artifact.passedCaseCount}/${artifact.caseCount} contained` : phase}<br />fixture only · zero promotion</div></div>
    <div className="relative mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-4">{lanes.map(({ lane, cases }) => <div key={lane} className="rounded-[9px] border border-white/[.07] bg-black/20 p-2" data-atlas-v380-lane={lane}><div className="mb-2 flex items-center gap-2 font-mono text-[6px] uppercase tracking-[.2em] text-white/30"><span>{lane}</span><i className="h-px flex-1 bg-red-100/15" /></div><div className="space-y-1">{cases.length ? cases.map((entry) => <div key={entry.id} className="rounded border border-red-100/[.09] bg-red-100/[.018] px-2 py-1.5" data-atlas-v380-case={entry.id} data-atlas-v380-disposition={entry.actualDisposition}><div className="truncate text-[7px] text-white/48">{entry.id}</div><div className="mt-0.5 flex justify-between gap-2 font-mono text-[6px] uppercase tracking-[.08em]"><span className="truncate text-white/25">{entry.reason}</span><span className={entry.actualDisposition === "rejected" ? "text-red-100/66" : "text-amber-100/66"}>{entry.actualDisposition}</span></div></div>) : <div className="rounded border border-white/[.05] px-2 py-2 font-mono text-[7px] text-white/20">{phase}</div>}</div></div>)}</div>
    <div className="relative mt-2 flex flex-wrap justify-between gap-2 border-t border-red-100/10 pt-2 font-mono text-[7px] text-white/30"><span>oversize · SHA · identity · fixture · authority · observed-counts</span><span className="text-red-100/[var(--atlas-v380-alert)]">negative fixtures never become measured evidence</span></div>
    <div aria-hidden="true" className="pointer-events-none absolute inset-x-0 bottom-0 h-px bg-gradient-to-r from-transparent via-red-100/60 to-transparent opacity-[var(--atlas-v380-scan)]" />
  </section>;
}
