"use client";

import { useEffect, useState } from "react";
import { parseRelativityEvidenceResponseV349, type RelativityEvidenceResponseV349 } from "../lib/relativityWorkbenchEvidenceV349";

export default function RelativityEvidenceSurfaceV349() {
  const [response, setResponse] = useState<RelativityEvidenceResponseV349>({ version: "v349-relativity-evidence-response", available: false, reason: "evidence-unavailable", snapshot: null });
  useEffect(() => { const controller = new AbortController(); void fetch("/api/atlas/relativity-evidence/v349", { cache: "no-store", signal: controller.signal }).then(async (value) => parseRelativityEvidenceResponseV349(await value.json())).then(setResponse).catch(() => { if (!controller.signal.aborted) setResponse({ version: "v349-relativity-evidence-response", available: false, reason: "evidence-corrupt", snapshot: null }); }); return () => controller.abort(); }, []);
  const visual = response.snapshot?.current.v349; const ready = response.available && visual != null; const status = ready ? "ready" : response.reason;
  return <section className="relative mt-2 overflow-hidden rounded-[10px] border border-fuchsia-100/15 bg-[linear-gradient(145deg,rgba(36,9,33,0.96),rgba(5,9,17,0.98)_68%,rgba(10,17,29,0.96))] p-3 font-mono text-[8px] text-white/52" data-atlas-relativity-evidence-v349 data-atlas-relativity-evidence-v349-status={status}>
    <div aria-hidden="true" className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_94%_0%,rgba(217,70,239,0.12),transparent_30%),linear-gradient(90deg,transparent_49.8%,rgba(148,220,255,0.025)_50%,transparent_50.2%)]" />
    <div className="relative flex flex-wrap items-end justify-between gap-2"><div><div className="text-[7px] uppercase tracking-[0.2em] text-fuchsia-100/44">Science Cinematic V8 · v349</div><div className="mt-0.5 text-[13px] tracking-[0.045em] text-fuchsia-50/90">Relativistic spectral observatory</div></div><div className="text-right text-[7px] text-fuchsia-100/64">{visual?.denseStatus ?? "dense unavailable"}<br /><span className="text-white/28">{ready ? "browser qualification not run" : status}</span></div></div>
    <div className="relative mt-3 grid gap-1.5 sm:grid-cols-4"><div className="rounded border border-white/[0.08] bg-black/20 px-2 py-2"><div className="text-[7px] uppercase text-white/30">runtime rows</div><div className="mt-1 text-[12px] text-fuchsia-50/84">{visual?.runtimeMatrixRows ?? 0}</div><div className="text-[7px] text-white/32">4 profiles · 8 groups</div></div><div className="rounded border border-white/[0.08] bg-black/20 px-2 py-2"><div className="text-[7px] uppercase text-white/30">Science</div><div className="mt-1 text-[12px] text-emerald-50/84">{visual?.scienceFieldsEquivalent && visual.sciencePayloadByteIdentical ? "FROZEN" : "PENDING"}</div><div className="text-[7px] text-white/32">authority digest unchanged</div></div><div className="rounded border border-white/[0.08] bg-black/20 px-2 py-2"><div className="text-[7px] uppercase text-white/30">Cinematic</div><div className="mt-1 text-[12px] text-fuchsia-50/84">{visual?.cinematicOutputsPairwiseDistinct ? "SEEDED" : "PENDING"}</div><div className="text-[7px] text-white/32">V5 · V6 · V7 · V8</div></div><div className="rounded border border-white/[0.08] bg-black/20 px-2 py-2"><div className="text-[7px] uppercase text-white/30">consumer</div><div className="mt-1 text-[10px] text-cyan-50/84">{visual?.presentationConsumer === "spectral-ribbon-reticle-channel-separation-seeded-overlay" ? "WIRED" : "PENDING"}</div><div className="text-[7px] text-white/32">presentation-only · no mutation</div></div></div>
    <div className="relative mt-2 flex flex-wrap items-center justify-between gap-2 border-t border-white/[0.06] pt-2 text-[7px] text-white/32"><span>{visual?.assetSelector ?? "asset unavailable"} · {visual?.localShadowManualOnly ? "local-shadow manual A/B" : "asset pending"}</span><span>{ready ? "dense 0/49 · aggregate unavailable" : response.reason === "lite-boundary" ? "Lite boundary" : "evidence unavailable"}</span></div>
  </section>;
}
