"use client";
import { useEffect, useState } from "react";
import { parseRelativityEvidenceResponseV346, type RelativityEvidenceResponseV346 } from "../lib/relativityWorkbenchEvidenceV346";
export default function RelativityEvidenceSurfaceV346() {
  const [response, setResponse] = useState<RelativityEvidenceResponseV346>({ version: "v346-relativity-evidence-response", available: false, reason: "evidence-unavailable", snapshot: null });
  useEffect(() => { const controller = new AbortController(); void fetch("/api/atlas/relativity-evidence/v346", { cache: "no-store", signal: controller.signal }).then(async (value) => parseRelativityEvidenceResponseV346(await value.json())).then(setResponse).catch(() => { if (!controller.signal.aborted) setResponse({ version: "v346-relativity-evidence-response", available: false, reason: "evidence-corrupt", snapshot: null }); }); return () => controller.abort(); }, []);
  const probe = response.snapshot?.current.v346; const ready = response.available && probe != null;
  return <section className="relative mt-2 overflow-hidden rounded-[10px] border border-cyan-100/15 bg-[linear-gradient(145deg,rgba(4,18,25,0.96),rgba(4,9,17,0.98)_66%,rgba(8,19,27,0.96))] p-3 font-mono text-[8px] text-white/52" data-atlas-relativity-evidence-v346 data-atlas-relativity-evidence-v346-status={ready ? "ready" : response.reason}>
    <div aria-hidden="true" className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_6%_0%,rgba(96,220,238,0.1),transparent_30%),linear-gradient(90deg,transparent_49.8%,rgba(148,220,255,0.025)_50%,transparent_50.2%)]" />
    <div className="relative flex flex-wrap items-end justify-between gap-2"><div><div className="text-[7px] uppercase tracking-[0.2em] text-cyan-100/42">Scientific image probe v346</div><div className="mt-0.5 text-[13px] tracking-[0.045em] text-cyan-50/90">Pixel / FITS index / uncertainty</div></div><div className="text-right text-[7px] text-cyan-100/64">{probe?.denseStatus ?? "dense unavailable"}<br /><span className="text-white/28">browser qualification not run</span></div></div>
    <div className="relative mt-3 grid gap-1.5 sm:grid-cols-4"><div className="rounded border border-white/[0.08] bg-black/20 px-2 py-2"><div className="text-[7px] uppercase text-white/30">cells</div><div className="mt-1 text-[12px] text-cyan-50/84">{probe?.hitCount ?? 0} / {probe?.uniqueHitCount ?? 0}</div><div className="text-[7px] text-white/32">mapped / unique</div></div><div className="rounded border border-white/[0.08] bg-black/20 px-2 py-2"><div className="text-[7px] uppercase text-white/30">single-flight</div><div className="mt-1 text-[12px] text-cyan-50/84">{probe?.singleFlightRequests ?? 0}</div><div className="text-[7px] text-white/32">probe requests</div></div><div className="rounded border border-white/[0.08] bg-black/20 px-2 py-2"><div className="text-[7px] uppercase text-white/30">cache delta</div><div className="mt-1 text-[12px] text-cyan-50/84">+{probe?.typedArrayCacheDelta ?? 0}</div><div className="text-[7px] text-white/32">tracked / released</div></div><div className="rounded border border-white/[0.08] bg-black/20 px-2 py-2"><div className="text-[7px] uppercase text-white/30">celestial WCS</div><div className="mt-1 text-[12px] text-amber-50/84">UNAVAILABLE</div><div className="text-[7px] text-white/32">index coordinates only</div></div></div>
    <div className="relative mt-2 flex flex-wrap items-center justify-between gap-2 border-t border-white/[0.06] pt-2 text-[7px] text-white/32"><span>{probe?.orientationInvariant ? "orientation invariant" : "orientation pending"} · {probe?.releaseBaseline && probe.corruptBaseline ? "release baseline" : "baseline pending"} · {probe?.noScienceMutation ? "Science unchanged" : "Science pending"}</span><span>{ready ? "intent-only probe" : response.reason === "lite-boundary" ? "Lite boundary" : "evidence unavailable"}</span></div>
  </section>;
}
